### PR TITLE
fix: re-add accordion animation

### PR DESCRIPTION
**Pull request by kipprice**
### Overview

Re-adds the animation to accordions opening & closing

### PR Checklist

- [x] Related to JIRA ticket: GM-136
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fff26cc01c26b00ecf6ed4d--gamut-preview.netlify.app>https://5fff26cc01c26b00ecf6ed4d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fff26cc01c26b00ecf6ed4d>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
YES 👏 ..! Played with it on Storybook and it looks great!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.11-alpha.fec587.0<br/>@codecademy/gamut-labs@7.14.2-alpha.fec587.0<br/>@codecademy/gamut@19.11.7-alpha.fec587.0<br/>@codecademy/styleguide@21.22.1-alpha.fec587.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011b60993030b8a74615386--gamut-preview.netlify.app>https://6011b60993030b8a74615386--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011b60993030b8a74615386>Deploy Logs</a></p>

**Pull request merged**
