### PR TITLE
fix(Flyout): change how we're setting full height

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Changes `height: 100vh` to `bottom: 0` within `Flyout` to fix bug on mobile browsers where the bottom of the `Flyout` was getting covered by the native browser navigation on the bottom.

You can test this by comparing the fix (https://portal-app-pr-176.dev-eks.codecademy.com/catalog) to the current behavior on staging (https://portal-app.staging-eks.codecademy.com/catalog) on your actual mobile device. Click the "Catalog Menu" button at the top of the page to trigger the Flyout and confirm that you are now able to fully see and click on the full catalog and sorting quiz links at the bottom.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-1083](https://codecademy.atlassian.net/browse/REACH-1083)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.47-alpha.0d3490.0<br/>@codecademy/gamut-labs@19.11.3-alpha.0d3490.0<br/>@codecademy/styleguide@41.10.17-alpha.0d3490.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d4d35f78faef5a2ffa912b--gamut-preview.netlify.app>https://60d4d35f78faef5a2ffa912b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d4d35f78faef5a2ffa912b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.49-alpha.dab9ae.0<br/>@codecademy/gamut-labs@19.11.5-alpha.dab9ae.0<br/>@codecademy/styleguide@41.10.19-alpha.dab9ae.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d5fd0bfb14ac6a46963c54--gamut-preview.netlify.app>https://60d5fd0bfb14ac6a46963c54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d5fd0bfb14ac6a46963c54>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.50-alpha.346d10.0<br/>@codecademy/gamut-labs@19.11.6-alpha.346d10.0<br/>@codecademy/styleguide@41.10.20-alpha.346d10.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d60c408443686f44acd825--gamut-preview.netlify.app>https://60d60c408443686f44acd825--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d60c408443686f44acd825>Deploy Logs</a></p>

**Review by aionate0812 — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.53-alpha.b53994.0<br/>@codecademy/gamut-labs@19.12.3-alpha.b53994.0<br/>@codecademy/styleguide@41.10.23-alpha.b53994.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9dfb41445a8ae9795c0e1--gamut-preview.netlify.app>https://60d9dfb41445a8ae9795c0e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9dfb41445a8ae9795c0e1>Deploy Logs</a></p>

**Review by MattSchiller — APPROVED** [review]
An elegant solution!

**Pull request merged**
