### PR TITLE
feat: add lock and networkUser icons for shareable sandbox

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

add Lock1 and NetworkUser icons for shareable sandbox

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: EGG-1367
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

Screen Shot 2021-06-24 at 3 26 17 PM
Screen Shot 2021-06-24 at 3 26 21 PM

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.5.0-alpha.339c14.0<br/>@codecademy/gamut-kit@0.4.49-alpha.339c14.0<br/>@codecademy/gamut-labs@19.11.5-alpha.339c14.0<br/>@codecademy/gamut@34.10.12-alpha.339c14.0<br/>@codecademy/styleguide@41.10.19-alpha.339c14.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d4dce8f6d53468adde6297--gamut-preview.netlify.app>https://60d4dce8f6d53468adde6297--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d4dce8f6d53468adde6297>Deploy Logs</a></p>

**Comment by natalieweesh** [comment]
for some reason the svg's are missing fill="none" so they're looking weird:
Screen Shot 2021-06-24 at 4 05 11 PM
Screen Shot 2021-06-24 at 4 05 08 PM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.5.0-alpha.092551.0<br/>@codecademy/gamut-kit@0.4.49-alpha.092551.0<br/>@codecademy/gamut-labs@19.11.5-alpha.092551.0<br/>@codecademy/gamut@34.10.12-alpha.092551.0<br/>@codecademy/styleguide@41.10.19-alpha.092551.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d5e832b7fb484fd5542bc6--gamut-preview.netlify.app>https://60d5e832b7fb484fd5542bc6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d5e832b7fb484fd5542bc6>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Super!

**Pull request merged**
