### PR TITLE
fix(Tabs): Classname didn't actually get forwarded to the container

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview
This seems like it should have been there before?

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.5-alpha.fe1849.0<br/>@codecademy/gamut@16.0.15-alpha.fe1849.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.5-alpha.16494b.0<br/>@codecademy/gamut@16.0.15-alpha.16494b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7744b928e9463b32fa592e--gamut-preview.netlify.app>https://5f7744b928e9463b32fa592e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7744b928e9463b32fa592e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7744e110a9c34a311caa98--gamut-preview.netlify.app>https://5f7744e110a9c34a311caa98--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7744e110a9c34a311caa98>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Probably a good idea to verify this against the monolith, but yes, agreed, this should be forwarded 😄

**Comment by codecaaron** [comment]
> Probably a good idea to verify this against the monolith, but yes, agreed, this should be forwarded 😄

Checked the usage of this, looks like nothing actually uses the classname (and if it does the class does not exist)

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.6-alpha.ecbda0.0<br/>@codecademy/gamut@16.1.1-alpha.ecbda0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7cbd2cb6e5b12b3ad42e81--gamut-preview.netlify.app>https://5f7cbd2cb6e5b12b3ad42e81--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7cbd2cb6e5b12b3ad42e81>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.7-alpha.85a7a8.0<br/>@codecademy/gamut@16.1.2-alpha.85a7a8.0<br/>@codecademy/styleguide@17.6.2-alpha.85a7a8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7cd4d5f8b559521a1e7adc--gamut-preview.netlify.app>https://5f7cd4d5f8b559521a1e7adc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7cd4d5f8b559521a1e7adc>Deploy Logs</a></p>

**Pull request merged**
