### PR TITLE
feat(Variance): base => _ for un scoped style [WEB-1381]

### PR DESCRIPTION
**Pull request by codecaaron**
### [Variance Migration Doc](https://www.notion.so/codecademy/Variance-Migration-a675bbc31b584fec9dfff72c0364b194)

Change variance's responsive object syntax unscoped key `base`  to `_` to match other frameworks as underscore denotes a behavior that is unrelated to the rest of the keys and saves 3 characters to probable prop bloat.

```tsx
// before
<Box p={{ base: 4, md: 8 }} />
// after
<Box p={{ _: 4, md: 8 }} />
```

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: WEB-1381
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.2.1-alpha.987947.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6063b52b7baa670096f142f7--gamut-preview.netlify.app>https://6063b52b7baa670096f142f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6063b52b7baa670096f142f7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.2.2-alpha.789121.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6063ff20ebf1fe75d4fb3e4c--gamut-preview.netlify.app>https://6063ff20ebf1fe75d4fb3e4c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6063ff20ebf1fe75d4fb3e4c>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
I actually kinda like `0` more than `_` since it matches with arrays... but if other folks are doing `_` then 🤷

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.3.1-alpha.a4054b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6064ae10c2c4a94a55f8514a--gamut-preview.netlify.app>https://6064ae10c2c4a94a55f8514a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6064ae10c2c4a94a55f8514a>Deploy Logs</a></p>

**Pull request merged**
