### PR TITLE
style(HubCard): Updated title font weight 

### PR DESCRIPTION
**Pull request by aionate0812**
### Overview

Updated title font-weight in HubCard component

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.5-alpha.cccb63.0<br/>@codecademy/gamut-labs@11.0.1-alpha.cccb63.0<br/>@codecademy/styleguide@30.1.4-alpha.cccb63.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60466b2c8424252bddfe5e40--gamut-preview.netlify.app>https://60466b2c8424252bddfe5e40--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60466b2c8424252bddfe5e40>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.6-alpha.fc995d.0<br/>@codecademy/gamut-labs@11.0.2-alpha.fc995d.0<br/>@codecademy/styleguide@30.2.1-alpha.fc995d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60478709c58b06cbb3573c60--gamut-preview.netlify.app>https://60478709c58b06cbb3573c60--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60478709c58b06cbb3573c60>Deploy Logs</a></p>

**Pull request merged**
