### PR TITLE
feat(popover): add outline prop

### PR DESCRIPTION
**Pull request by sooinc**
## Overview
Adds outline property to Popover component. Common use case will be for dropdowns.

### PR Checklist
- [ ] Related to designs:
- [x] Related to JIRA ticket: EGG-444
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.5-alpha.03a505.0<br/>@codecademy/gamut@17.3.4-alpha.03a505.0<br/>@codecademy/styleguide@18.5.4-alpha.03a505.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faec02e9c7ce201133e46bc--gamut-preview.netlify.app>https://5faec02e9c7ce201133e46bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faec02e9c7ce201133e46bc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.6-alpha.e00d73.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faec3ec047883009a2bca55--gamut-preview.netlify.app>https://5faec3ec047883009a2bca55--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faec3ec047883009a2bca55>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.6-alpha.de0d46.0<br/>@codecademy/gamut@17.3.5-alpha.de0d46.0<br/>@codecademy/styleguide@18.5.5-alpha.de0d46.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faec942a7e71a0ba64a6619--gamut-preview.netlify.app>https://5faec942a7e71a0ba64a6619--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faec942a7e71a0ba64a6619>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.7-alpha.691e2a.0<br/>@codecademy/gamut-styles@7.4.2-alpha.691e2a.0<br/>@codecademy/gamut@17.3.6-alpha.691e2a.0<br/>@codecademy/markdown-overrides@0.3.10-alpha.691e2a.0<br/>@codecademy/styleguide@18.5.6-alpha.691e2a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faecb57d40d430d56b5f16c--gamut-preview.netlify.app>https://5faecb57d40d430d56b5f16c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faecb57d40d430d56b5f16c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.8-alpha.46bd85.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faed002d40d431644b5ef15--gamut-preview.netlify.app>https://5faed002d40d431644b5ef15--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faed002d40d431644b5ef15>Deploy Logs</a></p>

**Pull request merged**
