### PR TITLE
fix(tracking): remove tracking and codebytes

### PR DESCRIPTION
**Pull request by BandanaKM**
### Overview

This pull request:

- removes the tracking and codebytes packages (they are now published from the monorepo)
- removes the codebyteEditor story in storybook, 
- updates the readme to remove references to tracking
- removes some codebytes-related scripts in package.json and ci
- since no tests are currently in this repo, passes ci with no tests   

### PR Checklist

- [x] Related to JIRA ticket: [WEB-2175](https://codecademy.atlassian.net/browse/WEB-2175)
- [x] I have run this code to verify it works

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@0.6.3-alpha.60fe1e.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@0.6.3-alpha.5c1d37.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@0.6.3-alpha.056630.0<br/></pre>

**Review by aresnik11 — APPROVED** [review]
Yay!!

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
