### PR TITLE
fix: Revert "fix: Revert "fix: add docs back to header and footer""

### PR DESCRIPTION
**Pull request by aionate0812**
Reverts Codecademy/client-modules#2025

Now that the issues with CC-Docs have been resolved we are adding back  the links to the header and footer

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.68-alpha.efcfed.0<br/>@codecademy/gamut-labs@19.24.12-alpha.efcfed.0<br/>@codecademy/styleguide@44.1.8-alpha.efcfed.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a54b66ea7a43582d46b67--gamut-preview.netlify.app>https://613a54b66ea7a43582d46b67--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a54b66ea7a43582d46b67>Deploy Logs</a></p>

**Review by christian-dinh — APPROVED** [review]
😭 

Screen Shot 2021-09-09 at 2 43 17 PM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.69-alpha.856290.0<br/>@codecademy/gamut-labs@19.25.1-alpha.856290.0<br/>@codecademy/styleguide@44.2.1-alpha.856290.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a71aad136471752bf40d6--gamut-preview.netlify.app>https://613a71aad136471752bf40d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a71aad136471752bf40d6>Deploy Logs</a></p>

**Pull request merged**
