### PR TITLE
feat: adding 3 new icons for business reporting

### PR DESCRIPTION
**Pull request by jenesh**
### Overview
We need to add 3 new icons that will be used in the Business Reporting project.

Icon Names:
- DataTransferVerticalIcon

Screen Shot 2021-02-12 at 1 28 50 PM

- DataFileBarsShareIcon

Screen Shot 2021-02-12 at 1 29 04 PM

- SettingsSliderVerticalIcon

Screen Shot 2021-02-12 at 1 29 18 PM

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EN-466](https://codecademy.atlassian.net/browse/EN-466)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.14.2-alpha.134b39.0<br/>@codecademy/gamut-illustrations@0.4.35-alpha.134b39.0<br/>@codecademy/gamut-labs@9.3.7-alpha.134b39.0<br/>@codecademy/gamut@21.3.8-alpha.134b39.0<br/>@codecademy/styleguide@25.2.7-alpha.134b39.0<br/></pre>

**Review by codecaaron — APPROVED** [review]
Just FYI you don't need to use the streamline name as ours.

`SettingsSliderVerticalIcon` is a bit of a mouthful but 🤷

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6026c94c1182972b7289589e--gamut-preview.netlify.app>https://6026c94c1182972b7289589e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6026c94c1182972b7289589e>Deploy Logs</a></p>

**Comment by jenesh** [comment]
> Just FYI you don't need to use the streamline name as ours.
> 
> `SettingsSliderVerticalIcon` is a bit of a mouthful but 🤷

They have a nice ring to them so I'm fine with keeping them haha.

**Pull request merged**
