### PR TITLE
feat(variance): Computed styles, and configurable CSSType narrowing [GM-233]

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

This adds a few new APIs to variance to increase quality of life.

### Props with Theme Computations
Certain styles do not have clear scalar values, cases where this occurs are largely secondary color properties - like borders, outlines, and box shadows.  While the first two examples have escape hatches through `outlineColor` and `borderColor` something like box shadow does not.  Requiring you to import tokens and template them directly to add colors.

**Current Usage**
```tsx
import { theme } from '@codecademy/gamut-styles';

const Card = styled.div(system.css({
  boxShadow: `0px 0px 0px 4px ${theme.colors.navy}`
})
```

The biggest problem here is that theme values are not guaranteed to exist between applications, pulling in tokens take that may not have references or represent the current theme present areas where regressions are increasingly possible.  

To fix this adding the ability to pass a function of theme - to any system property when using them within a `variant` and `css` function gives you the ability to use theme values that are guaranteed to be valid by context.

**Computational CSS**
```tsx
const Card = styled.div(system.css({
  boxShadow: ({ colors }) => `0px 0px 0px 4px ${colors.navy}`
})
```

### Custom Scale Types
Currently for anything that does not explicity exist on our theme we do not have many options for custom typings for properties.  Using the object syntax presents the same issues as CSS - exhaustive lists of possible values.  This normally is a very good thing as it forces intentionality within props - however many properties do not work with scales and are necessarily open ended.  These properties use pure CSSType (with slight modifications) for their prop signature - which depending on the property can be restrictive or entirely too permissible.

Technically Correct:
```tsx
<Box width="1020102#" /> 
``` 

To add a secondary level of typesafety between complete string anarchy and endless scale definitions, we can add the ability to define scalar templates with template literal types. 

```tsx
import { variance, createScale } from '@codecademy/variance';

const Box = styled.div(variance.create({
  width: {
    property: 'width',
    scale: createScale<`${number}${'%' | 'px' |  'rem'}`>()
  }
})
```

Now our props can have an extra layer of typesafety closer to standard CSS validation and highlighting but at the compile level!

```tsx
// Nope.jpg ❌ 
<Box width="100$" /> 

// Yep.png ✅ 
<Box width="100%" /> 
```

### How does this work?

While object keys need to be exhaustive and definite, array constituents do not.  By asserting the type of an empty array typescript can infer what a possible item might be through `Array[number]`.  This lets use define huge sets of possible options without a JS equivalent.

```tsx
  const customScale = createScale<`${number}${'%' | 'px' |  'rem'}`>()  // []
  type ScaleValues = typeof customScale[number] // `${number}${'%' | 'px' |  'rem'}`
```

#### Disclaimer 
There are a few properties this might work for initially, however `width` is not one of them.  This is very limited to extremely small sets of possible combinations - while template literals are very powerful they do not work well with complex computations and require limited possible definitions.  Contrived versions like with would not work as we need to support complex CSS math syntaxes like `calc(100% - 2rem)`.  

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: GM-233
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.5-alpha.054d6e.0<br/>@codecademy/gamut-illustrations@0.17.1-alpha.054d6e.0<br/>@codecademy/gamut-kit@0.4.1-alpha.054d6e.0<br/>@codecademy/gamut-labs@18.3.1-alpha.054d6e.0<br/>@codecademy/gamut-patterns@0.3.1-alpha.054d6e.0<br/>@codecademy/gamut-styles@10.2.1-alpha.054d6e.0<br/>@codecademy/gamut-tests@2.4.4-alpha.054d6e.0<br/>@codecademy/gamut@33.2.1-alpha.054d6e.0<br/>@codecademy/konamimojisplosion@0.2.35-alpha.054d6e.0<br/>@codecademy/markdown-overrides@0.5.47-alpha.054d6e.0<br/>@codecademy/styleguide@40.1.1-alpha.054d6e.0<br/>@codecademy/variance@0.12.1-alpha.054d6e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b0ff756b255d14408a2493--gamut-preview.netlify.app>https://60b0ff756b255d14408a2493--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b0ff756b255d14408a2493>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
documentation? otherwise pls ship i love it

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.1-alpha.0abea0.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.0abea0.0<br/>@codecademy/gamut-kit@0.4.13-alpha.0abea0.0<br/>@codecademy/gamut-labs@19.0.6-alpha.0abea0.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.0abea0.0<br/>@codecademy/gamut-styles@11.0.1-alpha.0abea0.0<br/>@codecademy/gamut-tests@2.4.6-alpha.0abea0.0<br/>@codecademy/gamut@34.0.3-alpha.0abea0.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.0abea0.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.0abea0.0<br/>@codecademy/styleguide@41.2.5-alpha.0abea0.0<br/>@codecademy/variance@0.12.2-alpha.0abea0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c03196e0fb563fec0f5c6b--gamut-preview.netlify.app>https://60c03196e0fb563fec0f5c6b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c03196e0fb563fec0f5c6b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.838302.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.838302.0<br/>@codecademy/gamut-kit@0.4.23-alpha.838302.0<br/>@codecademy/gamut-labs@19.5.1-alpha.838302.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.838302.0<br/>@codecademy/gamut-styles@11.2.1-alpha.838302.0<br/>@codecademy/gamut-tests@2.4.8-alpha.838302.0<br/>@codecademy/gamut@34.6.1-alpha.838302.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.838302.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.838302.0<br/>@codecademy/styleguide@41.7.7-alpha.838302.0<br/>@codecademy/variance@0.14.1-alpha.838302.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c77a9f952130008ed04f85--gamut-preview.netlify.app>https://60c77a9f952130008ed04f85--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c77a9f952130008ed04f85>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
🤤

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.2.1-alpha.7313f0.0<br/>@codecademy/gamut-illustrations@0.17.6-alpha.7313f0.0<br/>@codecademy/gamut-kit@0.4.26-alpha.7313f0.0<br/>@codecademy/gamut-labs@19.6.1-alpha.7313f0.0<br/>@codecademy/gamut-patterns@0.4.1-alpha.7313f0.0<br/>@codecademy/gamut-styles@11.3.1-alpha.7313f0.0<br/>@codecademy/gamut-tests@2.4.9-alpha.7313f0.0<br/>@codecademy/gamut@34.7.1-alpha.7313f0.0<br/>@codecademy/konamimojisplosion@0.2.40-alpha.7313f0.0<br/>@codecademy/markdown-overrides@0.5.52-alpha.7313f0.0<br/>@codecademy/styleguide@41.7.11-alpha.7313f0.0<br/>@codecademy/variance@0.14.1-alpha.7313f0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8e95843befa32f7527440--gamut-preview.netlify.app>https://60c8e95843befa32f7527440--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8e95843befa32f7527440>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca68020e863a00d77db81f--gamut-preview.netlify.app>https://60ca68020e863a00d77db81f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca68020e863a00d77db81f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca6af8f1b662098e289c2b--gamut-preview.netlify.app>https://60ca6af8f1b662098e289c2b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca6af8f1b662098e289c2b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.1-alpha.eaa240.0<br/>@codecademy/gamut-illustrations@0.17.8-alpha.eaa240.0<br/>@codecademy/gamut-kit@0.4.32-alpha.eaa240.0<br/>@codecademy/gamut-labs@19.9.1-alpha.eaa240.0<br/>@codecademy/gamut-patterns@0.4.3-alpha.eaa240.0<br/>@codecademy/gamut-styles@11.4.1-alpha.eaa240.0<br/>@codecademy/gamut-tests@2.4.11-alpha.eaa240.0<br/>@codecademy/gamut@34.9.1-alpha.eaa240.0<br/>@codecademy/konamimojisplosion@0.2.42-alpha.eaa240.0<br/>@codecademy/markdown-overrides@0.5.54-alpha.eaa240.0<br/>@codecademy/styleguide@41.10.1-alpha.eaa240.0<br/>@codecademy/variance@0.15.1-alpha.eaa240.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca6f429f31080a5fdc5c9c--gamut-preview.netlify.app>https://60ca6f429f31080a5fdc5c9c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca6f429f31080a5fdc5c9c>Deploy Logs</a></p>

**Pull request merged**
