### PR TITLE
chore(Text): Remove labs text and last uses of `TextDeprecated`. 

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Migration branch: https://github.com/codecademy-engineering/Codecademy/pull/24034

* Removes last uses of labs text and deletes it
* Removes last uses of TextDeprecated for internal components.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.af0e9d.0<br/>@codecademy/gamut-labs@14.4.1-alpha.af0e9d.0<br/>@codecademy/gamut@32.3.1-alpha.af0e9d.0<br/>@codecademy/styleguide@36.4.1-alpha.af0e9d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086eac2de926d2a7ebcb0c7--gamut-preview.netlify.app>https://6086eac2de926d2a7ebcb0c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086eac2de926d2a7ebcb0c7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.309e5a.0<br/>@codecademy/gamut-labs@14.4.4-alpha.309e5a.0<br/>@codecademy/gamut@32.3.4-alpha.309e5a.0<br/>@codecademy/styleguide@36.4.4-alpha.309e5a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608750d7e33c142955282108--gamut-preview.netlify.app>https://608750d7e33c142955282108--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608750d7e33c142955282108>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🔪

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM internally (yay!), but is this `!`? There are a lot of `Text` imports from labs in the monolith.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.59-alpha.36da40.0<br/>@codecademy/gamut-labs@15.1.2-alpha.36da40.0<br/>@codecademy/gamut@32.4.3-alpha.36da40.0<br/>@codecademy/styleguide@36.6.2-alpha.36da40.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608ac26f1ea98700cee61661--gamut-preview.netlify.app>https://608ac26f1ea98700cee61661--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608ac26f1ea98700cee61661>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.60-alpha.14463f.0<br/>@codecademy/gamut-labs@15.1.3-alpha.14463f.0<br/>@codecademy/gamut@32.4.4-alpha.14463f.0<br/>@codecademy/styleguide@36.6.3-alpha.14463f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608b06238fc171485fe102aa--gamut-preview.netlify.app>https://608b06238fc171485fe102aa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608b06238fc171485fe102aa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608b11f210293863b9f5524a--gamut-preview.netlify.app>https://608b11f210293863b9f5524a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608b11f210293863b9f5524a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.61-alpha.395713.0<br/>@codecademy/gamut-labs@15.2.1-alpha.395713.0<br/>@codecademy/gamut@32.5.1-alpha.395713.0<br/>@codecademy/styleguide@36.7.1-alpha.395713.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608b14a89b627d62269dec7e--gamut-preview.netlify.app>https://608b14a89b627d62269dec7e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608b14a89b627d62269dec7e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.62-alpha.e2a5ae.0<br/>@codecademy/gamut-labs@15.2.2-alpha.e2a5ae.0<br/>@codecademy/gamut@32.6.1-alpha.e2a5ae.0<br/>@codecademy/styleguide@36.8.1-alpha.e2a5ae.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608b171a924749780930445f--gamut-preview.netlify.app>https://608b171a924749780930445f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608b171a924749780930445f>Deploy Logs</a></p>

**Pull request merged**
