### PR TITLE
fix(GlobalFooter): update empty global footer onClick targets

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

adds correct `onClick` `target` for global footer links that previously had an empty string

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [REACH-946](https://codecademy.atlassian.net/browse/REACH-946)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.43-alpha.88fe9f.0<br/>@codecademy/gamut-labs@14.2.3-alpha.88fe9f.0<br/>@codecademy/styleguide@36.2.3-alpha.88fe9f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6081e1ed494aa300ab028d71--gamut-preview.netlify.app>https://6081e1ed494aa300ab028d71--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6081e1ed494aa300ab028d71>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
tyyy

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.44-alpha.f554ff.0<br/>@codecademy/gamut-labs@14.2.4-alpha.f554ff.0<br/>@codecademy/styleguide@36.2.5-alpha.f554ff.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608315ee7856de00a03fb7ac--gamut-preview.netlify.app>https://608315ee7856de00a03fb7ac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608315ee7856de00a03fb7ac>Deploy Logs</a></p>

**Pull request merged**
