### PR TITLE
feat(NotificationItem): add support for forum mentions

### PR DESCRIPTION
**Pull request by saghdaey**
### Overview

render notifications of type `forum_mention` w/ an '@' icon

see the forum_mention notification in [storybook]( https://608c81770b164e1d8569267a--gamut-preview.netlify.app/storybook/?path=/docs/molecules-notificationlist--notification-list)

[related monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/24141)

screenshot from my monolith feature branch -- using gamut alpha build from this PR
Screen Shot 2021-04-30 at 6 40 05 PM

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-1115](https://codecademy.atlassian.net/browse/EGG-1115)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.10-alpha.8fa316.0<br/>@codecademy/gamut-kit@0.3.60-alpha.8fa316.0<br/>@codecademy/gamut-labs@15.1.3-alpha.8fa316.0<br/>@codecademy/gamut@32.4.4-alpha.8fa316.0<br/>@codecademy/styleguide@36.6.3-alpha.8fa316.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.11.2-alpha.47d531.0<br/>@codecademy/gamut-kit@0.3.67-alpha.47d531.0<br/>@codecademy/gamut-labs@15.2.7-alpha.47d531.0<br/>@codecademy/gamut@32.7.4-alpha.47d531.0<br/>@codecademy/styleguide@36.9.4-alpha.47d531.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c81770b164e1d8569267a--gamut-preview.netlify.app>https://608c81770b164e1d8569267a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c81770b164e1d8569267a>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
It's so cool seeing this project get iterated on. 😍

**Review by dreamwasp — APPROVED** [review]
🚢

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.11.2-alpha.70680b.0<br/>@codecademy/gamut-kit@0.3.67-alpha.70680b.0<br/>@codecademy/gamut-labs@15.2.7-alpha.70680b.0<br/>@codecademy/gamut@32.7.4-alpha.70680b.0<br/>@codecademy/styleguide@36.9.4-alpha.70680b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60900af8dd1e9000c7430f1b--gamut-preview.netlify.app>https://60900af8dd1e9000c7430f1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60900af8dd1e9000c7430f1b>Deploy Logs</a></p>

**Pull request merged**
