### PR TITLE
fix(Text): Fontweight for body text and none scalar typings

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Changes props without a scale to include `string & {}` as the default type for CSSType allowing `letterSpacing="2px"`etc.
* Fixes variants for body text to include a font weight of `base` as this caused some issues with the GlobalFooter rendering as bold since `as="h4" variant="p-small"` would still render bold.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.7-alpha.99226f.0<br/>@codecademy/gamut-kit@0.3.49-alpha.99226f.0<br/>@codecademy/gamut-labs@14.4.1-alpha.99226f.0<br/>@codecademy/gamut-styles@9.6.1-alpha.99226f.0<br/>@codecademy/gamut-tests@2.3.19-alpha.99226f.0<br/>@codecademy/gamut@32.3.1-alpha.99226f.0<br/>@codecademy/konamimojisplosion@0.2.19-alpha.99226f.0<br/>@codecademy/markdown-overrides@0.5.31-alpha.99226f.0<br/>@codecademy/styleguide@36.4.1-alpha.99226f.0<br/>@codecademy/variance@0.10.1-alpha.99226f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088528d71766d00e9400b12--gamut-preview.netlify.app>https://6088528d71766d00e9400b12--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088528d71766d00e9400b12>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.8-alpha.658721.0<br/>@codecademy/gamut-kit@0.3.54-alpha.658721.0<br/>@codecademy/gamut-labs@14.4.6-alpha.658721.0<br/>@codecademy/gamut-styles@9.6.2-alpha.658721.0<br/>@codecademy/gamut-tests@2.3.20-alpha.658721.0<br/>@codecademy/gamut@32.4.1-alpha.658721.0<br/>@codecademy/konamimojisplosion@0.2.20-alpha.658721.0<br/>@codecademy/markdown-overrides@0.5.32-alpha.658721.0<br/>@codecademy/styleguide@36.5.2-alpha.658721.0<br/>@codecademy/variance@0.10.1-alpha.658721.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60886bb695b8dc0f374a1217--gamut-preview.netlify.app>https://60886bb695b8dc0f374a1217--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60886bb695b8dc0f374a1217>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Amusing.

Maybe we should create a type brand like helper type for these `string & {}`s, to make them more clear?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.8-alpha.7a0737.0<br/>@codecademy/gamut-kit@0.3.55-alpha.7a0737.0<br/>@codecademy/gamut-labs@14.5.1-alpha.7a0737.0<br/>@codecademy/gamut-styles@9.6.2-alpha.7a0737.0<br/>@codecademy/gamut-tests@2.3.20-alpha.7a0737.0<br/>@codecademy/gamut@32.4.1-alpha.7a0737.0<br/>@codecademy/konamimojisplosion@0.2.20-alpha.7a0737.0<br/>@codecademy/markdown-overrides@0.5.32-alpha.7a0737.0<br/>@codecademy/styleguide@36.5.3-alpha.7a0737.0<br/>@codecademy/variance@0.10.1-alpha.7a0737.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60888933fe17e91f8b5dc90f--gamut-preview.netlify.app>https://60888933fe17e91f8b5dc90f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60888933fe17e91f8b5dc90f>Deploy Logs</a></p>

**Pull request merged**
