### PR TITLE
ci: fix PR coverage issues due to parallelism

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

updates required builds for codecov to match CircleCI parallelism for tests (whoops!)
Also adds a goal % for the gamut package to at least keep it where it is now (89% ish)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605971426454b76390391cbe--gamut-preview.netlify.app>https://605971426454b76390391cbe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605971426454b76390391cbe>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6059756694aa7d5b9c1b0a2c--gamut-preview.netlify.app>https://6059756694aa7d5b9c1b0a2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6059756694aa7d5b9c1b0a2c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605979381730ea4cf8607d73--gamut-preview.netlify.app>https://605979381730ea4cf8607d73--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605979381730ea4cf8607d73>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6059e5db9495492d561d3c19--gamut-preview.netlify.app>https://6059e5db9495492d561d3c19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6059e5db9495492d561d3c19>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Pull request merged**
