### PR TITLE
fix(GridFormCheckbox): tight variant error spacing

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Spacing was weird on 'tight' spacing Checkboxes in GridForm. This fixes that (per @songstephen)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: gm-358
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b6128082f9b02e6ab091b--gamut-preview.netlify.app>https://613b6128082f9b02e6ab091b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b6128082f9b02e6ab091b>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by airrobb — APPROVED** [review]
v cozy

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.024d4b.0<br/>@codecademy/gamut-icons@5.10.0-alpha.024d4b.0<br/>@codecademy/gamut-illustrations@0.18.0-alpha.024d4b.0<br/>@codecademy/gamut-kit@0.5.71-alpha.024d4b.0<br/>@codecademy/gamut-labs@19.26.0-alpha.024d4b.0<br/>@codecademy/gamut-patterns@0.6.0-alpha.024d4b.0<br/>@codecademy/gamut-styles@11.10.0-alpha.024d4b.0<br/>@codecademy/gamut-system@0.8.0-alpha.024d4b.0<br/>@codecademy/gamut-tests@2.6.0-alpha.024d4b.0<br/>@codecademy/gamut@37.3.0-alpha.024d4b.0<br/>@codecademy/konamimojisplosion@0.3.0-alpha.024d4b.0<br/>@codecademy/macros@2.2.0-alpha.024d4b.0<br/>@codecademy/markdown-overrides@0.6.0-alpha.024d4b.0<br/>@codecademy/monaco@0.4.0-alpha.024d4b.0<br/>@codecademy/styleguide@44.3.0-alpha.024d4b.0<br/>@codecademy/tracking@0.14.0-alpha.024d4b.0<br/>@codecademy/variance@0.18.0-alpha.024d4b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b64b9f94826ef63495461--gamut-preview.netlify.app>https://613b64b9f94826ef63495461--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b64b9f94826ef63495461>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.72-alpha.77397e.0<br/>@codecademy/gamut-labs@19.26.1-alpha.77397e.0<br/>@codecademy/gamut@37.3.1-alpha.77397e.0<br/>@codecademy/monaco@0.4.1-alpha.77397e.0<br/>@codecademy/styleguide@44.3.1-alpha.77397e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b68ae36dc13f1709b1617--gamut-preview.netlify.app>https://613b68ae36dc13f1709b1617--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b68ae36dc13f1709b1617>Deploy Logs</a></p>

**Pull request merged**
