### PR TITLE
fix: use separate eslint-fix config

### PR DESCRIPTION
**Pull request by jakemhiller**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.acbaf3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602e78e2edaee923229661d6--gamut-preview.netlify.app>https://602e78e2edaee923229661d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602e78e2edaee923229661d6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.6c715f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.2b770a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60356af6c0501000cb543bff--gamut-preview.netlify.app>https://60356af6c0501000cb543bff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60356af6c0501000cb543bff>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.e38ab1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60357230ac15a10e910b5b81--gamut-preview.netlify.app>https://60357230ac15a10e910b5b81--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60357230ac15a10e910b5b81>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.17c800.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603573bb55a4140b62fb58d4--gamut-preview.netlify.app>https://603573bb55a4140b62fb58d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603573bb55a4140b62fb58d4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.e79115.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603581787fc48b0bbde7116d--gamut-preview.netlify.app>https://603581787fc48b0bbde7116d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603581787fc48b0bbde7116d>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@4.0.1-alpha.003dbf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6037d8e24f9c271c658db5f1--gamut-preview.netlify.app>https://6037d8e24f9c271c658db5f1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6037d8e24f9c271c658db5f1>Deploy Logs</a></p>

**Pull request merged**
