### PR TITLE
chore(Docs): Add deprecations and consolidate molecules / orgs

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Makes this up to date.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@33.3.7-alpha.06aaa6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e0eab3e73fc00ce57cfe0--gamut-preview.netlify.app>https://605e0eab3e73fc00ce57cfe0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e0eab3e73fc00ce57cfe0>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Awesome thanks. Could you also put a `@deprecated` on the components themselves so we get ~strikethroughs~ in editors?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.39-alpha.ee0f09.0<br/>@codecademy/gamut-labs@13.2.2-alpha.ee0f09.0<br/>@codecademy/gamut@29.4.6-alpha.ee0f09.0<br/>@codecademy/styleguide@33.3.7-alpha.ee0f09.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.4-alpha.9f8bda.0<br/>@codecademy/gamut-kit@0.2.39-alpha.9f8bda.0<br/>@codecademy/gamut-labs@13.2.2-alpha.9f8bda.0<br/>@codecademy/gamut-styles@9.1.1-alpha.9f8bda.0<br/>@codecademy/gamut-tests@2.3.1-alpha.9f8bda.0<br/>@codecademy/gamut@29.4.6-alpha.9f8bda.0<br/>@codecademy/konamimojisplosion@0.2.1-alpha.9f8bda.0<br/>@codecademy/markdown-overrides@0.5.14-alpha.9f8bda.0<br/>@codecademy/styleguide@33.3.7-alpha.9f8bda.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e1a4a4a719400b822c8bd--gamut-preview.netlify.app>https://605e1a4a4a719400b822c8bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e1a4a4a719400b822c8bd>Deploy Logs</a></p>

**Pull request merged**
