### PR TITLE
fix: allow empty strings for anchor and button hrefs

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Allow `""` as the href for `Anchor`s and `Button`s.

`""` as a href for an `<a>` makes it reload the page when clicked, which sometimes is the desired effect: e.g. on email verification pages.

image

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1388
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.48-alpha.91ecc9.0<br/>@codecademy/gamut-labs@13.2.11-alpha.91ecc9.0<br/>@codecademy/gamut@29.7.2-alpha.91ecc9.0<br/>@codecademy/styleguide@33.6.3-alpha.91ecc9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606b639c6ce2d400c04fcc37--gamut-preview.netlify.app>https://606b639c6ce2d400c04fcc37--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606b639c6ce2d400c04fcc37>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.217453.0<br/>@codecademy/gamut-labs@13.3.1-alpha.217453.0<br/>@codecademy/gamut@29.8.1-alpha.217453.0<br/>@codecademy/styleguide@33.7.2-alpha.217453.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606cdda57786dc1ecf02514d--gamut-preview.netlify.app>https://606cdda57786dc1ecf02514d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606cdda57786dc1ecf02514d>Deploy Logs</a></p>

**Pull request merged**
