### PR TITLE
fix: used useIsomorphicLayoutEffect instead of useLayoutEffect

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Uses `useIsomorphicLayoutEffect` instead of `useLayoutEffect` so React will stop complaining in SSR.

https://codecademy.slack.com/archives/CQ98K8PT6/p1611861223085600

### PR Checklist

- ~[ ] Related to designs:~
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by rogervera — APPROVED** [review]
TIL

**Review by borisonr — APPROVED** [review]
thanks!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.16-alpha.e7ce06.0<br/>@codecademy/gamut-labs@7.16.4-alpha.e7ce06.0<br/>@codecademy/gamut@20.0.3-alpha.e7ce06.0<br/>@codecademy/styleguide@22.0.3-alpha.e7ce06.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6013264debf8ff4813cb25d0--gamut-preview.netlify.app>https://6013264debf8ff4813cb25d0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6013264debf8ff4813cb25d0>Deploy Logs</a></p>

**Pull request merged**
