### PR TITLE
fix(Anchor): Interface hover => primary GM-314

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Fixes a regression issue for interface anchors where the text color for hover states didn't change.  This updates it to the correct color - primary.
* Changes anchor prop aliases to `color` over the older `textColor` work around prop name.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/N6TfoPI5OA7GanX6Zl8nWj/Buttons-%26-Links
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-314
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.15-alpha.da3114.0<br/>@codecademy/gamut-labs@19.19.1-alpha.da3114.0<br/>@codecademy/gamut@35.10.2-alpha.da3114.0<br/>@codecademy/styleguide@42.6.7-alpha.da3114.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610aba09b53b72049170c32a--gamut-preview.netlify.app>https://610aba09b53b72049170c32a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610aba09b53b72049170c32a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.d02bfa.0<br/>@codecademy/gamut-labs@19.19.5-alpha.d02bfa.0<br/>@codecademy/gamut@35.12.3-alpha.d02bfa.0<br/>@codecademy/styleguide@42.7.3-alpha.d02bfa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d7f6814cf62ee82b6b58a--gamut-preview.netlify.app>https://610d7f6814cf62ee82b6b58a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d7f6814cf62ee82b6b58a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.21-alpha.855c50.0<br/>@codecademy/gamut-labs@19.19.7-alpha.855c50.0<br/>@codecademy/gamut@35.13.1-alpha.855c50.0<br/>@codecademy/styleguide@42.7.6-alpha.855c50.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611163781bf4860f74e6de3b--gamut-preview.netlify.app>https://611163781bf4860f74e6de3b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611163781bf4860f74e6de3b>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Review by JoshuaKGoldberg — COMMENTED** [review]
Err, what's the context here?

And why was `textColor` ok before but not anymore?

**Comment by codecaaron** [comment]
> Err, what's the context here?
> 
> And why was `textColor` ok before but not anymore?

@JoshuaKGoldberg just a slow clean up to migrate all `textColor` references to `color` as they are identical and the technical problems that prevented using `color` as a prop have been fixed.  While it is now available textColor lives on and preferably we only have 1 prop for the `color` property, and I've been updating it slowly towards a soft deprecation.

**Review by JoshuaKGoldberg — APPROVED** [review]
okie dokie

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.375e10.0<br/>@codecademy/gamut-labs@19.19.8-alpha.375e10.0<br/>@codecademy/gamut@35.14.1-alpha.375e10.0<br/>@codecademy/styleguide@42.7.8-alpha.375e10.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6111b6ea36ed455d687321d8--gamut-preview.netlify.app>https://6111b6ea36ed455d687321d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6111b6ea36ed455d687321d8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.23-alpha.edc0ed.0<br/>@codecademy/gamut-labs@19.19.9-alpha.edc0ed.0<br/>@codecademy/gamut@36.0.1-alpha.edc0ed.0<br/>@codecademy/styleguide@43.0.1-alpha.edc0ed.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6113f1d06e393a151d069ead--gamut-preview.netlify.app>https://6113f1d06e393a151d069ead--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6113f1d06e393a151d069ead>Deploy Logs</a></p>

**Pull request merged**
