### PR TITLE
feat: add React icon

### PR DESCRIPTION
**Pull request by natalieweesh**
## Overview
add a React icon for use on the butterbar on the React 102 syllabus page (to redirect ppl to react-101) 
(needed for this PR: https://github.com/codecademy-engineering/Codecademy/pull/19427/)
Screen Shot 2020-09-28 at 2 23 37 PM

### PR Checklist

- [x] Related to designs: (found the deprecated React icon and used that svg)
- [x] Related to JIRA ticket: EGG-194
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
Screen Shot 2020-09-28 at 2 19 30 PM

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f722c19a42cb528b4b36725--gamut-preview.netlify.app>https://5f722c19a42cb528b4b36725--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f722c19a42cb528b4b36725>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM with the updated format. Nice!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.7.0-alpha.a4f466.0<br/>@codecademy/gamut-labs@4.2.3-alpha.a4f466.0<br/>@codecademy/gamut@16.0.13-alpha.a4f466.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f722ffff9a23153dbd0fb05--gamut-preview.netlify.app>https://5f722ffff9a23153dbd0fb05--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f722ffff9a23153dbd0fb05>Deploy Logs</a></p>

**Pull request merged**
