### PR TITLE
feat!: clean up tracker and remove auth token

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

* Removes the auth token from the package because I can repro not needing to use it in production.
* Cleans up the input options to be an object, instead of a list of params

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1431
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@1.0.0-alpha.011d04.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608ede5f6e4006f1b1bc215e--gamut-preview.netlify.app>https://608ede5f6e4006f1b1bc215e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608ede5f6e4006f1b1bc215e>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@1.0.0-alpha.13d8ed.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.12.0-alpha.aa8188.0<br/>@codecademy/gamut-kit@0.3.67-alpha.aa8188.0<br/>@codecademy/gamut-labs@15.2.7-alpha.aa8188.0<br/>@codecademy/gamut@32.8.0-alpha.aa8188.0<br/>@codecademy/styleguide@36.10.0-alpha.aa8188.0<br/>@codecademy/tracking@1.0.0-alpha.aa8188.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@1.0.0-alpha.035f58.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60900da3371844009ca45e0d--gamut-preview.netlify.app>https://60900da3371844009ca45e0d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60900da3371844009ca45e0d>Deploy Logs</a></p>

**Pull request merged**
