### PR TITLE
fix: prevent VO from reading Close Icon in Alert

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

prevent "Close Icon" from being read by VoiceOver when an Alert pops up

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: EGG-1529
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.4-alpha.635532.0<br/>@codecademy/gamut@18.0.1-alpha.635532.0<br/>@codecademy/styleguide@20.0.1-alpha.635532.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc66ecdf74c00008f0d4718--gamut-preview.netlify.app>https://5fc66ecdf74c00008f0d4718--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc66ecdf74c00008f0d4718>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.5-alpha.dfa8a3.0<br/>@codecademy/gamut@18.0.1-alpha.dfa8a3.0<br/>@codecademy/styleguide@20.0.2-alpha.dfa8a3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc68de48cb00524f627a58b--gamut-preview.netlify.app>https://5fc68de48cb00524f627a58b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc68de48cb00524f627a58b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.caf218.0<br/>@codecademy/gamut@19.0.2-alpha.caf218.0<br/>@codecademy/styleguide@21.0.2-alpha.caf218.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc6a0456399614274e5d271--gamut-preview.netlify.app>https://5fc6a0456399614274e5d271--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc6a0456399614274e5d271>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.348c6b.0<br/>@codecademy/gamut@19.0.2-alpha.348c6b.0<br/>@codecademy/styleguide@21.0.2-alpha.348c6b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7aab810d925bc0c69f1c1--gamut-preview.netlify.app>https://5fc7aab810d925bc0c69f1c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7aab810d925bc0c69f1c1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.8e81de.0<br/>@codecademy/gamut@19.0.2-alpha.8e81de.0<br/>@codecademy/styleguide@21.0.2-alpha.8e81de.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7b8eaf74c00c3490d446f--gamut-preview.netlify.app>https://5fc7b8eaf74c00c3490d446f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7b8eaf74c00c3490d446f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.0b30f3.0<br/>@codecademy/gamut@19.0.2-alpha.0b30f3.0<br/>@codecademy/styleguide@21.0.2-alpha.0b30f3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7c853328be6d7806ae90e--gamut-preview.netlify.app>https://5fc7c853328be6d7806ae90e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7c853328be6d7806ae90e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.d57008.0<br/>@codecademy/gamut@19.0.2-alpha.d57008.0<br/>@codecademy/styleguide@21.0.2-alpha.d57008.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7ccfbdff6b1aa4165380c--gamut-preview.netlify.app>https://5fc7ccfbdff6b1aa4165380c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7ccfbdff6b1aa4165380c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.8e0612.0<br/>@codecademy/gamut@19.0.2-alpha.8e0612.0<br/>@codecademy/styleguide@21.0.2-alpha.8e0612.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7cf867462cedff469025c--gamut-preview.netlify.app>https://5fc7cf867462cedff469025c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7cf867462cedff469025c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.87ce7f.0<br/>@codecademy/gamut@19.0.2-alpha.87ce7f.0<br/>@codecademy/styleguide@21.0.2-alpha.87ce7f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7d396f041f9bc02021353--gamut-preview.netlify.app>https://5fc7d396f041f9bc02021353--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7d396f041f9bc02021353>Deploy Logs</a></p>

**Pull request merged**
