### PR TITLE
feat(icon): Megaphone Icon

### PR DESCRIPTION
**Pull request by songstephen**
### Overview

Added megaphone-icon.svg to gamut-icons

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.9.4-alpha.fd52e7.0<br/>@codecademy/gamut-kit@0.5.67-alpha.fd52e7.0<br/>@codecademy/gamut-labs@19.24.11-alpha.fd52e7.0<br/>@codecademy/gamut@37.1.3-alpha.fd52e7.0<br/>@codecademy/monaco@0.3.15-alpha.fd52e7.0<br/>@codecademy/styleguide@44.1.7-alpha.fd52e7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a3d3782ba8638ef8fa2c9--gamut-preview.netlify.app>https://613a3d3782ba8638ef8fa2c9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a3d3782ba8638ef8fa2c9>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by songstephen** [comment]
Sorry to rerequest a review — the icon was too thick and I was trying to edit the stroke width without doing the weird Figma exports. But the only way I could do it was to apply a `stroke-width="0.624"` property to get it to be the same width as our other icons. Would this cause any problems?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.9.4-alpha.173562.0<br/>@codecademy/gamut-kit@0.5.67-alpha.173562.0<br/>@codecademy/gamut-labs@19.24.11-alpha.173562.0<br/>@codecademy/gamut@37.1.3-alpha.173562.0<br/>@codecademy/monaco@0.3.15-alpha.173562.0<br/>@codecademy/styleguide@44.1.7-alpha.173562.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a446b7a3d702fe85d95c1--gamut-preview.netlify.app>https://613a446b7a3d702fe85d95c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a446b7a3d702fe85d95c1>Deploy Logs</a></p>

**Comment by codecaaron** [comment]
> o rerequest a review — the icon was too thick and I was trying to edit the stroke width without doing the weird Figma exports. But the only way I could do it was to apply a `stroke-width="0.625"` property to get it to be the same width as our other icons. Would this cause any problems?

I don't think so as it's going to get converted to a single path anyway.  We can keep an eye on it though.

**Comment by songstephen** [comment]
Sounds good, the stroke widths are calculated correctly when I import them into Figma, but I know the actual markup with the `transform` x `stroke-width` could be messy. Happy to go back and touch this up again if we're experiencing issues.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.9.4-alpha.e7f602.0<br/>@codecademy/gamut-kit@0.5.68-alpha.e7f602.0<br/>@codecademy/gamut-labs@19.25.0-alpha.e7f602.0<br/>@codecademy/gamut-tests@2.5.0-alpha.e7f602.0<br/>@codecademy/gamut@37.2.0-alpha.e7f602.0<br/>@codecademy/konamimojisplosion@0.2.55-alpha.e7f602.0<br/>@codecademy/monaco@0.3.15-alpha.e7f602.0<br/>@codecademy/styleguide@44.2.0-alpha.e7f602.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a6467eb106308af312310--gamut-preview.netlify.app>https://613a6467eb106308af312310--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a6467eb106308af312310>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.9.4-alpha.9539f6.0<br/>@codecademy/gamut-kit@0.5.69-alpha.9539f6.0<br/>@codecademy/gamut-labs@19.25.1-alpha.9539f6.0<br/>@codecademy/gamut@37.2.1-alpha.9539f6.0<br/>@codecademy/monaco@0.3.16-alpha.9539f6.0<br/>@codecademy/styleguide@44.2.1-alpha.9539f6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a6712d136470f0fbf3ec7--gamut-preview.netlify.app>https://613a6712d136470f0fbf3ec7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a6712d136470f0fbf3ec7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.10.2-alpha.851a3e.0<br/>@codecademy/gamut-kit@0.5.75-alpha.851a3e.0<br/>@codecademy/gamut-labs@19.26.4-alpha.851a3e.0<br/>@codecademy/gamut@37.3.3-alpha.851a3e.0<br/>@codecademy/monaco@0.4.3-alpha.851a3e.0<br/>@codecademy/styleguide@44.4.1-alpha.851a3e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613fe56d4386a700b8c5a0c0--gamut-preview.netlify.app>https://613fe56d4386a700b8c5a0c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613fe56d4386a700b8c5a0c0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.10.2-alpha.e4cef5.0<br/>@codecademy/gamut-kit@0.5.80-alpha.e4cef5.0<br/>@codecademy/gamut-labs@20.0.1-alpha.e4cef5.0<br/>@codecademy/gamut@37.5.1-alpha.e4cef5.0<br/>@codecademy/monaco@0.4.6-alpha.e4cef5.0<br/>@codecademy/styleguide@44.6.2-alpha.e4cef5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61426a035bc1131576f9debd--gamut-preview.netlify.app>https://61426a035bc1131576f9debd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61426a035bc1131576f9debd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.10.2-alpha.71276b.0<br/>@codecademy/gamut-kit@0.5.83-alpha.71276b.0<br/>@codecademy/gamut-labs@20.0.4-alpha.71276b.0<br/>@codecademy/gamut@37.5.3-alpha.71276b.0<br/>@codecademy/monaco@0.4.8-alpha.71276b.0<br/>@codecademy/styleguide@44.6.6-alpha.71276b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61449a1009d01a2c0ed2c7b6--gamut-preview.netlify.app>https://61449a1009d01a2c0ed2c7b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61449a1009d01a2c0ed2c7b6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.10.2-alpha.05de7d.0<br/>@codecademy/gamut-kit@0.5.84-alpha.05de7d.0<br/>@codecademy/gamut-labs@20.1.1-alpha.05de7d.0<br/>@codecademy/gamut@37.5.3-alpha.05de7d.0<br/>@codecademy/monaco@0.4.8-alpha.05de7d.0<br/>@codecademy/styleguide@44.6.7-alpha.05de7d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6144e4cb0f59facd44699855--gamut-preview.netlify.app>https://6144e4cb0f59facd44699855--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6144e4cb0f59facd44699855>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.10.2-alpha.c45047.0<br/>@codecademy/gamut-kit@0.5.85-alpha.c45047.0<br/>@codecademy/gamut-labs@20.1.2-alpha.c45047.0<br/>@codecademy/gamut@37.6.1-alpha.c45047.0<br/>@codecademy/monaco@0.4.9-alpha.c45047.0<br/>@codecademy/styleguide@44.7.1-alpha.c45047.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148eba18b79431a41a861ab--gamut-preview.netlify.app>https://6148eba18b79431a41a861ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148eba18b79431a41a861ab>Deploy Logs</a></p>

**Pull request merged**
