### PR TITLE
fix(LayoutMenu): add aria-expanded

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Adds `aria-expanded` to the `Anchor` we are now using instead of the `AccordionButton` within the `LayoutMenu` to fix an accessibility bug.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-1192](https://codecademy.atlassian.net/browse/REACH-1192)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by MattSchiller — APPROVED** [review]
This adds `aria-expanded` to the component 👍

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.36-alpha.bd1354.0<br/>@codecademy/gamut-labs@19.22.2-alpha.bd1354.0<br/>@codecademy/styleguide@43.7.4-alpha.bd1354.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611ae193b338d543e259ba4c--gamut-preview.netlify.app>https://611ae193b338d543e259ba4c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611ae193b338d543e259ba4c>Deploy Logs</a></p>

**Review by katiezutter — APPROVED** [review]
Love it!

**Review by codecaaron — APPROVED** [review]

**Pull request merged**
