### PR TITLE
feat(ProLabel): Changes text color to 'background-current'

### PR DESCRIPTION
**Pull request by timjenkins**
### Overview

Changes `<ProLabel>` text color to pull from `background-current` css variable

Screen Shot 2021-07-26 at 11 47 31 AM

### PR Checklist

- [x] Related to designs: [link](https://www.figma.com/file/nWkEaTqiV12SGbbZS0Gmr4/Syllabus-Improvements?node-id=573%3A1)
- [x] Related to JIRA ticket: LX-4780
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]
Just a heads up this will not have an affect until this PR is merged :)

https://github.com/Codecademy/client-modules/pull/1849

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fee7e740e5040783b2924d--gamut-preview.netlify.app>https://60fee7e740e5040783b2924d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fee7e740e5040783b2924d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.73-alpha.1b0bab.0<br/>@codecademy/gamut-labs@19.16.11-alpha.1b0bab.0<br/>@codecademy/gamut@35.4.0-alpha.1b0bab.0<br/>@codecademy/styleguide@42.2.1-alpha.1b0bab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fef0fcc14e1915f2aa3cb3--gamut-preview.netlify.app>https://60fef0fcc14e1915f2aa3cb3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fef0fcc14e1915f2aa3cb3>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🙌

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.9-alpha.dbb5a7.0<br/>@codecademy/gamut-labs@19.18.1-alpha.dbb5a7.0<br/>@codecademy/gamut@35.8.0-alpha.dbb5a7.0<br/>@codecademy/styleguide@42.6.1-alpha.dbb5a7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61089254415ce01e2a626abc--gamut-preview.netlify.app>https://61089254415ce01e2a626abc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61089254415ce01e2a626abc>Deploy Logs</a></p>

**Pull request merged**
