### PR TITLE
feat(GlobalHeader, GlobalFooter): Learner stories link in global footer and global header

### PR DESCRIPTION
**Pull request by j10sanders**
### Overview

Just a link to /learner-stories in the header and footer.  instead of adding feature flag complexity, I think we can just let this marinate until the page is launched.

### PR Checklist

- [x] Related to designs: (designs aren't updated with correct copy, but approved by Tamar)
- [x] Related to JIRA ticket: GROW-2468, GROW-2467
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.34-alpha.c2219f.0<br/>@codecademy/gamut-labs@19.21.2-alpha.c2219f.0<br/>@codecademy/styleguide@43.7.2-alpha.c2219f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611aab05a479420bd5ad4174--gamut-preview.netlify.app>https://611aab05a479420bd5ad4174--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611aab05a479420bd5ad4174>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.36-alpha.129824.0<br/>@codecademy/gamut-labs@19.22.2-alpha.129824.0<br/>@codecademy/styleguide@43.7.4-alpha.129824.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611ae3edabf1243e34243b7b--gamut-preview.netlify.app>https://611ae3edabf1243e34243b7b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611ae3edabf1243e34243b7b>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by saghdaey — APPROVED** [review]
we love 2 see it

**Review by zippyzow — APPROVED** [review]

**Review by BandanaKM — APPROVED** [review]

**Comment by j10sanders** [comment]
@borisonr confirming Tamar QA'd in https://pr-26620.dev-eks.codecademy.com/

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.45-alpha.e59e81.0<br/>@codecademy/gamut-labs@19.23.8-alpha.e59e81.0<br/>@codecademy/styleguide@43.9.2-alpha.e59e81.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61255bb42e5e3f1c6387c6ac--gamut-preview.netlify.app>https://61255bb42e5e3f1c6387c6ac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61255bb42e5e3f1c6387c6ac>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.83-alpha.eb5e7c.0<br/>@codecademy/gamut-labs@20.0.4-alpha.eb5e7c.0<br/>@codecademy/styleguide@44.6.6-alpha.eb5e7c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614496d606a1fb52472c3814--gamut-preview.netlify.app>https://614496d606a1fb52472c3814--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614496d606a1fb52472c3814>Deploy Logs</a></p>

**Pull request merged**
