### PR TITLE
fix: added npmignore and module field for gamut-tests

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

The `.npmignore` is missing so the published package doesn't have a `dist/`.

I don't know that the `module` is necessary but figured we might as well.

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601dbc1b0aa75d8d2394cb2a--gamut-preview.netlify.app>https://601dbc1b0aa75d8d2394cb2a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601dbc1b0aa75d8d2394cb2a>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.30-alpha.887d13.0<br/>@codecademy/gamut-labs@9.2.5-alpha.887d13.0<br/>@codecademy/gamut-tests@1.1.2-alpha.887d13.0<br/>@codecademy/gamut@21.3.3-alpha.887d13.0<br/>@codecademy/styleguide@25.1.6-alpha.887d13.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601ed3ee5f91d44eaa7bca4f--gamut-preview.netlify.app>https://601ed3ee5f91d44eaa7bca4f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601ed3ee5f91d44eaa7bca4f>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.31-alpha.21a561.0<br/>@codecademy/gamut-labs@9.2.9-alpha.21a561.0<br/>@codecademy/gamut-tests@1.1.2-alpha.21a561.0<br/>@codecademy/gamut@21.3.4-alpha.21a561.0<br/>@codecademy/styleguide@25.1.10-alpha.21a561.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6021fb78461e742b471e5f5c--gamut-preview.netlify.app>https://6021fb78461e742b471e5f5c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6021fb78461e742b471e5f5c>Deploy Logs</a></p>

**Pull request merged**
