### PR TITLE
fix(emotion): Add emotion cache settings overrides and default speedy styles

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview

There has been a strange error with cache behavior with conditionally rendered components. Style tags are occasionally not present causing an error.  This change will by default remove the styles from being rendered in the DOM post SSR and allow consuming apps to configure their settings in other ways.  This will not affect SSR styles, only subsequent styles. This shouldn't have any visual effect and a slight performance increase in runtime. The node we mount them to will only be used to hydrate the cache on load. (note: we still need to extract the styles to some target in order to get nth-x selectors to render correctly so we need to keep the current SSR strategy in place)

Changes:
- Adds the ability to overwrite default cache settings.
- Turns on `speedy` by default (this uses constructed stylesheets and is no longer in the dom)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.5.2-alpha.226adf.0<br/>@codecademy/gamut-styles@7.4.7-alpha.226adf.0<br/>@codecademy/gamut@17.3.12-alpha.226adf.0<br/>@codecademy/markdown-overrides@0.3.15-alpha.226adf.0<br/>@codecademy/styleguide@18.8.4-alpha.226adf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb815ce00187e0090acf219--gamut-preview.netlify.app>https://5fb815ce00187e0090acf219--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb815ce00187e0090acf219>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.5.2-alpha.f73f4b.0<br/>@codecademy/gamut-styles@7.4.7-alpha.f73f4b.0<br/>@codecademy/gamut@17.3.12-alpha.f73f4b.0<br/>@codecademy/markdown-overrides@0.3.15-alpha.f73f4b.0<br/>@codecademy/styleguide@18.8.4-alpha.f73f4b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb81c0252c26b0d6b9979ad--gamut-preview.netlify.app>https://5fb81c0252c26b0d6b9979ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb81c0252c26b0d6b9979ad>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.3-alpha.0fded4.0<br/>@codecademy/gamut-styles@7.4.7-alpha.0fded4.0<br/>@codecademy/gamut@17.4.1-alpha.0fded4.0<br/>@codecademy/markdown-overrides@0.3.15-alpha.0fded4.0<br/>@codecademy/styleguide@18.10.2-alpha.0fded4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fbbc3f69e79d3bcfc3901a9--gamut-preview.netlify.app>https://5fbbc3f69e79d3bcfc3901a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fbbc3f69e79d3bcfc3901a9>Deploy Logs</a></p>

**Review by jakemhiller — COMMENTED** [review]
Based on your description it sounds like SSR components won't be styled when the page initially loads? Or are we just talking about components that aren't rendered on load

**Comment by codecaaron** [comment]
> Based on your description it sounds like SSR components won't be styled when the page initially loads? Or are we just talking about components that aren't rendered on load

Ah sorry, this was unclear.  This will not affect SSR, only subsequent styles.  This shouldn't have any visual effect and a slight performance increase in runtime.  The node we mount them to will only be used to hydrate the cache on load.  (note: we still need to extract the styles to _some_ target in order to get `nth-x` selectors to render correctly so we need to keep the current SSR strategy in place)

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.4-alpha.b284b1.0<br/>@codecademy/gamut-styles@7.4.7-alpha.b284b1.0<br/>@codecademy/gamut@17.4.2-alpha.b284b1.0<br/>@codecademy/markdown-overrides@0.3.15-alpha.b284b1.0<br/>@codecademy/styleguide@18.10.3-alpha.b284b1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fbd47e5a151b400f1a20fca--gamut-preview.netlify.app>https://5fbd47e5a151b400f1a20fca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fbd47e5a151b400f1a20fca>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.1-alpha.1a9e79.0<br/>@codecademy/gamut-styles@7.4.7-alpha.1a9e79.0<br/>@codecademy/gamut@17.4.3-alpha.1a9e79.0<br/>@codecademy/markdown-overrides@0.3.15-alpha.1a9e79.0<br/>@codecademy/styleguide@19.0.1-alpha.1a9e79.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc454c5da660a4a814aa096--gamut-preview.netlify.app>https://5fc454c5da660a4a814aa096--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc454c5da660a4a814aa096>Deploy Logs</a></p>

**Pull request merged**
