### PR TITLE
fix: add role to ToolTip for axe

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

change ToolTip aria-labelledby to aria-describedby to pass cypress-axe tests in portal-app

related PR in portal-app: https://github.com/codecademy-engineering/portal-app/pull/440

this was the axe error: 
```
Description:  Ensures ARIA attributes are allowed for an element's role
Elements must only use allowed ARIA attributes
https://dequeuniversity.com/rules/axe/4.2/aria-allowed-attr?application=axeAPI
"Fix all of the following:
  ARIA attribute cannot be used: aria-labelledby"
```

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: EGG-1345
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.37-alpha.0f0c10.0<br/>@codecademy/gamut-labs@19.22.3-alpha.0f0c10.0<br/>@codecademy/gamut@36.4.5-alpha.0f0c10.0<br/>@codecademy/styleguide@43.7.5-alpha.0f0c10.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611c065b8991920dabef5849--gamut-preview.netlify.app>https://611c065b8991920dabef5849--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611c065b8991920dabef5849>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.37-alpha.b69dfa.0<br/>@codecademy/gamut-labs@19.22.3-alpha.b69dfa.0<br/>@codecademy/gamut@36.4.5-alpha.b69dfa.0<br/>@codecademy/styleguide@43.7.5-alpha.b69dfa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611c0e27f4fe69095152f713--gamut-preview.netlify.app>https://611c0e27f4fe69095152f713--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611c0e27f4fe69095152f713>Deploy Logs</a></p>

**Review by dreamwasp — CHANGES_REQUESTED** [review]
i'm no longer getting the description on Voiceover when i tab to the target (which is now the icon inside the div, not the div itself 🤔)-- i think with 'aria-describedby', we may explicitly need to make this div tabbable... @katiezutter + @JoshuaKGoldberg may have better insight into this

**Comment by katiezutter** [comment]
> i'm no longer getting the description on Voiceover when i tab to the target (which is now the icon inside the div, not the div itself 🤔)-- i think with `aria-describedby`, we may explicitly need to make this div tabbable... @katiezutter + @JoshuaKGoldberg may have better insight into this

I unfortunately don't have much insight here, but I am able to hear the description in the tooltip just by tabbing using VO, so that's strange! I am hearing some duplicate narration though, which I thought we solved in the spring (https://codecademy.atlassian.net/browse/GROW-2360) but it might be back. (That would be separate from this ticket though!)

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.37-alpha.27026e.0<br/>@codecademy/gamut-labs@19.22.3-alpha.27026e.0<br/>@codecademy/gamut@36.4.5-alpha.27026e.0<br/>@codecademy/styleguide@43.7.5-alpha.27026e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611d290c46e30f1195f090b6--gamut-preview.netlify.app>https://611d290c46e30f1195f090b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611d290c46e30f1195f090b6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.37-alpha.1da38e.0<br/>@codecademy/gamut-labs@19.22.3-alpha.1da38e.0<br/>@codecademy/gamut@36.4.5-alpha.1da38e.0<br/>@codecademy/styleguide@43.7.5-alpha.1da38e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611d2ba2b766d300dd25a8e9--gamut-preview.netlify.app>https://611d2ba2b766d300dd25a8e9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611d2ba2b766d300dd25a8e9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.37-alpha.5fc77d.0<br/>@codecademy/gamut-labs@19.22.3-alpha.5fc77d.0<br/>@codecademy/gamut@36.4.5-alpha.5fc77d.0<br/>@codecademy/styleguide@43.7.5-alpha.5fc77d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611d2e73fd0006009281699c--gamut-preview.netlify.app>https://611d2e73fd0006009281699c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611d2e73fd0006009281699c>Deploy Logs</a></p>

**Comment by natalieweesh** [comment]
@dreamwasp adding `role="button"` seems to do the trick! axe doesn't complain anymore and the VO still works the same as before

**Review by dreamwasp — APPROVED** [review]
works like a dream 🙏

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.38-alpha.796207.0<br/>@codecademy/gamut-labs@19.23.1-alpha.796207.0<br/>@codecademy/gamut@36.4.5-alpha.796207.0<br/>@codecademy/styleguide@43.7.6-alpha.796207.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611d730c79eaf50b3d51186c--gamut-preview.netlify.app>https://611d730c79eaf50b3d51186c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611d730c79eaf50b3d51186c>Deploy Logs</a></p>

**Pull request merged**
