### PR TITLE
feat: Add file download icon

### PR DESCRIPTION
**Pull request by ahmed-abdallah**
### PR Checklist

- [ ] Related to Abstract designs:https://drive.google.com/file/d/17sY7BJQJLx_Y_Fjkso75fdPJq7SsOZh-/view?usp=sharing
- [ ] Related to JIRA ticket: EGG-224
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Swell!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.5.1-alpha.1a1f4f.0<br/>@codecademy/gamut-labs@4.1.7-alpha.1a1f4f.0<br/>@codecademy/gamut@16.0.10-alpha.1a1f4f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.5.1-alpha.3cf492.0<br/>@codecademy/gamut-labs@4.1.7-alpha.3cf492.0<br/>@codecademy/gamut@16.0.10-alpha.3cf492.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6cce0d7b19160f4c19d1f3--gamut-preview.netlify.app>https://5f6cce0d7b19160f4c19d1f3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6cce0d7b19160f4c19d1f3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6cce1a90d94b010c2cef43--gamut-preview.netlify.app>https://5f6cce1a90d94b010c2cef43--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6cce1a90d94b010c2cef43>Deploy Logs</a></p>

**Pull request merged**
