### PR TITLE
feat(GridForm): add placeholder field for TextArea in GridForm

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Adds placeholder field to TextArea component in GridForm. You can check it out on the ToolTip Section of the GridForm page.

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [egg-1307](https://codecademy.atlassian.net/browse/EGG-1307)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.114-alpha.a76ada.0<br/>@codecademy/gamut-labs@18.1.5-alpha.a76ada.0<br/>@codecademy/gamut@33.1.1-alpha.a76ada.0<br/>@codecademy/styleguide@40.0.2-alpha.a76ada.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ad66d4a34cdd00a04a55df--gamut-preview.netlify.app>https://60ad66d4a34cdd00a04a55df--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ad66d4a34cdd00a04a55df>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.114-alpha.3daa41.0<br/>@codecademy/gamut-labs@18.1.5-alpha.3daa41.0<br/>@codecademy/gamut@33.1.1-alpha.3daa41.0<br/>@codecademy/styleguide@40.0.2-alpha.3daa41.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ad68a7cafb5c009373facc--gamut-preview.netlify.app>https://60ad68a7cafb5c009373facc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ad68a7cafb5c009373facc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.117-alpha.5b737d.0<br/>@codecademy/gamut-labs@18.1.8-alpha.5b737d.0<br/>@codecademy/gamut@33.1.4-alpha.5b737d.0<br/>@codecademy/styleguide@40.0.5-alpha.5b737d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ae4a0f923d5400c60c2c04--gamut-preview.netlify.app>https://60ae4a0f923d5400c60c2c04--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ae4a0f923d5400c60c2c04>Deploy Logs</a></p>

**Review by katiezutter — APPROVED** [review]
Looks great - thanks!!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.1-alpha.0cfbc4.0<br/>@codecademy/gamut-labs@18.3.1-alpha.0cfbc4.0<br/>@codecademy/gamut@33.2.1-alpha.0cfbc4.0<br/>@codecademy/styleguide@40.1.1-alpha.0cfbc4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b0f4194cb2160ed32feca8--gamut-preview.netlify.app>https://60b0f4194cb2160ed32feca8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b0f4194cb2160ed32feca8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.1-alpha.b16dfa.0<br/>@codecademy/gamut-labs@18.3.1-alpha.b16dfa.0<br/>@codecademy/gamut@33.3.0-alpha.b16dfa.0<br/>@codecademy/styleguide@40.2.0-alpha.b16dfa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b0fec6f918df552363255f--gamut-preview.netlify.app>https://60b0fec6f918df552363255f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b0fec6f918df552363255f>Deploy Logs</a></p>

**Pull request merged**
