### PR TITLE
fix(LayoutMenu): Emotion Only GM-258

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Refactors LayoutMenu to use Anchor instead of Accordion button.

https://user-images.githubusercontent.com/52927224/122478595-b2b2b680-cf97-11eb-964e-4a5f853ecd6b.mov

Before: 
Screen Shot 2021-06-17 at 6 09 45 PM

After:
Screen Shot 2021-06-17 at 6 10 04 PM

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-258
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.38-alpha.9f2cc9.0<br/>@codecademy/gamut-labs@19.10.4-alpha.9f2cc9.0<br/>@codecademy/styleguide@41.10.8-alpha.9f2cc9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cbc293175d6208b1159185--gamut-preview.netlify.app>https://60cbc293175d6208b1159185--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cbc293175d6208b1159185>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.38-alpha.18dbc0.0<br/>@codecademy/gamut-labs@19.10.4-alpha.18dbc0.0<br/>@codecademy/styleguide@41.10.8-alpha.18dbc0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cbc45fbac8840ad13ed5a8--gamut-preview.netlify.app>https://60cbc45fbac8840ad13ed5a8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cbc45fbac8840ad13ed5a8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.38-alpha.8758ab.0<br/>@codecademy/gamut-labs@19.10.4-alpha.8758ab.0<br/>@codecademy/styleguide@41.10.8-alpha.8758ab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cbde90cd12ea27db3f68a7--gamut-preview.netlify.app>https://60cbde90cd12ea27db3f68a7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cbde90cd12ea27db3f68a7>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Very cool!

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
