### PR TITLE
fix: use internal App Store and Google Play images

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Uses checked-in images instead of externally hosted ones because external ones go down sometimes...

...and it's generally good to limit number of unique domain across downloads anyway.

Our end-to-end tests all started timing out this morning. No relevant code changes to blame. 

Turns out loading the "Download on the App Store" image hosted on apple's s3 account was giving a 504 bad gateway. 

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1409
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Review by dreamwasp — APPROVED** [review]
🚢

**Comment by JoshuaKGoldberg** [comment]
Oh and:

Screenshot of Apple and Google download links

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.18-alpha.631665.0<br/>@codecademy/gamut-labs@13.4.10-alpha.631665.0<br/>@codecademy/styleguide@33.9.10-alpha.631665.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607720c3c6cde600d8988bea--gamut-preview.netlify.app>https://607720c3c6cde600d8988bea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607720c3c6cde600d8988bea>Deploy Logs</a></p>

**Pull request merged**
