### PR TITLE
feat(Header): Hide header on print views

### PR DESCRIPTION
**Pull request by rogervera**
## Title
Adds a media query to hide header on print views.

### PR Checklist

- [x] Related to Abstract designs: [Link](https://app.abstract.com/projects/2127441a-6206-48a8-a50c-2babdc45377e/branches/a734bce1-87bc-4d73-ae7a-ef651d9bedf9/commits/6c4d60ada200d6c634fd0db54311c78a0be16a1d/files/ef858d0c-8c13-488f-8501-4d58a1e002ce/layers/41E5781E-53D5-4C34-AF4E-F26F9B3C5017?collectionId=b9e222a3-8b62-4f91-9df5-dbc07e6aadf9&collectionLayerId=d5a904a2-23a3-4b92-98a0-32844f106cdb)
- [x] Related to JIRA ticket: [DISCO-202](https://codecademy.atlassian.net/browse/DISCO-202)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

**Note:** 
- [ ] Confirmed this as a **global change for headers on print view** with Tímea (Discovery and Navigation team designer)

### Description
43f7b36f-0973-47e1-9a79-15143d21ac2d

Screen Shot 2020-05-13 at 12 10 41 PM

Screen Shot 2020-05-13 at 12 12 06 PM

---

## Merging your changes

When you are ready to merge to master and publish your changes, use the "squash and merge" button in GitHub, and follow the [PR Title Guide](https://github.com/Codecademy/client-modules#pr-title-guide) to format your PR title and write your PR merge description.

**IMPORTANT:** If your PR contains breaking changes, please remember to follow the instructions for breaking changes!

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.16-alpha.2ab8f8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ebbfd2c7a239b3f424cd2e3--codecademy-styleguide.netlify.app>https://5ebbfd2c7a239b3f424cd2e3--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5ebbfd2c7a239b3f424cd2e3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.16-alpha.40ba3e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ebc1f0cf2f1f96ac34dc78a--codecademy-styleguide.netlify.app>https://5ebc1f0cf2f1f96ac34dc78a--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5ebc1f0cf2f1f96ac34dc78a>Deploy Logs</a></p>

**Comment by judahtanthony** [comment]
> 💯. Maybe the footer should have this too?

Good call.  I'm embarrassed to say I didn't know the footer was in here.

**Comment by rogervera** [comment]
> 💯. Maybe the footer should have this too?

@JoshuaKGoldberg, noted with @judahtanthony! When/if the footer is ported to client-modules we can add the rule. Right now, that would mean adding it in the respective repos (monolith and static-sites).

**Pull request merged**
