### PR TITLE
feat(Text): Add more common utility variants / states as props GM-248

### PR DESCRIPTION
**Pull request by codecaaron**
### Props
There are a few commonly used style mixins that either are hard to migrate (like the fade-truncation scss mixin) or require custom overrides (in CSS-in-JS - `no-select` + `font-smoothing` + `screen-readeronly`):

This adds a few of these common patterns and inclusions as variant / state props - to remove common cases where we repeatedly extended a component with identical styles in different locations. 

**New Box Props**
- `no-select`: Toggle user selection / touch callouts

**Example**
```tsx
<Box no-select>
  <img src="x" />
</Box>
```

**New Text Props**
- `center`: Toggle `text-align: center`
- `block`: Toggle `display: block;`
- `screenreader`: Render text outside of document flow, while still visible for screenreaders.
- `smooth`: Enable font-smoothing.
- `truncate`:  Common truncation patterns for limiting text to a single line.
  - `ellipsis`: Standard ` text-overflow: elipsis`
  - `fade`: Fades the end of the line into the the background of the page.  (From the monolith mixin: `@include fade-truncation`)

**Example**
```tsx
// Truncation
<Text truncate="ellipsis" />
<Text truncate="fade">{superLongString}</Truncate>

// Screenreader
<Text screenreader>My Hiddent Text!</Text>

// Font Smoothing
<Text smooth />
```

### Typings 
 Certain properties like ` WebkitFontSmoothing` we not configurable through variance CSS functions.  So the typings have been expanded here to include the necessary Vendor properties.  This change applies to `css` `variant` and `states`.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-248
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.33ae17.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.33ae17.0<br/>@codecademy/gamut-kit@0.4.23-alpha.33ae17.0<br/>@codecademy/gamut-labs@19.5.1-alpha.33ae17.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.33ae17.0<br/>@codecademy/gamut-styles@11.2.1-alpha.33ae17.0<br/>@codecademy/gamut-tests@2.4.8-alpha.33ae17.0<br/>@codecademy/gamut@34.6.1-alpha.33ae17.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.33ae17.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.33ae17.0<br/>@codecademy/styleguide@41.7.6-alpha.33ae17.0<br/>@codecademy/variance@0.14.1-alpha.33ae17.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c76c57e8a42bbbcc136e57--gamut-preview.netlify.app>https://60c76c57e8a42bbbcc136e57--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c76c57e8a42bbbcc136e57>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
I'm a little worried about adding such significant non-CSS props as part of the core interface... but want to get some data from the wild on whether that's useful vs. confusing. Let's do it 🚢

**Review by dreamwasp — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.2.1-alpha.127bfd.0<br/>@codecademy/gamut-illustrations@0.17.6-alpha.127bfd.0<br/>@codecademy/gamut-kit@0.4.30-alpha.127bfd.0<br/>@codecademy/gamut-labs@19.8.1-alpha.127bfd.0<br/>@codecademy/gamut-patterns@0.4.1-alpha.127bfd.0<br/>@codecademy/gamut-styles@11.3.1-alpha.127bfd.0<br/>@codecademy/gamut-tests@2.4.9-alpha.127bfd.0<br/>@codecademy/gamut@34.7.2-alpha.127bfd.0<br/>@codecademy/konamimojisplosion@0.2.40-alpha.127bfd.0<br/>@codecademy/markdown-overrides@0.5.52-alpha.127bfd.0<br/>@codecademy/styleguide@41.9.1-alpha.127bfd.0<br/>@codecademy/variance@0.14.1-alpha.127bfd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca682e3c05ef00cacdabae--gamut-preview.netlify.app>https://60ca682e3c05ef00cacdabae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca682e3c05ef00cacdabae>Deploy Logs</a></p>

**Pull request merged**
