### PR TITLE
fix(Text): Make small text size 14px

### PR DESCRIPTION
**Pull request by codecaaron**

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Might want to check the monolith to make sure nobody was relying on the slightly smaller font size... otherwise ✅

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.2-alpha.3df90d.0<br/>@codecademy/gamut-styles@7.0.4-alpha.3df90d.0<br/>@codecademy/gamut@16.2.4-alpha.3df90d.0<br/>@codecademy/markdown-overrides@0.3.4-alpha.3df90d.0<br/>@codecademy/styleguide@17.7.4-alpha.3df90d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8f1a9a84a2b70e2cc0b0f7--gamut-preview.netlify.app>https://5f8f1a9a84a2b70e2cc0b0f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8f1a9a84a2b70e2cc0b0f7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.4-alpha.d0b67b.0<br/>@codecademy/gamut-styles@7.1.1-alpha.d0b67b.0<br/>@codecademy/gamut@16.2.6-alpha.d0b67b.0<br/>@codecademy/markdown-overrides@0.3.5-alpha.d0b67b.0<br/>@codecademy/styleguide@17.7.6-alpha.d0b67b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8f544d7e8cf31f0af2c3e6--gamut-preview.netlify.app>https://5f8f544d7e8cf31f0af2c3e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8f544d7e8cf31f0af2c3e6>Deploy Logs</a></p>

**Pull request merged**
