### PR TITLE
feat(docs): elaborate Popover vs ToolTip

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Elaborates on when to use `Popover` vs `ToolTip` in the Storybook docs.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.7.0-alpha.fb92a8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61439fc94118f81175f8e759--gamut-preview.netlify.app>https://61439fc94118f81175f8e759--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61439fc94118f81175f8e759>Deploy Logs</a></p>

**Review by songstephen — APPROVED** [review]
Looks good to me! Really appreciate the design intention here, and the linking between related components.

**Review by MattSchiller — APPROVED** [review]
Looks good. I'm excited for a time when the underlying implementations come together and this difference is purely a UX concern.

**Pull request merged**
