### PR TITLE
chore: ignored js and markdown files in Codecov

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Ignored irrelevant files in our code coverage calculations.

I've seen this show up in random PRs and it's kind of annoying... e.g. https://github.com/Codecademy/client-modules/pull/1285/files#diff-d788b7b37c486b1fd127d22253128549f7832bcfda99360f18eacd1086ff3346

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601b2bccb58ba33402a403e4--gamut-preview.netlify.app>https://601b2bccb58ba33402a403e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601b2bccb58ba33402a403e4>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Review by codecaaron — APPROVED** [review]
💯

**Comment by dreamwasp** [comment]
🚀🚀🚀

**Review by dreamwasp — APPROVED** [review]
🚀🚀🚀

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c90003966b2009106c005--gamut-preview.netlify.app>https://601c90003966b2009106c005--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c90003966b2009106c005>Deploy Logs</a></p>

**Pull request merged**
