### PR TITLE
feat: add a illustration for business team

### PR DESCRIPTION
**Pull request by jenesh**
### Overview

This PR aims to add a new illustration for the business team. 

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/Duc8xMrpR50jagRMGKDLWy/Welcome?node-id=266%3A6576
- [x] Related to JIRA ticket: EN-498
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

1. Visit https://6030466796063b4fc1b7e3f3--gamut-preview.netlify.app/storybook/?path=/docs/atoms-illustrations--editable-illustration
2. Change `illustration` `Control` to `Onboarding` and see that the illustration matches the designs.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.139786.0<br/>@codecademy/gamut-labs@10.1.1-alpha.139786.0<br/>@codecademy/gamut-tests@2.0.3-alpha.139786.0<br/>@codecademy/gamut@25.0.1-alpha.139786.0<br/>@codecademy/styleguide@29.1.1-alpha.139786.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6030149c96063b188eb7d597--gamut-preview.netlify.app>https://6030149c96063b188eb7d597--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6030149c96063b188eb7d597>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.c2e4e2.0<br/>@codecademy/gamut-labs@10.1.2-alpha.c2e4e2.0<br/>@codecademy/gamut-tests@2.0.3-alpha.c2e4e2.0<br/>@codecademy/gamut@25.0.1-alpha.c2e4e2.0<br/>@codecademy/styleguide@29.1.2-alpha.c2e4e2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6030466796063b4fc1b7e3f3--gamut-preview.netlify.app>https://6030466796063b4fc1b7e3f3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6030466796063b4fc1b7e3f3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.18dc34.0<br/>@codecademy/gamut-labs@10.1.2-alpha.18dc34.0<br/>@codecademy/gamut-tests@2.0.3-alpha.18dc34.0<br/>@codecademy/gamut@25.0.1-alpha.18dc34.0<br/>@codecademy/styleguide@29.1.3-alpha.18dc34.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6033cde6963d4c4c2148ca46--gamut-preview.netlify.app>https://6033cde6963d4c4c2148ca46--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6033cde6963d4c4c2148ca46>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.5.1-alpha.392aa2.0<br/>@codecademy/gamut-labs@10.1.5-alpha.392aa2.0<br/>@codecademy/gamut-tests@2.0.3-alpha.392aa2.0<br/>@codecademy/gamut@25.2.1-alpha.392aa2.0<br/>@codecademy/styleguide@29.3.3-alpha.392aa2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6034034703bbd40093159474--gamut-preview.netlify.app>https://6034034703bbd40093159474--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6034034703bbd40093159474>Deploy Logs</a></p>

**Pull request merged**
