### PR TITLE
fix(styles): Run babel on gamut-styles

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Runs babel on TS from gamut styles and adds our default config.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.3-alpha.315949.0<br/>@codecademy/gamut-labs@10.3.1-alpha.315949.0<br/>@codecademy/gamut-styles@8.2.1-alpha.315949.0<br/>@codecademy/gamut-tests@2.1.4-alpha.315949.0<br/>@codecademy/gamut@25.4.1-alpha.315949.0<br/>@codecademy/markdown-overrides@0.5.5-alpha.315949.0<br/>@codecademy/styleguide@29.6.2-alpha.315949.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fc3ad0881be817d6769ed--gamut-preview.netlify.app>https://603fc3ad0881be817d6769ed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fc3ad0881be817d6769ed>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.3-alpha.e6d063.0<br/>@codecademy/gamut-labs@10.3.2-alpha.e6d063.0<br/>@codecademy/gamut-styles@8.2.1-alpha.e6d063.0<br/>@codecademy/gamut-tests@2.1.4-alpha.e6d063.0<br/>@codecademy/gamut@25.4.2-alpha.e6d063.0<br/>@codecademy/markdown-overrides@0.5.5-alpha.e6d063.0<br/>@codecademy/styleguide@29.6.3-alpha.e6d063.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fc66ab8fa02a23654e9b8--gamut-preview.netlify.app>https://603fc66ab8fa02a23654e9b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fc66ab8fa02a23654e9b8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.3-alpha.87393e.0<br/>@codecademy/gamut-labs@10.3.3-alpha.87393e.0<br/>@codecademy/gamut-styles@8.2.1-alpha.87393e.0<br/>@codecademy/gamut-tests@2.1.4-alpha.87393e.0<br/>@codecademy/gamut@25.4.2-alpha.87393e.0<br/>@codecademy/markdown-overrides@0.5.5-alpha.87393e.0<br/>@codecademy/styleguide@29.6.4-alpha.87393e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603ff0473e57e00e920cb9aa--gamut-preview.netlify.app>https://603ff0473e57e00e920cb9aa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603ff0473e57e00e920cb9aa>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
yeet

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.3-alpha.331239.0<br/>@codecademy/gamut-labs@10.3.4-alpha.331239.0<br/>@codecademy/gamut-styles@8.2.1-alpha.331239.0<br/>@codecademy/gamut-tests@2.1.4-alpha.331239.0<br/>@codecademy/gamut@25.4.2-alpha.331239.0<br/>@codecademy/markdown-overrides@0.5.5-alpha.331239.0<br/>@codecademy/styleguide@29.6.5-alpha.331239.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60405822a906724756da276e--gamut-preview.netlify.app>https://60405822a906724756da276e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60405822a906724756da276e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.4-alpha.e703df.0<br/>@codecademy/gamut-labs@10.4.2-alpha.e703df.0<br/>@codecademy/gamut-styles@8.2.2-alpha.e703df.0<br/>@codecademy/gamut-tests@2.1.5-alpha.e703df.0<br/>@codecademy/gamut@25.4.4-alpha.e703df.0<br/>@codecademy/markdown-overrides@0.5.6-alpha.e703df.0<br/>@codecademy/styleguide@29.6.8-alpha.e703df.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60414b8c292be90f2e207065--gamut-preview.netlify.app>https://60414b8c292be90f2e207065--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60414b8c292be90f2e207065>Deploy Logs</a></p>

**Pull request merged**
