### PR TITLE
fix(Alert): Vertically centering alert CTA button

### PR DESCRIPTION
**Pull request by ZackMFleischman**
### Overview

This tweaks the CTA button to be vertically centered for alerts. This normally isn't a problem because most alerts are restricted to a single line, but we have a longer alert now coming down the pipe here:

**Before**
image

**After**
image

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/EGG-1465
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by katiezutter — APPROVED** [review]
lgtm!

**Review by JoshuaKGoldberg — COMMENTED** [review]
IIRC I made this same request some number of months ago and was told it's intentional as-is? If that's changed, then awesome, I'll defer to the Gamut specialists :)

**Comment by songstephen** [comment]
Gamut specialist here! We should go forward with the vertically centered CTA inside the Alert. I chatted with the team about this change and it should help the action stand out more :)

**Review by codecaaron — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]
🙏

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.72-alpha.e666e0.0<br/>@codecademy/gamut-labs@19.16.10-alpha.e666e0.0<br/>@codecademy/gamut@35.2.1-alpha.e666e0.0<br/>@codecademy/styleguide@42.1.4-alpha.e666e0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fee1e35f23e600c4af0fd7--gamut-preview.netlify.app>https://60fee1e35f23e600c4af0fd7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fee1e35f23e600c4af0fd7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ff02d690cec12f01bfdc1b--gamut-preview.netlify.app>https://60ff02d690cec12f01bfdc1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ff02d690cec12f01bfdc1b>Deploy Logs</a></p>

**Pull request merged**
