### PR TITLE
feat(Radio): Allow optional tooltip on radio option

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Radio option label allows an optional tooltip.

### PR Checklist

- [x] Related to designs: [updated Profile Edit form figma](https://www.figma.com/file/PG0kVYDIuLk3hE566beZUV/Profiles-(Concept-Refinement)?node-id=1608%3A134035)
- [x] Related to JIRA ticket: [EGG-1266](https://codecademy.atlassian.net/browse/EGG-1266)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by katiezutter** [comment]
Will link to how this will be used on the Profile Edit form in the monolith once the alpha packages are up!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60aeb20308fc34008ea56183--gamut-preview.netlify.app>https://60aeb20308fc34008ea56183--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60aeb20308fc34008ea56183>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.120-alpha.23f8d5.0<br/>@codecademy/gamut-labs@18.2.3-alpha.23f8d5.0<br/>@codecademy/gamut@33.1.6-alpha.23f8d5.0<br/>@codecademy/styleguide@40.0.8-alpha.23f8d5.0<br/></pre>

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Unit test please? :)

Looks great to me otherwise!

**Comment by katiezutter** [comment]
> Unit test please? :)
> 
> Looks great to me otherwise!

@JoshuaKGoldberg sure thing, once we have finalized what will happen here! (@dreamwasp and I are chatting tomorrow about whether we should instead just change the type of [`label`](https://github.com/Codecademy/client-modules/pull/1785/files#diff-d72ab5685d90ec5c7678849abf1a924f9554062d860ffa7cf90e3184c9941e95L74) to `React.ReactNode`)

**Comment by katiezutter** [comment]
Closing in favor of implementation in #1788

**Pull request closed without merging**
