### PR TITLE
fix(Testimonial): pass display prop to Anchor if href is defined

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

Passes `display` prop to `Anchor` tag so if `display:none` is passed to `Testimonial`, it applies that property to the wrapping `Anchor` if `href` is defined. This fixes [axe bug](https://codecademy.atlassian.net/jira/software/projects/DISC/boards/180?assignee=5fe2ae278332a1010e6200ad&selectedIssue=DISC-208) of `Anchor` having focus despite `Testimonial` having `display:none` property. 

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DISC-208
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.69-alpha.6b7dc6.0<br/>@codecademy/gamut-labs@19.25.1-alpha.6b7dc6.0<br/>@codecademy/styleguide@44.2.1-alpha.6b7dc6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b77b2c3c05300a1bbd100--gamut-preview.netlify.app>https://613b77b2c3c05300a1bbd100--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b77b2c3c05300a1bbd100>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.69-alpha.ad2486.0<br/>@codecademy/gamut-labs@19.25.1-alpha.ad2486.0<br/>@codecademy/styleguide@44.2.1-alpha.ad2486.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.73-alpha.b63da0.0<br/>@codecademy/gamut-labs@19.26.2-alpha.b63da0.0<br/>@codecademy/styleguide@44.3.2-alpha.b63da0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b9a58bd67ab1a590c6deb--gamut-preview.netlify.app>https://613b9a58bd67ab1a590c6deb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b9a58bd67ab1a590c6deb>Deploy Logs</a></p>

**Review by cstatro — APPROVED** [review]
LGTM

**Review by borisonr — APPROVED** [review]
looks great, mind adding a pr in portal with the gamut alpha so we can confirm axe tests pass?

**Comment by zippyzow** [comment]
> looks great, mind adding a pr in portal with the gamut alpha so we can confirm axe tests pass?

https://tengu.codecademy.com/learner-stories?PR_ENV=portal-app-pr-607

**Review by codecaaron — APPROVED** [review]
👍

**Pull request merged**
