### PR TITLE
feat: removed '@codecademy' from Webpack modules list

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Removed '@codecademy' from Webpack modules list

This was what allows us to `import` `from 'gamut'` in addition to `from '@codecademy/gamut'`.

### Notes

~Before merging, I'd like to try the alpha version of this out on the monolith: https://github.com/codecademy-engineering/Codecademy/pull/16015~ ✅ 

BREAKING CHANGE: You'll need to update imports.

### CODE REVIEW

**Comment by jakemhiller** [comment]
Just a reminder, this is a breaking change, so it needs a full version bump.

**Comment by JoshuaKGoldberg** [comment]
@jakemhiller confirmed. 

https://github.com/codecademy-engineering/Codecademy/pull/16015 was merged so I think this is ready to go. Would you like me to also convert Author to the new import format first?

**Comment by jakemhiller** [comment]
@JoshuaKGoldberg if Author is already pretty close to up-to-date it would be good to update it, I don't think that should block merging. I just want to make sure we use the correct commit format on the squash merge to make this a breaking change.

**Comment by JoshuaKGoldberg** [comment]
https://github.com/codecademy-engineering/author/pull/1127/

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.8.5-alpha.9a0203.1+9a0203eb<br/>@codecademy/enzyme-helpers@1.1.10-alpha.9a0203.41+9a0203eb<br/>@codecademy/gamut-templates@2.5.4-alpha.9a0203.1+9a0203eb<br/>@codecademy/gamut@2.12.1-alpha.9a0203.1+9a0203eb<br/>@codecademy/webpack-config@4.0.1-alpha.9a0203.35+9a0203eb<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e84a6daa063b235534162d6--codecademy-styleguide.netlify.com>https://5e84a6daa063b235534162d6--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e84a6daa063b235534162d6>Deploy Logs</a></p>

**Pull request merged**
