### PR TITLE
fix(mixins): Fix deprecation warning for sr-only

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview
This was annoying.  Sorry for keeping it in so long.

### PR Checklist

- [ ] Related to Abstract designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.1-alpha.de0a33.0<br/>@codecademy/gamut@16.0.5-alpha.de0a33.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]
😂

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6a1acb00678d126b9fccd5--gamut-preview.netlify.app>https://5f6a1acb00678d126b9fccd5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6a1acb00678d126b9fccd5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.2-alpha.7125d0.0<br/>@codecademy/gamut@16.0.5-alpha.7125d0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6a206b84b34900e7d42880--gamut-preview.netlify.app>https://5f6a206b84b34900e7d42880--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6a206b84b34900e7d42880>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.2-alpha.6358d2.0<br/>@codecademy/gamut@16.0.5-alpha.6358d2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6a221e0ca74c01588930a0--gamut-preview.netlify.app>https://5f6a221e0ca74c01588930a0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6a221e0ca74c01588930a0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.4-alpha.ad21cb.0<br/>@codecademy/gamut@16.0.7-alpha.ad21cb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6a3e630a3ee323ecc77ec6--gamut-preview.netlify.app>https://5f6a3e630a3ee323ecc77ec6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6a3e630a3ee323ecc77ec6>Deploy Logs</a></p>

**Pull request merged**
