### PR TITLE
chore: Upgrade storybook to 6.3.4

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Upgrades storybook to 6.3.4 which includes some nice performance benefits to props tables.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-294
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.2-alpha.f03500.0<br/>@codecademy/gamut-illustrations@0.17.11-alpha.f03500.0<br/>@codecademy/gamut-kit@0.4.65-alpha.f03500.0<br/>@codecademy/gamut-labs@19.16.3-alpha.f03500.0<br/>@codecademy/gamut-patterns@0.4.6-alpha.f03500.0<br/>@codecademy/gamut-styles@11.6.1-alpha.f03500.0<br/>@codecademy/gamut-tests@2.4.14-alpha.f03500.0<br/>@codecademy/gamut@34.14.4-alpha.f03500.0<br/>@codecademy/konamimojisplosion@0.2.45-alpha.f03500.0<br/>@codecademy/markdown-overrides@0.5.57-alpha.f03500.0<br/>@codecademy/styleguide@41.14.4-alpha.f03500.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f0a40554584500a838132a--gamut-preview.netlify.app>https://60f0a40554584500a838132a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f0a40554584500a838132a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.3.2-alpha.cf5e1d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61001a7968983b27366a101c--gamut-preview.netlify.app>https://61001a7968983b27366a101c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61001a7968983b27366a101c>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
heck yes

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.3.4-alpha.5ad44a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6102e8a04a903a618cf02fde--gamut-preview.netlify.app>https://6102e8a04a903a618cf02fde--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6102e8a04a903a618cf02fde>Deploy Logs</a></p>

**Pull request merged**
