### PR TITLE
perf: size reduced for checklist + pin icons

### PR DESCRIPTION
**Pull request by dreamwasp**
### PR Checklist

- [x] Related to designs: https://www.figma.com/file/nf7HbNhN7ygTle4xBTt4ER/Curated-Content?node-id=711%3A6856
- [x] Related to JIRA ticket: LX-4249
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
This PR reduces the file size of the checklist + pin icons (fixing a [previous PR](https://github.com/Codecademy/client-modules/pull/976))

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.10.1-alpha.6d8878.0<br/>@codecademy/gamut-labs@4.6.3-alpha.6d8878.0<br/>@codecademy/gamut@16.3.3-alpha.6d8878.0<br/>@codecademy/styleguide@17.10.4-alpha.6d8878.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa2b90301aedb0ca417b9a9--gamut-preview.netlify.app>https://5fa2b90301aedb0ca417b9a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa2b90301aedb0ca417b9a9>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — COMMENTED** [review]
We don't really do this for other icons because it makes it harder to correlate what their source code is to the original files, and have [SVGO set up](https://codecademy.slack.com/archives/C047ESP1T/p1604349961141700). Is there a context here @dreamwasp?

**Comment by dreamwasp** [comment]
> We don't really do this for other icons because it makes it harder to correlate what their source code is to the original files, and have [SVGO set up](https://codecademy.slack.com/archives/C047ESP1T/p1604349961141700). Is there a context here @dreamwasp?

@judahtanthony brought it up as something i should do w/r/t [this PR](https://github.com/Codecademy/client-modules/pull/976) - i just used the svgo command line tool so lmk if i went about it the wrong way or if this PR isn't needed!

**Comment by codecaaron** [comment]
So these icons already go through some optimization before becoming react components.  So the size of them as SVGs will not affect the size of the component we generate.

Since we don't distribute them specifically or use the actual assets, I've found it useful to preserve some of the meta info inside the markup and keep it human-readable for future updates and maintenance.

We definitely need to update the docs with this information.  Would you be up for pairing on making them a bit more clear with me!

**Comment by dreamwasp** [comment]
> So these icons already go through some optimization before becoming react components. So the size of them as SVGs will not affect the size of the component we generate.
> 
> Since we don't distribute them specifically or use the actual assets, I've found it useful to preserve some of the meta info inside the markup and keep it human-readable for future updates and maintenance.
> 
> We definitely need to update the docs with this information. Would you be up for pairing on making them a bit more clear with me! @dreamwasp

@codecaaron yes definitely! will take this to slack

**Pull request closed without merging**
