### PR TITLE
fix(SelectDropdown): Fix axe accessibility input issue + styling inconsistencies

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Turns out with a bit of futzing, it's possible with react-select to get the search input to recognized as a search input and the hidden input to be recognized as the value input  🙃.

I've tested it in a branch against Jonathan's current branch and have gotten it passing accessibility specs, woo!

Also tweaks some small margin and padding things - planning on refactoring its styling to remove dependence on `styles` in a future PR. 

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [GM-239](https://codecademy.atlassian.net/browse/GM-239)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.61-alpha.b17c32.0<br/>@codecademy/gamut-labs@19.15.4-alpha.b17c32.0<br/>@codecademy/gamut@34.13.3-alpha.b17c32.0<br/>@codecademy/styleguide@41.12.4-alpha.b17c32.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60df82fbc5f3c1637bb16aad--gamut-preview.netlify.app>https://60df82fbc5f3c1637bb16aad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60df82fbc5f3c1637bb16aad>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.61-alpha.4dad72.0<br/>@codecademy/gamut-labs@19.15.4-alpha.4dad72.0<br/>@codecademy/gamut@34.13.3-alpha.4dad72.0<br/>@codecademy/styleguide@41.12.4-alpha.4dad72.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60df900674fefb80fb200474--gamut-preview.netlify.app>https://60df900674fefb80fb200474--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60df900674fefb80fb200474>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.62-alpha.4b6c5d.0<br/>@codecademy/gamut-labs@19.15.5-alpha.4b6c5d.0<br/>@codecademy/gamut@34.14.1-alpha.4b6c5d.0<br/>@codecademy/styleguide@41.13.1-alpha.4b6c5d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ec5853cdf13f1c73fe4434--gamut-preview.netlify.app>https://60ec5853cdf13f1c73fe4434--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ec5853cdf13f1c73fe4434>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.63-alpha.d5e4ca.0<br/>@codecademy/gamut-labs@19.16.1-alpha.d5e4ca.0<br/>@codecademy/gamut@34.14.2-alpha.d5e4ca.0<br/>@codecademy/styleguide@41.14.1-alpha.d5e4ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ec6e4f7ad727395f09876c--gamut-preview.netlify.app>https://60ec6e4f7ad727395f09876c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ec6e4f7ad727395f09876c>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.63-alpha.6cb970.0<br/>@codecademy/gamut-labs@19.16.1-alpha.6cb970.0<br/>@codecademy/gamut@34.14.2-alpha.6cb970.0<br/>@codecademy/styleguide@41.14.1-alpha.6cb970.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60edcb9bfeb20820df9894e7--gamut-preview.netlify.app>https://60edcb9bfeb20820df9894e7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60edcb9bfeb20820df9894e7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.63-alpha.c3f5fb.0<br/>@codecademy/gamut-labs@19.16.1-alpha.c3f5fb.0<br/>@codecademy/gamut@34.14.2-alpha.c3f5fb.0<br/>@codecademy/styleguide@41.14.1-alpha.c3f5fb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60edd60dfaeeb22f111ccf92--gamut-preview.netlify.app>https://60edd60dfaeeb22f111ccf92--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60edd60dfaeeb22f111ccf92>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.63-alpha.af7b8a.0<br/>@codecademy/gamut-labs@19.16.1-alpha.af7b8a.0<br/>@codecademy/gamut@34.14.2-alpha.af7b8a.0<br/>@codecademy/styleguide@41.14.1-alpha.af7b8a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ef5c1e7965b22fa0834360--gamut-preview.netlify.app>https://60ef5c1e7965b22fa0834360--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ef5c1e7965b22fa0834360>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.67-alpha.6b0682.0<br/>@codecademy/gamut-labs@19.16.5-alpha.6b0682.0<br/>@codecademy/gamut@34.15.1-alpha.6b0682.0<br/>@codecademy/styleguide@41.15.1-alpha.6b0682.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f584d4bc7fd15f08301a28--gamut-preview.netlify.app>https://60f584d4bc7fd15f08301a28--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f584d4bc7fd15f08301a28>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.70-alpha.a23789.0<br/>@codecademy/gamut-labs@19.16.8-alpha.a23789.0<br/>@codecademy/gamut@35.1.1-alpha.a23789.0<br/>@codecademy/styleguide@42.1.1-alpha.a23789.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f6e108ef1d360a2db9aa5d--gamut-preview.netlify.app>https://60f6e108ef1d360a2db9aa5d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f6e108ef1d360a2db9aa5d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.70-alpha.6e65bc.0<br/>@codecademy/gamut-labs@19.16.8-alpha.6e65bc.0<br/>@codecademy/gamut@35.1.1-alpha.6e65bc.0<br/>@codecademy/styleguide@42.1.1-alpha.6e65bc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f894701164f748641911fd--gamut-preview.netlify.app>https://60f894701164f748641911fd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f894701164f748641911fd>Deploy Logs</a></p>

**Pull request merged**
