### PR TITLE
fix(Styleguide): Fixes system prop tooltip colors GM-322

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Refactors the tool tips for system prop groups to display in a more human readable format and use existing components.
* Fixes bug with selected prop group text color inheritance.
* Removes legacy style patterns from files that were still referencing `gamut-system` code.

**Before**
Screen Shot 2021-08-12 at 6 31 38 PM
Screen Shot 2021-08-12 at 6 31 41 PM

**After**
Screen Shot 2021-08-12 at 6 26 52 PM

### PR Checklist

- [x] Related to designs: Just the ones I make up in my brain.
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-322
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@43.2.2-alpha.dd0f27.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6115a6c00814c8499cc72c30--gamut-preview.netlify.app>https://6115a6c00814c8499cc72c30--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6115a6c00814c8499cc72c30>Deploy Logs</a></p>

**Review by saghdaey — APPROVED** [review]
👏🏼 ty!

**Review by dreamwasp — APPROVED** [review]
🔥

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@43.2.3-alpha.7b849b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116a468fc2e761d803bf13d--gamut-preview.netlify.app>https://6116a468fc2e761d803bf13d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116a468fc2e761d803bf13d>Deploy Logs</a></p>

**Pull request merged**
