### PR TITLE
chore: kill Ikona

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1156
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

I _think_ we don't use these these particular fonts anywhere that can't be easily swapped: really just a random head icon in /about. 

The LE still uses them in the monolith so this might have to be closed until LE next... I'll investigate with the alpha packages.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.1-alpha.076d2b.0<br/>@codecademy/gamut-styles@8.0.0-alpha.076d2b.0<br/>@codecademy/gamut@18.0.0-alpha.076d2b.0<br/>@codecademy/markdown-overrides@0.3.15-alpha.076d2b.0<br/>@codecademy/styleguide@19.0.1-alpha.076d2b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fbe5273ae4a4f60447dfa5f--gamut-preview.netlify.app>https://5fbe5273ae4a4f60447dfa5f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fbe5273ae4a4f60447dfa5f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc674e86c3c560d0a10f3ad--gamut-preview.netlify.app>https://5fc674e86c3c560d0a10f3ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc674e86c3c560d0a10f3ad>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.4-alpha.f70965.0<br/>@codecademy/gamut-styles@8.0.0-alpha.f70965.0<br/>@codecademy/gamut@19.0.0-alpha.f70965.0<br/>@codecademy/markdown-overrides@0.3.17-alpha.f70965.0<br/>@codecademy/styleguide@20.0.1-alpha.f70965.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.5be442.0<br/>@codecademy/gamut-styles@8.0.0-alpha.5be442.0<br/>@codecademy/gamut@20.0.0-alpha.5be442.0<br/>@codecademy/markdown-overrides@0.3.17-alpha.5be442.0<br/>@codecademy/styleguide@21.0.2-alpha.5be442.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc6aea2f74c0051c60d46dd--gamut-preview.netlify.app>https://5fc6aea2f74c0051c60d46dd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc6aea2f74c0051c60d46dd>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
Now that static-sites doesn't use Ikona, this really isn't breaking 😄 . Removed the `!` from the title.

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce59a02a31a40a354c2a21--gamut-preview.netlify.app>https://5fce59a02a31a40a354c2a21--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce59a02a31a40a354c2a21>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.1.1-alpha.c06d63.0<br/>@codecademy/gamut-styles@8.0.0-alpha.c06d63.0<br/>@codecademy/gamut@20.0.0-alpha.c06d63.0<br/>@codecademy/markdown-overrides@0.3.19-alpha.c06d63.0<br/>@codecademy/styleguide@21.1.1-alpha.c06d63.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcfaa280d8a851616547088--gamut-preview.netlify.app>https://5fcfaa280d8a851616547088--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcfaa280d8a851616547088>Deploy Logs</a></p>

**Pull request merged**
