### PR TITLE
feat(theme prop description): Adds descriptive text to theme prop

### PR DESCRIPTION
**Pull request by timjenkins**
### Overview
Adds descriptive text to theme props where they appear on components in storybook. 
"This prop is set automatically and indicates that it is a consumer of the Theme context. Do not pass anything to it."

Storybook: Adds descriptive text instructing users not to pass anything to theme props

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]
Love it

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@40.4.0-alpha.1da99d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7f34a851ff24ca1add9f5--gamut-preview.netlify.app>https://60b7f34a851ff24ca1add9f5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7f34a851ff24ca1add9f5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.1.0-alpha.a18003.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b92fc14251952df2143f40--gamut-preview.netlify.app>https://60b92fc14251952df2143f40--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b92fc14251952df2143f40>Deploy Logs</a></p>

**Pull request merged**
