### PR TITLE
fix: blur ToolTip target on escape key down

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

`ToolTip` targets will blur on Escape key down, for accessibility.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1486
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.3a6a3d.0<br/>@codecademy/gamut-labs@19.0.6-alpha.3a6a3d.0<br/>@codecademy/gamut@34.0.3-alpha.3a6a3d.0<br/>@codecademy/styleguide@41.2.5-alpha.3a6a3d.0<br/></pre>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bfc49263d51d463495f1e4--gamut-preview.netlify.app>https://60bfc49263d51d463495f1e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bfc49263d51d463495f1e4>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
heck yes

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.17-alpha.09f419.0<br/>@codecademy/gamut-labs@19.3.1-alpha.09f419.0<br/>@codecademy/gamut@34.3.1-alpha.09f419.0<br/>@codecademy/styleguide@41.5.1-alpha.09f419.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c167a55e8e035f43e3bed7--gamut-preview.netlify.app>https://60c167a55e8e035f43e3bed7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c167a55e8e035f43e3bed7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.19-alpha.417728.0<br/>@codecademy/gamut-labs@19.4.1-alpha.417728.0<br/>@codecademy/gamut@34.5.1-alpha.417728.0<br/>@codecademy/styleguide@41.7.1-alpha.417728.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c170e15382546e19d01366--gamut-preview.netlify.app>https://60c170e15382546e19d01366--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c170e15382546e19d01366>Deploy Logs</a></p>

**Pull request merged**
