### PR TITLE
fix: remove z index from popover

### PR DESCRIPTION
**Pull request by sylvanasantos**
### Overview

- fixed z index issue with popover component

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Context (PLEASE READ)
In #1385, I set the popover index to 1. My reasoning for this was that I wanted to fix this issue on storybook:
Screen Shot 2021-02-21 at 9 38 29 PM
Screen Shot 2021-02-21 at 9 38 49 PM

However, once I updated the gamut-labs version on the monolith, I realized that it caused issues with the global header as shown belo. Note: this is not on prod, just a zoo/pr server. 
Screen Shot 2021-02-21 at 9 35 14 PM

So in this pr, I am removing the z index so that the popover looks like this:
Screen Shot 2021-02-21 at 9 35 49 PM

Unfortunately, this means that the storybook will have that weird behavior shown above, but I think that will have to do? Let me know if you have any concerns.

### CODE REVIEW

**Review by airrobb — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.2-alpha.b85a6d.0<br/>@codecademy/styleguide@29.1.3-alpha.b85a6d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6033cf3e79faf744ec02f790--gamut-preview.netlify.app>https://6033cf3e79faf744ec02f790--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6033cf3e79faf744ec02f790>Deploy Logs</a></p>

**Comment by airrobb** [comment]
Yeah, let's update the docs to reflect that.  Storybook docs mode shouldn't change our code since its so far from our actually application.  Especially stacking / positioning contexts are completely out of whack.  In general if you need to change something to make it work, change storybook not the component.  Let's update some quick docs for this.

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.4-alpha.bad312.0<br/>@codecademy/styleguide@29.3.2-alpha.bad312.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6033f7200ba4ff00aa5cf295--gamut-preview.netlify.app>https://6033f7200ba4ff00aa5cf295--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6033f7200ba4ff00aa5cf295>Deploy Logs</a></p>

**Review by hmafzal — APPROVED** [review]
Darn z indices

**Pull request merged**
