### PR TITLE
feat!: update babel for react jsx transform

### PR DESCRIPTION
**Pull request by dreamwasp**
### PR Checklist

- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>babel-preset-codecademy@6.0.1-alpha.1a54e4.0<br/>@codecademy/codebytes@0.7.4-alpha.1a54e4.0<br/>@codecademy/tracking@0.25.1-alpha.1a54e4.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>babel-preset-codecademy@6.0.1-alpha.8dfef4.0<br/>@codecademy/codebytes@0.7.4-alpha.8dfef4.0<br/>@codecademy/tracking@0.25.1-alpha.8dfef4.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>babel-preset-codecademy@6.0.1-alpha.0c5e25.0<br/>@codecademy/codebytes@0.7.4-alpha.0c5e25.0<br/>@codecademy/tracking@0.25.1-alpha.0c5e25.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>babel-preset-codecademy@6.0.1-alpha.042681.0<br/>@codecademy/codebytes@0.7.4-alpha.042681.0<br/>@codecademy/tracking@0.25.1-alpha.042681.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
seems like we could just merge this? 👍

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>babel-preset-codecademy@6.0.1-alpha.d4c618.0<br/></pre>

**Pull request merged**
