### PR TITLE
fix: actually use testId prop in prefooter

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview

data-testid is helpful for e2e smoketesting, and we're already passing the prop in the dynamic renderer (it just isn't being applied lol woops)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-452](https://codecademy.atlassian.net/browse/REACH-452)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by christian-dinh** [comment]
just a note, this won't work without https://github.com/Codecademy/client-modules/pull/1242 (which I felt should be its own PR)

**Review by rogervera — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.4-alpha.f5a6d6.0<br/>@codecademy/gamut-labs@7.5.1-alpha.f5a6d6.0<br/>@codecademy/gamut@19.5.0-alpha.f5a6d6.0<br/>@codecademy/styleguide@21.5.1-alpha.f5a6d6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd8df7226ecae0b702e7216--gamut-preview.netlify.app>https://5fd8df7226ecae0b702e7216--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd8df7226ecae0b702e7216>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.5.2-alpha.75ed68.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd8e80026ecae1a692e6f3e--gamut-preview.netlify.app>https://5fd8e80026ecae1a692e6f3e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd8e80026ecae1a692e6f3e>Deploy Logs</a></p>

**Pull request merged**
