### PR TITLE
fix(Drawer): add 100% height to inner Box

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds 100% height to the intermediate `Box` within `Drawer`.

I'd missed this in https://github.com/Codecademy/client-modules/pull/2083, it needs to be there so tall content can have a vertical scrollbar.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GM-378 WEB-1417
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.100-alpha.944cb8.0<br/>@codecademy/gamut-labs@24.2.2-alpha.944cb8.0<br/>@codecademy/styleguide@47.3.1-alpha.944cb8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://615b1a4c858de32a773f5a2e--gamut-preview.netlify.app>https://615b1a4c858de32a773f5a2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/615b1a4c858de32a773f5a2e>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.101-alpha.652e65.0<br/>@codecademy/gamut-labs@24.3.1-alpha.652e65.0<br/>@codecademy/styleguide@47.3.2-alpha.652e65.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://615b69c1d88f5d00914fba3a--gamut-preview.netlify.app>https://615b69c1d88f5d00914fba3a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/615b69c1d88f5d00914fba3a>Deploy Logs</a></p>

**Pull request merged**
