### PR TITLE
style: use white-space: pre-line for Alert

### PR DESCRIPTION
**Pull request by mikeboyle**
## Overview
Adding this attribute will let consumers display multi-line content in an alert. For example, a template literal with line breaks, or a string using `/n` for line breaks.

Includes an update to the story to demonstrate this.
### PR Checklist
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change (n/a)

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@1.7.13-alpha.c62e59.0<br/>@codecademy/gamut@8.2.2-alpha.c62e59.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5126eb6a24ff4e7fa751da--gamut-preview.netlify.app>https://5f5126eb6a24ff4e7fa751da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5126eb6a24ff4e7fa751da>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.1-alpha.8a3404.0<br/>@codecademy/gamut-labs@4.0.2-alpha.8a3404.0<br/>@codecademy/gamut@16.0.4-alpha.8a3404.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f51281fe79d8f4f736681c3--gamut-preview.netlify.app>https://5f51281fe79d8f4f736681c3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f51281fe79d8f4f736681c3>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Pull request merged**
