### PR TITLE
chore(Styleguide): add args to toggle story

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Per sarah's request

* Add args to Toggle story

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@20.0.1-alpha.f16415.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc66f38ddfbcd00b4908ea2--gamut-preview.netlify.app>https://5fc66f38ddfbcd00b4908ea2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc66f38ddfbcd00b4908ea2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@20.0.1-alpha.b225f8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc6707f6c3c56011c10f960--gamut-preview.netlify.app>https://5fc6707f6c3c56011c10f960--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc6707f6c3c56011c10f960>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.2-alpha.aec9cb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7b17a8cb005ba1927da38--gamut-preview.netlify.app>https://5fc7b17a8cb005ba1927da38--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7b17a8cb005ba1927da38>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.4-alpha.95a2c3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7f1b7c8c1b700cd18a490--gamut-preview.netlify.app>https://5fc7f1b7c8c1b700cd18a490--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7f1b7c8c1b700cd18a490>Deploy Logs</a></p>

**Pull request merged**
