### PR TITLE
feat: add testId prop to Container

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview
as seen in [LayoutGrid](https://github.com/Codecademy/client-modules/blob/main/packages/gamut/src/Layout/LayoutGrid.tsx#L18). Not sure if most people care either way about this but it would make e2e testing the landing page builder a lil easier!

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-452](https://codecademy.atlassian.net/browse/REACH-452) (by way of https://github.com/Codecademy/client-modules/pull/1241)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd800e228a6a713b0b4126d--gamut-preview.netlify.app>https://5fd800e228a6a713b0b4126d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd800e228a6a713b0b4126d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.4-alpha.6f6e86.0<br/>@codecademy/gamut-labs@7.5.1-alpha.6f6e86.0<br/>@codecademy/gamut@19.5.0-alpha.6f6e86.0<br/>@codecademy/styleguide@21.5.1-alpha.6f6e86.0<br/></pre>

**Review by rogervera — APPROVED** [review]
Tis a good thing to have!

**Review by JoshuaKGoldberg — APPROVED** [review]
👍

**Pull request merged**
