### PR TITLE
fix(GlobalHeader): Fixes for the static-sites transition

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Fixes to issues that came up while migrating static-sites to the new Gamut GlobalHeader.

* Creates loading state (just the CC logo) for use while fetching user data
* Updates the copy/structure of the top navigation elements to match changes the Business team has recently made
* Fixes some tracking typos
* Removes the bottom border from the Gamut component (the border will now be handled by the consumer to accommodate for the fact that we change that border when we show the Search dropdown)

PR for transitioning to new header in static-sites (not yet up for official review): https://github.com/codecademy-engineering/static-sites/pull/561

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-537](https://codecademy.atlassian.net/browse/EGG-537)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.6-alpha.4a8d8a.0<br/>@codecademy/styleguide@24.0.4-alpha.4a8d8a.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.3.1-alpha.7a1e91.0<br/>@codecademy/styleguide@24.2.3-alpha.7a1e91.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601ab5d5861709295274a45c--gamut-preview.netlify.app>https://601ab5d5861709295274a45c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601ab5d5861709295274a45c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.3.1-alpha.d7a5a9.0<br/>@codecademy/styleguide@24.2.3-alpha.d7a5a9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601b0e166085830b98147e7f--gamut-preview.netlify.app>https://601b0e166085830b98147e7f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601b0e166085830b98147e7f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.3.4-alpha.425fd9.0<br/>@codecademy/styleguide@24.2.6-alpha.425fd9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c21aeb58ba374e5a408ed--gamut-preview.netlify.app>https://601c21aeb58ba374e5a408ed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c21aeb58ba374e5a408ed>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.0.0-alpha.ee4c1b.0<br/>@codecademy/styleguide@25.0.0-alpha.ee4c1b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c27699cef87419b6858d4--gamut-preview.netlify.app>https://601c27699cef87419b6858d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c27699cef87419b6858d4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.0.1-alpha.e1f20d.0<br/>@codecademy/styleguide@25.0.1-alpha.e1f20d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c3fe36cc7a76ac300dbfe--gamut-preview.netlify.app>https://601c3fe36cc7a76ac300dbfe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c3fe36cc7a76ac300dbfe>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
🌮

**Review by rogervera — APPROVED** [review]
LGTM. Testing with https://tengu.codecademy.com/student-center

**Pull request merged**
