### PR TITLE
fix(Checkbox): Fixes :checked + :disabled styles

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Checkbox had a funky state with Checked + Disabled.  This fixes it and adds some stories to ensure that we can catch it.

* Ensures we have the correct disabled state for checkbox elements

Made a separate [PR](https://github.com/Codecademy/client-modules/pull/1317) to ensure we have all end states have some story level visual example to help is with the refactoring effort.
 
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Screenshots
Screen Shot 2021-01-24 at 2 56 45 PM
Screen Shot 2021-01-24 at 2 57 12 PM

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600dd2e5df37f0ba9a7577d4--gamut-preview.netlify.app>https://600dd2e5df37f0ba9a7577d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600dd2e5df37f0ba9a7577d4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.8-alpha.7107d9.0<br/>@codecademy/gamut-labs@7.13.2-alpha.7107d9.0<br/>@codecademy/gamut@19.11.4-alpha.7107d9.0<br/>@codecademy/styleguide@21.19.1-alpha.7107d9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600e2ca086547a8f557192b6--gamut-preview.netlify.app>https://600e2ca086547a8f557192b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600e2ca086547a8f557192b6>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
✨

**Review by jenesh — APPROVED** [review]
LGTM 🚀

**Pull request merged**
