### PR TITLE
fix: clear errors on input change in GridForm

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds calls to `react-hook-form`'s `clearErrors` when GridForm inputs change.

### PR Checklist

- ~[] Related to designs:~
- [x] Related to JIRA ticket: WEB-1206
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

I needed to refactor at least the `GridFormTextInput` unit tests to be able to retrieve the `clearErrors` prop. I was tempted to apply the same refactor all over the other GridForm unit tests but held off because @dreamwasp you're planning on redoing things. Want me to go Wild on these tests?

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.c646a4.0<br/>@codecademy/gamut-labs@19.0.6-alpha.c646a4.0<br/>@codecademy/gamut@34.0.3-alpha.c646a4.0<br/>@codecademy/styleguide@41.2.4-alpha.c646a4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bfb84b17ad6e30ade8c800--gamut-preview.netlify.app>https://60bfb84b17ad6e30ade8c800--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bfb84b17ad6e30ade8c800>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
lgtm! pls hold off till GridForm refresh 🙂 -- just meant hold off on redoing all the tests, this is fine!

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.21-alpha.366d56.0<br/>@codecademy/gamut-labs@19.4.3-alpha.366d56.0<br/>@codecademy/gamut@34.5.2-alpha.366d56.0<br/>@codecademy/styleguide@41.7.3-alpha.366d56.0<br/></pre>

**Pull request merged**
