### PR TITLE
feat(Icon): Adds system props to all icons [GM-218]

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

This adds a few system prop groups to gamut-icons through the SVGR template.  The general strategy is to use the `.withComponent` api to forward a className to the actual Icon forwardRef component with the appropriate styles as well as forwarding any valid attribute.

The template imports this new base component and extends it with the local Icon componet.

```tsx
import { IconSvg } from './props';

const LocalIcon = forwardRef(/** usual stuff */);

export const IconName = IconSvg.withComponent(LocalIcon);
```

* Adds `layout` `spacing` `positioning` `color` to a styled SVG element that is consumed in each template.
* Adds a step to only forward valid attributes for width and height ensuring that we maintain svg display attributes where possible.
* Updates build step in CI to include required packages when building icons for tests gamut-system, variance, and gamut-styles.
* Updates Alert Icon to use system props.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GM-218
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.8.1-alpha.389ecc.0<br/>@codecademy/gamut-kit@0.3.67-alpha.389ecc.0<br/>@codecademy/gamut-labs@15.2.7-alpha.389ecc.0<br/>@codecademy/gamut@32.7.4-alpha.389ecc.0<br/>@codecademy/styleguide@36.9.4-alpha.389ecc.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.8.1-alpha.0b8b35.0<br/>@codecademy/gamut-kit@0.3.67-alpha.0b8b35.0<br/>@codecademy/gamut-labs@15.2.7-alpha.0b8b35.0<br/>@codecademy/gamut@32.7.4-alpha.0b8b35.0<br/>@codecademy/styleguide@36.9.4-alpha.0b8b35.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609012882cdf1700e1222405--gamut-preview.netlify.app>https://609012882cdf1700e1222405--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609012882cdf1700e1222405>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Awesome!

@natalieweesh this is what I'm hoping we can move to with the patterns.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.8.1-alpha.6a46c3.0<br/>@codecademy/gamut-kit@0.3.67-alpha.6a46c3.0<br/>@codecademy/gamut-labs@15.2.7-alpha.6a46c3.0<br/>@codecademy/gamut@32.7.4-alpha.6a46c3.0<br/>@codecademy/styleguide@36.9.4-alpha.6a46c3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609022c614ed1e00a6798432--gamut-preview.netlify.app>https://609022c614ed1e00a6798432--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609022c614ed1e00a6798432>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.8.1-alpha.775c09.0<br/>@codecademy/gamut-kit@0.3.68-alpha.775c09.0<br/>@codecademy/gamut-labs@15.2.8-alpha.775c09.0<br/>@codecademy/gamut@32.8.1-alpha.775c09.0<br/>@codecademy/styleguide@36.10.1-alpha.775c09.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090249e31a98b00d2c44d95--gamut-preview.netlify.app>https://6090249e31a98b00d2c44d95--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090249e31a98b00d2c44d95>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.8.1-alpha.4e0b44.0<br/>@codecademy/gamut-kit@0.3.68-alpha.4e0b44.0<br/>@codecademy/gamut-labs@15.2.8-alpha.4e0b44.0<br/>@codecademy/gamut@32.8.1-alpha.4e0b44.0<br/>@codecademy/styleguide@36.10.1-alpha.4e0b44.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60903c4016919900cae6fc3c--gamut-preview.netlify.app>https://60903c4016919900cae6fc3c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60903c4016919900cae6fc3c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090483e70b6b8117b28cb2a--gamut-preview.netlify.app>https://6090483e70b6b8117b28cb2a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090483e70b6b8117b28cb2a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.3d11be.0<br/>@codecademy/gamut-kit@0.3.70-alpha.3d11be.0<br/>@codecademy/gamut-labs@15.2.10-alpha.3d11be.0<br/>@codecademy/gamut@32.8.3-alpha.3d11be.0<br/>@codecademy/styleguide@36.11.2-alpha.3d11be.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609058be54afb600c7d327ca--gamut-preview.netlify.app>https://609058be54afb600c7d327ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609058be54afb600c7d327ca>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.302ab2.0<br/>@codecademy/gamut-kit@0.3.70-alpha.302ab2.0<br/>@codecademy/gamut-labs@15.2.10-alpha.302ab2.0<br/>@codecademy/gamut@32.8.3-alpha.302ab2.0<br/>@codecademy/styleguide@36.11.2-alpha.302ab2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60907dd889d283262daed7d2--gamut-preview.netlify.app>https://60907dd889d283262daed7d2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60907dd889d283262daed7d2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.ddce55.0<br/>@codecademy/gamut-kit@0.3.71-alpha.ddce55.0<br/>@codecademy/gamut-labs@15.2.11-alpha.ddce55.0<br/>@codecademy/gamut@32.8.4-alpha.ddce55.0<br/>@codecademy/styleguide@36.11.3-alpha.ddce55.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091530105e17b20aea9c28a--gamut-preview.netlify.app>https://6091530105e17b20aea9c28a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091530105e17b20aea9c28a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.58dbf0.0<br/>@codecademy/gamut-kit@0.3.72-alpha.58dbf0.0<br/>@codecademy/gamut-labs@15.3.1-alpha.58dbf0.0<br/>@codecademy/gamut@32.9.1-alpha.58dbf0.0<br/>@codecademy/styleguide@36.12.1-alpha.58dbf0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609165c7c9bd5d32342f2238--gamut-preview.netlify.app>https://609165c7c9bd5d32342f2238--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609165c7c9bd5d32342f2238>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.b848a0.0<br/>@codecademy/gamut-kit@0.3.75-alpha.b848a0.0<br/>@codecademy/gamut-labs@15.4.1-alpha.b848a0.0<br/>@codecademy/gamut@32.10.1-alpha.b848a0.0<br/>@codecademy/styleguide@36.13.1-alpha.b848a0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60918c08927fd0009e6f7e1f--gamut-preview.netlify.app>https://60918c08927fd0009e6f7e1f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60918c08927fd0009e6f7e1f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.7d18bc.0<br/>@codecademy/gamut-kit@0.3.76-alpha.7d18bc.0<br/>@codecademy/gamut-labs@15.4.2-alpha.7d18bc.0<br/>@codecademy/gamut@32.10.2-alpha.7d18bc.0<br/>@codecademy/styleguide@36.13.2-alpha.7d18bc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60919d6f9e44e60bb4398f87--gamut-preview.netlify.app>https://60919d6f9e44e60bb4398f87--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60919d6f9e44e60bb4398f87>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.3d7959.0<br/>@codecademy/gamut-kit@0.3.76-alpha.3d7959.0<br/>@codecademy/gamut-labs@15.4.2-alpha.3d7959.0<br/>@codecademy/gamut@32.10.2-alpha.3d7959.0<br/>@codecademy/styleguide@36.13.2-alpha.3d7959.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091ab5f8c5948243c3b48a6--gamut-preview.netlify.app>https://6091ab5f8c5948243c3b48a6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091ab5f8c5948243c3b48a6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.76e087.0<br/>@codecademy/gamut-kit@0.3.77-alpha.76e087.0<br/>@codecademy/gamut-labs@15.5.1-alpha.76e087.0<br/>@codecademy/gamut@32.11.1-alpha.76e087.0<br/>@codecademy/styleguide@36.13.3-alpha.76e087.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091fd52cc315811ea1be165--gamut-preview.netlify.app>https://6091fd52cc315811ea1be165--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091fd52cc315811ea1be165>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.088207.0<br/>@codecademy/gamut-kit@0.3.77-alpha.088207.0<br/>@codecademy/gamut-labs@15.5.1-alpha.088207.0<br/>@codecademy/gamut@32.11.1-alpha.088207.0<br/>@codecademy/styleguide@36.13.3-alpha.088207.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60929dd73bf13f25137a1b50--gamut-preview.netlify.app>https://60929dd73bf13f25137a1b50--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60929dd73bf13f25137a1b50>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.10.1-alpha.3e240b.0<br/>@codecademy/gamut-kit@0.3.82-alpha.3e240b.0<br/>@codecademy/gamut-labs@15.5.6-alpha.3e240b.0<br/>@codecademy/gamut@32.13.1-alpha.3e240b.0<br/>@codecademy/styleguide@36.15.1-alpha.3e240b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609338d3c2bd5900dcedcdd5--gamut-preview.netlify.app>https://609338d3c2bd5900dcedcdd5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609338d3c2bd5900dcedcdd5>Deploy Logs</a></p>

**Pull request merged**
