### PR TITLE
fix(Gamut): Standardizes node type props as "as" GM-53

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview
- Switches instances of tagName and el to as.
- Specifies at `React.ElementType` for non restrictive props instead of other types (string etc).  This is inline with `emotion/styled` typings for the same prop.
- Updates the functions to initialize with `div` so docgen can pick it up.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GM-53
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Yip yip LGTM! Looking forward to everything being as CSS-in-JS-y as possible..

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.5-alpha.11ea7b.0<br/>@codecademy/gamut@17.3.4-alpha.11ea7b.0<br/>@codecademy/styleguide@18.5.4-alpha.11ea7b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faebf2cf90af400d6f030e4--gamut-preview.netlify.app>https://5faebf2cf90af400d6f030e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faebf2cf90af400d6f030e4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.6-alpha.50344f.0<br/>@codecademy/gamut@17.3.5-alpha.50344f.0<br/>@codecademy/styleguide@18.5.5-alpha.50344f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faec325537ad700b0100e40--gamut-preview.netlify.app>https://5faec325537ad700b0100e40--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faec325537ad700b0100e40>Deploy Logs</a></p>

**Pull request merged**
