### PR TITLE
feat(Icons): Add checkout icons

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Add icons for checkout

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.5.1-alpha.ad464f.0<br/>@codecademy/gamut-kit@0.3.15-alpha.ad464f.0<br/>@codecademy/gamut-labs@13.4.7-alpha.ad464f.0<br/>@codecademy/gamut@29.9.7-alpha.ad464f.0<br/>@codecademy/styleguide@33.9.7-alpha.ad464f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6075f44243273a16d67f169a--gamut-preview.netlify.app>https://6075f44243273a16d67f169a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6075f44243273a16d67f169a>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by zippyzow — COMMENTED** [review]
Looks great, thanks for adding these! Looking at the preview app, it looks like we actually already have the ProgrammingHoldIcon under the name ExperienceIcon?

**Comment by JoshuaKGoldberg** [comment]
Ooh great catch @zippyzow!

I wonder if we could flag for approximately duplicated icons at build time...

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
What @zippyzow said 😄

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.5.1-alpha.72c6c6.0<br/>@codecademy/gamut-kit@0.3.15-alpha.72c6c6.0<br/>@codecademy/gamut-labs@13.4.7-alpha.72c6c6.0<br/>@codecademy/gamut@29.9.7-alpha.72c6c6.0<br/>@codecademy/styleguide@33.9.7-alpha.72c6c6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607c712bcaf5658b0a3bb9e5--gamut-preview.netlify.app>https://607c712bcaf5658b0a3bb9e5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607c712bcaf5658b0a3bb9e5>Deploy Logs</a></p>

**Review by zippyzow — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.7.1-alpha.2ed99d.0<br/>@codecademy/gamut-kit@0.3.31-alpha.2ed99d.0<br/>@codecademy/gamut-labs@13.5.8-alpha.2ed99d.0<br/>@codecademy/gamut@31.0.2-alpha.2ed99d.0<br/>@codecademy/styleguide@35.0.5-alpha.2ed99d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607da2e82be9f000a67a8b92--gamut-preview.netlify.app>https://607da2e82be9f000a67a8b92--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607da2e82be9f000a67a8b92>Deploy Logs</a></p>

**Pull request merged**
