### PR TITLE
feat: change LP components text color to navy

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Changes text color to navy for landing page components, per design request. Also refactors some components to use `Box` instead of styled divs.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-576]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.5-alpha.48d2c4.0<br/>@codecademy/styleguide@24.0.3-alpha.48d2c4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60198fa959bae81ca2d4343b--gamut-preview.netlify.app>https://60198fa959bae81ca2d4343b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60198fa959bae81ca2d4343b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.5-alpha.91247a.0<br/>@codecademy/styleguide@24.0.3-alpha.91247a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019954a59bae821abd43455--gamut-preview.netlify.app>https://6019954a59bae821abd43455--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019954a59bae821abd43455>Deploy Logs</a></p>

**Review by christian-dinh — APPROVED** [review]
and with 9 fewer lines to think about 🎉

**Review by rogervera — APPROVED** [review]
BOX! 📦

**Review by JoshuaKGoldberg — APPROVED** [review]
Great!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.2.1-alpha.b1ff89.0<br/>@codecademy/styleguide@24.2.1-alpha.b1ff89.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019d17fce9ffb0b6a0a522c--gamut-preview.netlify.app>https://6019d17fce9ffb0b6a0a522c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019d17fce9ffb0b6a0a522c>Deploy Logs</a></p>

**Pull request merged**
