### PR TITLE
fix(Anchor): Fixes pseudo state text decoration mismatches

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Had a regression when we migrated for some pseudo states @aresnik11 found.

* Removes underline from `interface` Anchors. 
* Adds underline for hover and active for `standard` anchors.
* Adds whitespace reset for inline links to correct Google Mobile issue with long links.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.eb0d8f.0<br/>@codecademy/gamut-labs@14.5.2-alpha.eb0d8f.0<br/>@codecademy/gamut@32.4.2-alpha.eb0d8f.0<br/>@codecademy/styleguide@36.5.4-alpha.eb0d8f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088a31cdd26c30ff7eb2eac--gamut-preview.netlify.app>https://6088a31cdd26c30ff7eb2eac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088a31cdd26c30ff7eb2eac>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.59-alpha.2d6296.0<br/>@codecademy/gamut-labs@15.1.2-alpha.2d6296.0<br/>@codecademy/gamut@32.4.3-alpha.2d6296.0<br/>@codecademy/styleguide@36.6.2-alpha.2d6296.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608ac358fc8e0400e87172ce--gamut-preview.netlify.app>https://608ac358fc8e0400e87172ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608ac358fc8e0400e87172ce>Deploy Logs</a></p>

**Pull request merged**
