### PR TITLE
fix: support navigator.sendBeacon not existing

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds a POST fallback for when `navigator.sendBeacon` doesn't exist -which is the case for Firefox when `beacon.enabled` is false.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1394
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.10.1-alpha.4b7052.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dcb642809a1d78c570b7cd--gamut-preview.netlify.app>https://60dcb642809a1d78c570b7cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dcb642809a1d78c570b7cd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dcb81c6b7d037188d7c5b6--gamut-preview.netlify.app>https://60dcb81c6b7d037188d7c5b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dcb81c6b7d037188d7c5b6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.11.1-alpha.448d4c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dcc0d8d8392700941ab160--gamut-preview.netlify.app>https://60dcc0d8d8392700941ab160--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dcc0d8d8392700941ab160>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.11.1-alpha.647357.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dcc3e094cbf10af189d82f--gamut-preview.netlify.app>https://60dcc3e094cbf10af189d82f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dcc3e094cbf10af189d82f>Deploy Logs</a></p>

**Pull request merged**
