### PR TITLE
chore: update yarn link instructions in README

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview
`yarn link`ing react is not always necessary, [as in static-sites](https://github.com/codecademy-engineering/static-sites/pull/451). Also, when react does need to be `yarn link`ed it is most effectively done at the client-modules root (particularly in the case of a gamut package depending on another gamut package, eg gamut-labs depending on gamut).

Explanation: since all client-modules packages list react as a peer dependency, they will resolve their react imports to the dev dependency version installed by the client-modules root. It is easier to link react one time there rather than separately in each package being linked (either directly or transitively)

for the changelog:

clarify yarn link instructions for react projects

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
I trust you and think this is reasonable, but we should confirm with the last person who ran into these struggles that we're not missing anything -- cc @neilzo ?

**Review by neilzo — APPROVED** [review]
Seems reasonable to me too.

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600b1f385dcdea00d9953daf--gamut-preview.netlify.app>https://600b1f385dcdea00d9953daf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600b1f385dcdea00d9953daf>Deploy Logs</a></p>

**Comment by jakemhiller** [comment]
Closed b/c this is outdated, we're trying to stop using yarn link

**Pull request closed without merging**
