### PR TITLE
docs: Checkbox

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
didn't swap the docs over, oops. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.16-alpha.870ab2.0<br/>@codecademy/gamut-labs@19.19.2-alpha.870ab2.0<br/>@codecademy/gamut@35.12.0-alpha.870ab2.0<br/>@codecademy/styleguide@42.7.0-alpha.870ab2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610c3adeeae3a2009e3fa3db--gamut-preview.netlify.app>https://610c3adeeae3a2009e3fa3db--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610c3adeeae3a2009e3fa3db>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.7.1-alpha.c7f55c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610c444b55581600d099a999--gamut-preview.netlify.app>https://610c444b55581600d099a999--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610c444b55581600d099a999>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.7.3-alpha.dd185b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d377f4f319fc6e9fcec06--gamut-preview.netlify.app>https://610d377f4f319fc6e9fcec06--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d377f4f319fc6e9fcec06>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.7.3-alpha.7f13a5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d7816185b20f50291c3ef--gamut-preview.netlify.app>https://610d7816185b20f50291c3ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d7816185b20f50291c3ef>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.7.4-alpha.5fead7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610da6d3fdc6d31e20d409c7--gamut-preview.netlify.app>https://610da6d3fdc6d31e20d409c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610da6d3fdc6d31e20d409c7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.7.6-alpha.c6b399.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.7.7-alpha.ab33bb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61117438044c782831ff60cb--gamut-preview.netlify.app>https://61117438044c782831ff60cb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61117438044c782831ff60cb>Deploy Logs</a></p>

**Pull request merged**
