### PR TITLE
fix(system): Bad operator

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview

Operator?  Can you help me place this call?  

Fix for gatsby upgrade https://github.com/codecademy-engineering/static-sites/pull/397/files

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
It would be nice if we found the place in Gatsby tooling that didn't like this & improved it, but we'll eventually lint for this so 🤷

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb5a2bfbf1ad111bb9fd71a--gamut-preview.netlify.app>https://5fb5a2bfbf1ad111bb9fd71a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb5a2bfbf1ad111bb9fd71a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.1-alpha.7978b4.0<br/>@codecademy/gamut-styles@7.4.4-alpha.7978b4.0<br/>@codecademy/gamut-system@0.1.3-alpha.7978b4.0<br/>@codecademy/gamut@17.3.9-alpha.7978b4.0<br/>@codecademy/markdown-overrides@0.3.12-alpha.7978b4.0<br/>@codecademy/styleguide@18.5.9-alpha.7978b4.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.1-alpha.28089d.0<br/>@codecademy/gamut-styles@7.4.4-alpha.28089d.0<br/>@codecademy/gamut-system@0.1.3-alpha.28089d.0<br/>@codecademy/gamut@17.3.9-alpha.28089d.0<br/>@codecademy/markdown-overrides@0.3.12-alpha.28089d.0<br/>@codecademy/styleguide@18.5.9-alpha.28089d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb5a6682ad69300d1e65ece--gamut-preview.netlify.app>https://5fb5a6682ad69300d1e65ece--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb5a6682ad69300d1e65ece>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.1-alpha.cfed03.0<br/>@codecademy/gamut-styles@7.4.4-alpha.cfed03.0<br/>@codecademy/gamut-system@0.1.3-alpha.cfed03.0<br/>@codecademy/gamut@17.3.9-alpha.cfed03.0<br/>@codecademy/markdown-overrides@0.3.12-alpha.cfed03.0<br/>@codecademy/styleguide@18.5.9-alpha.cfed03.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb5b80c90032e00c0a41535--gamut-preview.netlify.app>https://5fb5b80c90032e00c0a41535--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb5b80c90032e00c0a41535>Deploy Logs</a></p>

**Pull request merged**
