### PR TITLE
feat(GlobalHeader): adding referral link

### PR DESCRIPTION
**Pull request by cstatro**
### Overview
coauthored with @saghdaey 

### PR Checklist
Puts the referrals link back into the profile dropdown with visibility based on a prop in the `user` prop. 
- [ ] Related to designs:
- [x] Related to JIRA ticket: GROW-2422
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM!

Think this can be unit tested?

**Comment by cstatro** [comment]
@JoshuaKGoldberg yeah sure lol, this isn't review ready, i wanted to do that and figure out what some of these tracking specific values need to be. But definitely going to be testing here / monolith implementation

**Comment by JoshuaKGoldberg** [comment]
Oh ok! If it's not review ready you can make it a Draft and still get all the CI niceties.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.40-alpha.6dc793.0<br/>@codecademy/gamut-labs@19.10.6-alpha.6dc793.0<br/>@codecademy/styleguide@41.10.10-alpha.6dc793.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d11ce76d9df70f93b92865--gamut-preview.netlify.app>https://60d11ce76d9df70f93b92865--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d11ce76d9df70f93b92865>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.44-alpha.8f7f39.0<br/>@codecademy/gamut-labs@19.10.10-alpha.8f7f39.0<br/>@codecademy/styleguide@41.10.14-alpha.8f7f39.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d125860d9f12bbcf9f8a2f--gamut-preview.netlify.app>https://60d125860d9f12bbcf9f8a2f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d125860d9f12bbcf9f8a2f>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Pull request merged**
