### PR TITLE
fix(Styleguide): Move Box story to core

### PR DESCRIPTION
**Pull request by codecaaron**
Moves it.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.1-alpha.9f80fb.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]
I like to move it meme

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f9315ac85b28918a6e5259f--gamut-preview.netlify.app>https://5f9315ac85b28918a6e5259f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f9315ac85b28918a6e5259f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.9.1-alpha.c23727.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f931c789026882036bdd4d2--gamut-preview.netlify.app>https://5f931c789026882036bdd4d2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f931c789026882036bdd4d2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.10.1-alpha.95274e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f93322f1080493c8e8cbbf6--gamut-preview.netlify.app>https://5f93322f1080493c8e8cbbf6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f93322f1080493c8e8cbbf6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.10.1-alpha.cebb7e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f9352fbc7fa3162dc11a740--gamut-preview.netlify.app>https://5f9352fbc7fa3162dc11a740--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f9352fbc7fa3162dc11a740>Deploy Logs</a></p>

**Pull request merged**
