### PR TITLE
style(Subtitle): fixed lesson count bug when count is 0

### PR DESCRIPTION
**Pull request by aionate0812**
### Overview

Previously if the `scopeCount` prop in the `Subtitle` component was 0 it was returning `00` instead of nothing, added a conditional check to get the expected behavior

### Before
Screen Shot 2021-05-21 at 12 39 18 PM

### After 
Screen Shot 2021-05-21 at 12 41 33 PM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM as a bugfix

Maybe deserves a unit test? 😉

**Comment by aionate0812** [comment]
Test added 😄

**Review by judahtanthony — APPROVED** [review]
Looks good.  Thanks for updating the test.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.112-alpha.5c0613.0<br/>@codecademy/gamut-labs@18.1.3-alpha.5c0613.0<br/>@codecademy/styleguide@39.0.5-alpha.5c0613.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60abfdb939f49412ac2a8808--gamut-preview.netlify.app>https://60abfdb939f49412ac2a8808--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60abfdb939f49412ac2a8808>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.117-alpha.f84bf3.0<br/>@codecademy/gamut-labs@18.1.8-alpha.f84bf3.0<br/>@codecademy/styleguide@40.0.5-alpha.f84bf3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ae4137abbcd200a7509be5--gamut-preview.netlify.app>https://60ae4137abbcd200a7509be5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ae4137abbcd200a7509be5>Deploy Logs</a></p>

**Pull request merged**
