### PR TITLE
feat: bump ESLint configs to latest

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Bumps our lint packages to their latest and enables a bunch of rules that only had a few issues internally.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-2
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.bb29f4.0<br/>@codecademy/gamut-icons@5.9.4-alpha.bb29f4.0<br/>@codecademy/gamut-illustrations@0.17.21-alpha.bb29f4.0<br/>@codecademy/gamut-kit@0.5.55-alpha.bb29f4.0<br/>@codecademy/gamut-labs@19.23.18-alpha.bb29f4.0<br/>@codecademy/gamut-patterns@0.5.9-alpha.bb29f4.0<br/>@codecademy/gamut-styles@11.10.0-alpha.bb29f4.0<br/>@codecademy/gamut-system@0.8.0-alpha.bb29f4.0<br/>@codecademy/gamut-tests@2.4.24-alpha.bb29f4.0<br/>@codecademy/gamut@36.10.0-alpha.bb29f4.0<br/>@codecademy/konamimojisplosion@0.2.55-alpha.bb29f4.0<br/>@codecademy/markdown-overrides@0.5.68-alpha.bb29f4.0<br/>@codecademy/monaco@0.3.9-alpha.bb29f4.0<br/>@codecademy/styleguide@43.11.1-alpha.bb29f4.0<br/>@codecademy/tracking@0.14.0-alpha.bb29f4.0<br/>@codecademy/variance@0.18.0-alpha.bb29f4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6130edba2dcf0cefdb71f46c--gamut-preview.netlify.app>https://6130edba2dcf0cefdb71f46c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6130edba2dcf0cefdb71f46c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.2e1090.0<br/>@codecademy/gamut-icons@5.9.4-alpha.2e1090.0<br/>@codecademy/gamut-illustrations@0.17.21-alpha.2e1090.0<br/>@codecademy/gamut-kit@0.5.55-alpha.2e1090.0<br/>@codecademy/gamut-labs@19.23.18-alpha.2e1090.0<br/>@codecademy/gamut-patterns@0.5.9-alpha.2e1090.0<br/>@codecademy/gamut-styles@11.10.0-alpha.2e1090.0<br/>@codecademy/gamut-system@0.8.0-alpha.2e1090.0<br/>@codecademy/gamut-tests@2.4.24-alpha.2e1090.0<br/>@codecademy/gamut@36.10.0-alpha.2e1090.0<br/>@codecademy/konamimojisplosion@0.2.55-alpha.2e1090.0<br/>@codecademy/markdown-overrides@0.5.68-alpha.2e1090.0<br/>@codecademy/monaco@0.4.0-alpha.2e1090.0<br/>@codecademy/styleguide@43.11.1-alpha.2e1090.0<br/>@codecademy/tracking@0.14.0-alpha.2e1090.0<br/>@codecademy/variance@0.18.0-alpha.2e1090.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61310cca102702f890935ba8--gamut-preview.netlify.app>https://61310cca102702f890935ba8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61310cca102702f890935ba8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.9dd65d.0<br/>@codecademy/gamut-icons@5.10.0-alpha.9dd65d.0<br/>@codecademy/gamut-illustrations@0.18.0-alpha.9dd65d.0<br/>@codecademy/gamut-kit@0.5.55-alpha.9dd65d.0<br/>@codecademy/gamut-labs@19.24.0-alpha.9dd65d.0<br/>@codecademy/gamut-patterns@0.6.0-alpha.9dd65d.0<br/>@codecademy/gamut-styles@11.10.0-alpha.9dd65d.0<br/>@codecademy/gamut-system@0.8.0-alpha.9dd65d.0<br/>@codecademy/gamut-tests@2.5.0-alpha.9dd65d.0<br/>@codecademy/gamut@36.10.0-alpha.9dd65d.0<br/>@codecademy/konamimojisplosion@0.3.0-alpha.9dd65d.0<br/>@codecademy/macros@2.2.0-alpha.9dd65d.0<br/>@codecademy/markdown-overrides@0.6.0-alpha.9dd65d.0<br/>@codecademy/monaco@0.4.0-alpha.9dd65d.0<br/>@codecademy/styleguide@43.12.0-alpha.9dd65d.0<br/>@codecademy/tracking@0.14.0-alpha.9dd65d.0<br/>@codecademy/variance@0.18.0-alpha.9dd65d.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.ad39ee.0<br/>@codecademy/gamut-icons@5.10.0-alpha.ad39ee.0<br/>@codecademy/gamut-illustrations@0.18.0-alpha.ad39ee.0<br/>@codecademy/gamut-kit@0.5.60-alpha.ad39ee.0<br/>@codecademy/gamut-labs@19.25.0-alpha.ad39ee.0<br/>@codecademy/gamut-patterns@0.6.0-alpha.ad39ee.0<br/>@codecademy/gamut-styles@11.10.0-alpha.ad39ee.0<br/>@codecademy/gamut-system@0.8.0-alpha.ad39ee.0<br/>@codecademy/gamut-tests@2.5.0-alpha.ad39ee.0<br/>@codecademy/gamut@37.1.0-alpha.ad39ee.0<br/>@codecademy/konamimojisplosion@0.3.0-alpha.ad39ee.0<br/>@codecademy/macros@2.2.0-alpha.ad39ee.0<br/>@codecademy/markdown-overrides@0.6.0-alpha.ad39ee.0<br/>@codecademy/monaco@0.4.0-alpha.ad39ee.0<br/>@codecademy/styleguide@44.1.0-alpha.ad39ee.0<br/>@codecademy/tracking@0.14.0-alpha.ad39ee.0<br/>@codecademy/variance@0.18.0-alpha.ad39ee.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61326f38f3740785fbfd2b04--gamut-preview.netlify.app>https://61326f38f3740785fbfd2b04--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61326f38f3740785fbfd2b04>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.29766a.0<br/>@codecademy/gamut-icons@5.10.0-alpha.29766a.0<br/>@codecademy/gamut-illustrations@0.18.0-alpha.29766a.0<br/>@codecademy/gamut-kit@0.5.61-alpha.29766a.0<br/>@codecademy/gamut-labs@19.25.0-alpha.29766a.0<br/>@codecademy/gamut-patterns@0.6.0-alpha.29766a.0<br/>@codecademy/gamut-styles@11.10.0-alpha.29766a.0<br/>@codecademy/gamut-system@0.8.0-alpha.29766a.0<br/>@codecademy/gamut-tests@2.5.0-alpha.29766a.0<br/>@codecademy/gamut@37.2.0-alpha.29766a.0<br/>@codecademy/konamimojisplosion@0.3.0-alpha.29766a.0<br/>@codecademy/macros@2.2.0-alpha.29766a.0<br/>@codecademy/markdown-overrides@0.6.0-alpha.29766a.0<br/>@codecademy/monaco@0.4.0-alpha.29766a.0<br/>@codecademy/styleguide@44.2.0-alpha.29766a.0<br/>@codecademy/tracking@0.14.0-alpha.29766a.0<br/>@codecademy/variance@0.18.0-alpha.29766a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613287dc40b153c45cfa232c--gamut-preview.netlify.app>https://613287dc40b153c45cfa232c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613287dc40b153c45cfa232c>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
this looks good to me - have you tested the alpha in the repositories that use gamut? i don't think it *should* change anything but stranger things have happened

**Comment by JoshuaKGoldberg** [comment]
@dreamwasp yes! doing that soon!

**Comment by JoshuaKGoldberg** [comment]
Oh actually @dreamwasp yes, in https://github.com/codecademy-engineering/Codecademy/pull/26837. I'll get to portal-app and static-sites as part of my general ESLint cleanups too.

**Review by jakemhiller — APPROVED** [review]

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.56644e.0<br/>@codecademy/gamut-icons@5.10.0-alpha.56644e.0<br/>@codecademy/gamut-illustrations@0.18.0-alpha.56644e.0<br/>@codecademy/gamut-kit@0.5.67-alpha.56644e.0<br/>@codecademy/gamut-labs@19.25.0-alpha.56644e.0<br/>@codecademy/gamut-patterns@0.6.0-alpha.56644e.0<br/>@codecademy/gamut-styles@11.10.0-alpha.56644e.0<br/>@codecademy/gamut-system@0.8.0-alpha.56644e.0<br/>@codecademy/gamut-tests@2.5.0-alpha.56644e.0<br/>@codecademy/gamut@37.2.0-alpha.56644e.0<br/>@codecademy/konamimojisplosion@0.3.0-alpha.56644e.0<br/>@codecademy/macros@2.2.0-alpha.56644e.0<br/>@codecademy/markdown-overrides@0.6.0-alpha.56644e.0<br/>@codecademy/monaco@0.4.0-alpha.56644e.0<br/>@codecademy/styleguide@44.2.0-alpha.56644e.0<br/>@codecademy/tracking@0.14.0-alpha.56644e.0<br/>@codecademy/variance@0.18.0-alpha.56644e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a220e52df06233c5f08d8--gamut-preview.netlify.app>https://613a220e52df06233c5f08d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a220e52df06233c5f08d8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.4.0-alpha.9c9d3a.0<br/>@codecademy/gamut-icons@5.10.0-alpha.9c9d3a.0<br/>@codecademy/gamut-illustrations@0.18.0-alpha.9c9d3a.0<br/>@codecademy/gamut-kit@0.5.71-alpha.9c9d3a.0<br/>@codecademy/gamut-labs@19.26.0-alpha.9c9d3a.0<br/>@codecademy/gamut-patterns@0.6.0-alpha.9c9d3a.0<br/>@codecademy/gamut-styles@11.10.0-alpha.9c9d3a.0<br/>@codecademy/gamut-system@0.8.0-alpha.9c9d3a.0<br/>@codecademy/gamut-tests@2.6.0-alpha.9c9d3a.0<br/>@codecademy/gamut@37.3.0-alpha.9c9d3a.0<br/>@codecademy/konamimojisplosion@0.3.0-alpha.9c9d3a.0<br/>@codecademy/macros@2.2.0-alpha.9c9d3a.0<br/>@codecademy/markdown-overrides@0.6.0-alpha.9c9d3a.0<br/>@codecademy/monaco@0.4.0-alpha.9c9d3a.0<br/>@codecademy/styleguide@44.3.0-alpha.9c9d3a.0<br/>@codecademy/tracking@0.14.0-alpha.9c9d3a.0<br/>@codecademy/variance@0.18.0-alpha.9c9d3a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b5c1ff94826df4149577d--gamut-preview.netlify.app>https://613b5c1ff94826df4149577d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b5c1ff94826df4149577d>Deploy Logs</a></p>

**Pull request merged**
