### PR TITLE
feat(Tracking): add is_ugc attribute to tracking types

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview

adds `is_ugc` attribute to click, visit, and impression event tracking types (for use in portal-app)

### PR Checklist

- [x] Related to JIRA ticket: [REACH-1686](https://codecademy.atlassian.net/browse/REACH-1686)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.12-alpha.1404c3.0<br/>@codecademy/tracking@0.18.2-alpha.1404c3.0<br/></pre>

**Review by njradford — APPROVED** [review]
Simple and makes sense to me!

**Review by aresnik11 — APPROVED** [review]
This will def work! 2 questions:

1. Does it make sense to add this within `UserSharedData` since it is shared?
2. Might be worth double checking with / flagging to data science since there is a note saying to avoid adding additional properties

**Comment by christian-dinh** [comment]
@aresnik11 I would personally be fine doing `type: 'ugc'` on ugc events, I'll ask around though

**Comment by christian-dinh** [comment]
after some asking around it looks like we're good to go with `is_ugc`. The original reasoning was that user-generated content will likely find its way to other parts of the site in the future, and to that end we already have a second use-case in cc docs. Gonna go ahead ad merge this!

**Pull request merged**
