### PR TITLE
chore: Sunset FlexGrid

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Occasionally this causes styles to be added to catalog page for some reason so it removes it.

* This no longer has any references :(

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.3e4fd3.0<br/>@codecademy/gamut-labs@19.0.6-alpha.3e4fd3.0<br/>@codecademy/gamut@34.0.3-alpha.3e4fd3.0<br/>@codecademy/styleguide@41.2.5-alpha.3e4fd3.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
RIP

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bf88caae1c3a3b59def957--gamut-preview.netlify.app>https://60bf88caae1c3a3b59def957--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bf88caae1c3a3b59def957>Deploy Logs</a></p>

**Comment by jakemhiller** [comment]
I can't even find the initial commit of FlexGrid b/c it happened in the old `identity` package in a different GitHub org 🍺

**Comment by codecaaron** [comment]
> I can't even find the initial commit of FlexGrid b/c it happened in the old `identity` package in a different GitHub org 🍺

Ahead of its time <3

**Review by JoshuaKGoldberg — APPROVED** [review]
rip

**Review by dreamwasp — APPROVED** [review]
🪦💀🪦

**Pull request merged**
