### PR TITLE
feat: tight variant for Checkbox

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
adds a tight spacing variant for Checkbox + adds functionality to GridForm

### PR Checklist

- [x] Related to designs:[ here](https://www.figma.com/file/m0vPPF2ZPINGVV9SZBcVQx/Trial%3A-Content-Recommendations?node-id=219%3A1477)
- [x] Related to JIRA ticket: [gm-298](https://codecademy.atlassian.net/browse/GM-298)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.15-alpha.2a03df.0<br/>@codecademy/gamut-labs@19.19.1-alpha.2a03df.0<br/>@codecademy/gamut@35.10.2-alpha.2a03df.0<br/>@codecademy/styleguide@42.6.7-alpha.2a03df.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6109a83ea7ca5700b2cefe5f--gamut-preview.netlify.app>https://6109a83ea7ca5700b2cefe5f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6109a83ea7ca5700b2cefe5f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.15-alpha.252cb6.0<br/>@codecademy/gamut-labs@19.19.1-alpha.252cb6.0<br/>@codecademy/gamut@35.10.2-alpha.252cb6.0<br/>@codecademy/styleguide@42.6.7-alpha.252cb6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6109ab36a7ca57008ecefeb0--gamut-preview.netlify.app>https://6109ab36a7ca57008ecefeb0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6109ab36a7ca57008ecefeb0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.15-alpha.cb65a9.0<br/>@codecademy/gamut-labs@19.19.1-alpha.cb65a9.0<br/>@codecademy/gamut@35.10.2-alpha.cb65a9.0<br/>@codecademy/styleguide@42.6.7-alpha.cb65a9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6109aff51e26ce07528d2248--gamut-preview.netlify.app>https://6109aff51e26ce07528d2248--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6109aff51e26ce07528d2248>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.15-alpha.ef088a.0<br/>@codecademy/gamut-labs@19.19.1-alpha.ef088a.0<br/>@codecademy/gamut@35.10.2-alpha.ef088a.0<br/>@codecademy/styleguide@42.6.7-alpha.ef088a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6109b6a28764f313aad39ae7--gamut-preview.netlify.app>https://6109b6a28764f313aad39ae7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6109b6a28764f313aad39ae7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.16-alpha.ad5e91.0<br/>@codecademy/gamut-labs@19.19.2-alpha.ad5e91.0<br/>@codecademy/gamut@35.11.1-alpha.ad5e91.0<br/>@codecademy/styleguide@42.6.8-alpha.ad5e91.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610be7edfe98d8efd891cc7d--gamut-preview.netlify.app>https://610be7edfe98d8efd891cc7d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610be7edfe98d8efd891cc7d>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
:shipit:

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.16-alpha.dae137.0<br/>@codecademy/gamut-labs@19.19.2-alpha.dae137.0<br/>@codecademy/gamut@35.11.1-alpha.dae137.0<br/>@codecademy/styleguide@42.6.8-alpha.dae137.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610bfba8cbaffefe05ca4a72--gamut-preview.netlify.app>https://610bfba8cbaffefe05ca4a72--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610bfba8cbaffefe05ca4a72>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.16-alpha.9f8d02.0<br/>@codecademy/gamut-labs@19.19.2-alpha.9f8d02.0<br/>@codecademy/gamut@35.11.1-alpha.9f8d02.0<br/>@codecademy/styleguide@42.6.8-alpha.9f8d02.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610c006c24167eed7f2c451c--gamut-preview.netlify.app>https://610c006c24167eed7f2c451c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610c006c24167eed7f2c451c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.16-alpha.39b5a4.0<br/>@codecademy/gamut-labs@19.19.2-alpha.39b5a4.0<br/>@codecademy/gamut@35.11.1-alpha.39b5a4.0<br/>@codecademy/styleguide@42.6.8-alpha.39b5a4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610c0546cbaffe02d3ca5390--gamut-preview.netlify.app>https://610c0546cbaffe02d3ca5390--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610c0546cbaffe02d3ca5390>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
