### PR TITLE
feat(tracking): Add a fullstory boolean to TrackingOptions type

### PR DESCRIPTION
**Pull request by j10sanders**
### Overview

A small change: Fullstory only accepts client-side tracking (using analytics.track()).  So this adds an option for us to add fullstory tracking to events.  We plan to add this to onboarding-related events.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GROW-2047
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.2.2-alpha.bf71ec.0<br/></pre>

**Review by codecaaron — CHANGES_REQUESTED** [review]
Got some `/dist` relics from a deleted package to clean up.

Otherwise LGTM

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.2.2-alpha.ce2b44.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffddc9bc5f9e801127d5a68--gamut-preview.netlify.app>https://5ffddc9bc5f9e801127d5a68--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffddc9bc5f9e801127d5a68>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.2.2-alpha.9a25d6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffdf120c0aa100cce84fb98--gamut-preview.netlify.app>https://5ffdf120c0aa100cce84fb98--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffdf120c0aa100cce84fb98>Deploy Logs</a></p>

**Pull request merged**
