### PR TITLE
fix: aria-hidden tag added to chevron in accordion button component

### PR DESCRIPTION
**Pull request by dreamwasp**
## Overview
This PR adds the "aria-hidden" tag to the arrow icon of the AccordionButton component so that the chevron is not announced by VoiceOver.

### PR Checklist

- [x] Related to JIRA ticket: [LX-4294](https://codecademy.atlassian.net/browse/LX-4294)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
This PR adds the "aria-hidden" tag to the arrow icon of the AccordionButton component so that the chevron is not announced by VoiceOver as the icon itself is a decorative component.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.1-alpha.d67f6e.0<br/>@codecademy/gamut@16.2.3-alpha.d67f6e.0<br/>@codecademy/styleguide@17.7.3-alpha.d67f6e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8dcb107bb2230dc7df03a6--gamut-preview.netlify.app>https://5f8dcb107bb2230dc7df03a6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8dcb107bb2230dc7df03a6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.1-alpha.50895c.0<br/>@codecademy/gamut@16.2.3-alpha.50895c.0<br/>@codecademy/styleguide@17.7.3-alpha.50895c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8dcb73fa11050ce2a182cc--gamut-preview.netlify.app>https://5f8dcb73fa11050ce2a182cc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8dcb73fa11050ce2a182cc>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks!

**Pull request merged**
