### PR TITLE
feat(icon): StarCircleIcon

### PR DESCRIPTION
**Pull request by songstephen**
### Overview

Added StarCircleIcon for usage in CC Docs V2

### PR Checklist

- [X] Related to designs: https://www.figma.com/file/SwfwQZmV4jtK68QaCa89h3/CC-Docs-v2-User-Recognition?node-id=596%3A54970
- [ ] Related to JIRA ticket: ABC-123
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]
⭐ 🟢

**Review by JoshuaKGoldberg — APPROVED** [review]
⭐

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.9.4-alpha.e1833c.0<br/>@codecademy/gamut-kit@0.5.71-alpha.e1833c.0<br/>@codecademy/gamut-labs@19.25.3-alpha.e1833c.0<br/>@codecademy/gamut@37.2.1-alpha.e1833c.0<br/>@codecademy/monaco@0.3.16-alpha.e1833c.0<br/>@codecademy/styleguide@44.2.4-alpha.e1833c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b594c389cfee63242d535--gamut-preview.netlify.app>https://613b594c389cfee63242d535--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b594c389cfee63242d535>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61449a128f7fc6491b93fa62--gamut-preview.netlify.app>https://61449a128f7fc6491b93fa62--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61449a128f7fc6491b93fa62>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6144e4c956d0607f0ed3eff7--gamut-preview.netlify.app>https://6144e4c956d0607f0ed3eff7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6144e4c956d0607f0ed3eff7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148eddb33f6f51ce7b3fc84--gamut-preview.netlify.app>https://6148eddb33f6f51ce7b3fc84--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148eddb33f6f51ce7b3fc84>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.11.1-alpha.557856.0<br/>@codecademy/gamut-kit@0.5.86-alpha.557856.0<br/>@codecademy/gamut-labs@20.1.3-alpha.557856.0<br/>@codecademy/gamut@37.6.2-alpha.557856.0<br/>@codecademy/monaco@0.4.10-alpha.557856.0<br/>@codecademy/styleguide@44.7.2-alpha.557856.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148f1155531f0229b590102--gamut-preview.netlify.app>https://6148f1155531f0229b590102--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148f1155531f0229b590102>Deploy Logs</a></p>

**Pull request merged**
