### PR TITLE
fix(AppHeaderDropdown): fix jumpiness of bold text when dropdown is o…

### PR DESCRIPTION
**Pull request by natalieweesh**
…pened

### Overview

AppHeaderDropdown: fix jumpiness of bold text when dropdown menu is opened 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: EGG-776
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

BEFORE: (toggling open the dropdown pushes the triangle to the right when the text is bold)

ezgif-3-3d45c503e13e

AFTER: (the triangle does not get pushed to the right by the bold text)

ezgif-3-b118108a1019

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.3.3-alpha.8655bc.0<br/>@codecademy/styleguide@25.2.3-alpha.8655bc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6025689c632bfe50251b0991--gamut-preview.netlify.app>https://6025689c632bfe50251b0991--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6025689c632bfe50251b0991>Deploy Logs</a></p>

**Review by katiezutter — APPROVED** [review]
Nice! Even tried the alpha version on static-sites locally - looks great!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.3.5-alpha.24bad2.0<br/>@codecademy/styleguide@25.2.5-alpha.24bad2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6025aabac4c175012e1331e1--gamut-preview.netlify.app>https://6025aabac4c175012e1331e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6025aabac4c175012e1331e1>Deploy Logs</a></p>

**Pull request merged**
