### PR TITLE
fix(import): use relative path for logo import

### PR DESCRIPTION
**Pull request by saghdaey**
### PR Checklist

see convo - https://github.com/codecademy-engineering/Codecademy/pull/21360

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.1-alpha.e3a933.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60021914d3f5ac0e9f5066bb--gamut-preview.netlify.app>https://60021914d3f5ac0e9f5066bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60021914d3f5ac0e9f5066bb>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.2-alpha.d1944e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60021c662227c414745148f4--gamut-preview.netlify.app>https://60021c662227c414745148f4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60021c662227c414745148f4>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Pull request merged**
