### PR TITLE
feat(Card)!: Add color mode to card

### PR DESCRIPTION
**Pull request by sooinc**
### Overview

- feat: adds color mode to card

### PR Checklist
- adds color mode to cards which applies dynamic wrapper that uses color mode.

https://www.figma.com/proto/enGqhyq9xlbkCkJLArNWeR/Refine?node-id=423%3A920&scaling=min-zoom&page-id=417%3A550&starting-point-node-id=420%3A759

- [x] Related to designs: https://www.figma.com/file/ZUv9GvNr2pd0RneOdQPtwa/Build?node-id=2%3A41
- [x] Related to JIRA ticket: Egg-1710
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.56-alpha.266390.0<br/>@codecademy/gamut-labs@19.23.19-alpha.266390.0<br/>@codecademy/gamut@36.9.2-alpha.266390.0<br/>@codecademy/monaco@0.3.10-alpha.266390.0<br/>@codecademy/styleguide@43.11.2-alpha.266390.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6131648a9d12cd4bcf4c9740--gamut-preview.netlify.app>https://6131648a9d12cd4bcf4c9740--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6131648a9d12cd4bcf4c9740>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
👍 Nice!  Thanks for doing this

**Review by dreamwasp — APPROVED** [review]
yessssss

**Comment by codecaaron** [comment]
@sooinc  Looks like jest is doing funky things with imports again.  Try updating the import to `../Box` instead and your tests should pass.

Also when you release this version just do a quick cursory glance over where we are using cards (outside of curriculum etc) to see if everything looks shipshape.

**Comment by sooinc** [comment]
> @sooinc Looks like jest is doing funky things with imports again. Try updating the import to `../Box` instead and your tests should pass.
> 
> Also when you release this version just do a quick cursory glance over where we are using cards (outside of curriculum etc) to see if everything looks shipshape.

Ah thank you, that fixed it! And yes, here's my accompanying monolith PR that will release it: https://github.com/codecademy-engineering/Codecademy/pull/26874

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613233f5aa4cec72e6ce96b7--gamut-preview.netlify.app>https://613233f5aa4cec72e6ce96b7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613233f5aa4cec72e6ce96b7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.56-alpha.c1f56a.0<br/>@codecademy/gamut-labs@19.23.19-alpha.c1f56a.0<br/>@codecademy/gamut@36.9.2-alpha.c1f56a.0<br/>@codecademy/monaco@0.3.10-alpha.c1f56a.0<br/>@codecademy/styleguide@43.11.2-alpha.c1f56a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6132374140e8e94e30ed6e8e--gamut-preview.netlify.app>https://6132374140e8e94e30ed6e8e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6132374140e8e94e30ed6e8e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.58-alpha.44c7b2.0<br/>@codecademy/gamut-labs@19.24.2-alpha.44c7b2.0<br/>@codecademy/gamut@36.9.3-alpha.44c7b2.0<br/>@codecademy/monaco@0.3.11-alpha.44c7b2.0<br/>@codecademy/styleguide@43.11.4-alpha.44c7b2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61324e6242ef123f2e2afa79--gamut-preview.netlify.app>https://61324e6242ef123f2e2afa79--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61324e6242ef123f2e2afa79>Deploy Logs</a></p>

**Pull request merged**
