### PR TITLE
chore: bumped Node to 14

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Upgrades our infra to require Node 14.

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611e90e08d7a642dc7298c00--gamut-preview.netlify.app>https://611e90e08d7a642dc7298c00--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611e90e08d7a642dc7298c00>Deploy Logs</a></p>

**Review by codecaaron — CHANGES_REQUESTED** [review]
Could we update the version in the nvmrc too? https://github.com/Codecademy/client-modules/blob/main/.nvmrc

**Comment by codecaaron** [comment]
Also yay <3 thank you

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611e9d7fbf67343d60c1e0da--gamut-preview.netlify.app>https://611e9d7fbf67343d60c1e0da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611e9d7fbf67343d60c1e0da>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611fdecbdf8dc8982e10cd46--gamut-preview.netlify.app>https://611fdecbdf8dc8982e10cd46--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611fdecbdf8dc8982e10cd46>Deploy Logs</a></p>

**Pull request merged**
