### PR TITLE
fix: Hover + Shadow regression

### PR DESCRIPTION
**Pull request by codecaaron**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by dreamwasp — APPROVED** [review]
✅

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.2-alpha.dd3d61.0<br/>@codecademy/gamut-illustrations@0.17.9-alpha.dd3d61.0<br/>@codecademy/gamut-kit@0.4.33-alpha.dd3d61.0<br/>@codecademy/gamut-labs@19.9.2-alpha.dd3d61.0<br/>@codecademy/gamut-patterns@0.4.4-alpha.dd3d61.0<br/>@codecademy/gamut-styles@11.5.1-alpha.dd3d61.0<br/>@codecademy/gamut-tests@2.4.12-alpha.dd3d61.0<br/>@codecademy/gamut@34.10.1-alpha.dd3d61.0<br/>@codecademy/konamimojisplosion@0.2.43-alpha.dd3d61.0<br/>@codecademy/markdown-overrides@0.5.55-alpha.dd3d61.0<br/>@codecademy/styleguide@41.10.3-alpha.dd3d61.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.2-alpha.a889ea.0<br/>@codecademy/gamut-illustrations@0.17.9-alpha.a889ea.0<br/>@codecademy/gamut-kit@0.4.33-alpha.a889ea.0<br/>@codecademy/gamut-labs@19.9.2-alpha.a889ea.0<br/>@codecademy/gamut-patterns@0.4.4-alpha.a889ea.0<br/>@codecademy/gamut-styles@11.5.1-alpha.a889ea.0<br/>@codecademy/gamut-tests@2.4.12-alpha.a889ea.0<br/>@codecademy/gamut@34.10.1-alpha.a889ea.0<br/>@codecademy/konamimojisplosion@0.2.43-alpha.a889ea.0<br/>@codecademy/markdown-overrides@0.5.55-alpha.a889ea.0<br/>@codecademy/styleguide@41.10.3-alpha.a889ea.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb7c0ea994c400e3f7b21d--gamut-preview.netlify.app>https://60cb7c0ea994c400e3f7b21d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb7c0ea994c400e3f7b21d>Deploy Logs</a></p>

**Pull request merged**
