### PR TITLE
refactor(Quote): use Emotion and variants for dark/light theme

### PR DESCRIPTION
**Pull request by rogervera**
### Overview

Converts `Quote` (used internally for `Testimonials`) to Emotion and uses `variants` for dark/light theme.

### PR Checklist

- [ ] ~Related to designs:~
- [x] Related to JIRA ticket: [REACH-478](https://codecademy.atlassian.net/browse/REACH-478)
- [x] I have run this code to verify it works 
- [ ] This PR includes unit tests for the code change (Removed tests on className 😳)

### Testing
1.  Compare [old story](https://gamut.codecademy.com/storybook/?path=/docs/brand-atoms-quote--quote) vs [new story](https://6048eef1b4fc5f0fe0ea212f--gamut-preview.netlify.app/storybook/?path=/docs/brand-atoms-quote--quote) (**there should be no visual changes**)

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.2bbd70.0<br/>@codecademy/gamut-labs@11.1.1-alpha.2bbd70.0<br/>@codecademy/styleguide@30.4.3-alpha.2bbd70.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6048eef1b4fc5f0fe0ea212f--gamut-preview.netlify.app>https://6048eef1b4fc5f0fe0ea212f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6048eef1b4fc5f0fe0ea212f>Deploy Logs</a></p>

**Review by christian-dinh — APPROVED** [review]
:shipit:

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.13-alpha.1759fe.0<br/>@codecademy/gamut-labs@11.2.1-alpha.1759fe.0<br/>@codecademy/styleguide@30.5.1-alpha.1759fe.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60490afa4286500d049da424--gamut-preview.netlify.app>https://60490afa4286500d049da424--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60490afa4286500d049da424>Deploy Logs</a></p>

**Review by aresnik11 — COMMENTED** [review]
should https://github.com/Codecademy/client-modules/blob/main/packages/gamut-labs/src/brand/Quote/styles.module.scss get deleted? looks like we're no longer using it

**Review by aresnik11 — APPROVED** [review]
LGTM!

**Pull request merged**
