### PR TITLE
fix: update flex items to grow and shrink evenly in landing page features section

### PR DESCRIPTION
**Pull request by aresnik11**
### PR Checklist

- [x] Related to designs: https://www.figma.com/file/2aBlW1pgFt5PT6soRu1HXy/%E2%9C%8F%EF%B8%8F-Landing-Page-Templates---Unification?node-id=1%3A43
- [x] Related to JIRA ticket: [REACH-384]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
Add `flex: 1` to feature items so they all appear the same size.

### CODE REVIEW

**Review by rogervera — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.2-alpha.9c42a1.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.2-alpha.b86ead.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb849f1ef29232150d20dbc--gamut-preview.netlify.app>https://5fb849f1ef29232150d20dbc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb849f1ef29232150d20dbc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb849def6523626c6883487--gamut-preview.netlify.app>https://5fb849def6523626c6883487--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb849def6523626c6883487>Deploy Logs</a></p>

**Pull request merged**
