### PR TITLE
feat(Markdown): allow generated heading ids [CET-617]

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Adds `headingIds` prop to Markdown component, allowing for deterministically generated ids used for linking.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.26-alpha.a7e3bd.0<br/>@codecademy/gamut-labs@13.0.2-alpha.a7e3bd.0<br/>@codecademy/gamut@28.0.2-alpha.a7e3bd.0<br/>@codecademy/styleguide@32.0.4-alpha.a7e3bd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60550e4cd05c8951c7efc41a--gamut-preview.netlify.app>https://60550e4cd05c8951c7efc41a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60550e4cd05c8951c7efc41a>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Seems reasonable.

Any chance of a unit test?

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.28-alpha.c13baf.0<br/>@codecademy/gamut-labs@13.0.4-alpha.c13baf.0<br/>@codecademy/gamut@29.0.2-alpha.c13baf.0<br/>@codecademy/styleguide@33.0.2-alpha.c13baf.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.28-alpha.52b163.0<br/>@codecademy/gamut-labs@13.0.4-alpha.52b163.0<br/>@codecademy/gamut@29.0.2-alpha.52b163.0<br/>@codecademy/styleguide@33.0.2-alpha.52b163.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6058eddee9b96238056fb6c1--gamut-preview.netlify.app>https://6058eddee9b96238056fb6c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6058eddee9b96238056fb6c1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.29-alpha.14f94a.0<br/>@codecademy/gamut-labs@13.0.5-alpha.14f94a.0<br/>@codecademy/gamut@29.1.1-alpha.14f94a.0<br/>@codecademy/styleguide@33.0.3-alpha.14f94a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605937561962132afbdd5a19--gamut-preview.netlify.app>https://605937561962132afbdd5a19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605937561962132afbdd5a19>Deploy Logs</a></p>

**Pull request merged**
