### PR TITLE
feat(Styleguide): Flatten Navigation Hierarchy for Gamut Core

### PR DESCRIPTION
**Pull request by jakemhiller**
## Overview
Flattens Core to the top level navigation, making things we want to surface easier to find.  Also gets rid of custom sorting function since everything is a "kind" now.

### PR Checklist

- [ ] Related to Abstract designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description

---

## Merging your changes

When you are ready to merge to master and publish your changes, use the "squash and merge" button in GitHub, and follow the [PR Title Guide](https://github.com/Codecademy/client-modules#pr-title-guide) to format your PR title and write your PR merge description.

**IMPORTANT:** If your PR contains breaking changes, please remember to follow the instructions for breaking changes!

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f04cdbda49bf1ea4d05d073--codecademy-styleguide.netlify.app>https://5f04cdbda49bf1ea4d05d073--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f04cdbda49bf1ea4d05d073>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f04cff5b43e6fec6423ae39--codecademy-styleguide.netlify.app>https://5f04cff5b43e6fec6423ae39--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f04cff5b43e6fec6423ae39>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f04d1672ad641026865703c--codecademy-styleguide.netlify.app>https://5f04d1672ad641026865703c--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f04d1672ad641026865703c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f0de8f1ddc5f1db3194c164--codecademy-styleguide.netlify.app>https://5f0de8f1ddc5f1db3194c164--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f0de8f1ddc5f1db3194c164>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f0deea8fa04da024ef96cc8--codecademy-styleguide.netlify.app>https://5f0deea8fa04da024ef96cc8--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f0deea8fa04da024ef96cc8>Deploy Logs</a></p>

**Comment by jakemhiller** [comment]
I can't approve but I would 👍

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f0e09cdd0c11d019814819d--codecademy-styleguide.netlify.app>https://5f0e09cdd0c11d019814819d--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f0e09cdd0c11d019814819d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f0e0cc41ca7d3806d545081--codecademy-styleguide.netlify.app>https://5f0e0cc41ca7d3806d545081--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5f0e0cc41ca7d3806d545081>Deploy Logs</a></p>

**Pull request merged**
