### PR TITLE
fix(ProLabel): add title

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Adds a `title` tag to the `ProLabel` svg to fix an a11y bug on the catalog pages. The title is "Pro only" which matches what is currently read on the pro label for curriculum cards.

To test:
1. visit https://portal-app-pr-158.dev-eks.codecademy.com/catalog
2. open voice over and navigate via tab onto a career path card
3. confirm that it reads "pro only career path <path name> <difficulty level> <x lessons> ...."
4. navigate to a not pro course
5. confirm that it does not read "pro only"

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-1076](https://codecademy.atlassian.net/browse/REACH-1076)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.40-alpha.50e91f.0<br/>@codecademy/gamut-labs@19.10.6-alpha.50e91f.0<br/>@codecademy/styleguide@41.10.10-alpha.50e91f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0e923bc28c98c540ff9e9--gamut-preview.netlify.app>https://60d0e923bc28c98c540ff9e9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0e923bc28c98c540ff9e9>Deploy Logs</a></p>

**Comment by aresnik11** [comment]
hold on reviewing, this is not the correct way of solving this problem

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.40-alpha.71060c.0<br/>@codecademy/gamut-labs@19.10.6-alpha.71060c.0<br/>@codecademy/gamut@34.10.4-alpha.71060c.0<br/>@codecademy/styleguide@41.10.10-alpha.71060c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0f87f341eb600cb611454--gamut-preview.netlify.app>https://60d0f87f341eb600cb611454--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0f87f341eb600cb611454>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
Thank you <3

**Review by christian-dinh — APPROVED** [review]
pro only putter grips

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.41-alpha.b09b67.0<br/>@codecademy/gamut-labs@19.10.7-alpha.b09b67.0<br/>@codecademy/gamut@34.10.5-alpha.b09b67.0<br/>@codecademy/styleguide@41.10.11-alpha.b09b67.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d101a0da44c97bce9c02ce--gamut-preview.netlify.app>https://60d101a0da44c97bce9c02ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d101a0da44c97bce9c02ce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.42-alpha.b2cf21.0<br/>@codecademy/gamut-labs@19.10.8-alpha.b2cf21.0<br/>@codecademy/gamut@34.10.6-alpha.b2cf21.0<br/>@codecademy/styleguide@41.10.12-alpha.b2cf21.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d113cafef65653bbe11ac2--gamut-preview.netlify.app>https://60d113cafef65653bbe11ac2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d113cafef65653bbe11ac2>Deploy Logs</a></p>

**Pull request merged**
