### PR TITLE
feat: enable non-nullable-type-assertion-style

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Enables  [`non-nullable-type-assertion-style`](https://github.com/typescript-eslint/typescript-eslint/blob/v4.22.1/packages/eslint-plugin/docs/rules/non-nullable-type-assertion-style.md) in our ESLint preset, because it wasn't by default.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-2
- [x] I have run this code to verify it works
- ~[ ] This PR includes unit tests for the code change~

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.3.0-alpha.1354d1.0<br/>@codecademy/gamut-kit@0.4.45-alpha.1354d1.0<br/>@codecademy/gamut-labs@19.11.1-alpha.1354d1.0<br/>@codecademy/gamut@34.11.0-alpha.1354d1.0<br/>@codecademy/styleguide@41.10.15-alpha.1354d1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d3bdfd49f59e44f3c84ae8--gamut-preview.netlify.app>https://60d3bdfd49f59e44f3c84ae8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d3bdfd49f59e44f3c84ae8>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]
🙌

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.3.0-alpha.072947.0<br/>@codecademy/gamut-kit@0.4.52-alpha.072947.0<br/>@codecademy/gamut-labs@19.12.2-alpha.072947.0<br/>@codecademy/gamut@34.12.0-alpha.072947.0<br/>@codecademy/styleguide@41.10.22-alpha.072947.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9d574678fe048e5e7b7ee--gamut-preview.netlify.app>https://60d9d574678fe048e5e7b7ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9d574678fe048e5e7b7ee>Deploy Logs</a></p>

**Pull request merged**
