### PR TITLE
refactor!: update landing page exports

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Updates landing page to not export atoms only used within the larger components. This is a breaking change for any place importing `Title`, `Description`, `CTA`, or `Feature` from gamut-labs, which should only be in a couple of places in static sites.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-831](https://codecademy.atlassian.net/browse/REACH-831)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

static sites PR: https://github.com/codecademy-engineering/static-sites/pull/753

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.ce872d.0<br/>@codecademy/gamut-labs@14.4.1-alpha.ce872d.0<br/>@codecademy/styleguide@36.4.1-alpha.ce872d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60873bfc59de2000a69ffee5--gamut-preview.netlify.app>https://60873bfc59de2000a69ffee5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60873bfc59de2000a69ffee5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.55-alpha.f29484.0<br/>@codecademy/gamut-labs@14.5.1-alpha.f29484.0<br/>@codecademy/styleguide@36.5.3-alpha.f29484.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608871b01e704900b1f0deed--gamut-preview.netlify.app>https://608871b01e704900b1f0deed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608871b01e704900b1f0deed>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
okie dokie

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.470a18.0<br/>@codecademy/gamut-labs@14.5.2-alpha.470a18.0<br/>@codecademy/styleguide@36.5.4-alpha.470a18.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088a762a87f1e178dff0f5c--gamut-preview.netlify.app>https://6088a762a87f1e178dff0f5c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088a762a87f1e178dff0f5c>Deploy Logs</a></p>

**Review by christian-dinh — APPROVED** [review]
🔪

**Pull request merged**
