### PR TITLE
fix(LayoutGrid): Add ordered fallback

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Fixes a bug on chrome < 77 where the max column gap size calculation for layoutgrid would fail.  This adds a fall back less specific property for `grid-column-gap` which will have a standard value.  If there main value is present it will take precedence.

### Fix 
Screen Shot 2021-05-04 at 11 59 16 AM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
> chrome < 77

sad

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.74-alpha.fb5ed2.0<br/>@codecademy/gamut-labs@15.3.3-alpha.fb5ed2.0<br/>@codecademy/gamut@32.9.2-alpha.fb5ed2.0<br/>@codecademy/styleguide@36.12.4-alpha.fb5ed2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609172b443d3973ad253537e--gamut-preview.netlify.app>https://609172b443d3973ad253537e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609172b443d3973ad253537e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.75-alpha.8d1476.0<br/>@codecademy/gamut-labs@15.4.1-alpha.8d1476.0<br/>@codecademy/gamut@32.10.1-alpha.8d1476.0<br/>@codecademy/styleguide@36.13.1-alpha.8d1476.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609189921b5b1b0dfa7a84a2--gamut-preview.netlify.app>https://609189921b5b1b0dfa7a84a2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609189921b5b1b0dfa7a84a2>Deploy Logs</a></p>

**Pull request merged**
