### PR TITLE
feat(Icons): Added svg icons

### PR DESCRIPTION
**Pull request by j10sanders**
### PR Checklist

- [x] Related to Abstract designs: https://www.figma.com/file/Jz99UUx89a8rpKbSXkaRW7/Codecademy-styleguide-for-SheerID
- [x] Related to JIRA ticket: GROW-1805
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
Just added 4 svg icons that were given to me by Tamar - for the BTS checkout flow.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.2.1-alpha.67a523.0<br/>@codecademy/gamut-labs@2.0.6-alpha.67a523.0<br/>@codecademy/gamut@14.0.6-alpha.67a523.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f458e9676e20896f3c0676a--gamut-preview.netlify.app>https://5f458e9676e20896f3c0676a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f458e9676e20896f3c0676a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.2.1-alpha.ea537f.0<br/>@codecademy/gamut-labs@2.0.6-alpha.ea537f.0<br/>@codecademy/gamut@14.0.6-alpha.ea537f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f4682b5dfe94237e2d4d95d--gamut-preview.netlify.app>https://5f4682b5dfe94237e2d4d95d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f4682b5dfe94237e2d4d95d>Deploy Logs</a></p>

**Comment by j10sanders** [comment]
@Codecademy/web-platform hey can I get a review on this?  Looking to get this merged asap for the BTS campaign - thanks!

**Comment by JoshuaKGoldberg** [comment]
cc @codecaaron , this looks right per the docs but I forget exactly how we need to add things for React to pick them up...

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.2.1-alpha.435476.0<br/>@codecademy/gamut-labs@2.0.7-alpha.435476.0<br/>@codecademy/gamut@15.0.1-alpha.435476.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f47f9fe7e1277dfa8595a71--gamut-preview.netlify.app>https://5f47f9fe7e1277dfa8595a71--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f47f9fe7e1277dfa8595a71>Deploy Logs</a></p>

**Pull request merged**
