### PR TITLE
chore: Remove storyshots for some CI Savings GM-377

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* These aren't really testing anything other than being frustrating (no hooks / html tags) doesn't even catch errors.
* Save a minute on JEST CI run.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-377
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@46.0.1-alpha.d7d750.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614a52c32caf552f2f1abcb6--gamut-preview.netlify.app>https://614a52c32caf552f2f1abcb6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614a52c32caf552f2f1abcb6>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
yes plz

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://615209eea5d486d11efa4006--gamut-preview.netlify.app>https://615209eea5d486d11efa4006--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/615209eea5d486d11efa4006>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
good riddance

**Pull request merged**
