### PR TITLE
feat(PageWrapper): Extend stacking context reset element for pages with a background color

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Use Pagewrapper with a restricted background for GlobalPage that extends AppWrapper.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Hah thanks...

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.7f7ca1.0<br/>@codecademy/gamut-labs@15.4.2-alpha.7f7ca1.0<br/>@codecademy/gamut@32.10.2-alpha.7f7ca1.0<br/>@codecademy/styleguide@36.13.2-alpha.7f7ca1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091c0eee43b730db1e129ce--gamut-preview.netlify.app>https://6091c0eee43b730db1e129ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091c0eee43b730db1e129ce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091cd79276a3c11ca3a2674--gamut-preview.netlify.app>https://6091cd79276a3c11ca3a2674--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091cd79276a3c11ca3a2674>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.4-alpha.877e29.0<br/>@codecademy/gamut-kit@0.3.76-alpha.877e29.0<br/>@codecademy/gamut-labs@15.4.2-alpha.877e29.0<br/>@codecademy/gamut-styles@9.7.5-alpha.877e29.0<br/>@codecademy/gamut-tests@2.3.27-alpha.877e29.0<br/>@codecademy/gamut@32.10.2-alpha.877e29.0<br/>@codecademy/konamimojisplosion@0.2.27-alpha.877e29.0<br/>@codecademy/markdown-overrides@0.5.39-alpha.877e29.0<br/>@codecademy/styleguide@36.13.2-alpha.877e29.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.4-alpha.8be1dc.0<br/>@codecademy/gamut-kit@0.3.76-alpha.8be1dc.0<br/>@codecademy/gamut-labs@15.4.2-alpha.8be1dc.0<br/>@codecademy/gamut-styles@9.7.5-alpha.8be1dc.0<br/>@codecademy/gamut-tests@2.3.27-alpha.8be1dc.0<br/>@codecademy/gamut@32.10.2-alpha.8be1dc.0<br/>@codecademy/konamimojisplosion@0.2.27-alpha.8be1dc.0<br/>@codecademy/markdown-overrides@0.5.39-alpha.8be1dc.0<br/>@codecademy/styleguide@36.13.2-alpha.8be1dc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091d60528154d265ab26a41--gamut-preview.netlify.app>https://6091d60528154d265ab26a41--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091d60528154d265ab26a41>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.4-alpha.a102f4.0<br/>@codecademy/gamut-kit@0.3.76-alpha.a102f4.0<br/>@codecademy/gamut-labs@15.4.2-alpha.a102f4.0<br/>@codecademy/gamut-styles@9.7.5-alpha.a102f4.0<br/>@codecademy/gamut-tests@2.3.27-alpha.a102f4.0<br/>@codecademy/gamut@32.10.2-alpha.a102f4.0<br/>@codecademy/konamimojisplosion@0.2.27-alpha.a102f4.0<br/>@codecademy/markdown-overrides@0.5.39-alpha.a102f4.0<br/>@codecademy/styleguide@36.13.2-alpha.a102f4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091e9d830468a00a683c939--gamut-preview.netlify.app>https://6091e9d830468a00a683c939--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091e9d830468a00a683c939>Deploy Logs</a></p>

**Pull request merged**
