### PR TITLE
fix: used 'sanitize-markdown' fork of 'insane'

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Uses `sanitize-markdown` fork of `insane` that fixes a [crash bug](https://github.com/bevacqua/insane/issues/16) and improves on package naming inclusivity.

See https://github.com/JoshuaKGoldberg/sanitize-markdown, which includes https://github.com/bevacqua/insane/pull/20.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1273
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601d436083c314d9d21bdc5b--gamut-preview.netlify.app>https://601d436083c314d9d21bdc5b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601d436083c314d9d21bdc5b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.27-alpha.6cae81.0<br/>@codecademy/gamut-labs@9.1.1-alpha.6cae81.0<br/>@codecademy/gamut@21.2.4-alpha.6cae81.0<br/>@codecademy/styleguide@25.1.1-alpha.6cae81.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.27-alpha.cf6a49.0<br/>@codecademy/gamut-labs@9.1.1-alpha.cf6a49.0<br/>@codecademy/gamut@21.2.4-alpha.cf6a49.0<br/>@codecademy/styleguide@25.1.1-alpha.cf6a49.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601d48823c2ab5193d7e68ce--gamut-preview.netlify.app>https://601d48823c2ab5193d7e68ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601d48823c2ab5193d7e68ce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.27-alpha.e07b59.0<br/>@codecademy/gamut-labs@9.1.1-alpha.e07b59.0<br/>@codecademy/gamut@21.2.4-alpha.e07b59.0<br/>@codecademy/styleguide@25.1.1-alpha.e07b59.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601d4bab095b32eaba9e3a35--gamut-preview.netlify.app>https://601d4bab095b32eaba9e3a35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601d4bab095b32eaba9e3a35>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.34-alpha.29f229.0<br/>@codecademy/gamut-labs@9.3.2-alpha.29f229.0<br/>@codecademy/gamut@21.3.7-alpha.29f229.0<br/>@codecademy/styleguide@25.2.2-alpha.29f229.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60254819d4e48a3045c56adc--gamut-preview.netlify.app>https://60254819d4e48a3045c56adc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60254819d4e48a3045c56adc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.39-alpha.ddb4d1.0<br/>@codecademy/gamut-labs@10.0.5-alpha.ddb4d1.0<br/>@codecademy/gamut@22.0.3-alpha.ddb4d1.0<br/>@codecademy/styleguide@26.1.1-alpha.ddb4d1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602c0e4fe59284698ca816e9--gamut-preview.netlify.app>https://602c0e4fe59284698ca816e9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602c0e4fe59284698ca816e9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.39-alpha.c334d1.0<br/>@codecademy/gamut-labs@10.0.5-alpha.c334d1.0<br/>@codecademy/gamut@22.0.3-alpha.c334d1.0<br/>@codecademy/styleguide@26.1.1-alpha.c334d1.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.39-alpha.57d6fd.0<br/>@codecademy/gamut-labs@10.0.5-alpha.57d6fd.0<br/>@codecademy/gamut@22.0.3-alpha.57d6fd.0<br/>@codecademy/styleguide@26.1.2-alpha.57d6fd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602c10d46bcc776ecf9fa0ea--gamut-preview.netlify.app>https://602c10d46bcc776ecf9fa0ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602c10d46bcc776ecf9fa0ea>Deploy Logs</a></p>

**Pull request merged**
