### PR TITLE
Added Interstitial template

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
This'll be moved to the `gamut-templates` package once #571 is in. For now, this is intended as the new learning environment (LE) interstitial we'll move towards.

A couple of notes:
* Buttons don't have a super wide width anymore. Hooray!
* This hasn't passed desk check nitty gritty review with a designer (Sarah); that'll be in a followup PR after I've used this in the LE

https://app.goabstract.com/projects/197ebfd6-43b6-4aa8-9ab1-d290693d3b38/branches/a39a1c7c-1e2a-4010-9ba0-1e48c253ddfa/collections/93d2abac-d1f8-4fcb-b205-8a773bf251e7?collectionLayerId=364f9f42-a644-41c7-92d3-e6052ca7c307&mode=build&selected=2557029161-5B781B2B-2E4A-4CBE-984C-31664908EEA0

Screenshot of the interstitial with a lot of body text

Screenshot of the interstitial with a pre-title decoration

### CODE REVIEW

**Comment by jakemhiller** [comment]
The naming `LearningInterstitial` implies where it's used on the main site, what if we just called this `Interstitial`? Historically this is the only thing we ever really called an interstitial, it's just branched into other forms more recently, this is definitely the main "interstitial" format.

**Comment by hmafzal** [comment]
I don't know if it's intentional or not for some buttons to have wide width - eg for the pro upsell one, that might actually be intentional to give it more focus?

**Comment by JoshuaKGoldberg** [comment]
@hmafzal yes it's intentional - design has been irked for a while about how the button widths are nonstandard 😄

**Comment by JoshuaKGoldberg** [comment]
@jakemhiller talked with Sarah. All aboard `Interstitial`!

**Pull request merged**
