### PR TITLE
feat(Landing Page Components): Allow passing callback for link clicks inside Markdown

### PR DESCRIPTION
**Pull request by rogervera**
### Overview

Adds `onAnchorClick` to the `BaseProps` and for the `Feature` component to allow passing an `onAnchorClick` callback for descriptions rendered with Markdown.

### PR Checklist
- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-453](https://codecademy.atlassian.net/browse/REACH-453)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Testing
1. https://5fd7bb7be9996200bdccaefe--gamut-preview.netlify.app/storybook/?path=/docs/labs-landingpage-organisms-pagehero--with-cta
2. Open Console
3. Click on `Rob Thomas of Matchbox Twenty `
4. See message output

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.4.5-alpha.8185fb.0<br/>@codecademy/styleguide@21.4.4-alpha.8185fb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd7bb7be9996200bdccaefe--gamut-preview.netlify.app>https://5fd7bb7be9996200bdccaefe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd7bb7be9996200bdccaefe>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM. You might consider adding a unit test or two?

**Review by JoshuaKGoldberg — APPROVED** [review]
❤️

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd7ec8ef282da11efbdc701--gamut-preview.netlify.app>https://5fd7ec8ef282da11efbdc701--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd7ec8ef282da11efbdc701>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.4.5-alpha.2a70e6.0<br/>@codecademy/styleguide@21.4.4-alpha.2a70e6.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.4.5-alpha.2912c3.0<br/>@codecademy/styleguide@21.4.4-alpha.2912c3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd7f28433bc93015cb6772d--gamut-preview.netlify.app>https://5fd7f28433bc93015cb6772d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd7f28433bc93015cb6772d>Deploy Logs</a></p>

**Pull request merged**
