### PR TITLE
docs: standardized LP storybook pages

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Standardized storybook pages styling across all landing page components

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@24.0.3-alpha.3ba623.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60198f3e6fde521a781ed83d--gamut-preview.netlify.app>https://60198f3e6fde521a781ed83d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60198f3e6fde521a781ed83d>Deploy Logs</a></p>

**Review by christian-dinh — APPROVED** [review]
💯

**Review by dreamwasp — APPROVED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@24.2.2-alpha.78159f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019d6594239f10c0fd65e25--gamut-preview.netlify.app>https://6019d6594239f10c0fd65e25--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019d6594239f10c0fd65e25>Deploy Logs</a></p>

**Pull request merged**
