### PR TITLE
fix(GlobalPage): extending bg color to whole page height

### PR DESCRIPTION
**Pull request by jcenglish**
### Overview

Extends the background color to the whole page.

Before:
Screen Shot 2021-06-07 at 9 27 21 AM

After:
Screen Shot 2021-06-07 at 9 28 11 AM

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: EGG-1244
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.9-alpha.868d33.0<br/>@codecademy/gamut-labs@19.0.2-alpha.868d33.0<br/>@codecademy/styleguide@41.1.2-alpha.868d33.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60be1fe4c609846f2c8497db--gamut-preview.netlify.app>https://60be1fe4c609846f2c8497db--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60be1fe4c609846f2c8497db>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.10-alpha.449336.0<br/>@codecademy/gamut-labs@19.0.3-alpha.449336.0<br/>@codecademy/styleguide@41.2.1-alpha.449336.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60be31e24d9b8c10e064d706--gamut-preview.netlify.app>https://60be31e24d9b8c10e064d706--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60be31e24d9b8c10e064d706>Deploy Logs</a></p>

**Pull request merged**
