### PR TITLE
feat!: deprecate Button and ButtonBase

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### PR Checklist

- [x] Related to designs: https://www.figma.com/file/N6TfoPI5OA7GanX6Zl8nWj/Buttons-%E2%9C%85?node-id=268%3A16
- [x] Related to JIRA ticket: [GM-121](https://codecademy.atlassian.net/browse/GM-121)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

In preparation for #1070, marks the old buttons as deprecated in Storybook.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.6-alpha.00b0e3.0<br/>@codecademy/gamut@17.0.0-alpha.00b0e3.0<br/>@codecademy/styleguide@18.0.0-alpha.00b0e3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f90649d41b8820ca4c9abe3--gamut-preview.netlify.app>https://5f90649d41b8820ca4c9abe3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f90649d41b8820ca4c9abe3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.6-alpha.723c3c.0<br/>@codecademy/gamut@17.0.0-alpha.723c3c.0<br/>@codecademy/styleguide@18.0.0-alpha.723c3c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f90738f9e6195014b6580c0--gamut-preview.netlify.app>https://5f90738f9e6195014b6580c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f90738f9e6195014b6580c0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.6-alpha.13fe5f.0<br/>@codecademy/gamut@17.0.0-alpha.13fe5f.0<br/>@codecademy/styleguide@18.0.0-alpha.13fe5f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f96ed80caf4132fa50c5329--gamut-preview.netlify.app>https://5f96ed80caf4132fa50c5329--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f96ed80caf4132fa50c5329>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.6.3-alpha.04bc70.0<br/>@codecademy/gamut@17.0.0-alpha.04bc70.0<br/>@codecademy/styleguide@18.0.0-alpha.04bc70.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f99ed1b4b7d4714219b6b13--gamut-preview.netlify.app>https://5f99ed1b4b7d4714219b6b13--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f99ed1b4b7d4714219b6b13>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa0175ce50d1a349dd9ae3f--gamut-preview.netlify.app>https://5fa0175ce50d1a349dd9ae3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa0175ce50d1a349dd9ae3f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa01dea358dde3db2bfc0c4--gamut-preview.netlify.app>https://5fa01dea358dde3db2bfc0c4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa01dea358dde3db2bfc0c4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.1-alpha.a05f8f.0<br/>@codecademy/gamut@17.0.0-alpha.a05f8f.0<br/>@codecademy/styleguide@18.0.0-alpha.a05f8f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa0c602ebf56440a2cfff02--gamut-preview.netlify.app>https://5fa0c602ebf56440a2cfff02--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa0c602ebf56440a2cfff02>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.3-alpha.111988.0<br/>@codecademy/gamut@17.0.0-alpha.111988.0<br/>@codecademy/styleguide@18.0.0-alpha.111988.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa40a11fb2653b15a79255b--gamut-preview.netlify.app>https://5fa40a11fb2653b15a79255b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa40a11fb2653b15a79255b>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.8.1-alpha.21f737.0<br/>@codecademy/gamut@17.0.0-alpha.21f737.0<br/>@codecademy/styleguide@18.0.0-alpha.21f737.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa484a1cbada300b4d46440--gamut-preview.netlify.app>https://5fa484a1cbada300b4d46440--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa484a1cbada300b4d46440>Deploy Logs</a></p>

**Pull request merged**
