### PR TITLE
feat(webpack-config): upgrade node-sass to 8.0.0

### PR DESCRIPTION
**Pull request by jrood**
### Overview

This is one piece in resolving a long chain of blockers. I'm ultimately looking to resolve an a11y bug with our Gamut popover component. This raised a need to upgrade react-focus-on, which is tricky to do since our current version of node-sass relies an old version of node-gyp. Upgrading node-sass allows us to resolve a newer node-gyp which eases other package upgrades.

gamut PR link: https://github.com/Codecademy/gamut/pull/2700
styleguide: https://6410b96a147dc60a4f9ac66a--gamut-preview.netlify.app/

Changes in yarn.lock are split into 2 commits. The first includes updates from running yarn without any changes. The second includes updates after the node-sass upgrade.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@0.6.4-alpha.df59b9.0<br/>@codecademy/webpack-config@6.2.1-alpha.df59b9.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
in some other cases i think we've switched to `sass` which is the dart version to fix similar issues, but it's better to fix it in this package directly. You might be able to replace this with `sass` if you want to give it a try, i don't think that's a blocker to merge this though.

**Comment by jrood** [comment]
@jakemhiller ah good call! I've seen some deprecation warnings for `Using / for division outside of calc()` in Gamut, and I suspect we may need to fix those before switching to dart sass. I'll merge this to unblock the a11y fix, and then create a followup PR for switching to dart sass.

**Comment by jakemhiller** [comment]
@jrood yeah, those warnings are coming from dart sass, so we can upgrade without fixing them immediately, but we probably should shortly after at least.

**Pull request merged**
