### PR TITLE
docs: Relinked and cleaned up Figma Links

### PR DESCRIPTION
**Pull request by songstephen**
### Overview

Updated the Figma links to link directly to the components instead of the Gamut cover page

### PR Checklist

- [ ] Related to designs:
- [X] Related to JIRA ticket: ABC-123
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by airrobb — APPROVED** [review]

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@43.10.10-alpha.26eda2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://612f91deae501f1147b63bfd--gamut-preview.netlify.app>https://612f91deae501f1147b63bfd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/612f91deae501f1147b63bfd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.2.4-alpha.6608b5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b59b28ffb92d11d64976b--gamut-preview.netlify.app>https://613b59b28ffb92d11d64976b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b59b28ffb92d11d64976b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.6.6-alpha.e1a87e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61449a2dd8369e93f7982def--gamut-preview.netlify.app>https://61449a2dd8369e93f7982def--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61449a2dd8369e93f7982def>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.6.7-alpha.0149fc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148ccd9362bc600e59ef613--gamut-preview.netlify.app>https://6148ccd9362bc600e59ef613--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148ccd9362bc600e59ef613>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.84-alpha.e178ff.0<br/>@codecademy/gamut-labs@20.1.1-alpha.e178ff.0<br/>@codecademy/gamut@37.6.0-alpha.e178ff.0<br/>@codecademy/monaco@0.4.8-alpha.e178ff.0<br/>@codecademy/styleguide@44.7.0-alpha.e178ff.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148ce68c359da00ea74b6d1--gamut-preview.netlify.app>https://6148ce68c359da00ea74b6d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148ce68c359da00ea74b6d1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.7.1-alpha.a667bd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148da14922ff50aee9b98c9--gamut-preview.netlify.app>https://6148da14922ff50aee9b98c9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148da14922ff50aee9b98c9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.11.0-alpha.d563ab.0<br/>@codecademy/gamut-kit@0.5.85-alpha.d563ab.0<br/>@codecademy/gamut-labs@20.1.2-alpha.d563ab.0<br/>@codecademy/gamut@37.6.1-alpha.d563ab.0<br/>@codecademy/monaco@0.4.9-alpha.d563ab.0<br/>@codecademy/styleguide@44.7.1-alpha.d563ab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148edee227ea7296c66acb3--gamut-preview.netlify.app>https://6148edee227ea7296c66acb3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148edee227ea7296c66acb3>Deploy Logs</a></p>

**Pull request merged**
