### PR TITLE
fix: SkipToContent z :( 

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview
Screen Shot 2021-05-28 at 2 10 32 PM

* Go above header.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by dreamwasp — APPROVED** [review]
ouch

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.1-alpha.71bc5a.0<br/>@codecademy/gamut-labs@18.3.1-alpha.71bc5a.0<br/>@codecademy/gamut@33.2.1-alpha.71bc5a.0<br/>@codecademy/styleguide@40.1.1-alpha.71bc5a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b1369b351fbb49960e2019--gamut-preview.netlify.app>https://60b1369b351fbb49960e2019--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b1369b351fbb49960e2019>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.1-alpha.2e2caa.0<br/>@codecademy/gamut-labs@18.3.1-alpha.2e2caa.0<br/>@codecademy/gamut@33.2.1-alpha.2e2caa.0<br/>@codecademy/styleguide@40.1.1-alpha.2e2caa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b1392e8186080b5043d77d--gamut-preview.netlify.app>https://60b1392e8186080b5043d77d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b1392e8186080b5043d77d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.3-alpha.97f2c8.0<br/>@codecademy/gamut-labs@18.3.3-alpha.97f2c8.0<br/>@codecademy/gamut@33.4.1-alpha.97f2c8.0<br/>@codecademy/styleguide@40.3.1-alpha.97f2c8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b13d6252593b0a0a1b98de--gamut-preview.netlify.app>https://60b13d6252593b0a0a1b98de--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b13d6252593b0a0a1b98de>Deploy Logs</a></p>

**Pull request merged**
