### PR TITLE
feat: Add 2.5rem interval to spacing GM-317

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Adds 2..5rem / 40 to our spacing intervals.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-317
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.2-alpha.c828dc.0<br/>@codecademy/gamut-illustrations@0.17.16-alpha.c828dc.0<br/>@codecademy/gamut-kit@0.5.24-alpha.c828dc.0<br/>@codecademy/gamut-labs@19.19.10-alpha.c828dc.0<br/>@codecademy/gamut-patterns@0.5.4-alpha.c828dc.0<br/>@codecademy/gamut-styles@11.7.2-alpha.c828dc.0<br/>@codecademy/gamut-tests@2.4.19-alpha.c828dc.0<br/>@codecademy/gamut@36.0.2-alpha.c828dc.0<br/>@codecademy/konamimojisplosion@0.2.50-alpha.c828dc.0<br/>@codecademy/markdown-overrides@0.5.62-alpha.c828dc.0<br/>@codecademy/styleguide@43.0.2-alpha.c828dc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6113fc655adbdb1eb0f1069f--gamut-preview.netlify.app>https://6113fc655adbdb1eb0f1069f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6113fc655adbdb1eb0f1069f>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.2-alpha.71b909.0<br/>@codecademy/gamut-illustrations@0.17.16-alpha.71b909.0<br/>@codecademy/gamut-kit@0.5.25-alpha.71b909.0<br/>@codecademy/gamut-labs@19.19.11-alpha.71b909.0<br/>@codecademy/gamut-patterns@0.5.4-alpha.71b909.0<br/>@codecademy/gamut-styles@11.7.2-alpha.71b909.0<br/>@codecademy/gamut-tests@2.4.19-alpha.71b909.0<br/>@codecademy/gamut@36.1.1-alpha.71b909.0<br/>@codecademy/konamimojisplosion@0.2.50-alpha.71b909.0<br/>@codecademy/markdown-overrides@0.5.62-alpha.71b909.0<br/>@codecademy/styleguide@43.1.1-alpha.71b909.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6115482e0f503ff2b104b378--gamut-preview.netlify.app>https://6115482e0f503ff2b104b378--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6115482e0f503ff2b104b378>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.3-alpha.afeb63.0<br/>@codecademy/gamut-illustrations@0.17.17-alpha.afeb63.0<br/>@codecademy/gamut-kit@0.5.27-alpha.afeb63.0<br/>@codecademy/gamut-labs@19.20.2-alpha.afeb63.0<br/>@codecademy/gamut-patterns@0.5.5-alpha.afeb63.0<br/>@codecademy/gamut-styles@11.7.3-alpha.afeb63.0<br/>@codecademy/gamut-tests@2.4.20-alpha.afeb63.0<br/>@codecademy/gamut@36.1.2-alpha.afeb63.0<br/>@codecademy/konamimojisplosion@0.2.51-alpha.afeb63.0<br/>@codecademy/markdown-overrides@0.5.63-alpha.afeb63.0<br/>@codecademy/styleguide@43.2.2-alpha.afeb63.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6115ae68bd72c9518838d5f7--gamut-preview.netlify.app>https://6115ae68bd72c9518838d5f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6115ae68bd72c9518838d5f7>Deploy Logs</a></p>

**Pull request merged**
