### PR TITLE
fix(Toggle): remove aria-label

### PR DESCRIPTION
**Pull request by slin12**
### Overview
This came out of this ticket: https://codecademy.atlassian.net/browse/LX-4875
It can also be replicated in storybook by adding a label and using the screenreader to focus it. It only says 'Unchecked, checkbox'. 

Check the new storybook to see it with aria-label removed. The screenreader now reads the correct label. I believe the `aria-label` is not necessary (though I didn't realize it would actually cause bad behavior) since we already have a semantic label element.

Removes aria-label on the Toggle component as it was causing screenreaders to actually not associate the label with the toggle.

### PR Checklist

- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/LX-4875
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.33-alpha.634e20.0<br/>@codecademy/gamut-labs@9.2.12-alpha.634e20.0<br/>@codecademy/gamut@21.3.6-alpha.634e20.0<br/>@codecademy/styleguide@25.1.13-alpha.634e20.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602441d7232053483624f6e0--gamut-preview.netlify.app>https://602441d7232053483624f6e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602441d7232053483624f6e0>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
this is supremely weird behavior... would love to see this package/change in another monolith PR environment to see how it fixes this specific issue + how it affects the other places where Toggle is used

**Review by codecaaron — APPROVED** [review]

**Comment by slin12** [comment]
@dreamwasp yeah the behavior is super strange and i honestly do not know why it's happening. this is a pr env with the alpha packages: https://pr-22050.dev-eks.codecademy.com/paths/front-end-engineer-career-path/tracks/fecp-web-development-fundamentals/modules/fecp-learn-css-colors/lessons/color/exercises/foreground-vs-background (turn on `le_ui_upgrades_2020` feature flag if tools menu isn't showing). compare that with the staging version, where the screenreader actually reads the next label associated with the toggle which is SO WEIRD, and the last toggle doesn't get a label at all.

**Review by dreamwasp — APPROVED** [review]
lgtm! weird that it was happening but stoked that it's solved

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.34-alpha.f40b7b.0<br/>@codecademy/gamut-labs@9.3.4-alpha.f40b7b.0<br/>@codecademy/gamut@21.3.7-alpha.f40b7b.0<br/>@codecademy/styleguide@25.2.4-alpha.f40b7b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602586ef9c2b300a9777ddf4--gamut-preview.netlify.app>https://602586ef9c2b300a9777ddf4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602586ef9c2b300a9777ddf4>Deploy Logs</a></p>

**Pull request merged**
