### PR TITLE
fix(Checkbox): safari and ff labelling

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Fixes an issue where Checkboxes weren't being properly labelled on Safari + Firefox. Please check out the [Checkbox](https://612ff33f7b1bb40b3b04f8fb--gamut-preview.netlify.app/storybook/) story and the [Portal App PR](https://github.com/codecademy-engineering/portal-app/pull/542) to test the behavior. 

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: gm-241
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.54-alpha.683537.0<br/>@codecademy/gamut-labs@19.23.17-alpha.683537.0<br/>@codecademy/gamut@36.8.5-alpha.683537.0<br/>@codecademy/monaco@0.3.8-alpha.683537.0<br/>@codecademy/styleguide@43.10.11-alpha.683537.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://612ff33f7b1bb40b3b04f8fb--gamut-preview.netlify.app>https://612ff33f7b1bb40b3b04f8fb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/612ff33f7b1bb40b3b04f8fb>Deploy Logs</a></p>

**Review by vonbarown — APPROVED** [review]
🆔

**Review by JoshuaKGoldberg — APPROVED** [review]
🔥 

You could unit test this?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.55-alpha.3c0804.0<br/>@codecademy/gamut-labs@19.23.18-alpha.3c0804.0<br/>@codecademy/gamut@36.9.1-alpha.3c0804.0<br/>@codecademy/monaco@0.3.9-alpha.3c0804.0<br/>@codecademy/styleguide@43.11.1-alpha.3c0804.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6130d99050bf21ebe4d7c4d1--gamut-preview.netlify.app>https://6130d99050bf21ebe4d7c4d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6130d99050bf21ebe4d7c4d1>Deploy Logs</a></p>

**Pull request merged**
