### PR TITLE
feat(props): Support `color` and other HTML attributes as system props without type collision GM-247

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Type collisions caused by valid JSX attribute names like `color`, `width` and `height` caused certain props to be unusable for specific elements.   For elements that accept these props like `img` and `svg` system props would result in an intersection conflict between the default intrinsic element prop types.
```tsx
const Svg = styled('svg', system.color);

<Svg color={['primary', 'secondary']} /> // Type Error as color is `Scale<{ prop: 'color', scale: 'colors' }> & string`
```

The way around this is to ensure that the `shouldForwardProp` configuration is an appropriate type guard for the element https://emotion.sh/docs/typescript#forwarding-props

To make sure that these props are usable (instead of working around it with `textColor`) we can update our `styledOptions` object to be an actual type guard function returning the keys of non system props to the actual element and allowing emotion to correctly derive the type.

```tsx
// Doesn't Work - returned types are not limited to `div` attributes
const Box = styled('div', { 
  shouldForwardProp: (prop): prop is Exclude<keyof JSX.IntrinsicElements[keyof JSX.IntrinsicElements], ExcludedProps> 
})

// Works - Returned types extend 'div' attributes
const Box = styled('div', { 
  shouldForwardProp: (prop): prop is Exclude<keyof JSX.IntrinsicElements['div'], ExcludedProps> 
})
```

The type guard will not be inferred correctly if the element props specified to do not match the ones provided by `styledOptions`.  So for cases like `svg` we can call the function with a generic argument to appropriately configure the guard.  `styledOptions<'svg'>()`.  Ostensibly we could adopt a similar structure to `styled.div` for this behavior in the future as this pattern is annoying.

Example cases:
```tsx
 import { styledOptions } from '@codecademy/gamut-styles';
// default case for divs
 styled('div', styledOptions)();
// elements other than div
styled('svg', styledOptions<'svg'>())();
// additional non system props to filter
styled('div', styledOptions(['data-invalidsomething']))();
// Extending existing components
styled(Box)()
```

### Emotion Changes 
- Rename `styledConfig` to `styledOptions` and update places where it is used.
- Set the default html element of `styledOptions` to most frequent use `div` and provide a way to switch 
- Add some performance optimizations by pre filtering the list of all system props to props that will pass the default `isPropValid` provided by emotion for both base system props and additional props, decreasing the runtime cost of checking.
- Adds `color` along side `textColor` and updates cases where we used the default typings for this prop erroneously.
- Removes tests that are testing system props as certain props are no longer available.

### Icon Changes
- Updates the svgr config to only use currentColor for attr replacement
- Moves away from style attributes that are handled directly by system props (with the exception of size).
- Also refactors the style props / prop forwarding flow / types to be a bit simpler and removes some extra fluff. 

### PR Checklist

- [ ] ~Related to designs:~
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-247
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.023e51.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.023e51.0<br/>@codecademy/gamut-kit@0.4.23-alpha.023e51.0<br/>@codecademy/gamut-labs@19.5.1-alpha.023e51.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.023e51.0<br/>@codecademy/gamut-styles@11.2.1-alpha.023e51.0<br/>@codecademy/gamut-tests@2.4.8-alpha.023e51.0<br/>@codecademy/gamut@34.6.1-alpha.023e51.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.023e51.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.023e51.0<br/>@codecademy/styleguide@41.7.6-alpha.023e51.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.e9035b.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.e9035b.0<br/>@codecademy/gamut-kit@0.4.23-alpha.e9035b.0<br/>@codecademy/gamut-labs@19.5.1-alpha.e9035b.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.e9035b.0<br/>@codecademy/gamut-styles@11.2.1-alpha.e9035b.0<br/>@codecademy/gamut-tests@2.4.8-alpha.e9035b.0<br/>@codecademy/gamut@34.6.1-alpha.e9035b.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.e9035b.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.e9035b.0<br/>@codecademy/styleguide@41.7.6-alpha.e9035b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3e21a5da90027efae3dc7--gamut-preview.netlify.app>https://60c3e21a5da90027efae3dc7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3e21a5da90027efae3dc7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.af3f61.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.af3f61.0<br/>@codecademy/gamut-kit@0.4.23-alpha.af3f61.0<br/>@codecademy/gamut-labs@19.5.1-alpha.af3f61.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.af3f61.0<br/>@codecademy/gamut-styles@11.2.1-alpha.af3f61.0<br/>@codecademy/gamut-tests@2.4.8-alpha.af3f61.0<br/>@codecademy/gamut@34.6.1-alpha.af3f61.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.af3f61.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.af3f61.0<br/>@codecademy/styleguide@41.7.6-alpha.af3f61.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c41f94ebac3b47a921de4b--gamut-preview.netlify.app>https://60c41f94ebac3b47a921de4b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c41f94ebac3b47a921de4b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.ba379a.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.ba379a.0<br/>@codecademy/gamut-kit@0.4.23-alpha.ba379a.0<br/>@codecademy/gamut-labs@19.5.1-alpha.ba379a.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.ba379a.0<br/>@codecademy/gamut-styles@11.2.1-alpha.ba379a.0<br/>@codecademy/gamut-tests@2.4.8-alpha.ba379a.0<br/>@codecademy/gamut@34.6.1-alpha.ba379a.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.ba379a.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.ba379a.0<br/>@codecademy/styleguide@41.7.6-alpha.ba379a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c42532f0a6e9416fb4dbac--gamut-preview.netlify.app>https://60c42532f0a6e9416fb4dbac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c42532f0a6e9416fb4dbac>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.10b1e8.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.10b1e8.0<br/>@codecademy/gamut-kit@0.4.23-alpha.10b1e8.0<br/>@codecademy/gamut-labs@19.5.1-alpha.10b1e8.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.10b1e8.0<br/>@codecademy/gamut-styles@11.2.1-alpha.10b1e8.0<br/>@codecademy/gamut-tests@2.4.8-alpha.10b1e8.0<br/>@codecademy/gamut@34.6.1-alpha.10b1e8.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.10b1e8.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.10b1e8.0<br/>@codecademy/styleguide@41.7.6-alpha.10b1e8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c678255cb35056386c6dfd--gamut-preview.netlify.app>https://60c678255cb35056386c6dfd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c678255cb35056386c6dfd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.e9eb47.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.e9eb47.0<br/>@codecademy/gamut-kit@0.4.23-alpha.e9eb47.0<br/>@codecademy/gamut-labs@19.5.1-alpha.e9eb47.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.e9eb47.0<br/>@codecademy/gamut-styles@11.2.1-alpha.e9eb47.0<br/>@codecademy/gamut-tests@2.4.8-alpha.e9eb47.0<br/>@codecademy/gamut@34.6.1-alpha.e9eb47.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.e9eb47.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.e9eb47.0<br/>@codecademy/styleguide@41.7.6-alpha.e9eb47.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c67eff61cb7cd33d525290--gamut-preview.netlify.app>https://60c67eff61cb7cd33d525290--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c67eff61cb7cd33d525290>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.f0a708.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.f0a708.0<br/>@codecademy/gamut-kit@0.4.23-alpha.f0a708.0<br/>@codecademy/gamut-labs@19.5.1-alpha.f0a708.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.f0a708.0<br/>@codecademy/gamut-styles@11.2.1-alpha.f0a708.0<br/>@codecademy/gamut-tests@2.4.8-alpha.f0a708.0<br/>@codecademy/gamut@34.6.1-alpha.f0a708.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.f0a708.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.f0a708.0<br/>@codecademy/styleguide@41.7.6-alpha.f0a708.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c6865776cd88135564c632--gamut-preview.netlify.app>https://60c6865776cd88135564c632--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c6865776cd88135564c632>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Review by jakemhiller — APPROVED** [review]
nice

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.f4124f.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.f4124f.0<br/>@codecademy/gamut-kit@0.4.25-alpha.f4124f.0<br/>@codecademy/gamut-labs@19.5.3-alpha.f4124f.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.f4124f.0<br/>@codecademy/gamut-styles@11.2.1-alpha.f4124f.0<br/>@codecademy/gamut-tests@2.4.8-alpha.f4124f.0<br/>@codecademy/gamut@34.6.3-alpha.f4124f.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.f4124f.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.f4124f.0<br/>@codecademy/styleguide@41.7.9-alpha.f4124f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8b7e1131e4f00a0459a67--gamut-preview.netlify.app>https://60c8b7e1131e4f00a0459a67--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8b7e1131e4f00a0459a67>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.3-alpha.3040f6.0<br/>@codecademy/gamut-illustrations@0.17.5-alpha.3040f6.0<br/>@codecademy/gamut-kit@0.4.25-alpha.3040f6.0<br/>@codecademy/gamut-labs@19.5.3-alpha.3040f6.0<br/>@codecademy/gamut-patterns@0.3.5-alpha.3040f6.0<br/>@codecademy/gamut-styles@11.2.1-alpha.3040f6.0<br/>@codecademy/gamut-tests@2.4.8-alpha.3040f6.0<br/>@codecademy/gamut@34.6.3-alpha.3040f6.0<br/>@codecademy/konamimojisplosion@0.2.39-alpha.3040f6.0<br/>@codecademy/markdown-overrides@0.5.51-alpha.3040f6.0<br/>@codecademy/styleguide@41.7.10-alpha.3040f6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8d13c4324601d4307b5cd--gamut-preview.netlify.app>https://60c8d13c4324601d4307b5cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8d13c4324601d4307b5cd>Deploy Logs</a></p>

**Pull request merged**
