### PR TITLE
feat: Add admin theme

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Adds admin theme that changes the primary color to `blue-500` from `hyper`
* Adds snapshot for the admin theme.
* Fixes the merge logic for the Theme types within variance allow for 2 levels of nesting explicitly as relying on object intersection fails with key collision.
* Adds tests for the override behavior in `createTheme`

### PR Checklist

- [x] Related to designs: All of Business
- [x] Related to JIRA ticket: GM-286
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.6.1-alpha.4e3274.0<br/>@codecademy/gamut-illustrations@0.17.10-alpha.4e3274.0<br/>@codecademy/gamut-kit@0.4.63-alpha.4e3274.0<br/>@codecademy/gamut-labs@19.16.1-alpha.4e3274.0<br/>@codecademy/gamut-patterns@0.4.5-alpha.4e3274.0<br/>@codecademy/gamut-styles@11.5.2-alpha.4e3274.0<br/>@codecademy/gamut-tests@2.4.13-alpha.4e3274.0<br/>@codecademy/gamut@34.14.2-alpha.4e3274.0<br/>@codecademy/konamimojisplosion@0.2.44-alpha.4e3274.0<br/>@codecademy/markdown-overrides@0.5.56-alpha.4e3274.0<br/>@codecademy/styleguide@41.14.1-alpha.4e3274.0<br/>@codecademy/variance@0.16.1-alpha.4e3274.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f0569a7c198909036bbf04--gamut-preview.netlify.app>https://60f0569a7c198909036bbf04--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f0569a7c198909036bbf04>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.6.1-alpha.8a6ed5.0<br/>@codecademy/gamut-illustrations@0.17.10-alpha.8a6ed5.0<br/>@codecademy/gamut-kit@0.4.63-alpha.8a6ed5.0<br/>@codecademy/gamut-labs@19.16.1-alpha.8a6ed5.0<br/>@codecademy/gamut-patterns@0.4.5-alpha.8a6ed5.0<br/>@codecademy/gamut-styles@11.5.2-alpha.8a6ed5.0<br/>@codecademy/gamut-tests@2.4.13-alpha.8a6ed5.0<br/>@codecademy/gamut@34.14.2-alpha.8a6ed5.0<br/>@codecademy/konamimojisplosion@0.2.44-alpha.8a6ed5.0<br/>@codecademy/markdown-overrides@0.5.56-alpha.8a6ed5.0<br/>@codecademy/styleguide@41.14.1-alpha.8a6ed5.0<br/>@codecademy/variance@0.16.1-alpha.8a6ed5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f0808b80d3b100cac5ab10--gamut-preview.netlify.app>https://60f0808b80d3b100cac5ab10--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f0808b80d3b100cac5ab10>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.1-alpha.1ec560.0<br/>@codecademy/gamut-illustrations@0.17.10-alpha.1ec560.0<br/>@codecademy/gamut-kit@0.4.64-alpha.1ec560.0<br/>@codecademy/gamut-labs@19.16.2-alpha.1ec560.0<br/>@codecademy/gamut-patterns@0.4.5-alpha.1ec560.0<br/>@codecademy/gamut-styles@11.5.2-alpha.1ec560.0<br/>@codecademy/gamut-tests@2.4.13-alpha.1ec560.0<br/>@codecademy/gamut@34.14.3-alpha.1ec560.0<br/>@codecademy/konamimojisplosion@0.2.44-alpha.1ec560.0<br/>@codecademy/markdown-overrides@0.5.56-alpha.1ec560.0<br/>@codecademy/styleguide@41.14.3-alpha.1ec560.0<br/>@codecademy/variance@0.16.1-alpha.1ec560.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f089b925adf300916c019f--gamut-preview.netlify.app>https://60f089b925adf300916c019f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f089b925adf300916c019f>Deploy Logs</a></p>

**Pull request merged**
