### PR TITLE
fix(FillButton): corrected hover styles on FillButton in dark mode

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Correct `FillButton`'s hover color in dark mode to be a duller yellow instead of a hyper.

Also adds a link to the Figma doc in Storybook.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/N6TfoPI5OA7GanX6Zl8nWj/Buttons-%E2%9C%85?node-id=268%3A0
- [x] Related to JIRA ticket: WEB-1197
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.1-alpha.bdb9a3.0<br/>@codecademy/gamut-labs@7.4.2-alpha.bdb9a3.0<br/>@codecademy/gamut-styles@7.6.1-alpha.bdb9a3.0<br/>@codecademy/gamut@19.3.2-alpha.bdb9a3.0<br/>@codecademy/markdown-overrides@0.4.1-alpha.bdb9a3.0<br/>@codecademy/styleguide@21.4.1-alpha.bdb9a3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd42f888fce21de7a8897d7--gamut-preview.netlify.app>https://5fd42f888fce21de7a8897d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd42f888fce21de7a8897d7>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.1-alpha.0f733e.0<br/>@codecademy/gamut-labs@7.4.2-alpha.0f733e.0<br/>@codecademy/gamut-styles@7.6.1-alpha.0f733e.0<br/>@codecademy/gamut@19.3.2-alpha.0f733e.0<br/>@codecademy/markdown-overrides@0.4.1-alpha.0f733e.0<br/>@codecademy/styleguide@21.4.1-alpha.0f733e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd79301ae3de60a70739bd7--gamut-preview.netlify.app>https://5fd79301ae3de60a70739bd7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd79301ae3de60a70739bd7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.2-alpha.c6c919.0<br/>@codecademy/gamut-labs@7.4.3-alpha.c6c919.0<br/>@codecademy/gamut-styles@7.6.2-alpha.c6c919.0<br/>@codecademy/gamut@19.3.3-alpha.c6c919.0<br/>@codecademy/markdown-overrides@0.4.2-alpha.c6c919.0<br/>@codecademy/styleguide@21.4.2-alpha.c6c919.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.2-alpha.939582.0<br/>@codecademy/gamut-labs@7.4.3-alpha.939582.0<br/>@codecademy/gamut-styles@7.6.2-alpha.939582.0<br/>@codecademy/gamut@19.3.3-alpha.939582.0<br/>@codecademy/markdown-overrides@0.4.2-alpha.939582.0<br/>@codecademy/styleguide@21.4.2-alpha.939582.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd7a845a04e9f0aaca2c061--gamut-preview.netlify.app>https://5fd7a845a04e9f0aaca2c061--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd7a845a04e9f0aaca2c061>Deploy Logs</a></p>

**Pull request merged**
