### PR TITLE
feat: added CSS changes to <detail> and <summary> tags requested by Sara

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Added CSS changes to <detail> and <summary> tags requested by Sara

The specifications of the changes are exactly as requested by @SaraRoseGallagher.

Screenshot of the hot pink changes

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Personally, I would have gone with 💞 for some added fluidity, but this works too.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.4.3-alpha.09bbed.3+09bbed9e<br/>@codecademy/gamut-templates@2.3.4-alpha.09bbed.5+09bbed9e<br/>@codecademy/gamut@2.7.1-alpha.09bbed.5+09bbed9e<br/></pre>

**Comment by JoshuaKGoldberg** [comment]
@jakemhiller pointed out that the Design team might want different colors or other forms of styles for this. I suppose that's reasonable. Closing for now; we can always come back to this later when they approve these designs.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.4.3-alpha.8a4edf.4+8a4edf00<br/>@codecademy/gamut-templates@2.3.4-alpha.8a4edf.6+8a4edf00<br/>@codecademy/gamut@2.7.1-alpha.8a4edf.6+8a4edf00<br/></pre>

**Pull request closed without merging**
