### PR TITLE
feat: adding icons for Business repo

### PR DESCRIPTION
**Pull request by jenesh**
### Overview

This PR aims to add a few icons to the list of Regular icons for business use.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/2OIKtWBUzZyMi4GuOddAPA/Information-Architecture%3A-B2B?node-id=560%3A0
- [x] Related to JIRA ticket: [EN-632](https://codecademy.atlassian.net/browse/EN-632)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

Screen Shot 2021-05-05 at 10 33 07 AM

Screen Shot 2021-05-05 at 10 33 00 AM

Screen Shot 2021-05-05 at 10 33 18 AM

Screen Shot 2021-05-05 at 10 32 52 AM

Screen Shot 2021-05-05 at 10 33 31 AM

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.be9bce.0<br/>@codecademy/gamut-kit@0.3.71-alpha.be9bce.0<br/>@codecademy/gamut-labs@15.2.11-alpha.be9bce.0<br/>@codecademy/gamut@32.8.4-alpha.be9bce.0<br/>@codecademy/styleguide@36.11.3-alpha.be9bce.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091532b3fa16f1d95b158bc--gamut-preview.netlify.app>https://6091532b3fa16f1d95b158bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091532b3fa16f1d95b158bc>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Was this meant to be a draft? 🙂 

Screenshot of a squished StackedSquaresIcon

**Comment by jenesh** [comment]
> Was this meant to be a draft? 🙂
> 
> Screenshot of a squished StackedSquaresIcon

Yes sorry I was having issues with the icon and was waiting on the streamline assets. Uploading them in a few.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.8f33be.0<br/>@codecademy/gamut-kit@0.3.77-alpha.8f33be.0<br/>@codecademy/gamut-labs@15.5.1-alpha.8f33be.0<br/>@codecademy/gamut@32.11.1-alpha.8f33be.0<br/>@codecademy/styleguide@36.13.3-alpha.8f33be.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092ac0694b42d2e137bdddb--gamut-preview.netlify.app>https://6092ac0694b42d2e137bdddb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092ac0694b42d2e137bdddb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.7a15a0.0<br/>@codecademy/gamut-kit@0.3.78-alpha.7a15a0.0<br/>@codecademy/gamut-labs@15.5.2-alpha.7a15a0.0<br/>@codecademy/gamut@32.11.2-alpha.7a15a0.0<br/>@codecademy/styleguide@36.13.4-alpha.7a15a0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092b0cc7edc4d00ed0e4f24--gamut-preview.netlify.app>https://6092b0cc7edc4d00ed0e4f24--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092b0cc7edc4d00ed0e4f24>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.faca7d.0<br/>@codecademy/gamut-kit@0.3.79-alpha.faca7d.0<br/>@codecademy/gamut-labs@15.5.3-alpha.faca7d.0<br/>@codecademy/gamut@32.12.1-alpha.faca7d.0<br/>@codecademy/styleguide@36.14.1-alpha.faca7d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092cb28efc65c1d2f2111ff--gamut-preview.netlify.app>https://6092cb28efc65c1d2f2111ff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092cb28efc65c1d2f2111ff>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.2-alpha.f4d5dd.0<br/>@codecademy/gamut-kit@0.3.80-alpha.f4d5dd.0<br/>@codecademy/gamut-labs@15.5.4-alpha.f4d5dd.0<br/>@codecademy/gamut@32.12.2-alpha.f4d5dd.0<br/>@codecademy/styleguide@36.14.2-alpha.f4d5dd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609303272dbbb8248362d870--gamut-preview.netlify.app>https://609303272dbbb8248362d870--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609303272dbbb8248362d870>Deploy Logs</a></p>

**Pull request merged**
