### PR TITLE
feat(Icons): Custom root element and default aria-hidden

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

This removes some of the weird workarounds for system props and simplifies the typings / structure.

Adds a [custom transform ](https://react-svgr.com/docs/custom-transformations/) to handle the mapping (this isn't possible using a template unfortunately)

* Adds a custom SVGR babel transform plugin to remap the root JSX node to use a `styled.svg` component.
* Removes previous class name integration and leverages new styledOptions typeguardes for system props.
* Removes unused SVGR configurations - and ports the `size` attribute to a system prop local to the svg.
* Removes style attribute forwarding as system props are incompatible with `width` and `height` specifications as non pixel values throw errors

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-256
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.3-alpha.012b81.0<br/>@codecademy/gamut-kit@0.4.34-alpha.012b81.0<br/>@codecademy/gamut-labs@19.9.3-alpha.012b81.0<br/>@codecademy/gamut@34.10.2-alpha.012b81.0<br/>@codecademy/styleguide@41.10.4-alpha.012b81.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb92e27bf01e0836fbad3b--gamut-preview.netlify.app>https://60cb92e27bf01e0836fbad3b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb92e27bf01e0836fbad3b>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.3-alpha.d90dbb.0<br/>@codecademy/gamut-kit@0.4.39-alpha.d90dbb.0<br/>@codecademy/gamut-labs@19.10.5-alpha.d90dbb.0<br/>@codecademy/gamut@34.10.3-alpha.d90dbb.0<br/>@codecademy/styleguide@41.10.9-alpha.d90dbb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0c4260db00b547cedf114--gamut-preview.netlify.app>https://60d0c4260db00b547cedf114--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0c4260db00b547cedf114>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.3-alpha.82c730.0<br/>@codecademy/gamut-kit@0.4.40-alpha.82c730.0<br/>@codecademy/gamut-labs@19.10.6-alpha.82c730.0<br/>@codecademy/gamut@34.10.4-alpha.82c730.0<br/>@codecademy/styleguide@41.10.10-alpha.82c730.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0d5d68fd0a7cc11ae3ad4--gamut-preview.netlify.app>https://60d0d5d68fd0a7cc11ae3ad4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0d5d68fd0a7cc11ae3ad4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.3.3-alpha.0588b0.0<br/>@codecademy/gamut-kit@0.4.40-alpha.0588b0.0<br/>@codecademy/gamut-labs@19.10.6-alpha.0588b0.0<br/>@codecademy/gamut@34.10.4-alpha.0588b0.0<br/>@codecademy/styleguide@41.10.10-alpha.0588b0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0eef4d772a3967204441b--gamut-preview.netlify.app>https://60d0eef4d772a3967204441b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0eef4d772a3967204441b>Deploy Logs</a></p>

**Pull request merged**
