### PR TITLE
fix: Theme extension merge logic

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Fixed an issue with colormode extension merge logic, where a preemptive merge of the initial color modes attempted merging the flattened object with an unflattened parameter.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.2-alpha.293997.0<br/>@codecademy/gamut-illustrations@0.17.11-alpha.293997.0<br/>@codecademy/gamut-kit@0.4.65-alpha.293997.0<br/>@codecademy/gamut-labs@19.16.3-alpha.293997.0<br/>@codecademy/gamut-patterns@0.4.6-alpha.293997.0<br/>@codecademy/gamut-styles@11.6.1-alpha.293997.0<br/>@codecademy/gamut-tests@2.4.14-alpha.293997.0<br/>@codecademy/gamut@34.14.4-alpha.293997.0<br/>@codecademy/konamimojisplosion@0.2.45-alpha.293997.0<br/>@codecademy/markdown-overrides@0.5.57-alpha.293997.0<br/>@codecademy/styleguide@41.14.4-alpha.293997.0<br/>@codecademy/variance@0.17.1-alpha.293997.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.2-alpha.576611.0<br/>@codecademy/gamut-illustrations@0.17.11-alpha.576611.0<br/>@codecademy/gamut-kit@0.4.65-alpha.576611.0<br/>@codecademy/gamut-labs@19.16.3-alpha.576611.0<br/>@codecademy/gamut-patterns@0.4.6-alpha.576611.0<br/>@codecademy/gamut-styles@11.6.1-alpha.576611.0<br/>@codecademy/gamut-tests@2.4.14-alpha.576611.0<br/>@codecademy/gamut@34.14.4-alpha.576611.0<br/>@codecademy/konamimojisplosion@0.2.45-alpha.576611.0<br/>@codecademy/markdown-overrides@0.5.57-alpha.576611.0<br/>@codecademy/styleguide@41.14.4-alpha.576611.0<br/>@codecademy/variance@0.17.1-alpha.576611.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.2-alpha.144766.0<br/>@codecademy/gamut-illustrations@0.17.11-alpha.144766.0<br/>@codecademy/gamut-kit@0.4.65-alpha.144766.0<br/>@codecademy/gamut-labs@19.16.3-alpha.144766.0<br/>@codecademy/gamut-patterns@0.4.6-alpha.144766.0<br/>@codecademy/gamut-styles@11.6.1-alpha.144766.0<br/>@codecademy/gamut-tests@2.4.14-alpha.144766.0<br/>@codecademy/gamut@34.14.4-alpha.144766.0<br/>@codecademy/konamimojisplosion@0.2.45-alpha.144766.0<br/>@codecademy/markdown-overrides@0.5.57-alpha.144766.0<br/>@codecademy/styleguide@41.14.4-alpha.144766.0<br/>@codecademy/variance@0.17.1-alpha.144766.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.2-alpha.9affc9.0<br/>@codecademy/gamut-illustrations@0.17.11-alpha.9affc9.0<br/>@codecademy/gamut-kit@0.4.65-alpha.9affc9.0<br/>@codecademy/gamut-labs@19.16.3-alpha.9affc9.0<br/>@codecademy/gamut-patterns@0.4.6-alpha.9affc9.0<br/>@codecademy/gamut-styles@11.6.1-alpha.9affc9.0<br/>@codecademy/gamut-tests@2.4.14-alpha.9affc9.0<br/>@codecademy/gamut@34.14.4-alpha.9affc9.0<br/>@codecademy/konamimojisplosion@0.2.45-alpha.9affc9.0<br/>@codecademy/markdown-overrides@0.5.57-alpha.9affc9.0<br/>@codecademy/styleguide@41.14.4-alpha.9affc9.0<br/>@codecademy/variance@0.17.1-alpha.9affc9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f1d8864004497f9ec57c5b--gamut-preview.netlify.app>https://60f1d8864004497f9ec57c5b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f1d8864004497f9ec57c5b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.2-alpha.be029d.0<br/>@codecademy/gamut-illustrations@0.17.11-alpha.be029d.0<br/>@codecademy/gamut-kit@0.4.65-alpha.be029d.0<br/>@codecademy/gamut-labs@19.16.3-alpha.be029d.0<br/>@codecademy/gamut-patterns@0.4.6-alpha.be029d.0<br/>@codecademy/gamut-styles@11.6.1-alpha.be029d.0<br/>@codecademy/gamut-tests@2.4.14-alpha.be029d.0<br/>@codecademy/gamut@34.14.4-alpha.be029d.0<br/>@codecademy/konamimojisplosion@0.2.45-alpha.be029d.0<br/>@codecademy/markdown-overrides@0.5.57-alpha.be029d.0<br/>@codecademy/styleguide@41.14.5-alpha.be029d.0<br/>@codecademy/variance@0.17.1-alpha.be029d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f1dd64941c3e00981e387c--gamut-preview.netlify.app>https://60f1dd64941c3e00981e387c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f1dd64941c3e00981e387c>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]
more like theme extension merge MAGIC

**Pull request merged**
