### PR TITLE
docs: GridForm custom-group

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Adds docs for `custom-group`

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.14.1-alpha.711e37.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f061b8eb93cf14166d7f0f--gamut-preview.netlify.app>https://60f061b8eb93cf14166d7f0f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f061b8eb93cf14166d7f0f>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.14.2-alpha.7feb7b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f07db6416e0100e5fc0505--gamut-preview.netlify.app>https://60f07db6416e0100e5fc0505--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f07db6416e0100e5fc0505>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.14.4-alpha.800613.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f1888b620cf71f5ab6bbe4--gamut-preview.netlify.app>https://60f1888b620cf71f5ab6bbe4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f1888b620cf71f5ab6bbe4>Deploy Logs</a></p>

**Pull request merged**
