### PR TITLE
refactor(SplitInterstitial): deleting split interstitial

### PR DESCRIPTION
**Pull request by cstatro**
### PR Checklist
Removes the `SplitInterstitial` component. 

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]
Pull in main and lets get this GONE

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.48-alpha.937308.0<br/>@codecademy/gamut-labs@13.2.11-alpha.937308.0<br/>@codecademy/gamut@29.7.2-alpha.937308.0<br/>@codecademy/styleguide@33.6.3-alpha.937308.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6075b5c9c0ad55f6515a7d63--gamut-preview.netlify.app>https://6075b5c9c0ad55f6515a7d63--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6075b5c9c0ad55f6515a7d63>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.13-alpha.8145ff.0<br/>@codecademy/gamut-labs@13.4.5-alpha.8145ff.0<br/>@codecademy/gamut@29.9.6-alpha.8145ff.0<br/>@codecademy/styleguide@33.9.5-alpha.8145ff.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6075b8c8124b8400ae007c24--gamut-preview.netlify.app>https://6075b8c8124b8400ae007c24--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6075b8c8124b8400ae007c24>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
boom

**Comment by JoshuaKGoldberg** [comment]
rip my first gamut component 😢

**Pull request merged**
