### PR TITLE
fix(variance): Ensure array scales always qualify for transformation

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Array scales didn't trigger transformation flow for values.  This explicitly adds a check explicitly for arrays and adds a test to validate the behavior.
* Improves logic for looking up scalar values with a hof that returns the appropriate logic (computations were unnecessarily checking the types of scales)
* Splits out helpers to a separate file.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.2-alpha.7aeed7.0<br/>@codecademy/gamut-illustrations@0.17.16-alpha.7aeed7.0<br/>@codecademy/gamut-kit@0.5.25-alpha.7aeed7.0<br/>@codecademy/gamut-labs@19.19.11-alpha.7aeed7.0<br/>@codecademy/gamut-patterns@0.5.4-alpha.7aeed7.0<br/>@codecademy/gamut-styles@11.7.2-alpha.7aeed7.0<br/>@codecademy/gamut-tests@2.4.19-alpha.7aeed7.0<br/>@codecademy/gamut@36.1.1-alpha.7aeed7.0<br/>@codecademy/konamimojisplosion@0.2.50-alpha.7aeed7.0<br/>@codecademy/markdown-overrides@0.5.62-alpha.7aeed7.0<br/>@codecademy/styleguide@43.1.1-alpha.7aeed7.0<br/>@codecademy/variance@0.17.3-alpha.7aeed7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61156afa4cb892106c0159d9--gamut-preview.netlify.app>https://61156afa4cb892106c0159d9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61156afa4cb892106c0159d9>Deploy Logs</a></p>

**Review by MattSchiller — APPROVED** [review]
I'll admit the code's full ramifications outside of my use case is a bit beyond me, but in isolation this code looks good, and I'd like it to exist =)

Thanks!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611571297edd2d1b48090288--gamut-preview.netlify.app>https://611571297edd2d1b48090288--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611571297edd2d1b48090288>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.2-alpha.35a64e.0<br/>@codecademy/gamut-illustrations@0.17.16-alpha.35a64e.0<br/>@codecademy/gamut-kit@0.5.26-alpha.35a64e.0<br/>@codecademy/gamut-labs@19.20.1-alpha.35a64e.0<br/>@codecademy/gamut-patterns@0.5.4-alpha.35a64e.0<br/>@codecademy/gamut-styles@11.7.2-alpha.35a64e.0<br/>@codecademy/gamut-tests@2.4.19-alpha.35a64e.0<br/>@codecademy/gamut@36.1.1-alpha.35a64e.0<br/>@codecademy/konamimojisplosion@0.2.50-alpha.35a64e.0<br/>@codecademy/markdown-overrides@0.5.62-alpha.35a64e.0<br/>@codecademy/styleguide@43.2.1-alpha.35a64e.0<br/>@codecademy/variance@0.17.3-alpha.35a64e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61157fc616db1a2781efcefc--gamut-preview.netlify.app>https://61157fc616db1a2781efcefc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61157fc616db1a2781efcefc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.2-alpha.dc88cf.0<br/>@codecademy/gamut-illustrations@0.17.16-alpha.dc88cf.0<br/>@codecademy/gamut-kit@0.5.26-alpha.dc88cf.0<br/>@codecademy/gamut-labs@19.20.1-alpha.dc88cf.0<br/>@codecademy/gamut-patterns@0.5.4-alpha.dc88cf.0<br/>@codecademy/gamut-styles@11.7.2-alpha.dc88cf.0<br/>@codecademy/gamut-tests@2.4.19-alpha.dc88cf.0<br/>@codecademy/gamut@36.1.1-alpha.dc88cf.0<br/>@codecademy/konamimojisplosion@0.2.50-alpha.dc88cf.0<br/>@codecademy/markdown-overrides@0.5.62-alpha.dc88cf.0<br/>@codecademy/styleguide@43.2.1-alpha.dc88cf.0<br/>@codecademy/variance@0.17.3-alpha.dc88cf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61158351b851f42d7291d7d9--gamut-preview.netlify.app>https://61158351b851f42d7291d7d9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61158351b851f42d7291d7d9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.2-alpha.8588b0.0<br/>@codecademy/gamut-illustrations@0.17.16-alpha.8588b0.0<br/>@codecademy/gamut-kit@0.5.26-alpha.8588b0.0<br/>@codecademy/gamut-labs@19.20.1-alpha.8588b0.0<br/>@codecademy/gamut-patterns@0.5.4-alpha.8588b0.0<br/>@codecademy/gamut-styles@11.7.2-alpha.8588b0.0<br/>@codecademy/gamut-tests@2.4.19-alpha.8588b0.0<br/>@codecademy/gamut@36.1.1-alpha.8588b0.0<br/>@codecademy/konamimojisplosion@0.2.50-alpha.8588b0.0<br/>@codecademy/markdown-overrides@0.5.62-alpha.8588b0.0<br/>@codecademy/styleguide@43.2.1-alpha.8588b0.0<br/>@codecademy/variance@0.17.3-alpha.8588b0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61158c4b65dc4c3a3e837fea--gamut-preview.netlify.app>https://61158c4b65dc4c3a3e837fea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61158c4b65dc4c3a3e837fea>Deploy Logs</a></p>

**Pull request merged**
