### PR TITLE
fix: landing page descriptions margin-top adjustments

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Adjust margin-top of descriptions in 2 places within landing page components, per design feedback.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/2aBlW1pgFt5PT6soRu1HXy/%E2%9C%8F%EF%B8%8F-Landing-Page-Templates---Unification?node-id=244%3A663
- [x] Related to JIRA ticket: [REACH-520](https://codecademy.atlassian.net/browse/REACH-520)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.7-alpha.169d83.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60086dc443761845d9c7eed1--gamut-preview.netlify.app>https://60086dc443761845d9c7eed1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60086dc443761845d9c7eed1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60088631c5722f00a5f99b76--gamut-preview.netlify.app>https://60088631c5722f00a5f99b76--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60088631c5722f00a5f99b76>Deploy Logs</a></p>

**Review by judahtanthony — APPROVED** [review]
Thanks

**Pull request merged**
