### PR TITLE
chore: bump component-test-setup to v0.3.1

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Bumps `component-test-setup` to its latest version, which includes couple of bugfixes.

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.3-alpha.601b4e.0<br/>@codecademy/gamut-kit@0.3.71-alpha.601b4e.0<br/>@codecademy/gamut-labs@15.2.11-alpha.601b4e.0<br/>@codecademy/gamut-styles@9.7.4-alpha.601b4e.0<br/>@codecademy/gamut-tests@2.3.26-alpha.601b4e.0<br/>@codecademy/gamut@32.8.4-alpha.601b4e.0<br/>@codecademy/konamimojisplosion@0.2.26-alpha.601b4e.0<br/>@codecademy/markdown-overrides@0.5.38-alpha.601b4e.0<br/>@codecademy/styleguide@36.11.3-alpha.601b4e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60915ab63e5ebb26fbd244cc--gamut-preview.netlify.app>https://60915ab63e5ebb26fbd244cc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60915ab63e5ebb26fbd244cc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.3-alpha.b48643.0<br/>@codecademy/gamut-kit@0.3.72-alpha.b48643.0<br/>@codecademy/gamut-labs@15.3.1-alpha.b48643.0<br/>@codecademy/gamut-styles@9.7.4-alpha.b48643.0<br/>@codecademy/gamut-tests@2.3.26-alpha.b48643.0<br/>@codecademy/gamut@32.9.1-alpha.b48643.0<br/>@codecademy/konamimojisplosion@0.2.26-alpha.b48643.0<br/>@codecademy/markdown-overrides@0.5.38-alpha.b48643.0<br/>@codecademy/styleguide@36.12.1-alpha.b48643.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60916214da25ad2928d06202--gamut-preview.netlify.app>https://60916214da25ad2928d06202--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60916214da25ad2928d06202>Deploy Logs</a></p>

**Pull request merged**
