### PR TITLE
refactor(Alert): Adding InlineAlertType

### PR DESCRIPTION
**Pull request by ZackMFleischman**
### Overview

I was changing a banner from a normal banner to an inline banner in the monolith and needed to write this as my type in a state hook:
```
  const [banner, setBanner] = useState<
    [Exclude<AlertType, 'notice' | 'feature'>, string]
  >();
```
The restriction of the AlertType for inlines isn't straightforward to type (`Exclude<AlertType, 'notice' | 'feature'>`), so I'm adding the type alias `InlineAlertType` to make this less burdensome.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: none
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by jakemhiller — APPROVED** [review]
yep, makes sense to me!

**Review by dreamwasp — APPROVED** [review]
nice!

**Review by codecaaron — APPROVED** [review]
👍

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.33-alpha.ea1907.0<br/>@codecademy/gamut-labs@13.1.3-alpha.ea1907.0<br/>@codecademy/gamut@29.4.1-alpha.ea1907.0<br/>@codecademy/styleguide@33.3.1-alpha.ea1907.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605a1b3416041a00a75dcba8--gamut-preview.netlify.app>https://605a1b3416041a00a75dcba8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605a1b3416041a00a75dcba8>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
My review definitely isn't required but this is such a beautiful change, you deserve all of our ✅ s

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.34-alpha.89c678.0<br/>@codecademy/gamut-labs@13.1.4-alpha.89c678.0<br/>@codecademy/gamut@29.4.2-alpha.89c678.0<br/>@codecademy/styleguide@33.3.2-alpha.89c678.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605b73f0fe662b009746399f--gamut-preview.netlify.app>https://605b73f0fe662b009746399f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605b73f0fe662b009746399f>Deploy Logs</a></p>

**Pull request merged**
