### PR TITLE
feat!: Controlled Checkboxes 

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
refactoring Checkboxes to be controlled components + related documentation. [monolith integration PR](https://github.com/codecademy-engineering/Codecademy/pull/25850) 

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: GM-157
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.7131ce.0<br/>@codecademy/gamut-labs@19.16.9-alpha.7131ce.0<br/>@codecademy/gamut@35.1.2-alpha.7131ce.0<br/>@codecademy/styleguide@42.1.2-alpha.7131ce.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f9b81a8dd9cf2a1156b2ae--gamut-preview.netlify.app>https://60f9b81a8dd9cf2a1156b2ae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f9b81a8dd9cf2a1156b2ae>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.d8a539.0<br/>@codecademy/gamut-labs@19.16.9-alpha.d8a539.0<br/>@codecademy/gamut@35.1.2-alpha.d8a539.0<br/>@codecademy/styleguide@42.1.2-alpha.d8a539.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fac3f409b55720059efcbb--gamut-preview.netlify.app>https://60fac3f409b55720059efcbb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fac3f409b55720059efcbb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.6812ef.0<br/>@codecademy/gamut-labs@19.16.9-alpha.6812ef.0<br/>@codecademy/gamut@35.1.2-alpha.6812ef.0<br/>@codecademy/styleguide@42.1.2-alpha.6812ef.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fac6f79261e52383ca9e69--gamut-preview.netlify.app>https://60fac6f79261e52383ca9e69--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fac6f79261e52383ca9e69>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.68315c.0<br/>@codecademy/gamut-labs@19.16.9-alpha.68315c.0<br/>@codecademy/gamut@35.1.2-alpha.68315c.0<br/>@codecademy/styleguide@42.1.2-alpha.68315c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fad6e6a8008f0b63cf7c55--gamut-preview.netlify.app>https://60fad6e6a8008f0b63cf7c55--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fad6e6a8008f0b63cf7c55>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.103b36.0<br/>@codecademy/gamut-labs@19.16.9-alpha.103b36.0<br/>@codecademy/gamut@35.1.2-alpha.103b36.0<br/>@codecademy/styleguide@42.1.2-alpha.103b36.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fae14ea34b28136726091a--gamut-preview.netlify.app>https://60fae14ea34b28136726091a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fae14ea34b28136726091a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.03986b.0<br/>@codecademy/gamut-labs@19.16.9-alpha.03986b.0<br/>@codecademy/gamut@35.1.2-alpha.03986b.0<br/>@codecademy/styleguide@42.1.2-alpha.03986b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fae34b37e9071b45d9073a--gamut-preview.netlify.app>https://60fae34b37e9071b45d9073a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fae34b37e9071b45d9073a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.71-alpha.a87793.0<br/>@codecademy/gamut-labs@19.16.9-alpha.a87793.0<br/>@codecademy/gamut@35.1.2-alpha.a87793.0<br/>@codecademy/styleguide@42.1.2-alpha.a87793.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fae987df12b721ac4d0b72--gamut-preview.netlify.app>https://60fae987df12b721ac4d0b72--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fae987df12b721ac4d0b72>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by codecaaron — APPROVED** [review]
🔥

**Pull request merged**
