### PR TITLE
fix(SelectDropdown): parse options fix for select dropdown

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Fixed the utilities for SelectDropdown, it was doing weird things when passed an id.

### PR Checklist

- [x] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.84-alpha.e65a38.0<br/>@codecademy/gamut-labs@20.1.1-alpha.e65a38.0<br/>@codecademy/gamut@37.5.3-alpha.e65a38.0<br/>@codecademy/monaco@0.4.8-alpha.e65a38.0<br/>@codecademy/styleguide@44.6.7-alpha.e65a38.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61451a9c5f8f9230fa92ab3f--gamut-preview.netlify.app>https://61451a9c5f8f9230fa92ab3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61451a9c5f8f9230fa92ab3f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.84-alpha.3731f1.0<br/>@codecademy/gamut-labs@20.1.1-alpha.3731f1.0<br/>@codecademy/gamut@37.5.3-alpha.3731f1.0<br/>@codecademy/monaco@0.4.8-alpha.3731f1.0<br/>@codecademy/styleguide@44.6.7-alpha.3731f1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148b33ad86da1bed65521e9--gamut-preview.netlify.app>https://6148b33ad86da1bed65521e9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148b33ad86da1bed65521e9>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.12.0-alpha.19607e.0<br/>@codecademy/gamut-kit@0.5.86-alpha.19607e.0<br/>@codecademy/gamut-labs@20.2.0-alpha.19607e.0<br/>@codecademy/gamut@37.6.2-alpha.19607e.0<br/>@codecademy/monaco@0.4.10-alpha.19607e.0<br/>@codecademy/styleguide@44.8.0-alpha.19607e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148f30f1c206d2830f5cdb5--gamut-preview.netlify.app>https://6148f30f1c206d2830f5cdb5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148f30f1c206d2830f5cdb5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148ff4a2ffd68334d430d26--gamut-preview.netlify.app>https://6148ff4a2ffd68334d430d26--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148ff4a2ffd68334d430d26>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.90-alpha.a39278.0<br/>@codecademy/gamut-labs@23.0.1-alpha.a39278.0<br/>@codecademy/gamut@37.6.3-alpha.a39278.0<br/>@codecademy/monaco@0.4.11-alpha.a39278.0<br/>@codecademy/styleguide@46.0.1-alpha.a39278.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614b371da30718caf3a61075--gamut-preview.netlify.app>https://614b371da30718caf3a61075--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614b371da30718caf3a61075>Deploy Logs</a></p>

**Pull request merged**
