### PR TITLE
chore(brand-components): filled out knobs for other Brand stories

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Filled out knobs for other Brand stories

Marketing was looking to take screenshots of custom values, so this'll help them out a little.

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e90932817210f455f13c75f--codecademy-styleguide.netlify.com>https://5e90932817210f455f13c75f--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e90932817210f455f13c75f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e9095aa8d19e8616c56f36e--codecademy-styleguide.netlify.com>https://5e9095aa8d19e8616c56f36e--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e9095aa8d19e8616c56f36e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e90988211596c57f7dca8ae--codecademy-styleguide.netlify.com>https://5e90988211596c57f7dca8ae--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e90988211596c57f7dca8ae>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
I'll follow up with a standardized `decoratedStories`/`decoratedStory` pair of functions we can wrap all of them with.

**Pull request merged**
