### PR TITLE
chore(Styleguide): Upgrade to storybook 6.1.10

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Upgrades to [6.1](https://storybook.js.org/blog/storybook-6-1/)
- Should include some nice performance and navigation increases including a 20s shorter startup time.  
- There are no breaking changes with this version or deprecations we need to be worried about.

* Upgrades to storybook [6.1](https://storybook.js.org/blog/storybook-6-1/)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.6-alpha.a7aa4f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fca8f0101c13200e08905d5--gamut-preview.netlify.app>https://5fca8f0101c13200e08905d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fca8f0101c13200e08905d5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.7-alpha.c0fd77.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcaba57fb0bcc30a2f2a68d--gamut-preview.netlify.app>https://5fcaba57fb0bcc30a2f2a68d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcaba57fb0bcc30a2f2a68d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.7-alpha.1cc29a.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.7-alpha.398790.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce5e37d2eb631530decbba--gamut-preview.netlify.app>https://5fce5e37d2eb631530decbba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce5e37d2eb631530decbba>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.0.8-alpha.df3c3c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce771b0dba2b012c5c09bf--gamut-preview.netlify.app>https://5fce771b0dba2b012c5c09bf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce771b0dba2b012c5c09bf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.1.1-alpha.82657d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcf9106dc69cff57a40dd99--gamut-preview.netlify.app>https://5fcf9106dc69cff57a40dd99--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcf9106dc69cff57a40dd99>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.1.2-alpha.26c304.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcfb1309205fe012cfcae79--gamut-preview.netlify.app>https://5fcfb1309205fe012cfcae79--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcfb1309205fe012cfcae79>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
