### PR TITLE
fix(app header mobile & notifs empty container): add + fix test ids

### PR DESCRIPTION
**Pull request by saghdaey**
### Overview
A couple small fixes that came up while working on 
1) Working on PR to Move Monolith to use Gamut Global Header
2) Notifications Work

for 1 - 

- Updated AppHeaderMobile to follow behavior on production ( if the mobile menu is open, and screen size grows to desktop size - hide the mobile menu. if screen size shrinks again to mobile size, mobile menu reopens )
- added test id for mobile menu

for 2 -
- fixed data test id on empty notifications container
- (context: https://github.com/codecademy-engineering/Codecademy/pull/22305#pullrequestreview-596744770)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.10-alpha.41d7ed.0<br/>@codecademy/gamut@25.3.3-alpha.41d7ed.0<br/>@codecademy/styleguide@29.4.3-alpha.41d7ed.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60367150cea23e369ddf4d15--gamut-preview.netlify.app>https://60367150cea23e369ddf4d15--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60367150cea23e369ddf4d15>Deploy Logs</a></p>

**Review by sooinc — APPROVED** [review]
LGTM! thanks for making the fix!

**Review by dreamwasp — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
