### PR TITLE
feat: enable @typescript-eslint/prefer-optional-chain

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Enables the `@typescript-eslint/prefer-optional-chain` in our lint config.

Not marking as breaking because I like it and I'll send a corresponding monolith PR. 🤘

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-2
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.2.0-alpha.b52d78.0<br/>@codecademy/gamut-kit@0.4.9-alpha.b52d78.0<br/>@codecademy/gamut-labs@19.1.0-alpha.b52d78.0<br/>@codecademy/gamut@34.1.0-alpha.b52d78.0<br/>@codecademy/styleguide@41.1.2-alpha.b52d78.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60be09986deb9545dd6ad4e3--gamut-preview.netlify.app>https://60be09986deb9545dd6ad4e3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60be09986deb9545dd6ad4e3>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.2.0-alpha.1fd40c.0<br/>@codecademy/gamut-kit@0.4.20-alpha.1fd40c.0<br/>@codecademy/gamut-labs@19.5.0-alpha.1fd40c.0<br/>@codecademy/gamut@34.6.0-alpha.1fd40c.0<br/>@codecademy/styleguide@41.7.2-alpha.1fd40c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c2544acc5eb31e852bdd48--gamut-preview.netlify.app>https://60c2544acc5eb31e852bdd48--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c2544acc5eb31e852bdd48>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.2.0-alpha.955bcc.0<br/>@codecademy/gamut-kit@0.4.21-alpha.955bcc.0<br/>@codecademy/gamut-labs@19.5.0-alpha.955bcc.0<br/>@codecademy/gamut@34.6.0-alpha.955bcc.0<br/>@codecademy/styleguide@41.7.3-alpha.955bcc.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.2.0-alpha.e8984b.0<br/>@codecademy/gamut-kit@0.4.22-alpha.e8984b.0<br/>@codecademy/gamut-labs@19.5.0-alpha.e8984b.0<br/>@codecademy/gamut@34.6.0-alpha.e8984b.0<br/>@codecademy/styleguide@41.7.4-alpha.e8984b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c397025108f80d9f3ffcf9--gamut-preview.netlify.app>https://60c397025108f80d9f3ffcf9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c397025108f80d9f3ffcf9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@5.2.0-alpha.0d72ca.0<br/>@codecademy/gamut-kit@0.4.22-alpha.0d72ca.0<br/>@codecademy/gamut-labs@19.5.0-alpha.0d72ca.0<br/>@codecademy/gamut@34.6.0-alpha.0d72ca.0<br/>@codecademy/styleguide@41.7.4-alpha.0d72ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c39a6b5538530f9f6f7b51--gamut-preview.netlify.app>https://60c39a6b5538530f9f6f7b51--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c39a6b5538530f9f6f7b51>Deploy Logs</a></p>

**Pull request merged**
