### PR TITLE
fix(ColorMode): Ref Forarding for BG + ColorMode

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Fixes an issue where this couldn't accept a ref in certain cases and makes the prop types more expansive.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by dreamwasp — APPROVED** [review]
✅

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.7-alpha.ef0a2c.0<br/>@codecademy/gamut-kit@0.3.50-alpha.ef0a2c.0<br/>@codecademy/gamut-labs@14.4.2-alpha.ef0a2c.0<br/>@codecademy/gamut-styles@9.6.1-alpha.ef0a2c.0<br/>@codecademy/gamut-tests@2.3.19-alpha.ef0a2c.0<br/>@codecademy/gamut@32.3.2-alpha.ef0a2c.0<br/>@codecademy/konamimojisplosion@0.2.19-alpha.ef0a2c.0<br/>@codecademy/markdown-overrides@0.5.31-alpha.ef0a2c.0<br/>@codecademy/styleguide@36.4.2-alpha.ef0a2c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60872ce0b7afce00907c0849--gamut-preview.netlify.app>https://60872ce0b7afce00907c0849--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60872ce0b7afce00907c0849>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.7-alpha.008110.0<br/>@codecademy/gamut-kit@0.3.51-alpha.008110.0<br/>@codecademy/gamut-labs@14.4.3-alpha.008110.0<br/>@codecademy/gamut-styles@9.6.1-alpha.008110.0<br/>@codecademy/gamut-tests@2.3.19-alpha.008110.0<br/>@codecademy/gamut@32.3.3-alpha.008110.0<br/>@codecademy/konamimojisplosion@0.2.19-alpha.008110.0<br/>@codecademy/markdown-overrides@0.5.31-alpha.008110.0<br/>@codecademy/styleguide@36.4.3-alpha.008110.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60874634976dc619855390ee--gamut-preview.netlify.app>https://60874634976dc619855390ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60874634976dc619855390ee>Deploy Logs</a></p>

**Pull request merged**
