### PR TITLE
feat: "Louder" Error with alerts in dev

### PR DESCRIPTION
**Pull request by MattSchiller**
### Overview

Added new component to both log errors and pop more obvious alert in dev experience.

Recently for our hotkey providers, we wanted a way to log an error without crashing the page (aka, hitting the error boundary), but still alerting the developer. So here we have a fixed style alert (so it shows even when the page is scrolled, unlike `floating`). In prod, it doesn't pop that alert at all, which is a bit of a more graceful way of handling an error like this.

This is something we could use elsewhere when we want to alert developers on an issue without halting all rendering of the page.

In-use examples:

Screen Shot 2021-05-07 at 3 13 35 PM

Still visible/obvious even after scrolling:
Screen Shot 2021-05-07 at 3 13 40 PM

### PR Checklist

- [ ] Related to designs:
- [X] Related to JIRA ticket: GA-79
- [X] I have run this code to verify it works
- [X] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.87-alpha.5b7561.0<br/>@codecademy/gamut-labs@15.7.2-alpha.5b7561.0<br/>@codecademy/gamut@32.15.2-alpha.5b7561.0<br/>@codecademy/styleguide@37.1.3-alpha.5b7561.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609593ae91a273106028e283--gamut-preview.netlify.app>https://609593ae91a273106028e283--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609593ae91a273106028e283>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.87-alpha.f1d436.0<br/>@codecademy/gamut-labs@15.7.2-alpha.f1d436.0<br/>@codecademy/gamut@32.15.2-alpha.f1d436.0<br/>@codecademy/styleguide@37.1.3-alpha.f1d436.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609596e391a273137c28e2e0--gamut-preview.netlify.app>https://609596e391a273137c28e2e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609596e391a273137c28e2e0>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Hmm let's talk about this. We already have an error alert that can be retrofitted for this use case 🤔

**Comment by MattSchiller** [comment]
> Hmm let's talk about this. We already have an error alert that can be retrofitted for this use case 🤔

Oh, sure. I thought we did talk about this on our call last week and I got the green light to build this? I must've misunderstood.

Happy to go in whatever direction we decide though, can totally pause on this till then.

**Comment by MattSchiller** [comment]
Looks like we're not gonna use this 👍

**Pull request closed without merging**
