### PR TITLE
docs: Add installation + setup guide to storybook GM-254

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Adds Gamut set up guide for new applications at a top level section.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-254
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.7.7-alpha.b5436b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c7885d7401a60832e274fa--gamut-preview.netlify.app>https://60c7885d7401a60832e274fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c7885d7401a60832e274fa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.4-alpha.33ba03.0<br/>@codecademy/gamut-labs@19.16.16-alpha.33ba03.0<br/>@codecademy/gamut@35.4.4-alpha.33ba03.0<br/>@codecademy/styleguide@42.3.5-alpha.33ba03.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61043c27bcf39a0c652d63ec--gamut-preview.netlify.app>https://61043c27bcf39a0c652d63ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61043c27bcf39a0c652d63ec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.3.8-alpha.59a67c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61081f508de07f3e0adda416--gamut-preview.netlify.app>https://61081f508de07f3e0adda416--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61081f508de07f3e0adda416>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.3.8-alpha.e74921.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61083119dcc8a27e8a54a82c--gamut-preview.netlify.app>https://61083119dcc8a27e8a54a82c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61083119dcc8a27e8a54a82c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@42.3.8-alpha.bdfef3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610837f4ac08280ef834dd55--gamut-preview.netlify.app>https://610837f4ac08280ef834dd55--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610837f4ac08280ef834dd55>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🔥

**Pull request merged**
