### PR TITLE
chore(Styles): Assorted theme / variable additions

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview

- Flattened color swatch values to be accessible by a single key on the color object: `${color}-${weight}`
- Add our 5 box shadows to the theme.
- Adds spacing scale to grid-gap system functions for future use.
- Clean up relic files.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.3-alpha.7dc395.0<br/>@codecademy/gamut-styles@7.4.1-alpha.7dc395.0<br/>@codecademy/gamut@17.3.2-alpha.7dc395.0<br/>@codecademy/markdown-overrides@0.3.9-alpha.7dc395.0<br/>@codecademy/styleguide@18.5.2-alpha.7dc395.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fad97b10b10809baa7bd782--gamut-preview.netlify.app>https://5fad97b10b10809baa7bd782--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fad97b10b10809baa7bd782>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fad9ae04523e88e34438f14--gamut-preview.netlify.app>https://5fad9ae04523e88e34438f14--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fad9ae04523e88e34438f14>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.3-alpha.080c80.0<br/>@codecademy/gamut-styles@7.4.1-alpha.080c80.0<br/>@codecademy/gamut@17.3.2-alpha.080c80.0<br/>@codecademy/markdown-overrides@0.3.9-alpha.080c80.0<br/>@codecademy/styleguide@18.5.2-alpha.080c80.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.0.6-alpha.7ceb19.0<br/>@codecademy/gamut-labs@5.2.3-alpha.7ceb19.0<br/>@codecademy/gamut-styles@7.4.1-alpha.7ceb19.0<br/>@codecademy/gamut-system@0.1.1-alpha.7ceb19.0<br/>@codecademy/gamut@17.3.2-alpha.7ceb19.0<br/>@codecademy/markdown-overrides@0.3.9-alpha.7ceb19.0<br/>@codecademy/styleguide@18.5.2-alpha.7ceb19.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faeadd4afa9340c556822f1--gamut-preview.netlify.app>https://5faeadd4afa9340c556822f1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faeadd4afa9340c556822f1>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.6-alpha.4187ca.0<br/>@codecademy/gamut-styles@7.4.2-alpha.4187ca.0<br/>@codecademy/gamut@17.3.5-alpha.4187ca.0<br/>@codecademy/markdown-overrides@0.3.10-alpha.4187ca.0<br/>@codecademy/styleguide@18.5.5-alpha.4187ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faec5e6a7e71a01384a68c8--gamut-preview.netlify.app>https://5faec5e6a7e71a01384a68c8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faec5e6a7e71a01384a68c8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.7-alpha.71a40f.0<br/>@codecademy/gamut-styles@7.4.2-alpha.71a40f.0<br/>@codecademy/gamut@17.3.6-alpha.71a40f.0<br/>@codecademy/markdown-overrides@0.3.10-alpha.71a40f.0<br/>@codecademy/styleguide@18.5.6-alpha.71a40f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faec85bc7bace0baaeb88b7--gamut-preview.netlify.app>https://5faec85bc7bace0baaeb88b7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faec85bc7bace0baaeb88b7>Deploy Logs</a></p>

**Pull request merged**
