### PR TITLE
docs: fleshed out Anchor (link) guidelines

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Improved documentation and references around accessible links in the `Anchor` docs.

### PR Checklist

- ~[ ] Related to designs:~
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- ~[ ] This PR includes unit tests for the code change~

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.6.6-alpha.67435b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fe7bc14605fe1bc8fa29b50--gamut-preview.netlify.app>https://5fe7bc14605fe1bc8fa29b50--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fe7bc14605fe1bc8fa29b50>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
💯

**Comment by JoshuaKGoldberg** [comment]
oops, forgot about the merge system... 😬

**Pull request merged**
