### PR TITLE
fix: Turn on global style color aliases [GM-242]

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Follow up to https://github.com/codecademy-engineering/Codecademy/pull/24604

* Side effect from removing the ColorMode component that was wrapping Platform is that text color was no longer set this fixes an issue on some views where the color was inherited deeply.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-242
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.1-alpha.d04f94.0<br/>@codecademy/gamut-illustrations@0.15.1-alpha.d04f94.0<br/>@codecademy/gamut-kit@0.3.111-alpha.d04f94.0<br/>@codecademy/gamut-labs@18.1.2-alpha.d04f94.0<br/>@codecademy/gamut-patterns@0.2.1-alpha.d04f94.0<br/>@codecademy/gamut-styles@10.1.1-alpha.d04f94.0<br/>@codecademy/gamut-tests@2.4.1-alpha.d04f94.0<br/>@codecademy/gamut@32.20.1-alpha.d04f94.0<br/>@codecademy/konamimojisplosion@0.2.32-alpha.d04f94.0<br/>@codecademy/markdown-overrides@0.5.44-alpha.d04f94.0<br/>@codecademy/styleguide@39.0.4-alpha.d04f94.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a57dd78ac96f00aeeaf113--gamut-preview.netlify.app>https://60a57dd78ac96f00aeeaf113--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a57dd78ac96f00aeeaf113>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.6-alpha.7b4023.0<br/>@codecademy/gamut-illustrations@0.17.2-alpha.7b4023.0<br/>@codecademy/gamut-kit@0.4.7-alpha.7b4023.0<br/>@codecademy/gamut-labs@18.4.1-alpha.7b4023.0<br/>@codecademy/gamut-patterns@0.3.2-alpha.7b4023.0<br/>@codecademy/gamut-styles@10.2.2-alpha.7b4023.0<br/>@codecademy/gamut-tests@2.4.5-alpha.7b4023.0<br/>@codecademy/gamut@33.4.4-alpha.7b4023.0<br/>@codecademy/konamimojisplosion@0.2.36-alpha.7b4023.0<br/>@codecademy/markdown-overrides@0.5.48-alpha.7b4023.0<br/>@codecademy/styleguide@40.3.5-alpha.7b4023.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7fa614b4783507b6f7cf5--gamut-preview.netlify.app>https://60b7fa614b4783507b6f7cf5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7fa614b4783507b6f7cf5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.0.1-alpha.9c1361.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.9c1361.0<br/>@codecademy/gamut-kit@0.4.8-alpha.9c1361.0<br/>@codecademy/gamut-labs@19.0.1-alpha.9c1361.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.9c1361.0<br/>@codecademy/gamut-styles@11.0.1-alpha.9c1361.0<br/>@codecademy/gamut-tests@2.4.6-alpha.9c1361.0<br/>@codecademy/gamut@34.0.1-alpha.9c1361.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.9c1361.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.9c1361.0<br/>@codecademy/styleguide@41.1.1-alpha.9c1361.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ba44a86a8ff99acb629c83--gamut-preview.netlify.app>https://60ba44a86a8ff99acb629c83--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ba44a86a8ff99acb629c83>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ba4f82493c4154d9c21936--gamut-preview.netlify.app>https://60ba4f82493c4154d9c21936--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ba4f82493c4154d9c21936>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.0.1-alpha.ba73d6.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.ba73d6.0<br/>@codecademy/gamut-kit@0.4.8-alpha.ba73d6.0<br/>@codecademy/gamut-labs@19.0.1-alpha.ba73d6.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.ba73d6.0<br/>@codecademy/gamut-styles@11.0.1-alpha.ba73d6.0<br/>@codecademy/gamut-tests@2.4.6-alpha.ba73d6.0<br/>@codecademy/gamut@34.0.1-alpha.ba73d6.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.ba73d6.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.ba73d6.0<br/>@codecademy/styleguide@41.1.1-alpha.ba73d6.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.0.1-alpha.3776af.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.3776af.0<br/>@codecademy/gamut-kit@0.4.8-alpha.3776af.0<br/>@codecademy/gamut-labs@19.0.1-alpha.3776af.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.3776af.0<br/>@codecademy/gamut-styles@11.0.1-alpha.3776af.0<br/>@codecademy/gamut-tests@2.4.6-alpha.3776af.0<br/>@codecademy/gamut@34.0.1-alpha.3776af.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.3776af.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.3776af.0<br/>@codecademy/styleguide@41.1.1-alpha.3776af.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ba6cd7b8a2c58f822ab639--gamut-preview.netlify.app>https://60ba6cd7b8a2c58f822ab639--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ba6cd7b8a2c58f822ab639>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.0.1-alpha.8be734.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.8be734.0<br/>@codecademy/gamut-kit@0.4.8-alpha.8be734.0<br/>@codecademy/gamut-labs@19.0.1-alpha.8be734.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.8be734.0<br/>@codecademy/gamut-styles@11.0.1-alpha.8be734.0<br/>@codecademy/gamut-tests@2.4.6-alpha.8be734.0<br/>@codecademy/gamut@34.0.1-alpha.8be734.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.8be734.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.8be734.0<br/>@codecademy/styleguide@41.1.1-alpha.8be734.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ba6e617340437414a1be0e--gamut-preview.netlify.app>https://60ba6e617340437414a1be0e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ba6e617340437414a1be0e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.0.1-alpha.a08f02.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.a08f02.0<br/>@codecademy/gamut-kit@0.4.9-alpha.a08f02.0<br/>@codecademy/gamut-labs@19.0.2-alpha.a08f02.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.a08f02.0<br/>@codecademy/gamut-styles@11.0.1-alpha.a08f02.0<br/>@codecademy/gamut-tests@2.4.6-alpha.a08f02.0<br/>@codecademy/gamut@34.0.2-alpha.a08f02.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.a08f02.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.a08f02.0<br/>@codecademy/styleguide@41.1.2-alpha.a08f02.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bbd3f47dcd2049b38e60c4--gamut-preview.netlify.app>https://60bbd3f47dcd2049b38e60c4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bbd3f47dcd2049b38e60c4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.1-alpha.67ef87.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.67ef87.0<br/>@codecademy/gamut-kit@0.4.13-alpha.67ef87.0<br/>@codecademy/gamut-labs@19.0.6-alpha.67ef87.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.67ef87.0<br/>@codecademy/gamut-styles@11.0.1-alpha.67ef87.0<br/>@codecademy/gamut-tests@2.4.6-alpha.67ef87.0<br/>@codecademy/gamut@34.0.3-alpha.67ef87.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.67ef87.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.67ef87.0<br/>@codecademy/styleguide@41.2.4-alpha.67ef87.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60be94cc56e2322f7ab07a87--gamut-preview.netlify.app>https://60be94cc56e2322f7ab07a87--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60be94cc56e2322f7ab07a87>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.1-alpha.90db9f.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.90db9f.0<br/>@codecademy/gamut-kit@0.4.13-alpha.90db9f.0<br/>@codecademy/gamut-labs@19.0.6-alpha.90db9f.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.90db9f.0<br/>@codecademy/gamut-styles@11.0.1-alpha.90db9f.0<br/>@codecademy/gamut-tests@2.4.6-alpha.90db9f.0<br/>@codecademy/gamut@34.0.3-alpha.90db9f.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.90db9f.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.90db9f.0<br/>@codecademy/styleguide@41.2.4-alpha.90db9f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60becba1d30b1a8b7157972b--gamut-preview.netlify.app>https://60becba1d30b1a8b7157972b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60becba1d30b1a8b7157972b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.1-alpha.a4c415.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.a4c415.0<br/>@codecademy/gamut-kit@0.4.13-alpha.a4c415.0<br/>@codecademy/gamut-labs@19.0.6-alpha.a4c415.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.a4c415.0<br/>@codecademy/gamut-styles@11.0.1-alpha.a4c415.0<br/>@codecademy/gamut-tests@2.4.6-alpha.a4c415.0<br/>@codecademy/gamut@34.0.3-alpha.a4c415.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.a4c415.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.a4c415.0<br/>@codecademy/styleguide@41.2.4-alpha.a4c415.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60becd9245a70b7a6604f9a2--gamut-preview.netlify.app>https://60becd9245a70b7a6604f9a2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60becd9245a70b7a6604f9a2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.1-alpha.6dea70.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.6dea70.0<br/>@codecademy/gamut-kit@0.4.13-alpha.6dea70.0<br/>@codecademy/gamut-labs@19.0.6-alpha.6dea70.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.6dea70.0<br/>@codecademy/gamut-styles@11.0.1-alpha.6dea70.0<br/>@codecademy/gamut-tests@2.4.6-alpha.6dea70.0<br/>@codecademy/gamut@34.0.3-alpha.6dea70.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.6dea70.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.6dea70.0<br/>@codecademy/styleguide@41.2.4-alpha.6dea70.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bed2dd3c34fe9545a3a366--gamut-preview.netlify.app>https://60bed2dd3c34fe9545a3a366--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bed2dd3c34fe9545a3a366>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.1-alpha.3cfb8d.0<br/>@codecademy/gamut-illustrations@0.17.3-alpha.3cfb8d.0<br/>@codecademy/gamut-kit@0.4.13-alpha.3cfb8d.0<br/>@codecademy/gamut-labs@19.0.6-alpha.3cfb8d.0<br/>@codecademy/gamut-patterns@0.3.3-alpha.3cfb8d.0<br/>@codecademy/gamut-styles@11.0.1-alpha.3cfb8d.0<br/>@codecademy/gamut-tests@2.4.6-alpha.3cfb8d.0<br/>@codecademy/gamut@34.0.3-alpha.3cfb8d.0<br/>@codecademy/konamimojisplosion@0.2.37-alpha.3cfb8d.0<br/>@codecademy/markdown-overrides@0.5.49-alpha.3cfb8d.0<br/>@codecademy/styleguide@41.2.5-alpha.3cfb8d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bf845569bc4a38a9311440--gamut-preview.netlify.app>https://60bf845569bc4a38a9311440--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bf845569bc4a38a9311440>Deploy Logs</a></p>

**Pull request merged**
