### PR TITLE
feat(Gamut): Allow GridFormCheckboxInput to take in a ReactNode as its label

### PR DESCRIPTION
**Pull request by masungwon**
## Allow `GridFormCheckboxInput` to take in a ReactNode as its `label` type

- `GridFormCheckboxInput` currently only accepts `string` as `label` type. This limits customization and does not parallel the existing `Checkbox` functionality. So in this PR, we extend `GridFormCheckboxInput` to accept ReactNode as its `label` type.
- JIRA: https://codecademy.atlassian.net/browse/GM-7

### CODE REVIEW

**Comment by jakemhiller** [comment]
are there any other inputs where we should make this change?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.8-alpha.ff6bb0.0<br/>@codecademy/gamut@7.5.2-alpha.ff6bb0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb4317daccaca846dcff53f--codecademy-styleguide.netlify.app>https://5eb4317daccaca846dcff53f--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb4317daccaca846dcff53f>Deploy Logs</a></p>

**Comment by masungwon** [comment]
> @JoshuaKGoldberg @masungwon are there any other grid form inputs where we should make this change?

@jakemhiller None that I'm aware of.

**Pull request merged**
