### PR TITLE
feat: added Pause icon

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### PR Checklist

- [x] Related to ~Abstract~ designs: https://drive.google.com/file/d/1MiNqbgRmYhId4bWucXbamqcaNvgSJUTt/view
- [x] Related to JIRA ticket: WEB-857
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

Adds a "pause" icon we can use for play/pause buttons. This'll be used in the Careers page for the animated gifs.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.5.0-alpha.e727fb.0<br/>@codecademy/gamut-labs@4.1.5-alpha.e727fb.0<br/>@codecademy/gamut@16.0.8-alpha.e727fb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6c18a93f1f77702a15b91a--gamut-preview.netlify.app>https://5f6c18a93f1f77702a15b91a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6c18a93f1f77702a15b91a>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.5.0-alpha.dc9f52.0<br/>@codecademy/gamut-labs@4.1.5-alpha.dc9f52.0<br/>@codecademy/gamut@16.0.8-alpha.dc9f52.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6c9e8007b0fb3a0ce1b62a--gamut-preview.netlify.app>https://5f6c9e8007b0fb3a0ce1b62a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6c9e8007b0fb3a0ce1b62a>Deploy Logs</a></p>

**Pull request merged**
