### PR TITLE
fix(Flyout): Move Close Icon Placement

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Moves the close icon in `Flyout` in by 8px on the top and right to align with Codecademy logo in `LayoutMenu` and fix issue where the x-button sometimes overlaps with the scroll bar

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]

**Review by rogervera — APPROVED** [review]
👋🏽

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.36-alpha.6cbd4a.0<br/>@codecademy/gamut-labs@19.10.2-alpha.6cbd4a.0<br/>@codecademy/styleguide@41.10.6-alpha.6cbd4a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cbb6b8175d6200a0158fe3--gamut-preview.netlify.app>https://60cbb6b8175d6200a0158fe3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cbb6b8175d6200a0158fe3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.37-alpha.2ee283.0<br/>@codecademy/gamut-labs@19.10.3-alpha.2ee283.0<br/>@codecademy/styleguide@41.10.7-alpha.2ee283.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cbb9a13ee40100a2f4ff98--gamut-preview.netlify.app>https://60cbb9a13ee40100a2f4ff98--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cbb9a13ee40100a2f4ff98>Deploy Logs</a></p>

**Pull request merged**
