### PR TITLE
feat: new @codecademy/tsconfig package

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds a new `@codecademy/tsconfig.json` package to help "guide" new projects towards enabling the "fun" compiler options.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1367
- [x] I have run this code to verify it works
- ~[ ] This PR includes unit tests for the code change~

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/konamimojisplosion@0.3.0-alpha.6654ab.0<br/>@codecademy/tsconfig@0.2.0-alpha.6654ab.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/konamimojisplosion@0.3.0-alpha.115c70.0<br/>@codecademy/tsconfig@0.2.0-alpha.115c70.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6061c1254b22a278792e6dce--gamut-preview.netlify.app>https://6061c1254b22a278792e6dce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6061c1254b22a278792e6dce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.4.1-alpha.0e022c.0<br/>@codecademy/gamut-kit@0.2.40-alpha.0e022c.0<br/>@codecademy/gamut-labs@13.2.3-alpha.0e022c.0<br/>@codecademy/gamut@29.4.7-alpha.0e022c.0<br/>@codecademy/styleguide@33.3.8-alpha.0e022c.0<br/>@codecademy/tsconfig@0.2.0-alpha.0e022c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6061c480e856ff00894d1e46--gamut-preview.netlify.app>https://6061c480e856ff00894d1e46--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6061c480e856ff00894d1e46>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
🔥

**Review by dreamwasp — APPROVED** [review]
"fun"!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.4.1-alpha.8e6361.0<br/>@codecademy/gamut-kit@0.2.43-alpha.8e6361.0<br/>@codecademy/gamut-labs@13.2.6-alpha.8e6361.0<br/>@codecademy/gamut@29.5.1-alpha.8e6361.0<br/>@codecademy/styleguide@33.4.1-alpha.8e6361.0<br/>@codecademy/tsconfig@0.2.0-alpha.8e6361.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606390168e2c9037448f5e8a--gamut-preview.netlify.app>https://606390168e2c9037448f5e8a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606390168e2c9037448f5e8a>Deploy Logs</a></p>

**Pull request merged**
