### PR TITLE
chore(Icons): Remove deprecated icon and Card components

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Notifications was the last bastion of this, now they have been summarily replaced!

Monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/23762

Updates:
* `<CardShell />` - Converted to emotion with a few more variant states `hoverable` `flat` (no shadows).
* Updates Admin Section to use Cards over CardShell and fixes the hover states.
* Removes deprecated button usage in favor of fill buttons.

Removals:
* `<CardBody />` => `<Box paddingX={16} />`
* `<CardFooter />` => `<Box position="relative" />`
* `<Icon />` - Last usages were converted to new Icons directly as LinkCard were the final consumer and had no more down stream usages.

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
🔪 ❗  🔥

**Review by dreamwasp — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
even more

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.28-alpha.dda891.0<br/>@codecademy/gamut-labs@13.5.5-alpha.dda891.0<br/>@codecademy/gamut@31.0.2-alpha.dda891.0<br/>@codecademy/styleguide@35.0.2-alpha.dda891.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607886b9ff0afb7521f58393--gamut-preview.netlify.app>https://607886b9ff0afb7521f58393--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607886b9ff0afb7521f58393>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.28-alpha.c32279.0<br/>@codecademy/gamut-labs@13.5.5-alpha.c32279.0<br/>@codecademy/gamut@31.0.2-alpha.c32279.0<br/>@codecademy/styleguide@35.0.2-alpha.c32279.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60799cd8798f75026357e121--gamut-preview.netlify.app>https://60799cd8798f75026357e121--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60799cd8798f75026357e121>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.30-alpha.19b110.0<br/>@codecademy/gamut-labs@13.5.7-alpha.19b110.0<br/>@codecademy/gamut@31.0.2-alpha.19b110.0<br/>@codecademy/styleguide@35.0.4-alpha.19b110.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.30-alpha.216ce2.0<br/>@codecademy/gamut-labs@13.5.7-alpha.216ce2.0<br/>@codecademy/gamut@31.0.2-alpha.216ce2.0<br/>@codecademy/styleguide@35.0.4-alpha.216ce2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.31-alpha.77a958.0<br/>@codecademy/gamut-labs@13.5.8-alpha.77a958.0<br/>@codecademy/gamut@31.0.2-alpha.77a958.0<br/>@codecademy/styleguide@35.0.5-alpha.77a958.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607d9940e680e1499743932c--gamut-preview.netlify.app>https://607d9940e680e1499743932c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607d9940e680e1499743932c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.33-alpha.992027.0<br/>@codecademy/gamut-labs@13.5.10-alpha.992027.0<br/>@codecademy/gamut@31.0.4-alpha.992027.0<br/>@codecademy/styleguide@35.0.7-alpha.992027.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607db101f767e500e345a1e4--gamut-preview.netlify.app>https://607db101f767e500e345a1e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607db101f767e500e345a1e4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.36-alpha.1cf615.0<br/>@codecademy/gamut-labs@13.5.13-alpha.1cf615.0<br/>@codecademy/gamut@31.0.7-alpha.1cf615.0<br/>@codecademy/styleguide@35.0.10-alpha.1cf615.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607e375f340bb246aa236ee4--gamut-preview.netlify.app>https://607e375f340bb246aa236ee4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607e375f340bb246aa236ee4>Deploy Logs</a></p>

**Pull request merged**
