### PR TITLE
feat: allowed disabled inputs for GridForm

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Allows a `disabled` field prop for input groups in `GridForm`.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/QguSYdyjvb52ArvcWqM0pM/re-verify-email?node-id=1%3A22
    * Note: the designs refer to new inputs that aren't yet ready
- [x] Related to JIRA ticket: WEB-1277
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

~I'm running this by ~Mike Kenny~ Brendan and Tamar now for tweaks.~ ✅ 

Screenshot of the disabled input

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.33-alpha.610945.0<br/>@codecademy/gamut-labs@9.2.12-alpha.610945.0<br/>@codecademy/gamut@21.4.0-alpha.610945.0<br/>@codecademy/styleguide@25.2.0-alpha.610945.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602452fd8f4cb04f02e1c832--gamut-preview.netlify.app>https://602452fd8f4cb04f02e1c832--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602452fd8f4cb04f02e1c832>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.37-alpha.ba6b68.0<br/>@codecademy/gamut-labs@10.0.3-alpha.ba6b68.0<br/>@codecademy/gamut@22.1.0-alpha.ba6b68.0<br/>@codecademy/styleguide@26.1.0-alpha.ba6b68.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602735c98ca5c532bb5b300f--gamut-preview.netlify.app>https://602735c98ca5c532bb5b300f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602735c98ca5c532bb5b300f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.37-alpha.892c2c.0<br/>@codecademy/gamut-labs@10.0.3-alpha.892c2c.0<br/>@codecademy/gamut@22.1.0-alpha.892c2c.0<br/>@codecademy/styleguide@26.1.0-alpha.892c2c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602c331380c8680c3f89bbb0--gamut-preview.netlify.app>https://602c331380c8680c3f89bbb0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602c331380c8680c3f89bbb0>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
🎉

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.42-alpha.37441d.0<br/>@codecademy/gamut-labs@10.0.8-alpha.37441d.0<br/>@codecademy/gamut@23.1.0-alpha.37441d.0<br/>@codecademy/styleguide@27.1.0-alpha.37441d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602d3063cbd4581af243a33a--gamut-preview.netlify.app>https://602d3063cbd4581af243a33a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602d3063cbd4581af243a33a>Deploy Logs</a></p>

**Pull request merged**
