### PR TITLE
feat: Add BrowserPuzzle and Python illustrations

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Add BrowserPuzzle and Python illustrations.

For use in workspace cards.

Screen Shot 2021-05-04 at 4 57 28 PM

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/hPv0Q1QJZa3nfcxsmc8dHV/Build?node-id=16%3A1
- [x] Related to JIRA ticket: [EGG-1106](https://codecademy.atlassian.net/browse/EGG-1106)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.4-alpha.b7e686.0<br/>@codecademy/gamut-kit@0.3.76-alpha.b7e686.0<br/>@codecademy/gamut-labs@15.4.2-alpha.b7e686.0<br/>@codecademy/gamut@32.10.2-alpha.b7e686.0<br/>@codecademy/styleguide@36.13.2-alpha.b7e686.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091c3f80e0b790c0af4c934--gamut-preview.netlify.app>https://6091c3f80e0b790c0af4c934--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091c3f80e0b790c0af4c934>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.13.5-alpha.479288.0<br/>@codecademy/gamut-kit@0.3.77-alpha.479288.0<br/>@codecademy/gamut-labs@15.5.1-alpha.479288.0<br/>@codecademy/gamut@32.11.1-alpha.479288.0<br/>@codecademy/styleguide@36.13.3-alpha.479288.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092aab9cf07a135f4f4bb87--gamut-preview.netlify.app>https://6092aab9cf07a135f4f4bb87--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092aab9cf07a135f4f4bb87>Deploy Logs</a></p>

**Pull request merged**
