### PR TITLE
feat: Added HiddenText component

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Overview

We use this in the monolith and are likely to eventually use it in static-sites. We generally try not to create divergent experiences for accessibility vs. non-accessibility forms, but sometimes this is unavoidable.

### PR Checklist

- ~[ ] Related to Abstract designs:~
- [x] Related to JIRA ticket: WEB-1047
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

Similar to the monolith, except in CSS-in-JS instead of CSS modules.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@3.0.2-alpha.02f6d7.0<br/>@codecademy/gamut@16.0.2-alpha.02f6d7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f4eaac7a33a7b0b3f50c879--gamut-preview.netlify.app>https://5f4eaac7a33a7b0b3f50c879--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f4eaac7a33a7b0b3f50c879>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@3.0.2-alpha.2fc29f.0<br/>@codecademy/gamut@16.0.2-alpha.2fc29f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f4ecae9612e7a00c1d163ef--gamut-preview.netlify.app>https://5f4ecae9612e7a00c1d163ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f4ecae9612e7a00c1d163ef>Deploy Logs</a></p>

**Review by jcenglish — APPROVED** [review]
👍

**Pull request merged**
