### PR TITLE
feat: Adding option to set GridForm breakType to "none"

### PR DESCRIPTION
**Pull request by ZebGirouard**
### Overview

- Adds `breakType` field to `GridForm`
- Passes `breakType` to `GridFormSectionBreak`
- Adds value of "none" to `breakType` which stops rendering of `GridFormSectionBreak`
- Documents new prop under existing `## Sections` section

### PR Checklist

- [x] Related to designs: (per Abby M)
- [x] Related to JIRA ticket: CP-990
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.53-alpha.ae96bf.0<br/>@codecademy/gamut-labs@19.23.16-alpha.ae96bf.0<br/>@codecademy/gamut@36.8.4-alpha.ae96bf.0<br/>@codecademy/monaco@0.3.7-alpha.ae96bf.0<br/>@codecademy/styleguide@43.10.10-alpha.ae96bf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://612fcf5667074a08e82e4729--gamut-preview.netlify.app>https://612fcf5667074a08e82e4729--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/612fcf5667074a08e82e4729>Deploy Logs</a></p>

**Comment by ZebGirouard** [comment]
Tests added!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.53-alpha.bbeb21.0<br/>@codecademy/gamut-labs@19.23.16-alpha.bbeb21.0<br/>@codecademy/gamut@36.8.4-alpha.bbeb21.0<br/>@codecademy/monaco@0.3.7-alpha.bbeb21.0<br/>@codecademy/styleguide@43.10.10-alpha.bbeb21.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.54-alpha.ef6b00.0<br/>@codecademy/gamut-labs@19.23.17-alpha.ef6b00.0<br/>@codecademy/gamut@36.8.5-alpha.ef6b00.0<br/>@codecademy/monaco@0.3.8-alpha.ef6b00.0<br/>@codecademy/styleguide@43.10.11-alpha.ef6b00.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://612ffcdf8a6d1116e92a24bd--gamut-preview.netlify.app>https://612ffcdf8a6d1116e92a24bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/612ffcdf8a6d1116e92a24bd>Deploy Logs</a></p>

**Pull request merged**
