### PR TITLE
feat: add illustration for empty section

### PR DESCRIPTION
**Pull request by sooinc**
### Overview
Added hills illustration that is being used in Profile page (when viewing someone else's empty profile):
https://github.com/codecademy-engineering/Codecademy/pull/24551

Will eventually use in Dashboard as well.

- add Hills illustration for empty section 

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/PG0kVYDIuLk3hE566beZUV/Profiles-(Concept-Refinement)?node-id=377%3A0
- [x] Related to JIRA ticket: EGG-1136
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.14.4-alpha.64f3ea.0<br/>@codecademy/gamut-kit@0.3.104-alpha.64f3ea.0<br/>@codecademy/gamut-labs@17.1.2-alpha.64f3ea.0<br/>@codecademy/gamut@32.18.9-alpha.64f3ea.0<br/>@codecademy/styleguide@38.1.2-alpha.64f3ea.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a2efeaa93fad00b8edecd9--gamut-preview.netlify.app>https://60a2efeaa93fad00b8edecd9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a2efeaa93fad00b8edecd9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.14.5-alpha.81f53b.0<br/>@codecademy/gamut-kit@0.3.105-alpha.81f53b.0<br/>@codecademy/gamut-labs@17.2.1-alpha.81f53b.0<br/>@codecademy/gamut@32.19.1-alpha.81f53b.0<br/>@codecademy/styleguide@38.2.1-alpha.81f53b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a515f6751de5025d42b6b3--gamut-preview.netlify.app>https://60a515f6751de5025d42b6b3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a515f6751de5025d42b6b3>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.14.5-alpha.45b350.0<br/>@codecademy/gamut-kit@0.3.106-alpha.45b350.0<br/>@codecademy/gamut-labs@17.3.1-alpha.45b350.0<br/>@codecademy/gamut@32.19.2-alpha.45b350.0<br/>@codecademy/styleguide@38.3.1-alpha.45b350.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a5505d3f1a392a90909257--gamut-preview.netlify.app>https://60a5505d3f1a392a90909257--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a5505d3f1a392a90909257>Deploy Logs</a></p>

**Pull request merged**
