### PR TITLE
feat(Gamut): Allowed GridForm text fields to be of type 'date'

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Allowed GridForm text fields to be of type 'date'

No plans on using it in prod, but it uses the built-in browser date things now and is useful on our internal admin pages.

Screen recording of using a date input

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.7-alpha.362266.0<br/>@codecademy/gamut@7.5.1-alpha.362266.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb34636e7ed0afe67dba2b5--codecademy-styleguide.netlify.app>https://5eb34636e7ed0afe67dba2b5--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb34636e7ed0afe67dba2b5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.7-alpha.86be32.0<br/>@codecademy/gamut@7.5.1-alpha.86be32.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb34b7753d2df0263e2ca43--codecademy-styleguide.netlify.app>https://5eb34b7753d2df0263e2ca43--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb34b7753d2df0263e2ca43>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.7-alpha.034c06.0<br/>@codecademy/gamut@7.5.1-alpha.034c06.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@1.5.10-alpha.bd39ec.0<br/>@codecademy/gamut@7.5.4-alpha.bd39ec.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb4735416f2720223c102e5--codecademy-styleguide.netlify.app>https://5eb4735416f2720223c102e5--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb4735416f2720223c102e5>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
@jakemhiller yeah I really like that. I'll add it to the Gamut board 😄 🚀

**Pull request merged**
