### PR TITLE
docs: Updated Modal documentation and Figma links

### PR DESCRIPTION
**Pull request by songstephen**
### Overview

Updated documentation and Figma links to the `Modal` and `Dialog` stories

### PR Checklist

- [X] Related to designs: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=2449%3A3770
- [X] Related to JIRA ticket: [GM-321](https://codecademy.atlassian.net/browse/GM-321)
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@43.7.6-alpha.e059bf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611d66fd5789ab09cfc37a3b--gamut-preview.netlify.app>https://611d66fd5789ab09cfc37a3b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611d66fd5789ab09cfc37a3b>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
niceeee

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@43.7.7-alpha.c73247.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611d9ef4fbab223bef6796d6--gamut-preview.netlify.app>https://611d9ef4fbab223bef6796d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611d9ef4fbab223bef6796d6>Deploy Logs</a></p>

**Pull request merged**
