### PR TITLE
feat: added focus-visible to newer buttons and similar

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Used `:focus-visible` instead of `:focus` in what feels like the remainder of relevant buttons that should have it.

That's:

* The new buttons (amusing that they're getting it after the old SCSS ones)
* Accordion buttons
* Alert buttons
* Banner buttons

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/N6TfoPI5OA7GanX6Zl8nWj/Buttons-%E2%9C%85?node-id=268%3A0
- [x] Related to JIRA ticket: WEB-1152
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Review by jakemhiller — APPROVED** [review]
🎊

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.4-alpha.15acc1.0<br/>@codecademy/gamut-labs@7.5.1-alpha.15acc1.0<br/>@codecademy/gamut@19.5.0-alpha.15acc1.0<br/>@codecademy/styleguide@21.5.1-alpha.15acc1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd8d12d8856cb011bdedea3--gamut-preview.netlify.app>https://5fd8d12d8856cb011bdedea3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd8d12d8856cb011bdedea3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.2-alpha.b6b5ff.0<br/>@codecademy/gamut-labs@7.5.3-alpha.b6b5ff.0<br/>@codecademy/gamut@19.6.0-alpha.b6b5ff.0<br/>@codecademy/styleguide@21.5.2-alpha.b6b5ff.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fda23bf9ea9461383b8fa68--gamut-preview.netlify.app>https://5fda23bf9ea9461383b8fa68--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fda23bf9ea9461383b8fa68>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.3-alpha.03a46a.0<br/>@codecademy/gamut-labs@7.5.4-alpha.03a46a.0<br/>@codecademy/gamut@19.7.0-alpha.03a46a.0<br/>@codecademy/styleguide@21.6.1-alpha.03a46a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fda27149d147c0159212d2c--gamut-preview.netlify.app>https://5fda27149d147c0159212d2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fda27149d147c0159212d2c>Deploy Logs</a></p>

**Pull request merged**
