### PR TITLE
fix: update sideEffects values to fix tree shaking issues with css

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Updated with new SideEffectsPlugin replacement (addition, really) that uses proper globbing.

The added code is a combination of the plugin from Webpack 4 and the globbing from webpack 5, and will be removed in the webpack 5 upgrade branch once i merge this in.

This will likely slow down production builds slightly, but i don't think it will be enough to notice.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
`gamut-illustrations` too?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.1-alpha.e5cdae.0<br/>@codecademy/gamut-labs@7.5.3-alpha.e5cdae.0<br/>@codecademy/gamut@19.5.1-alpha.e5cdae.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.e5cdae.0<br/>@codecademy/styleguide@21.5.2-alpha.e5cdae.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd93512edfd4201145b8963--gamut-preview.netlify.app>https://5fd93512edfd4201145b8963--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd93512edfd4201145b8963>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — DISMISSED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.1-alpha.f5def2.0<br/>@codecademy/gamut-labs@7.5.3-alpha.f5def2.0<br/>@codecademy/gamut-styles@7.6.3-alpha.f5def2.0<br/>@codecademy/gamut@19.5.1-alpha.f5def2.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.f5def2.0<br/>@codecademy/styleguide@21.5.2-alpha.f5def2.0<br/>@codecademy/webpack-config@5.2.2-alpha.f5def2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.5-alpha.86620d.0<br/>@codecademy/gamut-labs@7.5.6-alpha.86620d.0<br/>@codecademy/gamut-styles@7.6.3-alpha.86620d.0<br/>@codecademy/gamut@19.7.2-alpha.86620d.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.86620d.0<br/>@codecademy/styleguide@21.6.3-alpha.86620d.0<br/>@codecademy/webpack-config@5.2.2-alpha.86620d.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.5-alpha.85d678.0<br/>@codecademy/gamut-labs@7.5.6-alpha.85d678.0<br/>@codecademy/gamut-styles@7.6.3-alpha.85d678.0<br/>@codecademy/gamut@19.7.2-alpha.85d678.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.85d678.0<br/>@codecademy/styleguide@21.6.3-alpha.85d678.0<br/>@codecademy/webpack-config@5.2.2-alpha.85d678.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fdb9b132119e40dfca2663e--gamut-preview.netlify.app>https://5fdb9b132119e40dfca2663e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fdb9b132119e40dfca2663e>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
That codecov spam >.>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.5-alpha.f86a75.0<br/>@codecademy/gamut-labs@7.5.6-alpha.f86a75.0<br/>@codecademy/gamut-styles@7.6.3-alpha.f86a75.0<br/>@codecademy/gamut@19.7.2-alpha.f86a75.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.f86a75.0<br/>@codecademy/styleguide@21.6.3-alpha.f86a75.0<br/>@codecademy/webpack-config@5.2.2-alpha.f86a75.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fdbbdf200f3e00d04b74e27--gamut-preview.netlify.app>https://5fdbbdf200f3e00d04b74e27--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fdbbdf200f3e00d04b74e27>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.5-alpha.bbcc07.0<br/>@codecademy/gamut-labs@7.5.6-alpha.bbcc07.0<br/>@codecademy/gamut-styles@7.6.3-alpha.bbcc07.0<br/>@codecademy/gamut@19.7.2-alpha.bbcc07.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.bbcc07.0<br/>@codecademy/styleguide@21.6.3-alpha.bbcc07.0<br/>@codecademy/webpack-config@5.2.2-alpha.bbcc07.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fdbf0678d9d4500ae857218--gamut-preview.netlify.app>https://5fdbf0678d9d4500ae857218--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fdbf0678d9d4500ae857218>Deploy Logs</a></p>

**Pull request closed without merging**
