### PR TITLE
feat(Markdown): Add onAnchorClick prop

### PR DESCRIPTION
**Pull request by rogervera**
### Overview

Adds an `onAnchorClick` prop to the Markdown component for passing down to `<a/>` tags.

### PR Checklist
- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-453](https://codecademy.atlassian.net/browse/REACH-453)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
This seems reasonable for now!

Something to think about long term: what happens when people want other onClick handlers for our overrides? Buttons, maybe? I can't think of anything but maybe something to back-of-mind ruminate on...

**Comment by rogervera** [comment]
> This seems reasonable for now!
> 
> Something to think about long term: what happens when people want other onClick handlers for our overrides? Buttons, maybe? I can't think of anything but maybe something to back-of-mind ruminate on...

Perhaps an `onClickHandlers` prop to group them, similar to `overrides`?
```ts
onClickHandlers: {
  onAnchorClick,
  onButtonClick,
  ...
}
```

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.2.3-alpha.4c7247.0<br/>@codecademy/gamut-labs@7.4.4-alpha.4c7247.0<br/>@codecademy/gamut@19.3.4-alpha.4c7247.0<br/>@codecademy/styleguide@21.4.3-alpha.4c7247.0<br/></pre>

**Comment by JoshuaKGoldberg** [comment]
Yeah maybe! Even more generic, a pattern some libraries use is exporting the base object (in this case the default `overrides`) and letting people `merge(overrides,otherStuff)`.

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd7b35731424701153cb53a--gamut-preview.netlify.app>https://5fd7b35731424701153cb53a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd7b35731424701153cb53a>Deploy Logs</a></p>

**Pull request merged**
