### PR TITLE
chore(Card): Migrate to Variance and more performant structure.

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

- Switches card variants to `variance` implementation of the API, but leaves current system props in place.
- Adds border scales for ez borders.
- Refactors Card to use Box Shadow instead of pseudo elements for the interim.  This will eventually need to be multiple elements as we standardize Card with persistent pattern backdrops.  This should resolve rounding bugs with card borders.
- Updates HubCard with the new Card API.
- Changes downstream consumers of card.

### PR Checklist

- [x] Related to designs:  All Cards
- [x] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.15-alpha.564d45.0<br/>@codecademy/gamut-kit@0.3.29-alpha.564d45.0<br/>@codecademy/gamut-labs@13.5.6-alpha.564d45.0<br/>@codecademy/gamut-styles@9.5.2-alpha.564d45.0<br/>@codecademy/gamut-tests@2.3.13-alpha.564d45.0<br/>@codecademy/gamut@31.0.2-alpha.564d45.0<br/>@codecademy/konamimojisplosion@0.2.13-alpha.564d45.0<br/>@codecademy/markdown-overrides@0.5.25-alpha.564d45.0<br/>@codecademy/styleguide@35.0.3-alpha.564d45.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607c66b101d8c0cb6580ec5e--gamut-preview.netlify.app>https://607c66b101d8c0cb6580ec5e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607c66b101d8c0cb6580ec5e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.15-alpha.d9c13c.0<br/>@codecademy/gamut-kit@0.3.29-alpha.d9c13c.0<br/>@codecademy/gamut-labs@13.5.6-alpha.d9c13c.0<br/>@codecademy/gamut-styles@9.5.2-alpha.d9c13c.0<br/>@codecademy/gamut-tests@2.3.13-alpha.d9c13c.0<br/>@codecademy/gamut@31.0.2-alpha.d9c13c.0<br/>@codecademy/konamimojisplosion@0.2.13-alpha.d9c13c.0<br/>@codecademy/markdown-overrides@0.5.25-alpha.d9c13c.0<br/>@codecademy/styleguide@35.0.3-alpha.d9c13c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607c687a4a11f6d93810020e--gamut-preview.netlify.app>https://607c687a4a11f6d93810020e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607c687a4a11f6d93810020e>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
cool

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607de6ecef24202aa82e64a5--gamut-preview.netlify.app>https://607de6ecef24202aa82e64a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607de6ecef24202aa82e64a5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.2-alpha.ab0d9c.0<br/>@codecademy/gamut-kit@0.3.35-alpha.ab0d9c.0<br/>@codecademy/gamut-labs@13.5.12-alpha.ab0d9c.0<br/>@codecademy/gamut-styles@9.5.3-alpha.ab0d9c.0<br/>@codecademy/gamut-tests@2.3.14-alpha.ab0d9c.0<br/>@codecademy/gamut@31.0.6-alpha.ab0d9c.0<br/>@codecademy/konamimojisplosion@0.2.14-alpha.ab0d9c.0<br/>@codecademy/markdown-overrides@0.5.26-alpha.ab0d9c.0<br/>@codecademy/styleguide@35.0.9-alpha.ab0d9c.0<br/></pre>

**Pull request merged**
