### PR TITLE
feat(Toast):  Allow JSX icons GM-262

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Allows for achievement icons to be rendered correctly to port current toasts to new structure.

* Allow toasts to render an inline icon within the container.
* Any string passed is treated as a url and used as a background image.
* Adds example using an illustration.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/dT4E3SLymYjmhJFxbIOJz0/Toasts?node-id=2%3A38
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-262
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0f9276d9df7e914b92733--gamut-preview.netlify.app>https://60d0f9276d9df7e914b92733--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0f9276d9df7e914b92733>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.41-alpha.24256a.0<br/>@codecademy/gamut-labs@19.10.7-alpha.24256a.0<br/>@codecademy/gamut@34.10.5-alpha.24256a.0<br/>@codecademy/styleguide@41.10.11-alpha.24256a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0fc732d18a1e9d285bdcc--gamut-preview.netlify.app>https://60d0fc732d18a1e9d285bdcc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0fc732d18a1e9d285bdcc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.63-alpha.93c647.0<br/>@codecademy/gamut-labs@19.16.1-alpha.93c647.0<br/>@codecademy/gamut@34.14.2-alpha.93c647.0<br/>@codecademy/styleguide@41.14.1-alpha.93c647.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f0592aeb93cf09f16d8134--gamut-preview.netlify.app>https://60f0592aeb93cf09f16d8134--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f0592aeb93cf09f16d8134>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.63-alpha.d3f4ae.0<br/>@codecademy/gamut-labs@19.16.1-alpha.d3f4ae.0<br/>@codecademy/gamut@34.14.2-alpha.d3f4ae.0<br/>@codecademy/styleguide@41.14.1-alpha.d3f4ae.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f05d6225448111a19484ab--gamut-preview.netlify.app>https://60f05d6225448111a19484ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f05d6225448111a19484ab>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🙌

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.66-alpha.26e7bf.0<br/>@codecademy/gamut-labs@19.16.4-alpha.26e7bf.0<br/>@codecademy/gamut@34.14.5-alpha.26e7bf.0<br/>@codecademy/styleguide@41.14.6-alpha.26e7bf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f200ecdda5dd29a74c88e5--gamut-preview.netlify.app>https://60f200ecdda5dd29a74c88e5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f200ecdda5dd29a74c88e5>Deploy Logs</a></p>

**Pull request merged**
