### PR TITLE
chore: removed Intellimize IDs

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Removes `data-intellimize` from code now that we no longer use Intellimize.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.6-alpha.184c1a.0<br/>@codecademy/gamut-labs@13.3.6-alpha.184c1a.0<br/>@codecademy/styleguide@33.8.2-alpha.184c1a.0<br/></pre>

**Review by jenesh — APPROVED** [review]
:shipit:

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606f4f338b0ac30088156607--gamut-preview.netlify.app>https://606f4f338b0ac30088156607--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606f4f338b0ac30088156607>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
Aww yiss

**Review by dreamwasp — APPROVED** [review]
✂

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.7-alpha.8d2efd.0<br/>@codecademy/gamut-labs@13.3.7-alpha.8d2efd.0<br/>@codecademy/styleguide@33.8.4-alpha.8d2efd.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.7-alpha.115202.0<br/>@codecademy/gamut-labs@13.3.7-alpha.115202.0<br/>@codecademy/styleguide@33.8.4-alpha.115202.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.7-alpha.44bbce.0<br/>@codecademy/gamut-labs@13.3.7-alpha.44bbce.0<br/>@codecademy/styleguide@33.8.4-alpha.44bbce.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070aa99fd013b3f10b54253--gamut-preview.netlify.app>https://6070aa99fd013b3f10b54253--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070aa99fd013b3f10b54253>Deploy Logs</a></p>

**Pull request merged**
