### PR TITLE
feat: allow Avatar to be passed a className to allow responsive sizing

### PR DESCRIPTION
**Pull request by rogervera**
## Add a className prop to Avatar to allow for style override (like responsive sizing)

Currently, the styles for the Avatar component were fixed: (either regular `76px` or large `118px`).
This meant that in the Testimonial component that uses these Avatars, the images could not be responsive.

Screen Shot 2020-03-03 at 11 37 26 AM

> When the revert to medium sizing occurred, the Avatar would remain large, as the component's own `large` property would simply be passed down to the Avatar.

**Fix:**
Allow a className prop to be passed to the parent container of `<Avatar/>`

screen-capture (18)

**Refactor:**
Clean up styling

---

## Merging your changes

When you are ready to merge to master, use the "squash and merge" button in GitHub, and follow the [commit message guide](/README.md#commit-message-guide) to write your commit message.

### CODE REVIEW

**Comment by rogervera** [comment]
screen-capture (19)

Alternative approach that avoids needing className:

```
      > div {
        width: 118px;
        height: 118px;

        &::before {
          height: 110px;
          width: 110px;
        }

        > img {
          width: 110px;
          height: 110px;
        }
      }
```

This could just be added in the styling for the testimonial component. Since it's where the exception is needed.

**Comment by rogervera** [comment]
As per discussion with @JoshuaKGoldberg here https://github.com/Codecademy/client-modules/pull/645#discussion_r387741869
This PR has been brought back to life. 🧟‍♂️

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.3.4-alpha.50bb2e.1+50bb2e2a<br/>@codecademy/gamut-templates@2.3.2-alpha.50bb2e.1+50bb2e2a<br/>@codecademy/gamut@2.6.1-alpha.50bb2e.1+50bb2e2a<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.3.5-alpha.7cc7a0.2+7cc7a08a<br/>@codecademy/gamut-templates@2.3.3-alpha.7cc7a0.2+7cc7a08a<br/>@codecademy/gamut@2.6.2-alpha.7cc7a0.2+7cc7a08a<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.3.5-alpha.4d23dd.3+4d23ddb0<br/></pre>

**Comment by JoshuaKGoldberg** [comment]
Agh forgot to mention this in the approval @rogervera - can you file a followup task to do the improvement soon?

**Comment by rogervera** [comment]
> Agh forgot to mention this in the approval @rogervera - can you file a followup task to do the improvement soon?

Yes! @JoshuaKGoldberg  

Ticket made: https://codecademy.atlassian.net/browse/DISCO-78

**Pull request merged**
