### PR TITLE
fix(Checkbox): Safari + Firefox accessibility but better this time 

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Ran into a couple automated axe failures and implemented a better cross-browser solution.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: gm-341
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.56-alpha.0ee861.0<br/>@codecademy/gamut-labs@19.23.19-alpha.0ee861.0<br/>@codecademy/gamut@36.9.2-alpha.0ee861.0<br/>@codecademy/monaco@0.3.10-alpha.0ee861.0<br/>@codecademy/styleguide@43.11.2-alpha.0ee861.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61323b3040e8e94df9ed7247--gamut-preview.netlify.app>https://61323b3040e8e94df9ed7247--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61323b3040e8e94df9ed7247>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.57-alpha.c3fb0f.0<br/>@codecademy/gamut-labs@19.24.1-alpha.c3fb0f.0<br/>@codecademy/gamut@36.9.2-alpha.c3fb0f.0<br/>@codecademy/monaco@0.3.10-alpha.c3fb0f.0<br/>@codecademy/styleguide@43.11.3-alpha.c3fb0f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61323ef421e0dd5d46a0e6fe--gamut-preview.netlify.app>https://61323ef421e0dd5d46a0e6fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61323ef421e0dd5d46a0e6fe>Deploy Logs</a></p>

**Review by vonbarown — APPROVED** [review]

**Review by airrobb — APPROVED** [review]

**Review by codecaaron — APPROVED** [review]

**Pull request merged**
