### PR TITLE
feat: add idSuffix prop to Pattern

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds an optional `idSuffix` prop to `Pattern` for the case of multiple patterns on a page causing duplicate `id`s.

This is a much cheaper PR than https://github.com/Codecademy/client-modules/pull/1856: I spent an hour, timeboxed, playing around with deterministic ID generation and hated every strategy I could come up with.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: GROW-2394, GM-261
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d1ee982d18a1f97785bbb7--gamut-preview.netlify.app>https://60d1ee982d18a1f97785bbb7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d1ee982d18a1f97785bbb7>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
✨

**Review by codecaaron — APPROVED** [review]
👍  Maybe one day 🤷

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.047439.0<br/>@codecademy/gamut-labs@19.11.1-alpha.047439.0<br/>@codecademy/gamut@34.11.0-alpha.047439.0<br/>@codecademy/styleguide@41.10.15-alpha.047439.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d21f9c341eb6464a61149b--gamut-preview.netlify.app>https://60d21f9c341eb6464a61149b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d21f9c341eb6464a61149b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.51-alpha.2b8959.0<br/>@codecademy/gamut-labs@19.12.1-alpha.2b8959.0<br/>@codecademy/gamut@34.11.0-alpha.2b8959.0<br/>@codecademy/styleguide@41.10.21-alpha.2b8959.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d627127caae600dd4b7f8f--gamut-preview.netlify.app>https://60d627127caae600dd4b7f8f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d627127caae600dd4b7f8f>Deploy Logs</a></p>

**Pull request merged**
