### PR TITLE
fix(Icons): Fix default size 16

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Undefined size results in:
Screen Shot 2021-06-21 at 5 51 54 PM

* Uses default props for the SVG instead of style attributes

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.4.1-alpha.fad564.0<br/>@codecademy/gamut-kit@0.4.42-alpha.fad564.0<br/>@codecademy/gamut-labs@19.10.8-alpha.fad564.0<br/>@codecademy/gamut@34.10.6-alpha.fad564.0<br/>@codecademy/styleguide@41.10.12-alpha.fad564.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d10d98ebc545fdc0b6f0d4--gamut-preview.netlify.app>https://60d10d98ebc545fdc0b6f0d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d10d98ebc545fdc0b6f0d4>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.4.1-alpha.1f8d38.0<br/>@codecademy/gamut-kit@0.4.43-alpha.1f8d38.0<br/>@codecademy/gamut-labs@19.10.9-alpha.1f8d38.0<br/>@codecademy/gamut@34.10.7-alpha.1f8d38.0<br/>@codecademy/styleguide@41.10.13-alpha.1f8d38.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d11b7a624fea1264716aa2--gamut-preview.netlify.app>https://60d11b7a624fea1264716aa2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d11b7a624fea1264716aa2>Deploy Logs</a></p>

**Pull request merged**
