### PR TITLE
fix(GlobalHeader): Limit buttons on mobile header < XS to 1 and use small size GM-345

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Adds logic for small button usage on the mobile menu
* Ensures that only 1 button is visible when under our smallest breakpoint to prevent blowout.

Screen Shot 2021-09-03 at 6 43 48 PM
Screen Shot 2021-09-03 at 9 30 28 PM

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-345
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.58-alpha.484ce4.0<br/>@codecademy/gamut-labs@19.24.2-alpha.484ce4.0<br/>@codecademy/styleguide@43.11.4-alpha.484ce4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6132ac9b22f9e2c3603ad06c--gamut-preview.netlify.app>https://6132ac9b22f9e2c3603ad06c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6132ac9b22f9e2c3603ad06c>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
this looks good! since i'm not super familiar with this component, i don't really get why this AppHeader component would ever render on mobile if we have the AppHeaderMobile component as well  🤔

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.66-alpha.b475d5.0<br/>@codecademy/gamut-labs@19.24.10-alpha.b475d5.0<br/>@codecademy/styleguide@44.1.6-alpha.b475d5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6138f590d6093a00adc92887--gamut-preview.netlify.app>https://6138f590d6093a00adc92887--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6138f590d6093a00adc92887>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
👍 
Unit test?

**Pull request merged**
