### PR TITLE
feat(Markdown): Add default bottom margin

### PR DESCRIPTION
**Pull request by slin12**
### Overview

Adds margin-bottom for Markdown tables 

Sonny flagged that C-Devs currently have to explicitly add a `<br />` after a Markdown table because there is no margin, which is annoying. If they don't, it looks like this: https://staging.codecademy.com/resources/docs/javascript/dates

This PR adds some default margin-bottom to Markdown tables.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.99d598.0<br/>@codecademy/gamut-labs@19.19.6-alpha.99d598.0<br/>@codecademy/gamut@35.13.0-alpha.99d598.0<br/>@codecademy/styleguide@42.7.4-alpha.99d598.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61113935ea2a79e51e9b3603--gamut-preview.netlify.app>https://61113935ea2a79e51e9b3603--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61113935ea2a79e51e9b3603>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.2a281d.0<br/>@codecademy/gamut-labs@19.19.6-alpha.2a281d.0<br/>@codecademy/gamut@35.13.0-alpha.2a281d.0<br/>@codecademy/styleguide@42.7.5-alpha.2a281d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61114bb7a1f469078042701d--gamut-preview.netlify.app>https://61114bb7a1f469078042701d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61114bb7a1f469078042701d>Deploy Logs</a></p>

**Pull request merged**
