### PR TITLE
fix: use relative import for ProLogoAlt test

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview
Previous import style was breaking `yarn build-all` for me for some reason? This fixes that issue and the tests still pass with relative imports so this should at least be more consistent with other tests now.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket:
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by rogervera — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.60aa62.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7bd443bd97fa78f279133--gamut-preview.netlify.app>https://5fc7bd443bd97fa78f279133--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7bd443bd97fa78f279133>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.0b3b85.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7c7b28cb005ddbb27a1fe--gamut-preview.netlify.app>https://5fc7c7b28cb005ddbb27a1fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7c7b28cb005ddbb27a1fe>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.840e24.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7ccef4b9e27aa59d30b01--gamut-preview.netlify.app>https://5fc7ccef4b9e27aa59d30b01--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7ccef4b9e27aa59d30b01>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.5e1fdb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7d9d0404c1ac65baf35be--gamut-preview.netlify.app>https://5fc7d9d0404c1ac65baf35be--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7d9d0404c1ac65baf35be>Deploy Logs</a></p>

**Pull request merged**
