### PR TITLE
fix: scr => src

### PR DESCRIPTION
**Pull request by dreamwasp**
### PR Checklist
lil typo fix
- [ ] Related to designs:
- [x] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.24.1-alpha.305275.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6012f4edacbae738a09f0534--gamut-preview.netlify.app>https://6012f4edacbae738a09f0534--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6012f4edacbae738a09f0534>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.24.2-alpha.a3c08d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6012fc490d1e82497701c949--gamut-preview.netlify.app>https://6012fc490d1e82497701c949--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6012fc490d1e82497701c949>Deploy Logs</a></p>

**Pull request merged**
