### PR TITLE
fix(ToolTip): A11y Update

### PR DESCRIPTION
**Pull request by rogervera**
### Overview
Keyboard-only users were not able to activate the tooltip. Screenreader users did not have the tooltip narrated to them.

Change `focus` to  `focus-within` & adds `aria-live: polite` for ToolTip contents.
Removes storybook comment on non-clickable elements allowed within.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: REACH-774
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Testing
1. Turn on VoiceOver on Mac (or ChromeVox extension for Chrome/any alternative)
2. https://606dbfd55f00601ac8e7c74b--gamut-preview.netlify.app/storybook/?path=/docs/atoms-tooltip--tool-tip
3. Keyboard nav to over the tooltips

Screen Shot 2021-04-07 at 10 29 24 AM

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.470ad9.0<br/>@codecademy/gamut-labs@13.3.1-alpha.470ad9.0<br/>@codecademy/gamut@29.8.1-alpha.470ad9.0<br/>@codecademy/styleguide@33.7.2-alpha.470ad9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606dbfd55f00601ac8e7c74b--gamut-preview.netlify.app>https://606dbfd55f00601ac8e7c74b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606dbfd55f00601ac8e7c74b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.2-alpha.5d9b59.0<br/>@codecademy/gamut-labs@13.3.2-alpha.5d9b59.0<br/>@codecademy/gamut@29.8.2-alpha.5d9b59.0<br/>@codecademy/styleguide@33.7.3-alpha.5d9b59.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606dc1ff94a4de312ee15458--gamut-preview.netlify.app>https://606dc1ff94a4de312ee15458--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606dc1ff94a4de312ee15458>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Yup, this looks good to me!

For reference (Roger and I talked about this on Slack), I'm also working on a general docs & visuals overhaul for tooltips next. https://github.com/Codecademy/client-modules/commit/8fe5240e0beb79ef70e7a388fcf27558f03a77c9

**Comment by rogervera** [comment]
Yes! Full Slack thread: https://codecademy.slack.com/archives/CGQPTPR27/p1616690106016900

> Yup, this looks good to me!
> 
> For reference (Roger and I talked about this on Slack), I'm also working on a general docs & visuals overhaul for tooltips next. [8fe5240](https://github.com/Codecademy/client-modules/commit/8fe5240e0beb79ef70e7a388fcf27558f03a77c9)

**Pull request merged**
