### PR TITLE
feat(Variance): Use only the global emotion theme type (Stage 5: Acceptance) [WEB-1382]

### PR DESCRIPTION
**Pull request by codecaaron**
### Changes to Typesystem
1. Removes all builder methods / drilled generics in favor of just using the locally declared emotion theme.
1. Declares its own local version of the emotion theme to ensure that breakpoints must always be present if you are extending it.
2. All types now read from this global type instead of inference and type drilling.  (IE types won't need a minimum of 2 arguments to work since Theme is globally available).
3. Where variance is used if the user has a configured theme that is typed differently it will respect the local type.  This ensures that type restrictions between domains are possible without recreating methods. 

For example adding new colors to platform would cause issues in the old way, since the colors method would read off the theme that was supplied at creation.  In this new world the old methods will work since the key hasn't changed.

```tsx
const platformTheme = {
 ...baseTheme,
 colors: {
   ...baseTheme.colors,
   ...platformColors,
}
} as const;

declare module '@emotion/react' {
  export interface Theme extends BaseTheme, typeof platformTheme {}
}
```

You can check this out in action in the [tests](https://github.com/Codecademy/client-modules/blob/609bc7f3ab936d856225fb9885d0ae5afeac8b58/packages/variance/src/__tests__/localTheme.ts#L28-L29) where we redeclare a scoped version of `Theme` and the our methods adhere to the change automatically.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: WEB-1382
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.4.1-alpha.83ffb0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6064c2ba08af725fa7a7c9d7--gamut-preview.netlify.app>https://6064c2ba08af725fa7a7c9d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6064c2ba08af725fa7a7c9d7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.4.1-alpha.cbe419.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6064c42d3224e26010f38ab3--gamut-preview.netlify.app>https://6064c42d3224e26010f38ab3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6064c42d3224e26010f38ab3>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Nice, you were right -- this is a bit cleaner 😄

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.4.1-alpha.afe61c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6064edff6bca1500b65b5c0d--gamut-preview.netlify.app>https://6064edff6bca1500b65b5c0d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6064edff6bca1500b65b5c0d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/variance@0.4.1-alpha.a26a9d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6064f00022160b009e03db7c--gamut-preview.netlify.app>https://6064f00022160b009e03db7c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6064f00022160b009e03db7c>Deploy Logs</a></p>

**Pull request merged**
