### PR TITLE
ci: fix test parallelism

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Fixes glob for test files in CircleCI

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7d3e37462ceeb5768fa53--gamut-preview.netlify.app>https://5fc7d3e37462ceeb5768fa53--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7d3e37462ceeb5768fa53>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7d9b5f041f9c979020ffa--gamut-preview.netlify.app>https://5fc7d9b5f041f9c979020ffa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7d9b5f041f9c979020ffa>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.2f9bc0.0<br/>@codecademy/gamut@19.0.2-alpha.2f9bc0.0<br/>@codecademy/styleguide@21.0.2-alpha.2f9bc0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7dbf2ddfbcdfd6d908bd0--gamut-preview.netlify.app>https://5fc7dbf2ddfbcdfd6d908bd0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7dbf2ddfbcdfd6d908bd0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7df66639961ebd3e5c7ee--gamut-preview.netlify.app>https://5fc7df66639961ebd3e5c7ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7df66639961ebd3e5c7ee>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7e0c0f6603fe3eb846467--gamut-preview.netlify.app>https://5fc7e0c0f6603fe3eb846467--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7e0c0f6603fe3eb846467>Deploy Logs</a></p>

**Pull request merged**
