### PR TITLE
feat: add DeleteFilledIcon

### PR DESCRIPTION
**Pull request by sylvanasantos**
### Overview

Added new regular icon called DeleteFilledIcon

- Needed it for the new quiz interstitial updates (see figma linked below)

### PR Checklist

- [ ] Related to designs: [quiz interstitial](https://www.figma.com/file/W0tE6eavVjbNE0QCP2GsE1/Effort-Ecosystem?node-id=381%3A1250)
- [ ] Related to JIRA ticket: EGG-930
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.3.2-alpha.4c38bd.0<br/>@codecademy/gamut-kit@0.2.29-alpha.4c38bd.0<br/>@codecademy/gamut-labs@13.0.5-alpha.4c38bd.0<br/>@codecademy/gamut@29.1.1-alpha.4c38bd.0<br/>@codecademy/styleguide@33.0.3-alpha.4c38bd.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.3.2-alpha.35e21a.0<br/>@codecademy/gamut-kit@0.2.34-alpha.35e21a.0<br/>@codecademy/gamut-labs@13.1.4-alpha.35e21a.0<br/>@codecademy/gamut@29.4.2-alpha.35e21a.0<br/>@codecademy/styleguide@33.3.2-alpha.35e21a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605b9462e3558500bf2c7396--gamut-preview.netlify.app>https://605b9462e3558500bf2c7396--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605b9462e3558500bf2c7396>Deploy Logs</a></p>

**Review by ZackMFleischman — APPROVED** [review]
Looks like a filled in delete icon! 👍

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.3.3-alpha.15c0b5.0<br/>@codecademy/gamut-kit@0.2.36-alpha.15c0b5.0<br/>@codecademy/gamut-labs@13.1.6-alpha.15c0b5.0<br/>@codecademy/gamut@29.4.4-alpha.15c0b5.0<br/>@codecademy/styleguide@33.3.4-alpha.15c0b5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605cbcbfbd0c9278ff321f64--gamut-preview.netlify.app>https://605cbcbfbd0c9278ff321f64--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605cbcbfbd0c9278ff321f64>Deploy Logs</a></p>

**Pull request merged**
