### PR TITLE
feat: onboarded eslint-plugin-simple-import-sort into ESLint plugin

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds `eslint-plugin-import-sort` to our ESLint configuration with the (strongly) recommended default settings.

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1180
- [x] I have run this code to verify it works
- ~[ ] This PR includes unit tests for the code change~

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.81583b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc684edddfbcd20f1908b80--gamut-preview.netlify.app>https://5fc684edddfbcd20f1908b80--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc684edddfbcd20f1908b80>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.695164.0<br/>@codecademy/gamut-labs@6.0.4-alpha.695164.0<br/>@codecademy/gamut-styles@7.4.9-alpha.695164.0<br/>@codecademy/gamut-system@0.1.6-alpha.695164.0<br/>@codecademy/gamut@18.0.1-alpha.695164.0<br/>@codecademy/markdown-overrides@0.3.17-alpha.695164.0<br/>@codecademy/styleguide@20.0.1-alpha.695164.0<br/>@codecademy/tracking@0.1.3-alpha.695164.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc69249f74c002b850d4841--gamut-preview.netlify.app>https://5fc69249f74c002b850d4841--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc69249f74c002b850d4841>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc693ad7462ce375468f880--gamut-preview.netlify.app>https://5fc693ad7462ce375468f880--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc693ad7462ce375468f880>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.079b0f.0<br/>@codecademy/gamut-labs@6.0.5-alpha.079b0f.0<br/>@codecademy/gamut-styles@7.4.9-alpha.079b0f.0<br/>@codecademy/gamut-system@0.1.6-alpha.079b0f.0<br/>@codecademy/gamut@18.0.1-alpha.079b0f.0<br/>@codecademy/markdown-overrides@0.3.17-alpha.079b0f.0<br/>@codecademy/styleguide@20.0.2-alpha.079b0f.0<br/>@codecademy/tracking@0.1.3-alpha.079b0f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.95a787.0<br/>@codecademy/gamut-labs@7.1.5-alpha.95a787.0<br/>@codecademy/gamut-styles@7.5.3-alpha.95a787.0<br/>@codecademy/gamut-system@0.1.7-alpha.95a787.0<br/>@codecademy/gamut@19.1.4-alpha.95a787.0<br/>@codecademy/markdown-overrides@0.3.20-alpha.95a787.0<br/>@codecademy/styleguide@21.1.7-alpha.95a787.0<br/>@codecademy/tracking@0.1.4-alpha.95a787.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd1556e0b60c90c61e13e75--gamut-preview.netlify.app>https://5fd1556e0b60c90c61e13e75--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd1556e0b60c90c61e13e75>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.2dcb55.0<br/>@codecademy/gamut-labs@7.1.5-alpha.2dcb55.0<br/>@codecademy/gamut-styles@7.5.3-alpha.2dcb55.0<br/>@codecademy/gamut-system@0.1.7-alpha.2dcb55.0<br/>@codecademy/gamut@19.1.4-alpha.2dcb55.0<br/>@codecademy/markdown-overrides@0.3.20-alpha.2dcb55.0<br/>@codecademy/styleguide@21.1.7-alpha.2dcb55.0<br/>@codecademy/tracking@0.1.4-alpha.2dcb55.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd158252c19141652f712e6--gamut-preview.netlify.app>https://5fd158252c19141652f712e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd158252c19141652f712e6>Deploy Logs</a></p>

**Review by hmafzal — APPROVED** [review]
LGTM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.624b7e.0<br/>@codecademy/gamut-labs@7.2.1-alpha.624b7e.0<br/>@codecademy/gamut-styles@7.5.3-alpha.624b7e.0<br/>@codecademy/gamut-system@0.1.7-alpha.624b7e.0<br/>@codecademy/gamut@19.2.1-alpha.624b7e.0<br/>@codecademy/markdown-overrides@0.3.20-alpha.624b7e.0<br/>@codecademy/styleguide@21.2.1-alpha.624b7e.0<br/>@codecademy/tracking@0.1.4-alpha.624b7e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd2678fcc67f837ae06a1e3--gamut-preview.netlify.app>https://5fd2678fcc67f837ae06a1e3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd2678fcc67f837ae06a1e3>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.46ced3.0<br/>@codecademy/gamut-labs@7.3.1-alpha.46ced3.0<br/>@codecademy/gamut-styles@7.5.3-alpha.46ced3.0<br/>@codecademy/gamut-system@0.1.7-alpha.46ced3.0<br/>@codecademy/gamut@19.2.1-alpha.46ced3.0<br/>@codecademy/markdown-overrides@0.3.20-alpha.46ced3.0<br/>@codecademy/styleguide@21.2.1-alpha.46ced3.0<br/>@codecademy/tracking@0.1.4-alpha.46ced3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd3b18470990f24fc0c14e0--gamut-preview.netlify.app>https://5fd3b18470990f24fc0c14e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd3b18470990f24fc0c14e0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.9a22d6.0<br/>@codecademy/gamut-labs@7.3.1-alpha.9a22d6.0<br/>@codecademy/gamut-styles@7.5.3-alpha.9a22d6.0<br/>@codecademy/gamut-system@0.1.7-alpha.9a22d6.0<br/>@codecademy/gamut@19.2.1-alpha.9a22d6.0<br/>@codecademy/markdown-overrides@0.3.20-alpha.9a22d6.0<br/>@codecademy/styleguide@21.2.2-alpha.9a22d6.0<br/>@codecademy/tracking@0.1.4-alpha.9a22d6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd3c16870990f31fa0c1869--gamut-preview.netlify.app>https://5fd3c16870990f31fa0c1869--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd3c16870990f31fa0c1869>Deploy Logs</a></p>

**Pull request merged**
