### PR TITLE
chore(Dependencies): Deps

### PR DESCRIPTION
**Pull request by codecaaron**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.0.5-alpha.a3e44f.0<br/>@codecademy/gamut-labs@4.7.1-alpha.a3e44f.0<br/>@codecademy/gamut@16.4.1-alpha.a3e44f.0<br/>@codecademy/styleguide@17.11.1-alpha.a3e44f.0<br/>@codecademy/webpack-config@5.1.1-alpha.a3e44f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa2d96d2dd32a257c2861a1--gamut-preview.netlify.app>https://5fa2d96d2dd32a257c2861a1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa2d96d2dd32a257c2861a1>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Nice, LGTM! Played around in the styleguide deploy and it's all looking good.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.0.5-alpha.effd30.0<br/>@codecademy/gamut-labs@4.7.2-alpha.effd30.0<br/>@codecademy/gamut@16.4.2-alpha.effd30.0<br/>@codecademy/styleguide@17.11.2-alpha.effd30.0<br/>@codecademy/webpack-config@5.1.1-alpha.effd30.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa2de478303721cd6f5daaa--gamut-preview.netlify.app>https://5fa2de478303721cd6f5daaa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa2de478303721cd6f5daaa>Deploy Logs</a></p>

**Pull request merged**
