### PR TITLE
chore(Styleguide): Deprecate addon-knobs GM-138

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Deprecates `addon-knobs` in favor of controls.   While knobs are useful they really are not synergistic with the data structure that Storybook is built on.  Controls, on the other hand, are, while a bit more limited, a foundational part of the docs architecture.  Since they both achieve roughly the same effect, I'd like to remove one in favor of encouraging standards and understanding of the other.

Some stories will not have `onClick` callbacks that actively mutate state correctly.  However, the users will still be able to see the `actions` log and interact with the `PropsTable` docs block to see all possible states.

Other PRs will include changes that build on this switch:
- [VSCode snippets](https://github.com/Codecademy/client-modules/pull/1291) - Story snippets that default to using args.

### Changes

* Removes `@storybook/addon-knobs` dependency.
* Converts stories that utilized knobs to use args / controls.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GM-138
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.497b6d.0<br/>@codecademy/macros@1.1.1-alpha.497b6d.0<br/>@codecademy/styleguide@21.14.1-alpha.497b6d.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.03152b.0<br/>@codecademy/macros@1.1.1-alpha.03152b.0<br/>@codecademy/styleguide@21.14.1-alpha.03152b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6004858a9d0752a8a92e9db8--gamut-preview.netlify.app>https://6004858a9d0752a8a92e9db8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6004858a9d0752a8a92e9db8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600488beab6d72b1e2aa7672--gamut-preview.netlify.app>https://600488beab6d72b1e2aa7672--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600488beab6d72b1e2aa7672>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.9b9805.0<br/>@codecademy/macros@1.1.1-alpha.9b9805.0<br/>@codecademy/styleguide@21.14.1-alpha.9b9805.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.69a54d.0<br/>@codecademy/macros@1.1.1-alpha.69a54d.0<br/>@codecademy/styleguide@21.14.1-alpha.69a54d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6004ccf8b454fce687585441--gamut-preview.netlify.app>https://6004ccf8b454fce687585441--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6004ccf8b454fce687585441>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.554c1b.0<br/>@codecademy/macros@1.1.1-alpha.554c1b.0<br/>@codecademy/styleguide@21.14.1-alpha.554c1b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6004d209ab6d72311baa73b7--gamut-preview.netlify.app>https://6004d209ab6d72311baa73b7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6004d209ab6d72311baa73b7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.3a6c9d.0<br/>@codecademy/macros@1.1.1-alpha.3a6c9d.0<br/>@codecademy/styleguide@21.14.1-alpha.3a6c9d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6004d9dd34bcda9c81b34d04--gamut-preview.netlify.app>https://6004d9dd34bcda9c81b34d04--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6004d9dd34bcda9c81b34d04>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
rip

**Review by dreamwasp — APPROVED** [review]
✨

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.1-alpha.8ea31c.0<br/>@codecademy/gamut-illustrations@0.4.4-alpha.8ea31c.0<br/>@codecademy/gamut-labs@7.10.4-alpha.8ea31c.0<br/>@codecademy/gamut@19.11.0-alpha.8ea31c.0<br/>@codecademy/macros@1.1.2-alpha.8ea31c.0<br/>@codecademy/styleguide@21.15.0-alpha.8ea31c.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.15.1-alpha.d8489a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60072dac47d984586d0ba811--gamut-preview.netlify.app>https://60072dac47d984586d0ba811--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60072dac47d984586d0ba811>Deploy Logs</a></p>

**Pull request merged**
