### PR TITLE
feat: touched up Notifications and allowed Markdown

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Touched up Notifications UI per new designs and replace 3 line truncation with Markdown support.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/YIkTZt94L56nP0V0UIKiNg/Hackaton-Winter-2020---tuba?node-id=51%3A182
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

New designs courtesy of Tuba from Friday's Holiday 2020 Hackathon! Notable changes:
* Removed truncation
  * As it turns out, marketing has been tailoring their notifications to _not_ hit the existing `...` truncation in the component. There's also nowhere to see that full text. So we soft-agreed that there's not much use in engineering enforcing the three line maximum: it's really more of a their-side thing. Getting rid of it cleaned up the code for markdown a lot!
* Added an optional CTA at the bottom

**TODO**: Mobile designs!

Screenshot of three notifications in the list

Switches the unit tests from Enzyme's `shallow` to `mount` while I'm in the area.

Removes the button + focus outline from the empty state. This was a very old accessibility "fix" I'd added out of ignorance of proper `aria-live` patterns. In reality, I should have made the whole notifications area a dropdown in the monolith.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.6-alpha.af5f36.0<br/>@codecademy/gamut@19.1.0-alpha.af5f36.0<br/>@codecademy/styleguide@21.1.0-alpha.af5f36.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.6-alpha.e6dbfc.0<br/>@codecademy/gamut@19.1.0-alpha.e6dbfc.0<br/>@codecademy/styleguide@21.1.0-alpha.e6dbfc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fca788b5e24aa00ee2715e2--gamut-preview.netlify.app>https://5fca788b5e24aa00ee2715e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fca788b5e24aa00ee2715e2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.6-alpha.8a1e2a.0<br/>@codecademy/gamut@19.1.0-alpha.8a1e2a.0<br/>@codecademy/styleguide@21.1.0-alpha.8a1e2a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fca8ea61990ca00b5c923df--gamut-preview.netlify.app>https://5fca8ea61990ca00b5c923df--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fca8ea61990ca00b5c923df>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.6-alpha.0b1ee1.0<br/>@codecademy/gamut@19.1.0-alpha.0b1ee1.0<br/>@codecademy/styleguide@21.1.0-alpha.0b1ee1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce44d6ea7f2280b345c634--gamut-preview.netlify.app>https://5fce44d6ea7f2280b345c634--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce44d6ea7f2280b345c634>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.6-alpha.fdd718.0<br/>@codecademy/gamut@19.1.0-alpha.fdd718.0<br/>@codecademy/styleguide@21.1.0-alpha.fdd718.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce4be87bde0600fcae7ae6--gamut-preview.netlify.app>https://5fce4be87bde0600fcae7ae6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce4be87bde0600fcae7ae6>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
Closing to keep my PR queue small.

**Pull request closed without merging**
