### PR TITLE
feat(tracking): :sparkles: Including field to track business seat data 

### PR DESCRIPTION
**Pull request by vonbarown**
### Overview

Updating to include the ability to track a users business seat data

integration [PR ](https://github.com/codecademy-engineering/Codecademy/pull/30534)

### PR Checklist

- [x] Related to JIRA ticket: [EN-1447](https://codecademy.atlassian.net/browse/EN-1447)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.655232.0<br/>@codecademy/tracking@0.20.1-alpha.655232.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.28137f.0<br/>@codecademy/tracking@0.20.1-alpha.28137f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.0d1611.0<br/>@codecademy/tracking@0.20.1-alpha.0d1611.0<br/></pre>

**Review by dreamwasp — CHANGES_REQUESTED** [review]
can you remove the yarn diff from this PR? it seems unrelated 🤔

**Review by dreamwasp — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.7e7d1e.0<br/>@codecademy/tracking@0.20.1-alpha.7e7d1e.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.db084c.0<br/>@codecademy/tracking@0.20.1-alpha.db084c.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.1fc813.0<br/>@codecademy/tracking@0.20.1-alpha.1fc813.0<br/></pre>

**Review by dreamwasp — COMMENTED** [review]
i wonder if it makes sense to nest these under a `business_user` (or something) object?

**Comment by vonbarown** [comment]
> i wonder if it makes sense to nest these under a `business_user` (or something) object?

That makes sense, originally had it this way to line up with the version we in the backend. but I was able to reuse those for certain event will update

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.7.1-alpha.aff429.0<br/>@codecademy/tracking@0.22.1-alpha.aff429.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
