### PR TITLE
fix: reduce column gaps on mobile for LP components

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Reduces column gaps on mobile within the `PageHero` and `PageFeatures` landing page components so they don't overflow.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description
Previously if you went to https://staging.codecademy.com/about/careers-v2 on mobile, you are able to scroll to the right and can see the value props overflowing. Using dev tools you can see that the grid is the cause and reducing the grid gaps on mobile will resolve this.
Screen Shot 2021-02-11 at 5 53 37 PM
Screen Shot 2021-02-11 at 5 55 44 PM

### CODE REVIEW

**Review by christian-dinh — APPROVED** [review]
I take it `LayoutGrid` doesn't have a `base` option, and `xs` goes all the way down? 🚢  if so!

**Review by dreamwasp — APPROVED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.3.6-alpha.80c214.0<br/>@codecademy/styleguide@25.2.6-alpha.80c214.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6026a528751b76008d9e34c6--gamut-preview.netlify.app>https://6026a528751b76008d9e34c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6026a528751b76008d9e34c6>Deploy Logs</a></p>

**Pull request merged**
