### PR TITLE
docs(Input): Fixes input documentation

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
The Input storybook page was't rendering, I fixed it so it does again.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60945502a4abf913c00243d1--gamut-preview.netlify.app>https://60945502a4abf913c00243d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60945502a4abf913c00243d1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@37.1.1-alpha.d3dc54.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60945c43ff0738239c17990c--gamut-preview.netlify.app>https://60945c43ff0738239c17990c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60945c43ff0738239c17990c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@37.2.1-alpha.d154c5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60993c03717d8c8049c8bd98--gamut-preview.netlify.app>https://60993c03717d8c8049c8bd98--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60993c03717d8c8049c8bd98>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60993e8a280e71b3add5f3be--gamut-preview.netlify.app>https://60993e8a280e71b3add5f3be--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60993e8a280e71b3add5f3be>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Ha, thanks

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609992c84a999e1ff57ca7a5--gamut-preview.netlify.app>https://609992c84a999e1ff57ca7a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609992c84a999e1ff57ca7a5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@37.2.2-alpha.9bb3fa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609994dae50e54339be524ce--gamut-preview.netlify.app>https://609994dae50e54339be524ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609994dae50e54339be524ce>Deploy Logs</a></p>

**Pull request merged**
