### PR TITLE
fix: Updated icon sizes for condensed MenuItems

### PR DESCRIPTION
**Pull request by songstephen**
### Overview

Updated the Icon size for the Condensed variant of MenuItem

### PR Checklist

- [X] Related to designs:
- [X] Related to JIRA ticket: ABC-123
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.16-alpha.acb9e4.0<br/>@codecademy/gamut-labs@19.19.2-alpha.acb9e4.0<br/>@codecademy/gamut@35.11.1-alpha.acb9e4.0<br/>@codecademy/styleguide@42.6.8-alpha.acb9e4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610af40e24167e00a12c4643--gamut-preview.netlify.app>https://610af40e24167e00a12c4643--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610af40e24167e00a12c4643>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
nice!!

**Review by codecaaron — APPROVED** [review]
<33

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.ef87c6.0<br/>@codecademy/gamut-labs@19.19.5-alpha.ef87c6.0<br/>@codecademy/gamut@35.12.3-alpha.ef87c6.0<br/>@codecademy/styleguide@42.7.3-alpha.ef87c6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d7a6b14cf62edd0b6b5e4--gamut-preview.netlify.app>https://610d7a6b14cf62edd0b6b5e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d7a6b14cf62edd0b6b5e4>Deploy Logs</a></p>

**Pull request merged**
