### PR TITLE
feat(Text): New Text primitive using system styles

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview
Partial rebase of Partial Rebase of #953

### Additions
- `<Text />` primitive using the new style functions from gamut system.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Review by jakemhiller — APPROVED** [review]
looks like the netlify preview never deployed, but this lgtm

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.0.1-alpha.10467d.0<br/>@codecademy/gamut-styles@7.2.1-alpha.10467d.0<br/>@codecademy/gamut-system@0.1.0-alpha.10467d.0<br/>@codecademy/gamut@17.0.1-alpha.10467d.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.10467d.0<br/>@codecademy/styleguide@18.0.1-alpha.10467d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa95ba4979f7dd16b3ae81f--gamut-preview.netlify.app>https://5fa95ba4979f7dd16b3ae81f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa95ba4979f7dd16b3ae81f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.1.0-alpha.c867bc.0<br/>@codecademy/gamut-styles@7.3.0-alpha.c867bc.0<br/>@codecademy/gamut@17.2.0-alpha.c867bc.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.c867bc.0<br/>@codecademy/styleguide@18.2.0-alpha.c867bc.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.1.0-alpha.a99be2.0<br/>@codecademy/gamut-styles@7.3.0-alpha.a99be2.0<br/>@codecademy/gamut@17.2.0-alpha.a99be2.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.a99be2.0<br/>@codecademy/styleguide@18.2.0-alpha.a99be2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faadacaf8993b1bee6daf44--gamut-preview.netlify.app>https://5faadacaf8993b1bee6daf44--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faadacaf8993b1bee6daf44>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.1.1-alpha.66edd6.0<br/>@codecademy/styleguide@18.2.1-alpha.66edd6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faadb2a938db72201733dcc--gamut-preview.netlify.app>https://5faadb2a938db72201733dcc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faadb2a938db72201733dcc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.1.1-alpha.7767d7.0<br/>@codecademy/styleguide@18.2.1-alpha.7767d7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faadbb35dbd2f32fc35a5b5--gamut-preview.netlify.app>https://5faadbb35dbd2f32fc35a5b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faadbb35dbd2f32fc35a5b5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faadc18c1fe6d1935434dfd--gamut-preview.netlify.app>https://5faadc18c1fe6d1935434dfd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faadc18c1fe6d1935434dfd>Deploy Logs</a></p>

**Pull request merged**
