### PR TITLE
fix(macros): Fixes regex syntax

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Accidentally used some glob syntax for the regex here, and it was turning `Layouts` in to `Layo`.  So layo-ff me!

* Fix regex syntax in file path sanitization.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/macros@1.1.1-alpha.ae4369.0<br/>@codecademy/styleguide@21.14.1-alpha.ae4369.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6002402cc8877540d08a4b15--gamut-preview.netlify.app>https://6002402cc8877540d08a4b15--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6002402cc8877540d08a4b15>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Ha, I actually just noticed this on prod

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/macros@1.1.1-alpha.77edb3.0<br/>@codecademy/styleguide@21.14.2-alpha.77edb3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60071fc4ba3b85447b923c84--gamut-preview.netlify.app>https://60071fc4ba3b85447b923c84--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60071fc4ba3b85447b923c84>Deploy Logs</a></p>

**Pull request merged**
