### PR TITLE
fix(Docs): Add TS MDX parsing and DocGen config changes

### PR DESCRIPTION
**Pull request by codecaaron**
# Changes
- DocGen will take named Enum / Union types and transform them into their literals.
- Adds MDX to babel typescript loader.

## Notes: 
Previously this wouldn't work:
```tsx
type Something = 'thing1' | 'thing2'

type ComponentProps = {
  propName: Something,
};
```

Before:
Screen Shot 2020-05-04 at 12 08 46 PM

After:
Screen Shot 2020-05-04 at 12 08 43 PM

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb04038bc739653dacead56--codecademy-styleguide.netlify.app>https://5eb04038bc739653dacead56--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb04038bc739653dacead56>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
It's a pity the `Default` doesn't mention the string literal format though... 🤷 ah well.

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb057fb8b57ce018899c5ce--codecademy-styleguide.netlify.app>https://5eb057fb8b57ce018899c5ce--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb057fb8b57ce018899c5ce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5eb06a3dcfa81401865fd665--codecademy-styleguide.netlify.app>https://5eb06a3dcfa81401865fd665--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5eb06a3dcfa81401865fd665>Deploy Logs</a></p>

**Pull request merged**
