### PR TITLE
feat(tracking): update contentful event name

### PR DESCRIPTION
**Pull request by bndiep**
### Overview

Updates the event name for viewed Contentful experiments.

### PR Checklist

- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.5dd2eb.0<br/>@codecademy/tracking@0.20.1-alpha.5dd2eb.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.c48492.0<br/>@codecademy/tracking@0.20.1-alpha.c48492.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/codebytes@0.6.14-alpha.83d9e2.0<br/>@codecademy/tracking@0.20.1-alpha.83d9e2.0<br/></pre>

**Comment by bndiep** [comment]
This work is no longer required.

**Pull request closed without merging**
