### PR TITLE
chore(Gamut)!: removed deprecated primary, blue, red, and yellow button colors

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Removed deprecated primary, red, and yellow button colors

These button colors are deprecated and replaced with the slightly better:

| Old | New |
| --- | --- |
| `blue` | `brand-blue` |
| `primary` | `brand-red` |
| `red` | `brand-red` |
| `yellow` | `brand-yellow` |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.8.17-alpha.d95e20.0<br/>@codecademy/gamut@3.0.1-alpha.d95e20.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e8f9cf181a5278ff6abffef--codecademy-styleguide.netlify.com>https://5e8f9cf181a5278ff6abffef--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e8f9cf181a5278ff6abffef>Deploy Logs</a></p>

**Comment by jakemhiller** [comment]
Red and Yellow have newer `$color-` values, why not replace them with the newer colors and remove the equivalent brand values? Maybe I’m wrong at this point but I thought the main color variables were the canonical “colors” and brand colors were borderline deprecated 🤷🏻‍♂️

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.8.17-alpha.de170f.0<br/>@codecademy/gamut@3.0.1-alpha.de170f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e922b18802ada32ee8bc719--codecademy-styleguide.netlify.com>https://5e922b18802ada32ee8bc719--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e922b18802ada32ee8bc719>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.8.29-alpha.876521.0<br/>@codecademy/gamut-styles@2.3.0-alpha.876521.0<br/>@codecademy/gamut@3.7.3-alpha.876521.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e99b631d3d7c67a5474029a--codecademy-styleguide.netlify.app>https://5e99b631d3d7c67a5474029a--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e99b631d3d7c67a5474029a>Deploy Logs</a></p>

**Pull request merged**
