### PR TITLE
feat(Icons): Adds initial Mini Bold streamline icons

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

This adds some mini+bold icons to `gamut-icons` but keeps asset folders separate for easier maintenance.  I have prefixed all new icons there with `Mini` ostensibly this could be auto formatted for anything in the `svg/mini` folder through a shell script.

These are still available with the same entrypoint `gamut-icons` because naming is guaranteed to be unique.

* Adds new icons that are required for Alert v2.
* Adds table of contents for Icons and splits mini and regular into 2 pages.
* Updates file structure for svg assets (this does not affect downstream changes).

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.13.1-alpha.87d3fd.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.87d3fd.0<br/>@codecademy/gamut-labs@7.13.5-alpha.87d3fd.0<br/>@codecademy/gamut@19.11.6-alpha.87d3fd.0<br/>@codecademy/styleguide@21.20.3-alpha.87d3fd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6010f619e426f4a0130368d1--gamut-preview.netlify.app>https://6010f619e426f4a0130368d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6010f619e426f4a0130368d1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.13.1-alpha.26d24f.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.26d24f.0<br/>@codecademy/gamut-labs@7.14.1-alpha.26d24f.0<br/>@codecademy/gamut@19.11.6-alpha.26d24f.0<br/>@codecademy/styleguide@21.21.1-alpha.26d24f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60119108e426f4745e036524--gamut-preview.netlify.app>https://60119108e426f4745e036524--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60119108e426f4745e036524>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011954293030b6a27615194--gamut-preview.netlify.app>https://6011954293030b6a27615194--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011954293030b6a27615194>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.13.1-alpha.3ef47d.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.3ef47d.0<br/>@codecademy/gamut-labs@7.14.1-alpha.3ef47d.0<br/>@codecademy/gamut@19.11.6-alpha.3ef47d.0<br/>@codecademy/styleguide@21.21.1-alpha.3ef47d.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.13.1-alpha.f10a53.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.f10a53.0<br/>@codecademy/gamut-labs@7.14.1-alpha.f10a53.0<br/>@codecademy/gamut@19.11.6-alpha.f10a53.0<br/>@codecademy/styleguide@21.21.1-alpha.f10a53.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011a8873317e45c0c238333--gamut-preview.netlify.app>https://6011a8873317e45c0c238333--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011a8873317e45c0c238333>Deploy Logs</a></p>

**Pull request merged**
