### PR TITLE
fix: stop using CardBody padding in ToolTip

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Changed `Tooltip` to use a regular `div` for its children contents. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

The monolith's (annoyingly) subtly different CSS orderings cause `CardBody`'s CSS to go on top of `Tooltip`'s. 

CardBody overriding Tooltip padding CSS in dev tools on production

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcfba8c3ef7730bf6d69203--gamut-preview.netlify.app>https://5fcfba8c3ef7730bf6d69203--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcfba8c3ef7730bf6d69203>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.1.2-alpha.6a16f7.0<br/>@codecademy/gamut@19.1.2-alpha.6a16f7.0<br/>@codecademy/styleguide@21.1.3-alpha.6a16f7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcfbe6126375a0a0a101e2e--gamut-preview.netlify.app>https://5fcfbe6126375a0a0a101e2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcfbe6126375a0a0a101e2e>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
😅

**Pull request merged**
