### PR TITLE
docs(Readme): Fix "Working with pre-published changes" format

### PR DESCRIPTION
**Pull request by neilzo**
## Overview

It reads nicer and correctly numbers the steps 💅

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f2c36b367743eb4dea83f3d--gamut-preview.netlify.app>https://5f2c36b367743eb4dea83f3d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f2c36b367743eb4dea83f3d>Deploy Logs</a></p>

**Comment by neilzo** [comment]
> Merging #908 into main will increase coverage by 15.56%.

I'll take it!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f2c7806d55c6c6816dca0bc--gamut-preview.netlify.app>https://5f2c7806d55c6c6816dca0bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f2c7806d55c6c6816dca0bc>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
@neilzo you experienced the joy of Codecov being weird. Don't worry, you'll experience it again.

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f31580dd1005001631ae51e--gamut-preview.netlify.app>https://5f31580dd1005001631ae51e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f31580dd1005001631ae51e>Deploy Logs</a></p>

**Pull request merged**
