### PR TITLE
fix(colors): Red Swap for accessible errors GM-281

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Removes red-400 and adds red-600
* Swaps `danger-hover` and `feedback-error` to new red.
* Changes Error alerts to use red-600.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/EVbJ1Qn3FhHDLjtztmrWkt/Color-Research?node-id=72%3A44
- [x] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-281
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
yee

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6101762ea9026c220c13c44a--gamut-preview.netlify.app>https://6101762ea9026c220c13c44a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6101762ea9026c220c13c44a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.4-alpha.e6aba6.0<br/>@codecademy/gamut-illustrations@0.17.13-alpha.e6aba6.0<br/>@codecademy/gamut-kit@0.5.3-alpha.e6aba6.0<br/>@codecademy/gamut-labs@19.16.15-alpha.e6aba6.0<br/>@codecademy/gamut-patterns@0.5.1-alpha.e6aba6.0<br/>@codecademy/gamut-styles@11.6.3-alpha.e6aba6.0<br/>@codecademy/gamut-tests@2.4.16-alpha.e6aba6.0<br/>@codecademy/gamut@35.4.3-alpha.e6aba6.0<br/>@codecademy/konamimojisplosion@0.2.47-alpha.e6aba6.0<br/>@codecademy/markdown-overrides@0.5.59-alpha.e6aba6.0<br/>@codecademy/monaco@0.1.0-alpha.e6aba6.0<br/>@codecademy/styleguide@42.3.3-alpha.e6aba6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61018852a0e4df40fd0212bd--gamut-preview.netlify.app>https://61018852a0e4df40fd0212bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61018852a0e4df40fd0212bd>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.4-alpha.35298d.0<br/>@codecademy/gamut-illustrations@0.17.13-alpha.35298d.0<br/>@codecademy/gamut-kit@0.5.3-alpha.35298d.0<br/>@codecademy/gamut-labs@19.16.15-alpha.35298d.0<br/>@codecademy/gamut-patterns@0.5.1-alpha.35298d.0<br/>@codecademy/gamut-styles@11.6.3-alpha.35298d.0<br/>@codecademy/gamut-tests@2.4.16-alpha.35298d.0<br/>@codecademy/gamut@35.4.3-alpha.35298d.0<br/>@codecademy/konamimojisplosion@0.2.47-alpha.35298d.0<br/>@codecademy/markdown-overrides@0.5.59-alpha.35298d.0<br/>@codecademy/styleguide@42.3.3-alpha.35298d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6102b61b3969162d41cd960f--gamut-preview.netlify.app>https://6102b61b3969162d41cd960f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6102b61b3969162d41cd960f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.7.4-alpha.19bf21.0<br/>@codecademy/gamut-illustrations@0.17.13-alpha.19bf21.0<br/>@codecademy/gamut-kit@0.5.3-alpha.19bf21.0<br/>@codecademy/gamut-labs@19.16.15-alpha.19bf21.0<br/>@codecademy/gamut-patterns@0.5.1-alpha.19bf21.0<br/>@codecademy/gamut-styles@11.6.3-alpha.19bf21.0<br/>@codecademy/gamut-tests@2.4.16-alpha.19bf21.0<br/>@codecademy/gamut@35.4.3-alpha.19bf21.0<br/>@codecademy/konamimojisplosion@0.2.47-alpha.19bf21.0<br/>@codecademy/markdown-overrides@0.5.59-alpha.19bf21.0<br/>@codecademy/styleguide@42.3.3-alpha.19bf21.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6102b9bb61c2711f63501695--gamut-preview.netlify.app>https://6102b9bb61c2711f63501695--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6102b9bb61c2711f63501695>Deploy Logs</a></p>

**Pull request merged**
