### PR TITLE
feat: added new Target illustration

### PR DESCRIPTION
**Pull request by sylvanasantos**
### Overview

Added a new Target illustration

### PR Checklist

- [ ] Related to designs: [figma](https://www.figma.com/file/E7CZLBi8CNgovH5mN1ivZz/Concept-Refinement?node-id=125%3A597)
- [ ] Related to JIRA ticket: EGG-1013
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.8.0-alpha.64c269.0<br/>@codecademy/gamut-illustrations@0.9.15-alpha.64c269.0<br/>@codecademy/gamut-kit@0.3.31-alpha.64c269.0<br/>@codecademy/gamut-labs@13.5.8-alpha.64c269.0<br/>@codecademy/gamut@31.0.2-alpha.64c269.0<br/>@codecademy/styleguide@35.0.5-alpha.64c269.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607da451cc29ab00b9c7ec01--gamut-preview.netlify.app>https://607da451cc29ab00b9c7ec01--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607da451cc29ab00b9c7ec01>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, thanks!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.15-alpha.b6249a.0<br/>@codecademy/gamut-kit@0.3.32-alpha.b6249a.0<br/>@codecademy/gamut-labs@13.5.9-alpha.b6249a.0<br/>@codecademy/gamut@31.0.3-alpha.b6249a.0<br/>@codecademy/styleguide@35.0.6-alpha.b6249a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607daab46fccfc00aef2ecec--gamut-preview.netlify.app>https://607daab46fccfc00aef2ecec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607daab46fccfc00aef2ecec>Deploy Logs</a></p>

**Pull request merged**
