### PR TITLE
chore(ContentContainer): Convert ContentContainer to variance API [GM-206]

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

Variance Migration Board: https://www.notion.so/codecademy/Variance-Migration-a675bbc31b584fec9dfff72c0364b194

Changes:
* Updates internal variant API to new library.  This is a functionality no op.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GM-206
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.33-alpha.e146e5.0<br/>@codecademy/gamut-labs@13.5.10-alpha.e146e5.0<br/>@codecademy/gamut@31.0.4-alpha.e146e5.0<br/>@codecademy/styleguide@35.0.7-alpha.e146e5.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]
👌

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607dafd1ff290a00c563e79e--gamut-preview.netlify.app>https://607dafd1ff290a00c563e79e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607dafd1ff290a00c563e79e>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.34-alpha.3ac36b.0<br/>@codecademy/gamut-labs@13.5.11-alpha.3ac36b.0<br/>@codecademy/gamut@31.0.5-alpha.3ac36b.0<br/>@codecademy/styleguide@35.0.8-alpha.3ac36b.0<br/></pre>

**Pull request merged**
