### PR TITLE
fix(Notification): Remove moment from notification and remove rendundancies WEB-1093

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview

- Removes time formatting from Notification and removes moment as a dependency. 
- Gets rid of redundant features like `maxNotifications` and other date formatting in favor of app configuration.

Monolith Update: https://github.com/codecademy-engineering/Codecademy/pull/20274#partial-pull-merging

PR Env: https://pr-20274.dev-eks.codecademy.com

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: WEB-1093
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.3.3-alpha.0b74c6.0<br/>@codecademy/gamut@17.3.9-alpha.0b74c6.0<br/>@codecademy/styleguide@18.5.9-alpha.0b74c6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb410bba6dbdd6978b05c45--gamut-preview.netlify.app>https://5fb410bba6dbdd6978b05c45--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb410bba6dbdd6978b05c45>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.3.3-alpha.d4c78e.0<br/>@codecademy/gamut@17.3.9-alpha.d4c78e.0<br/>@codecademy/styleguide@18.5.9-alpha.d4c78e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb41356d1e3126ef5199ff5--gamut-preview.netlify.app>https://5fb41356d1e3126ef5199ff5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb41356d1e3126ef5199ff5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb43b991155320d67335131--gamut-preview.netlify.app>https://5fb43b991155320d67335131--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb43b991155320d67335131>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.3.3-alpha.6f160d.0<br/>@codecademy/gamut@17.3.9-alpha.6f160d.0<br/>@codecademy/styleguide@18.5.9-alpha.6f160d.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.3-alpha.bfd18b.0<br/>@codecademy/gamut@17.4.1-alpha.bfd18b.0<br/>@codecademy/styleguide@18.10.2-alpha.bfd18b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fbbc7653917fddc2f11a565--gamut-preview.netlify.app>https://5fbbc7653917fddc2f11a565--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fbbc7653917fddc2f11a565>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.4-alpha.b8077d.0<br/>@codecademy/gamut@17.4.2-alpha.b8077d.0<br/>@codecademy/styleguide@18.10.3-alpha.b8077d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fbd45fc88faa4010350b586--gamut-preview.netlify.app>https://5fbd45fc88faa4010350b586--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fbd45fc88faa4010350b586>Deploy Logs</a></p>

**Pull request merged**
