### PR TITLE
feat: add Keyhole illustration

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

add Keyhole illustration for use on private profile page

for use in this PR: https://github.com/codecademy-engineering/Codecademy/pull/24726

### PR Checklist

- [ ] Related to designs: [figma](https://www.figma.com/file/PG0kVYDIuLk3hE566beZUV/Profiles-(Concept-Refinement)?node-id=998%3A0)
- [ ] Related to JIRA ticket: EGG-1176
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

Screen Shot 2021-05-25 at 11 02 51 AM

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.16.0-alpha.0f9fcd.0<br/>@codecademy/gamut-kit@0.3.113-alpha.0f9fcd.0<br/>@codecademy/gamut-labs@18.1.4-alpha.0f9fcd.0<br/>@codecademy/gamut@33.0.1-alpha.0f9fcd.0<br/>@codecademy/styleguide@40.0.1-alpha.0f9fcd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ad0d411d1eca009faa6273--gamut-preview.netlify.app>https://60ad0d411d1eca009faa6273--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ad0d411d1eca009faa6273>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.16.0-alpha.e1cde2.0<br/>@codecademy/gamut-kit@0.3.113-alpha.e1cde2.0<br/>@codecademy/gamut-labs@18.1.4-alpha.e1cde2.0<br/>@codecademy/gamut@33.0.1-alpha.e1cde2.0<br/>@codecademy/styleguide@40.0.1-alpha.e1cde2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ad15845a59140dfe439ba0--gamut-preview.netlify.app>https://60ad15845a59140dfe439ba0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ad15845a59140dfe439ba0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.16.0-alpha.701acc.0<br/>@codecademy/gamut-kit@0.3.114-alpha.701acc.0<br/>@codecademy/gamut-labs@18.1.5-alpha.701acc.0<br/>@codecademy/gamut@33.1.1-alpha.701acc.0<br/>@codecademy/styleguide@40.0.2-alpha.701acc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ad6b452801dc00eaf53614--gamut-preview.netlify.app>https://60ad6b452801dc00eaf53614--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ad6b452801dc00eaf53614>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.16.0-alpha.299183.0<br/>@codecademy/gamut-kit@0.3.115-alpha.299183.0<br/>@codecademy/gamut-labs@18.1.6-alpha.299183.0<br/>@codecademy/gamut@33.1.2-alpha.299183.0<br/>@codecademy/styleguide@40.0.3-alpha.299183.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ad6d794c2b0400da93dca1--gamut-preview.netlify.app>https://60ad6d794c2b0400da93dca1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ad6d794c2b0400da93dca1>Deploy Logs</a></p>

**Pull request merged**
