### PR TITLE
fix(Styleguide): Remove markdown knob from showing up everywhere

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview

Markdown knobs would sometimes show up on erroneous stories.  This converts it to args to prevent it from happening.

Screen Shot 2020-11-17 at 10 40 09 AM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.9-alpha.ce76a4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3fe363757b55b1b149009--gamut-preview.netlify.app>https://5fb3fe363757b55b1b149009--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3fe363757b55b1b149009>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.7.1-alpha.70cb98.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb6a722f8648707d555e046--gamut-preview.netlify.app>https://5fb6a722f8648707d555e046--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb6a722f8648707d555e046>Deploy Logs</a></p>

**Pull request merged**
