### PR TITLE
fix: remove fill color from ArrowChevronDownFilledIcon

### PR DESCRIPTION
**Pull request by natalieweesh**
## Overview
remove fill and stroke color from ArrowChevronDownFilledIcon svg so that it can change color based on css color property

needed for Codecademy-engineering/Codecademy#19905 

### PR Checklist

- [ ] Related to designs: [figma](https://www.figma.com/file/7PNKwpTpXjRrPjcCRSu215/Global-Nav?node-id=899%3A100)
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
Screen Shot 2020-11-05 at 10 49 26 AM

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.10.1-alpha.4c63c4.0<br/>@codecademy/gamut-labs@4.7.3-alpha.4c63c4.0<br/>@codecademy/gamut@16.4.3-alpha.4c63c4.0<br/>@codecademy/styleguide@17.11.3-alpha.4c63c4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa41fb26ff11d9f3af3f3df--gamut-preview.netlify.app>https://5fa41fb26ff11d9f3af3f3df--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa41fb26ff11d9f3af3f3df>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.10.1-alpha.5c15fb.0<br/>@codecademy/gamut-labs@4.8.0-alpha.5c15fb.0<br/>@codecademy/gamut@16.4.3-alpha.5c15fb.0<br/>@codecademy/styleguide@17.12.0-alpha.5c15fb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa45fbc2e5aa3114261f9d8--gamut-preview.netlify.app>https://5fa45fbc2e5aa3114261f9d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa45fbc2e5aa3114261f9d8>Deploy Logs</a></p>

**Review by saghdaey — APPROVED** [review]

**Pull request merged**
