### PR TITLE
fix(styleguide): Enable no jsx-no-undef on mdx

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview
A few little buggers.

* Re-enables no undef for *.mdx

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.2-alpha.bc8fb4.0<br/>@codecademy/styleguide@21.15.4-alpha.bc8fb4.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]
trrue

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6008505cdcb7bc3a54a4e581--gamut-preview.netlify.app>https://6008505cdcb7bc3a54a4e581--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6008505cdcb7bc3a54a4e581>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.2-alpha.057d32.0<br/>@codecademy/styleguide@21.15.4-alpha.057d32.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.2-alpha.28e56a.0<br/>@codecademy/styleguide@21.15.5-alpha.28e56a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6008557f6abe3731fc356fa9--gamut-preview.netlify.app>https://6008557f6abe3731fc356fa9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6008557f6abe3731fc356fa9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.2-alpha.057369.0<br/>@codecademy/styleguide@21.15.6-alpha.057369.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60085d72e474c633010d0c59--gamut-preview.netlify.app>https://60085d72e474c633010d0c59--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60085d72e474c633010d0c59>Deploy Logs</a></p>

**Pull request merged**
