### PR TITLE
fix: adding aria-required for required GridForm fields

### PR DESCRIPTION
**Pull request by vonbarown**
### Overview

 Adding ``aria-required`` to required GridForm fields to improve accessibility 

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [GM-199](https://codecademy.atlassian.net/browse/GM-199) 
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6077276fdb38910a9fe7753a--gamut-preview.netlify.app>https://6077276fdb38910a9fe7753a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6077276fdb38910a9fe7753a>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks! 🌮

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.19-alpha.a72b65.0<br/>@codecademy/gamut-labs@13.4.11-alpha.a72b65.0<br/>@codecademy/gamut@29.9.9-alpha.a72b65.0<br/>@codecademy/styleguide@33.9.11-alpha.a72b65.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.19-alpha.2d7376.0<br/>@codecademy/gamut-labs@13.4.11-alpha.2d7376.0<br/>@codecademy/gamut@29.9.9-alpha.2d7376.0<br/>@codecademy/styleguide@33.9.11-alpha.2d7376.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
beautiful

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60773775a4daa617f2a3c29c--gamut-preview.netlify.app>https://60773775a4daa617f2a3c29c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60773775a4daa617f2a3c29c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.19-alpha.ba56fd.0<br/>@codecademy/gamut-labs@13.4.11-alpha.ba56fd.0<br/>@codecademy/gamut@29.9.9-alpha.ba56fd.0<br/>@codecademy/styleguide@33.9.11-alpha.ba56fd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607745073c9a692eba80fd22--gamut-preview.netlify.app>https://607745073c9a692eba80fd22--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607745073c9a692eba80fd22>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.24-alpha.26f0ae.0<br/>@codecademy/gamut-labs@13.5.1-alpha.26f0ae.0<br/>@codecademy/gamut@30.1.1-alpha.26f0ae.0<br/>@codecademy/styleguide@34.2.1-alpha.26f0ae.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60783b098d9ebb01f20b26cb--gamut-preview.netlify.app>https://60783b098d9ebb01f20b26cb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60783b098d9ebb01f20b26cb>Deploy Logs</a></p>

**Pull request merged**
