### PR TITLE
feat(Icons): Add initial streamline icons

### PR DESCRIPTION
**Pull request by codecaaron**
## Initial Streamline Icon map.

This is used for the new notification standard.

Icons used:
```
check-circle-1
remove-circle
information-circle
alert-triangle
rating-star-circle
close
arrow-up-1
arrow-down-1
```
Icons mapped:
- All Arrow Chevrons
- Close Icon

New Icons Added:
- InfoCircle
- CheckCircle
- RemoveCircle
- StarCircle

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@2.2.2-alpha.ef2fd6.0<br/></pre>

**Comment by codecaaron** [comment]
The direct 1:1 mappings are being tracked here: https://docs.google.com/spreadsheets/d/1RweMak-8XrdG-lI-EOsL7QqCGvmTJ_mcaNIgCSf71rI/edit#gid=0

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e8c926a3e0f6e021ffaa8f8--codecademy-styleguide.netlify.com>https://5e8c926a3e0f6e021ffaa8f8--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e8c926a3e0f6e021ffaa8f8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@2.2.2-alpha.e6454c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e8f568f9e8a85ccf746313a--codecademy-styleguide.netlify.com>https://5e8f568f9e8a85ccf746313a--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e8f568f9e8a85ccf746313a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@2.2.3-alpha.fcfd4b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e99c158c690ed58603d5107--codecademy-styleguide.netlify.app>https://5e99c158c690ed58603d5107--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e99c158c690ed58603d5107>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@2.2.3-alpha.8a8cc4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e9da7a15b6d1288beaa4a6b--codecademy-styleguide.netlify.app>https://5e9da7a15b6d1288beaa4a6b--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e9da7a15b6d1288beaa4a6b>Deploy Logs</a></p>

**Pull request merged**
