### PR TITLE
feat(Header)!: reroute header upsell for upgrade

### PR DESCRIPTION
**Pull request by borisonr**
### Overview

This leverages the checkout url both for trial and non-trial upsells in the header (tryProForFree and upgradeToPro) instead of routing upgradeToPro to the pro membership landing page

integration branches: https://github.com/codecademy-engineering/Codecademy/pull/24432, https://github.com/codecademy-engineering/static-sites/pull/776, https://github.com/codecademy-engineering/portal-app/pull/40

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [GROW-2331](https://codecademy.atlassian.net/browse/GROW-2331)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
+ Egg friends who worked on the header :)

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.0b9402.0<br/>@codecademy/gamut-labs@16.0.2-alpha.0b9402.0<br/>@codecademy/styleguide@37.5.5-alpha.0b9402.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c169890061b0f94e33721--gamut-preview.netlify.app>https://609c169890061b0f94e33721--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c169890061b0f94e33721>Deploy Logs</a></p>

**Comment by borisonr** [comment]
sorry wasn't ready for review yet just wanted to test it out with an alpha!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.2879cd.0<br/>@codecademy/gamut-labs@16.0.2-alpha.2879cd.0<br/>@codecademy/styleguide@37.5.5-alpha.2879cd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c1b2cd984a500c65f3f9d--gamut-preview.netlify.app>https://609c1b2cd984a500c65f3f9d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c1b2cd984a500c65f3f9d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.221380.0<br/>@codecademy/gamut-labs@16.0.2-alpha.221380.0<br/>@codecademy/styleguide@37.5.5-alpha.221380.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM from a web plat perspective. Maybe someone from engagement might care?

**Review by zippyzow — APPROVED** [review]
Looks good and seeing `proCheckoutUrl` in [netlify preview](proCheckoutUrl) as well 👍

**Review by saghdaey — APPROVED** [review]
awesome

**Review by dreamwasp — APPROVED** [review]
🙌

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.101-alpha.782ef4.0<br/>@codecademy/gamut-labs@16.0.6-alpha.782ef4.0<br/>@codecademy/styleguide@37.5.9-alpha.782ef4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e78a2c6e80d11787c8d9d--gamut-preview.netlify.app>https://609e78a2c6e80d11787c8d9d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e78a2c6e80d11787c8d9d>Deploy Logs</a></p>

**Pull request merged**
