### PR TITLE
feat: add social media icons and update target illustration

### PR DESCRIPTION
**Pull request by sylvanasantos**
### Overview

- added new outline icons for twitter, github, and linkedin
- updated the Target illustration to have a fill color

Note: used in [this](https://github.com/codecademy-engineering/Codecademy/pull/24191) pr

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.0-alpha.a848f0.0<br/>@codecademy/gamut-illustrations@0.12.0-alpha.a848f0.0<br/>@codecademy/gamut-kit@0.3.67-alpha.a848f0.0<br/>@codecademy/gamut-labs@15.2.7-alpha.a848f0.0<br/>@codecademy/gamut@32.7.4-alpha.a848f0.0<br/>@codecademy/styleguide@36.9.4-alpha.a848f0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090067a6d46a100bc4e8d8b--gamut-preview.netlify.app>https://6090067a6d46a100bc4e8d8b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090067a6d46a100bc4e8d8b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.0-alpha.498ba9.0<br/>@codecademy/gamut-illustrations@0.12.0-alpha.498ba9.0<br/>@codecademy/gamut-kit@0.3.67-alpha.498ba9.0<br/>@codecademy/gamut-labs@15.2.7-alpha.498ba9.0<br/>@codecademy/gamut@32.7.4-alpha.498ba9.0<br/>@codecademy/styleguide@36.9.4-alpha.498ba9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609008e36d46a100d14e8e40--gamut-preview.netlify.app>https://609008e36d46a100d14e8e40--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609008e36d46a100d14e8e40>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.0-alpha.5ebbf4.0<br/>@codecademy/gamut-illustrations@0.12.0-alpha.5ebbf4.0<br/>@codecademy/gamut-kit@0.3.67-alpha.5ebbf4.0<br/>@codecademy/gamut-labs@15.2.7-alpha.5ebbf4.0<br/>@codecademy/gamut@32.7.4-alpha.5ebbf4.0<br/>@codecademy/styleguide@36.9.4-alpha.5ebbf4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60900ef837184400b0a461cf--gamut-preview.netlify.app>https://60900ef837184400b0a461cf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60900ef837184400b0a461cf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.0-alpha.e65ace.0<br/>@codecademy/gamut-illustrations@0.12.0-alpha.e65ace.0<br/>@codecademy/gamut-kit@0.3.67-alpha.e65ace.0<br/>@codecademy/gamut-labs@15.2.7-alpha.e65ace.0<br/>@codecademy/gamut@32.7.4-alpha.e65ace.0<br/>@codecademy/styleguide@36.9.4-alpha.e65ace.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609027f47efda3008d40cd46--gamut-preview.netlify.app>https://609027f47efda3008d40cd46--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609027f47efda3008d40cd46>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.9.0-alpha.3af4f1.0<br/>@codecademy/gamut-illustrations@0.13.0-alpha.3af4f1.0<br/>@codecademy/gamut-kit@0.3.68-alpha.3af4f1.0<br/>@codecademy/gamut-labs@15.2.8-alpha.3af4f1.0<br/>@codecademy/gamut@32.8.1-alpha.3af4f1.0<br/>@codecademy/styleguide@36.10.1-alpha.3af4f1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60902e19d64d8d008d787667--gamut-preview.netlify.app>https://60902e19d64d8d008d787667--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60902e19d64d8d008d787667>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Pull request merged**
