### PR TITLE
chore: bumped eslint-config dependencies and TypeScript to latest

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### PR Checklist

- ~[ ] Related to Abstract designs:~
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

TypeScript 4 is not supported in the old version of `@typescript-eslint/parser` we're using, as the AST has changed: https://app.circleci.com/pipelines/github/codecademy-engineering/Codecademy/49329/workflows/ac8b16fa-d05e-4c94-8339-2432b1a4845e/jobs/797082

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.0.1-alpha.3ba36e.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.0.1-alpha.390e4e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6cb975a6b26401297a403f--gamut-preview.netlify.app>https://5f6cb975a6b26401297a403f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6cb975a6b26401297a403f>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
Closing in favor of #968; will reopen another more targeted PR or two after that lands

**Pull request closed without merging**
