### PR TITLE
fix: fixes an a11y bug in the MenuItem component

### PR DESCRIPTION
**Pull request by saghdaey**
## Overview

This is part of EGG-167, which addressed a11y problems in the delete account page & updated the UI of the page. Most of the ticket requirements of EGG-167 were handled in a PR to the monolith which has already been approved + merged.

This is specifically the work fo [A11Y-427 ](https://codecademy.atlassian.net/browse/A11Y-427), the third ticket linked to EGG-167 which addresses an a11y issue on the side menu of the account pages.

I used aria-label on the list item element to add "current page" so that when tabbing thru the page w/ voice over on, you know which page is selected. 

To test, I set up my local copy of the monolith to use my local gamut build following the instructions on the client-modules repo. I tried a few different things like "aria-selected" (which is more for inputs) & "aria-current" (which doesn't seem to be widely supported), before settling on adding an "aria-label" to the list item.
I also tried using gamut's Hidden Text component but it was not read by the screen reader.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: EGG-167
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.1-alpha.e5fca1.0<br/>@codecademy/gamut@17.2.1-alpha.e5fca1.0<br/>@codecademy/styleguide@18.3.1-alpha.e5fca1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fab3a03d221eb527b2c61aa--gamut-preview.netlify.app>https://5fab3a03d221eb527b2c61aa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fab3a03d221eb527b2c61aa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.2-alpha.9d12fe.0<br/>@codecademy/gamut@17.3.1-alpha.9d12fe.0<br/>@codecademy/styleguide@18.4.2-alpha.9d12fe.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fab3b689713dd561b99d009--gamut-preview.netlify.app>https://5fab3b689713dd561b99d009--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fab3b689713dd561b99d009>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.2-alpha.613342.0<br/>@codecademy/gamut@17.3.1-alpha.613342.0<br/>@codecademy/styleguide@18.5.1-alpha.613342.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fad798be45a686f7977d976--gamut-preview.netlify.app>https://5fad798be45a686f7977d976--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fad798be45a686f7977d976>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — COMMENTED** [review]
My Macbook is broken so I can't verify with VoiceOver -- but when I try on Windows with its built-in Narrator, the `current page` doesn't get narrated. My guess is that the `As` should get the `aria-label` because it's the link?

**Comment by saghdaey** [comment]
> My Macbook is broken so I can't verify with VoiceOver -- but when I try on Windows with its built-in Narrator, the `current page` doesn't get narrated. My guess is that the `As` should get the `aria-label` because it's the link?

I ended up putting it on the <li> because putting  it on the 'As' overrode the default aria-label of the link (that were not actually setting in the MenuItem component)

here's a screenshot from what it looks like (without my changes) in staging --> 
Screen Shot 2020-11-12 at 2 02 20 PM

**Review by JoshuaKGoldberg — DISMISSED** [review]
In that case, awesome, lgtm!

**Review by JoshuaKGoldberg — APPROVED** [review]
Talking on Slack - we're good after all :)

**Comment by saghdaey** [comment]
Ok I read we shouldn't use aria-label on an ListItem: 
"Don't use aria-label or aria-labelledby on any other non-interactive content such as p, legend, li, or ul, because it is ignored."
https://www.w3.org/TR/using-aria/#label-support 

So Instead, I tried passing in the aria-label as part of the "asProps" but that also didn't work --> 

top window = gamut MenuItem, 
bottom window = AccountMenu in the monolith
it assigns to asProps.ariaLabel what I would like the aria-label to be on the link. 
menu item receives that and should be assigning it to "aria-label" on line 43 in the top window

see Warning in the terminal (on the right): "Invalid ARIA attribute 'ariaLabel'. Did you mean 'aria-label'? 

Screen Shot 2020-11-12 at 5 09 44 PM

**Review by JoshuaKGoldberg — APPROVED** [review]
Although it's a little odd having a separate `ariaLabel` prop when `asProps` can exist, we're going to clean this all up to be CSS-in-JS anyway so whoop, let's ship this!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.2.5-alpha.204f7e.0<br/>@codecademy/gamut@17.3.4-alpha.204f7e.0<br/>@codecademy/styleguide@18.5.4-alpha.204f7e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5faeb8cda60d6821b84e7ade--gamut-preview.netlify.app>https://5faeb8cda60d6821b84e7ade--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5faeb8cda60d6821b84e7ade>Deploy Logs</a></p>

**Pull request merged**
