### PR TITLE
ci: use conventionalcommits instead of angular

### PR DESCRIPTION
**Pull request by jakemhiller**
allows us to use the new `feat!: message` syntax for breaking changes

---

## Merging your changes

When you are ready to merge to master, use the "squash and merge" button in GitHub, and follow the [commit message guide](/README.md#commit-message-guide) to write your commit message.

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e867494f5845870cbbe1661--codecademy-styleguide.netlify.com>https://5e867494f5845870cbbe1661--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e867494f5845870cbbe1661>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e87532c4142b217885d7108--codecademy-styleguide.netlify.com>https://5e87532c4142b217885d7108--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e87532c4142b217885d7108>Deploy Logs</a></p>

**Comment by jakemhiller** [comment]
@JoshuaKGoldberg yes, and i'll change the readme in this PR

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e875c4e93e79d9773c1da05--codecademy-styleguide.netlify.com>https://5e875c4e93e79d9773c1da05--codecademy-styleguide.netlify.com</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e875c4e93e79d9773c1da05>Deploy Logs</a></p>

**Pull request merged**
