### PR TITLE
fix: refine landing page ui

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview
per feedback from Dev (and slack discussion last week), this PR includes the following:
* remove component margins + paddings
* make hero always render h1
* give Title and Description a default max width

### PR Checklist

- [x] Related to designs: [these'ns](gma.com/file/2aBlW1pgFt5PT6soRu1HXy/✏%EF%B8%8F-Landing-Page-Templates---Unification?node-id=1%3A43)
- [x] Related to JIRA ticket: [REACH-449](https://codecademy.atlassian.net/browse/REACH-449)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Okie dokie!

**Review by rogervera — APPROVED** [review]
LGTM, ran locally

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.2-alpha.b1d22b.0<br/>@codecademy/gamut@19.0.2-alpha.b1d22b.0<br/>@codecademy/styleguide@21.0.2-alpha.b1d22b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7dd69f041f9ce79020d50--gamut-preview.netlify.app>https://5fc7dd69f041f9ce79020d50--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7dd69f041f9ce79020d50>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.3-alpha.ba72a4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc7e596328be6f47d6af1bc--gamut-preview.netlify.app>https://5fc7e596328be6f47d6af1bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc7e596328be6f47d6af1bc>Deploy Logs</a></p>

**Pull request merged**
