### PR TITLE
fix(ToolTip): A11y Updates (revert of revert)

### PR DESCRIPTION
**Pull request by rogervera**
### Overview
Keyboard-only users were not able to activate the tooltip. Screenreader users did not have the tooltip narrated to them.

Change `focus` to  `focus-within` & adds `aria-live: polite` for ToolTip contents.
Removes storybook comment on non-clickable elements allowed within.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: REACH-774
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Testing
1. Turn on VoiceOver on Mac (or ChromeVox extension for Chrome/any alternative)
2. https://606dbfd55f00601ac8e7c74b--gamut-preview.netlify.app/storybook/?path=/docs/atoms-tooltip--tool-tip
3. Keyboard nav to over the tooltips

Screen Shot 2021-04-07 at 10 29 24 AM

________
### Note
I moved too fast on the original PR and merged https://github.com/Codecademy/client-modules/pull/1604 before getting input from all teams requested! My mistake.

Reverts Codecademy/client-modules#1605 which reverts https://github.com/Codecademy/client-modules/pull/1604

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.4-alpha.c14a61.0<br/>@codecademy/gamut-labs@13.3.4-alpha.c14a61.0<br/>@codecademy/gamut@29.8.4-alpha.c14a61.0<br/>@codecademy/styleguide@33.7.5-alpha.c14a61.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606dd70017c3fc00c0ce9f0e--gamut-preview.netlify.app>https://606dd70017c3fc00c0ce9f0e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606dd70017c3fc00c0ce9f0e>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
My approval still holds 😛 , thanks for going back on the merge & looking for more feedback!

**Review by dreamwasp — APPROVED** [review]
i love this!!! only change i'd suggest is adding `aria-hidden` to the actual info icon so that it doesn't get read out loud after the tooltip explanation but not a blocker

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.5-alpha.cb1956.0<br/>@codecademy/gamut-labs@13.3.5-alpha.cb1956.0<br/>@codecademy/gamut@29.9.1-alpha.cb1956.0<br/>@codecademy/styleguide@33.8.1-alpha.cb1956.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606f1e9851d5c6f23e564471--gamut-preview.netlify.app>https://606f1e9851d5c6f23e564471--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606f1e9851d5c6f23e564471>Deploy Logs</a></p>

**Pull request merged**
