### PR TITLE
chore(deps): Emotion Dependency clean up

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview

* Removes unneeded dev dependencies and sets it for the workspace.
* Updates standard peer version requirements to latest.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.11.1-alpha.285b71.0<br/>@codecademy/gamut-illustrations@0.14.1-alpha.285b71.0<br/>@codecademy/gamut-kit@0.3.84-alpha.285b71.0<br/>@codecademy/gamut-labs@15.6.1-alpha.285b71.0<br/>@codecademy/gamut-patterns@0.1.1-alpha.285b71.0<br/>@codecademy/gamut-styles@9.8.1-alpha.285b71.0<br/>@codecademy/gamut-system@0.7.2-alpha.285b71.0<br/>@codecademy/gamut-tests@2.3.28-alpha.285b71.0<br/>@codecademy/gamut@32.14.1-alpha.285b71.0<br/>@codecademy/konamimojisplosion@0.2.28-alpha.285b71.0<br/>@codecademy/markdown-overrides@0.5.40-alpha.285b71.0<br/>@codecademy/styleguide@37.0.2-alpha.285b71.0<br/>@codecademy/variance@0.11.2-alpha.285b71.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60940a8707adc912fdcb38d3--gamut-preview.netlify.app>https://60940a8707adc912fdcb38d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60940a8707adc912fdcb38d3>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
okie dokie

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.11.1-alpha.d8c191.0<br/>@codecademy/gamut-illustrations@0.14.1-alpha.d8c191.0<br/>@codecademy/gamut-kit@0.3.86-alpha.d8c191.0<br/>@codecademy/gamut-labs@15.7.1-alpha.d8c191.0<br/>@codecademy/gamut-patterns@0.1.1-alpha.d8c191.0<br/>@codecademy/gamut-styles@9.8.1-alpha.d8c191.0<br/>@codecademy/gamut-system@0.7.2-alpha.d8c191.0<br/>@codecademy/gamut-tests@2.3.28-alpha.d8c191.0<br/>@codecademy/gamut@32.15.1-alpha.d8c191.0<br/>@codecademy/konamimojisplosion@0.2.28-alpha.d8c191.0<br/>@codecademy/markdown-overrides@0.5.40-alpha.d8c191.0<br/>@codecademy/styleguide@37.1.2-alpha.d8c191.0<br/>@codecademy/variance@0.11.2-alpha.d8c191.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.11.1-alpha.eece80.0<br/>@codecademy/gamut-illustrations@0.14.1-alpha.eece80.0<br/>@codecademy/gamut-kit@0.3.86-alpha.eece80.0<br/>@codecademy/gamut-labs@15.7.1-alpha.eece80.0<br/>@codecademy/gamut-patterns@0.1.1-alpha.eece80.0<br/>@codecademy/gamut-styles@9.8.1-alpha.eece80.0<br/>@codecademy/gamut-system@0.7.2-alpha.eece80.0<br/>@codecademy/gamut-tests@2.3.28-alpha.eece80.0<br/>@codecademy/gamut@32.15.1-alpha.eece80.0<br/>@codecademy/konamimojisplosion@0.2.28-alpha.eece80.0<br/>@codecademy/markdown-overrides@0.5.40-alpha.eece80.0<br/>@codecademy/styleguide@37.1.2-alpha.eece80.0<br/>@codecademy/variance@0.11.2-alpha.eece80.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60956da501560280e53f5844--gamut-preview.netlify.app>https://60956da501560280e53f5844--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60956da501560280e53f5844>Deploy Logs</a></p>

**Pull request merged**
