### PR TITLE
fix: allow override of tooltip alignment

### PR DESCRIPTION
**Pull request by borisonr**
### Overview

we want to be able to override the alignment of a tooltip in a gridform field

integration pr: codecademy-engineering/Codecademy#24641
was having lerna issues in the original pr so im trying it again... (this time i pulled main before creating the new branch... third times a charm?)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a7ff1027af87118b5b5280--gamut-preview.netlify.app>https://60a7ff1027af87118b5b5280--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a7ff1027af87118b5b5280>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60abaae55c027b009cd64fb6--gamut-preview.netlify.app>https://60abaae55c027b009cd64fb6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60abaae55c027b009cd64fb6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.1-alpha.04e034.0<br/>@codecademy/gamut-illustrations@0.15.1-alpha.04e034.0<br/>@codecademy/gamut-kit@0.3.111-alpha.04e034.0<br/>@codecademy/gamut-labs@18.1.2-alpha.04e034.0<br/>@codecademy/gamut-patterns@0.2.1-alpha.04e034.0<br/>@codecademy/gamut-styles@10.1.1-alpha.04e034.0<br/>@codecademy/gamut-tests@2.4.1-alpha.04e034.0<br/>@codecademy/gamut@32.20.1-alpha.04e034.0<br/>@codecademy/konamimojisplosion@0.2.32-alpha.04e034.0<br/>@codecademy/markdown-overrides@0.5.44-alpha.04e034.0<br/>@codecademy/styleguide@39.0.4-alpha.04e034.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60abad2827d1e300d23fac7e--gamut-preview.netlify.app>https://60abad2827d1e300d23fac7e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60abad2827d1e300d23fac7e>Deploy Logs</a></p>

**Pull request merged**
