### PR TITLE
chore(BrandMono)!: Remove Roboto Mono in favor of using Suisse 

### PR DESCRIPTION
**Pull request by codecaaron**
### Overview
Slack thread: https://codecademy.slack.com/archives/C02FUTRDX/p1611861691004600
Codecademy PR: https://github.com/codecademy-engineering/Codecademy/pull/21736

* Removes unused component

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.5-alpha.a4b2df.0<br/>@codecademy/styleguide@22.0.4-alpha.a4b2df.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60133a6951f4170148b91ddc--gamut-preview.netlify.app>https://60133a6951f4170148b91ddc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60133a6951f4170148b91ddc>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
🌮

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.6-alpha.b9ad34.0<br/>@codecademy/gamut-labs@8.0.3-alpha.b9ad34.0<br/>@codecademy/styleguide@23.1.1-alpha.b9ad34.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601835010d53121c347c557b--gamut-preview.netlify.app>https://601835010d53121c347c557b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601835010d53121c347c557b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.25-alpha.b43388.0<br/>@codecademy/gamut-labs@8.3.2-alpha.b43388.0<br/>@codecademy/gamut@21.2.2-alpha.b43388.0<br/>@codecademy/styleguide@24.2.4-alpha.b43388.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c144bfabeb23c0f38e8cf--gamut-preview.netlify.app>https://601c144bfabeb23c0f38e8cf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c144bfabeb23c0f38e8cf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.3.4-alpha.97e51c.0<br/>@codecademy/styleguide@24.2.6-alpha.97e51c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c24abf69c1a5b18a72901--gamut-preview.netlify.app>https://601c24abf69c1a5b18a72901--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c24abf69c1a5b18a72901>Deploy Logs</a></p>

**Pull request merged**
