### PR TITLE
feat(modal): add aria-modal="true"

### PR DESCRIPTION
**Pull request by slin12**
### Overview

This PR adds the `aria-modal="true"` label to the modal card per recommendations here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html 

While on voiceover, this should now disallow voiceover users to access items behind the modal.
To see what's happening now, visit a modal (https://staging.codecademy.com/content-items/8468d948f32e506d7440adf1c004cce1), click on the task item, then with voiceover on use ctrl-option-left/right arrow to escape the modal. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: https://codecademy.atlassian.net/browse/LX-4514
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.5-alpha.df5990.0<br/>@codecademy/gamut@19.1.0-alpha.df5990.0<br/>@codecademy/styleguide@21.0.5-alpha.df5990.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc9464b6681a042b14923e4--gamut-preview.netlify.app>https://5fc9464b6681a042b14923e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc9464b6681a042b14923e4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.5-alpha.856db0.0<br/>@codecademy/gamut@19.1.0-alpha.856db0.0<br/>@codecademy/styleguide@21.0.5-alpha.856db0.0<br/></pre>

**Review by JoshuaKGoldberg — APPROVED** [review]
Tried this out and it works well for me - I'll defer to @jcenglish for any deep complex thoughts 😄

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc94a022aaaa100b16457a8--gamut-preview.netlify.app>https://5fc94a022aaaa100b16457a8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc94a022aaaa100b16457a8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.5-alpha.22c7f0.0<br/>@codecademy/gamut@19.1.0-alpha.22c7f0.0<br/>@codecademy/styleguide@21.0.5-alpha.22c7f0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc94ec801780e00bc195594--gamut-preview.netlify.app>https://5fc94ec801780e00bc195594--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc94ec801780e00bc195594>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.6-alpha.e6d376.0<br/>@codecademy/gamut@19.1.0-alpha.e6d376.0<br/>@codecademy/styleguide@21.0.6-alpha.e6d376.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc96348ef7da019fa33dfd8--gamut-preview.netlify.app>https://5fc96348ef7da019fa33dfd8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc96348ef7da019fa33dfd8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce52251d2e2100ee097378--gamut-preview.netlify.app>https://5fce52251d2e2100ee097378--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce52251d2e2100ee097378>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce558350852c0b7d2a7529--gamut-preview.netlify.app>https://5fce558350852c0b7d2a7529--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce558350852c0b7d2a7529>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce5a0c6d72810d49c466e8--gamut-preview.netlify.app>https://5fce5a0c6d72810d49c466e8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce5a0c6d72810d49c466e8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce5dfc563ea719e7fd58aa--gamut-preview.netlify.app>https://5fce5dfc563ea719e7fd58aa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce5dfc563ea719e7fd58aa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce60371d2e21138b096daa--gamut-preview.netlify.app>https://5fce60371d2e21138b096daa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce60371d2e21138b096daa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.11.2-alpha.c1da1c.0<br/>@codecademy/gamut-labs@7.0.6-alpha.c1da1c.0<br/>@codecademy/gamut-styles@7.5.1-alpha.c1da1c.0<br/>@codecademy/gamut-system@0.1.6-alpha.c1da1c.0<br/>@codecademy/gamut@19.1.0-alpha.c1da1c.0<br/>@codecademy/markdown-overrides@0.3.18-alpha.c1da1c.0<br/>@codecademy/styleguide@21.0.8-alpha.c1da1c.0<br/>@codecademy/tracking@0.1.3-alpha.c1da1c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce81fd02478d00f1638086--gamut-preview.netlify.app>https://5fce81fd02478d00f1638086--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce81fd02478d00f1638086>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.0.7-alpha.cecd84.0<br/>@codecademy/gamut@19.1.0-alpha.cecd84.0<br/>@codecademy/styleguide@21.0.9-alpha.cecd84.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fce8746aaceab008fea5f99--gamut-preview.netlify.app>https://5fce8746aaceab008fea5f99--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fce8746aaceab008fea5f99>Deploy Logs</a></p>

**Pull request merged**
