### PR TITLE
feat(Styleguide): Adds docgen parser for system props

### PR DESCRIPTION
**Pull request by codecaaron**
## Overview
Adds an addon to sanitize and standardize system prop docgen values and update controls to work with select menus.

Check it out: [here](https://5fb3fb67b53fa84c86696705--gamut-preview.netlify.app/storybook/?path=/docs/typography-text-labs--text)

Changes:
- Adds a custom addon preset to reformat system specific argTypes.  This checks all registered argTypes and reformats the description / summary / and control.
- Changes the Blocks => components (no external changes).

Further work:
- Some options lists are too long and the current method of sanitization will not solve this.
- We do not have a basic prop description for each specific prop yet.  Ideally, we should mention the scale's origin on the theme.  This will require some extra work to add meta data to the style templates in the system. 
- We don't have a place to add the `Theme` shape docs.  And I would like to.

**before**
Screen Shot 2020-11-16 at 9 33 06 PM

**after**
Screen Shot 2020-11-16 at 9 32 39 PM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.7-alpha.15d002.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3377ba9660e008afd394a--gamut-preview.netlify.app>https://5fb3377ba9660e008afd394a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3377ba9660e008afd394a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.5c8fe3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb338a2f8045901033a8085--gamut-preview.netlify.app>https://5fb338a2f8045901033a8085--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb338a2f8045901033a8085>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.315e76.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.6a06c2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.fcfc93.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3f2b97874583ea1f341ba--gamut-preview.netlify.app>https://5fb3f2b97874583ea1f341ba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3f2b97874583ea1f341ba>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.a64ac3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3f36c297e3143e4d9c1d5--gamut-preview.netlify.app>https://5fb3f36c297e3143e4d9c1d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3f36c297e3143e4d9c1d5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.511086.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3f500d613514accaf38a8--gamut-preview.netlify.app>https://5fb3f500d613514accaf38a8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3f500d613514accaf38a8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.8-alpha.924a1d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3fb67b53fa84c86696705--gamut-preview.netlify.app>https://5fb3fb67b53fa84c86696705--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3fb67b53fa84c86696705>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.9-alpha.9b23d3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb3fe80a6dbdd43c4b05f3f--gamut-preview.netlify.app>https://5fb3fe80a6dbdd43c4b05f3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb3fe80a6dbdd43c4b05f3f>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.5.10-alpha.3dd9f1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb69f08d518b8012dc0ed51--gamut-preview.netlify.app>https://5fb69f08d518b8012dc0ed51--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb69f08d518b8012dc0ed51>Deploy Logs</a></p>

**Pull request merged**
