### PR TITLE
fix(Select): add aria-hidden to ArrowDownChevron

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Fixes  [REACH-908](https://codecademy.atlassian.net/browse/REACH-908), static-site monolith tests bumped [here](https://github.com/codecademy-engineering/static-sites/pull/743)

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: REACH-908
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.38-alpha.f70908.0<br/>@codecademy/gamut-labs@13.5.15-alpha.f70908.0<br/>@codecademy/gamut@31.1.1-alpha.f70908.0<br/>@codecademy/styleguide@35.1.1-alpha.f70908.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607efbd07d34b600a7a46804--gamut-preview.netlify.app>https://607efbd07d34b600a7a46804--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607efbd07d34b600a7a46804>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.d49c46.0<br/>@codecademy/gamut-labs@14.0.1-alpha.d49c46.0<br/>@codecademy/gamut@32.0.1-alpha.d49c46.0<br/>@codecademy/styleguide@36.0.1-alpha.d49c46.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f3141091ff900a3c706c6--gamut-preview.netlify.app>https://607f3141091ff900a3c706c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f3141091ff900a3c706c6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.40-alpha.9e5589.0<br/>@codecademy/gamut-labs@14.1.1-alpha.9e5589.0<br/>@codecademy/gamut@32.0.1-alpha.9e5589.0<br/>@codecademy/styleguide@36.1.1-alpha.9e5589.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608034d1cf83cc5099ec0bf2--gamut-preview.netlify.app>https://608034d1cf83cc5099ec0bf2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608034d1cf83cc5099ec0bf2>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by aresnik11 — APPROVED** [review]
LGTM! Thanks for updating

**Review by JoshuaKGoldberg — APPROVED** [review]
:+1: confirmed I couldn't find `StyledFlexbox` used anywhere

**Review by christian-dinh — APPROVED** [review]
ty!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.40-alpha.de6696.0<br/>@codecademy/gamut-labs@14.1.1-alpha.de6696.0<br/>@codecademy/gamut@32.0.1-alpha.de6696.0<br/>@codecademy/styleguide@36.1.1-alpha.de6696.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60805c83672052215f83e019--gamut-preview.netlify.app>https://60805c83672052215f83e019--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60805c83672052215f83e019>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.51-alpha.d78518.0<br/>@codecademy/gamut-labs@14.4.3-alpha.d78518.0<br/>@codecademy/gamut@32.3.3-alpha.d78518.0<br/>@codecademy/styleguide@36.4.3-alpha.d78518.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608746dd8ba134194e4ee807--gamut-preview.netlify.app>https://608746dd8ba134194e4ee807--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608746dd8ba134194e4ee807>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.78-alpha.513f5e.0<br/>@codecademy/gamut-labs@15.5.2-alpha.513f5e.0<br/>@codecademy/gamut@32.11.2-alpha.513f5e.0<br/>@codecademy/styleguide@36.13.4-alpha.513f5e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092b9a80689381023b9a34a--gamut-preview.netlify.app>https://6092b9a80689381023b9a34a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092b9a80689381023b9a34a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.79-alpha.6dac1a.0<br/>@codecademy/gamut-labs@15.5.3-alpha.6dac1a.0<br/>@codecademy/gamut@32.12.1-alpha.6dac1a.0<br/>@codecademy/styleguide@36.14.1-alpha.6dac1a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092ce3bca7bd21ec3762715--gamut-preview.netlify.app>https://6092ce3bca7bd21ec3762715--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092ce3bca7bd21ec3762715>Deploy Logs</a></p>

**Pull request merged**
