### PR TITLE
ci: allow autoupdate when PRs have the shipit or auto update labels

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

This will auto-update PRs that have the "ship it" and "Auto Update" labels.

Seems like it will only work once I merge it, so i'll have to test it out there.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc81e6177d2340db672574e--gamut-preview.netlify.app>https://5fc81e6177d2340db672574e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc81e6177d2340db672574e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc81f26eb1a831ec1768b93--gamut-preview.netlify.app>https://5fc81f26eb1a831ec1768b93--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc81f26eb1a831ec1768b93>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd13f3f809b221b7d773725--gamut-preview.netlify.app>https://5fd13f3f809b221b7d773725--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd13f3f809b221b7d773725>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]
💯

**Pull request merged**
