### PR TITLE
feat(Styleguide): use green background for localhost storybook

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Should make it harder to mistake whether you're on local dev.

Which is something I do constantly...

Screenshot of the page with a green backround

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.3.0-alpha.8e7d82.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a8349a6d9ee31a782a3e8--gamut-preview.netlify.app>https://613a8349a6d9ee31a782a3e8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a8349a6d9ee31a782a3e8>Deploy Logs</a></p>

**Comment by airrobb** [comment]
What do you think about switching the BG here https://github.com/Codecademy/client-modules/blob/main/packages/styleguide/.storybook/components/Docs/DocsPage.tsx#L85 to beige like the main app?

**Comment by codecaaron** [comment]
@JoshuaKGoldberg What do you think about switching the BG here https://github.com/Codecademy/client-modules/blob/main/packages/styleguide/.storybook/components/Docs/DocsPage.tsx#L85 to beige like the main app?

**Comment by JoshuaKGoldberg** [comment]
@codecaaron heh maybe! I was hoping to get this in as a quick fix and then have us apply some design love to the site overall 😄

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@44.4.0-alpha.a81715.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613f9cec207bc5008e31c73e--gamut-preview.netlify.app>https://613f9cec207bc5008e31c73e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613f9cec207bc5008e31c73e>Deploy Logs</a></p>

**Pull request merged**
