### PR TITLE
feat(gamut-styles): Add responsive utils

### PR DESCRIPTION
**Pull request by codecaaron**
## Gamut Styles utils
- shares viewport names and mixin for all gamut-styles consumers.

They are used here:  https://github.com/Codecademy/client-modules/pull/722  

For whatever reason the dependencies are resolving with multiple versions of gamut-styles when in the same build (some chicken before the egg thing). 

I am moving shared variables to gamut-styles so they can be used by gamut / brand components as well as be referenced in monolith components for consistency.

I will update that PR accordingly once this is in.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.8.21-alpha.ac349b.0<br/>@codecademy/gamut-styles@2.2.12-alpha.ac349b.0<br/>@codecademy/gamut@3.4.1-alpha.ac349b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e9742febbeabe2c7b686b6b--codecademy-styleguide.netlify.app>https://5e9742febbeabe2c7b686b6b--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e9742febbeabe2c7b686b6b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/brand-components@0.8.24-alpha.ced8ad.0<br/>@codecademy/gamut-styles@2.2.12-alpha.ced8ad.0<br/>@codecademy/gamut@3.5.1-alpha.ced8ad.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5e974606c0a579019f8afc68--codecademy-styleguide.netlify.app>https://5e974606c0a579019f8afc68--codecademy-styleguide.netlify.app</a></p><p><a href=https://app.netlify.com/sites/codecademy-styleguide/deploys/5e974606c0a579019f8afc68>Deploy Logs</a></p>

**Comment by codecaaron** [comment]
Sorry forgot to add the description:

They are used here:  https://github.com/Codecademy/client-modules/pull/722  

For whatever reason the dependencies are resolving with multiple versions of gamut-styles when in the same build (some chicken before the egg thing).  I am moving shared variables to gamut-styles so they can be used by gamut / brand components as well as experimental monolith components.

I will update that PR accordingly once this is in.

**Pull request merged**
