### PR TITLE
docs(text): add some utility examples

### PR DESCRIPTION
**Pull request by slin12**
### Overview

Storybook update to Text with some examples of truncate, smooth, and screenreader.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

Visit https://60d630117caae60c9e4b7fce--gamut-preview.netlify.app/storybook/?path=/docs/typography-text--text and see section 3. Utilities

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.93427e.0<br/>@codecademy/gamut-labs@19.12.2-alpha.93427e.0<br/>@codecademy/gamut@34.11.1-alpha.93427e.0<br/>@codecademy/styleguide@41.10.22-alpha.93427e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d630117caae60c9e4b7fce--gamut-preview.netlify.app>https://60d630117caae60c9e4b7fce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d630117caae60c9e4b7fce>Deploy Logs</a></p>

**Review by codecaaron — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.55-alpha.9d4c16.0<br/>@codecademy/gamut-labs@19.13.1-alpha.9d4c16.0<br/>@codecademy/gamut@34.12.1-alpha.9d4c16.0<br/>@codecademy/styleguide@41.10.25-alpha.9d4c16.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60da2a7241b0f33ef517d985--gamut-preview.netlify.app>https://60da2a7241b0f33ef517d985--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60da2a7241b0f33ef517d985>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60db406cd5f67b00911814cc--gamut-preview.netlify.app>https://60db406cd5f67b00911814cc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60db406cd5f67b00911814cc>Deploy Logs</a></p>

**Pull request merged**
