### PR TITLE
feat!: release -kit-4.7

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

feat(GridForm): rowspan fields ([#1796](https://github.com/Codecademy/client-modules/pull/1796)) 
fix: Filter non forwardable props on icons ([#1800](https://github.com/Codecademy/client-modules/pull/1800)) 
width 100% ([#1798](https://github.com/Codecademy/client-modules/pull/1798))
refactor: Input, TextArea, FormGroupLabel + Select to system props ([#1762](https://github.com/Codecademy/client-modules/pull/1798)) 
feat: add custom-group to GridForm ([#1792](https://github.com/Codecademy/client-modules/pull/1792))
style(Subtitle): fixed lesson count bug when count is 0 ([#1771](https://github.com/Codecademy/client-modules/pull/1771)) 
feat(themes): add editor colors to platform theme ([#1789](https://github.com/Codecademy/client-modules/pull/1789) 
Fix anchor pseudo elements ([#1757](https://github.com/Codecademy/client-modules/pull/1757))
fix(EmptySection): fix spacing issues ([#1787](https://github.com/Codecademy/client-modules/pull/1757))

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.6-alpha.3af79d.0<br/>@codecademy/gamut-illustrations@0.17.2-alpha.3af79d.0<br/>@codecademy/gamut-kit@0.4.7-alpha.3af79d.0<br/>@codecademy/gamut-labs@18.4.1-alpha.3af79d.0<br/>@codecademy/gamut-patterns@0.3.2-alpha.3af79d.0<br/>@codecademy/gamut-styles@10.2.2-alpha.3af79d.0<br/>@codecademy/gamut-tests@2.4.5-alpha.3af79d.0<br/>@codecademy/gamut@33.5.0-alpha.3af79d.0<br/>@codecademy/konamimojisplosion@0.2.36-alpha.3af79d.0<br/>@codecademy/markdown-overrides@0.5.48-alpha.3af79d.0<br/>@codecademy/styleguide@40.4.0-alpha.3af79d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7f1fab2ceeb44fcde58c7--gamut-preview.netlify.app>https://60b7f1fab2ceeb44fcde58c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7f1fab2ceeb44fcde58c7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.6-alpha.c3d435.0<br/>@codecademy/gamut-illustrations@0.17.2-alpha.c3d435.0<br/>@codecademy/gamut-kit@0.4.7-alpha.c3d435.0<br/>@codecademy/gamut-labs@18.4.1-alpha.c3d435.0<br/>@codecademy/gamut-patterns@0.3.2-alpha.c3d435.0<br/>@codecademy/gamut-styles@10.3.0-alpha.c3d435.0<br/>@codecademy/gamut-tests@2.4.5-alpha.c3d435.0<br/>@codecademy/gamut@33.5.0-alpha.c3d435.0<br/>@codecademy/konamimojisplosion@0.2.36-alpha.c3d435.0<br/>@codecademy/markdown-overrides@0.5.48-alpha.c3d435.0<br/>@codecademy/styleguide@40.4.0-alpha.c3d435.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.6-alpha.674f03.0<br/>@codecademy/gamut-illustrations@0.17.2-alpha.674f03.0<br/>@codecademy/gamut-kit@0.4.7-alpha.674f03.0<br/>@codecademy/gamut-labs@18.4.1-alpha.674f03.0<br/>@codecademy/gamut-patterns@0.3.2-alpha.674f03.0<br/>@codecademy/gamut-styles@10.3.0-alpha.674f03.0<br/>@codecademy/gamut-tests@2.4.5-alpha.674f03.0<br/>@codecademy/gamut@33.5.0-alpha.674f03.0<br/>@codecademy/konamimojisplosion@0.2.36-alpha.674f03.0<br/>@codecademy/markdown-overrides@0.5.48-alpha.674f03.0<br/>@codecademy/styleguide@40.4.0-alpha.674f03.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7f631df3fbe4bcdd36614--gamut-preview.netlify.app>https://60b7f631df3fbe4bcdd36614--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7f631df3fbe4bcdd36614>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.6-alpha.1aae72.0<br/>@codecademy/gamut-illustrations@0.17.2-alpha.1aae72.0<br/>@codecademy/gamut-kit@0.4.7-alpha.1aae72.0<br/>@codecademy/gamut-labs@18.4.1-alpha.1aae72.0<br/>@codecademy/gamut-patterns@0.3.2-alpha.1aae72.0<br/>@codecademy/gamut-styles@10.3.0-alpha.1aae72.0<br/>@codecademy/gamut-tests@2.4.5-alpha.1aae72.0<br/>@codecademy/gamut@33.5.0-alpha.1aae72.0<br/>@codecademy/konamimojisplosion@0.2.36-alpha.1aae72.0<br/>@codecademy/markdown-overrides@0.5.48-alpha.1aae72.0<br/>@codecademy/styleguide@40.4.0-alpha.1aae72.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7f957f7e873517709ff4c--gamut-preview.netlify.app>https://60b7f957f7e873517709ff4c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7f957f7e873517709ff4c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.14.6-alpha.7db175.0<br/>@codecademy/gamut-illustrations@0.17.2-alpha.7db175.0<br/>@codecademy/gamut-kit@0.4.7-alpha.7db175.0<br/>@codecademy/gamut-labs@18.4.1-alpha.7db175.0<br/>@codecademy/gamut-patterns@0.3.2-alpha.7db175.0<br/>@codecademy/gamut-styles@10.3.0-alpha.7db175.0<br/>@codecademy/gamut-tests@2.4.5-alpha.7db175.0<br/>@codecademy/gamut@33.5.0-alpha.7db175.0<br/>@codecademy/konamimojisplosion@0.2.36-alpha.7db175.0<br/>@codecademy/markdown-overrides@0.5.48-alpha.7db175.0<br/>@codecademy/styleguide@40.4.0-alpha.7db175.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b824b10e3e042d8bc66d91--gamut-preview.netlify.app>https://60b824b10e3e042d8bc66d91--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b824b10e3e042d8bc66d91>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
