### PR TITLE
fix: fix Layout wording for SM sizes

### PR DESCRIPTION
**Pull request by vonbarown**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by codecaaron — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.9.1-alpha.97d550.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca6696c9bd1e00c9abb19e--gamut-preview.netlify.app>https://60ca6696c9bd1e00c9abb19e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca6696c9bd1e00c9abb19e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.9.1-alpha.ded9ad.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca6a1ae08f5700b467b3b8--gamut-preview.netlify.app>https://60ca6a1ae08f5700b467b3b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca6a1ae08f5700b467b3b8>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@41.10.2-alpha.b52d2c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca779c58392200b123ccb2--gamut-preview.netlify.app>https://60ca779c58392200b123ccb2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca779c58392200b123ccb2>Deploy Logs</a></p>

**Pull request merged**
