### PR TITLE
fix(Tab): Used default outline for active and focused Tabs

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### PR Checklist

- ~[ ] Related to Abstract designs:~ _(informal conversation with Yassine)_
- [x] Related to JIRA ticket: A11Y-283 A11Y-284
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

`ButtonBase` removes the default `outline` from active/focused buttons, which is not a behavior we want here. The only button style I can tell was being used from it was the white background.

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f1f049e7ed8d601f7c866d4--gamut-preview.netlify.app>https://5f1f049e7ed8d601f7c866d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f1f049e7ed8d601f7c866d4>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
@codecaaron good call, I'll make a preview environment of the monolith just to be sure...

...once I figure out why this thing isn't publishing 😐

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@1.7.53-alpha.0702ff.0<br/>@codecademy/gamut@12.1.2-alpha.0702ff.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f1f14c688c3308c71c8fee5--gamut-preview.netlify.app>https://5f1f14c688c3308c71c8fee5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f1f14c688c3308c71c8fee5>Deploy Logs</a></p>

**Comment by JoshuaKGoldberg** [comment]
@codecaaron it makes them accessible as we'd hope. Happy.

Screenshot of an Overview and Syllabus tab pair, with Overview given visible tab focus

**Pull request merged**
