### PR TITLE
docs: Clarify landing page sub-components as atoms, not organisms

### PR DESCRIPTION
**Pull request by rogervera**
## Overview
Moves LandingPageCTA, *Title, and *Description into the Atoms directory in Storybook.
Moves LandingPageHero into the Organisms directory in Storybook.

### PR Checklist

- [ ] ~Related to designs:~
- [x] Related to JIRA ticket: REACH-378
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

But how could it be the parts and the whole and the same time? 🧐 

https://atomicdesign.bradfrost.com/chapter-2/#atoms

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.8.1-alpha.15a3a9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb6be59d0f3ef1fc3240bec--gamut-preview.netlify.app>https://5fb6be59d0f3ef1fc3240bec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb6be59d0f3ef1fc3240bec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@18.8.1-alpha.dfeee3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb6c109d60af924f1c9f79f--gamut-preview.netlify.app>https://5fb6c109d60af924f1c9f79f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb6c109d60af924f1c9f79f>Deploy Logs</a></p>

**Pull request merged**
