### PR TITLE
chore(eslint)!: update eslint + ts-lint pkgs

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Upgrades eslint + ts-eslint packages and configures the  new change to the `@typescript-eslint/no-misused-promises` rule.

Monolith alpha branch [here](https://github.com/codecademy-engineering/Codecademy/pull/29998)
Portal alpha branch [here](https://github.com/codecademy-engineering/portal-app/pull/1658)
Also cut ticket to maybe turn these on [here](https://codecademy.atlassian.net/jira/software/projects/WEB/boards/138?selectedIssue=WEB-1937)

Unblocks work from scss custom lintr rule - https://github.com/Codecademy/gamut/pull/2201
### PR Checklist

- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.0f7663.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.95e9e9.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.56c74e.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.f6e633.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.dd7f25.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.923396.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.30aaa7.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.75c2d7.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.e782d9.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.198b4a.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@7.0.3-alpha.034cc1.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
