### PR TITLE
chore!: replace VisualTheme enum with string type union

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### PR Checklist

- ~[ ] Related to designs:~
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description

Directly uses a type union for `VisualTheme` modes instead of the more complex enum.

This was an experimental-ish choice I'd made and defended over time because I like the idea of hiding details of the fields within very type safe lookups... but it's confusing people in the monolith and generally being a bit of a tooling pain.

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.1-alpha.eef907.0<br/>@codecademy/gamut@17.3.9-alpha.eef907.0<br/>@codecademy/styleguide@18.5.9-alpha.eef907.0<br/></pre>

**Review by rogervera — APPROVED** [review]
Much better for usability/comprehension IMO. 👍 

Whenever/if ever a site-wide Dark/Light mode is a feature, would VisualTheme / enum solution make more sense again?

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb5666a5ac1012a252600b4--gamut-preview.netlify.app>https://5fb5666a5ac1012a252600b4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb5666a5ac1012a252600b4>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Review by sylvanasantos — APPROVED** [review]
Yesss! So much better! Thanks for refactoring Josh! Hope it safes you some trouble in the long run!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.1-alpha.fe912a.0<br/>@codecademy/gamut@17.3.9-alpha.fe912a.0<br/>@codecademy/styleguide@18.5.9-alpha.fe912a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb593367f616500c17e7123--gamut-preview.netlify.app>https://5fb593367f616500c17e7123--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb593367f616500c17e7123>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.4-alpha.059951.0<br/>@codecademy/gamut@18.0.1-alpha.059951.0<br/>@codecademy/styleguide@20.0.1-alpha.059951.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc673f3a51aab0b2e2bf878--gamut-preview.netlify.app>https://5fc673f3a51aab0b2e2bf878--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc673f3a51aab0b2e2bf878>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@6.0.5-alpha.030851.0<br/>@codecademy/gamut@18.0.1-alpha.030851.0<br/>@codecademy/styleguide@20.0.2-alpha.030851.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fc69051ddfbcd26ac90945e--gamut-preview.netlify.app>https://5fc69051ddfbcd26ac90945e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fc69051ddfbcd26ac90945e>Deploy Logs</a></p>

**Pull request merged**
